### ISSUE TITLE
Change in GitHub Releases API broke Webi installs

### ISSUE THREAD

**Issue by coolaj86** [mikefarah/yq#1003]
Hello!

Just wanted to make a note that since we use the GitHub Releases API that when you change the package format, it may also break any installers and deploy tools that depend on that API.

PR is up for the fix (https://github.com/webinstall/webi-installers/pull/328), but it would be nice to have a heads up in the future. :)

Thanks.

P.S. What do you think about moving the `yq.1` files into `./share/man/man1/yq.1`? That would make it less ambiguous between trying to match for the binary and the supporting files (especially if you ever change the name to include the version number, such as `yq-v4.6.1`).

**Comment by mikefarah** [comment]
Oh I see - noted. That won't happen to often, but I'll keep it in mind. 

I don't want to move the man file now - as you say some people may depend on where it is now. The manpage itself has the version embedded in it - can't see a reason to ever put the version in the filename itself (I think that would also break `man yq` as it wouldn't match the file anymore).

**Comment by coolaj86** [comment]
I think the path for the man file, when installed is supposed to be `~/.local/opt/yq/share/man/man1/yq.1`.

**Comment by coolaj86** [comment]
Currently the filename isn't `yq` inside the tarball, etc.

Instead it's `yq_OS_ARCH`.

**Comment by mikefarah** [comment]
From what I read there's a couple of different conventions for where to put man pages - the original ticket for the man page had the path I've set. Ofcourse, you are free to copy it to where it's appropriate on your setup.

**Comment by coolaj86** [comment]
@mikefarah I finally figured out the MANPATH issue.

Indeed, it should be relative to the install location.

Assuming someone installs to `~/.local/bin/yq`, the man pages should go into `~/.local/share/man/man1/yq.1`.

If they install to `~/.local/opt/yq/bin/yq` then the man pages should go into `~/.local/opt/yq/share/man/man1`.

MANPATH is automatically updated when PATH is updated.

See <https://github.com/webinstall/webi-installers/issues/338>.

**Comment by mikefarah** [comment]
neat!
