### ISSUE TITLE
Resolve $ref from OpenAPI?

### ISSUE THREAD

**Issue by braco** [mikefarah/yq#1004]
I think this is an OpenAPI idiom, but it would be nice if there was a way to support it?:

```
components:
  schemas:
    Thing:
      oneOf:
        - $ref: '#/components/schemas/AnotherThing'
        - $ref: '#/components/schemas/YetAnotherThing'
```

I want to get `.components.schemas.Thing` with all of the $refs resolved, meaning that the $ref would be replaced with the content of that file, as an OpenAPI parser would.

in the meantime,
```
npx @redocly/openapi-cli bundle -d build/spec.yml -o build/resolved-spec.yml
yq e ".components.schemas.Thing | explode(.)" build/resolved-spec.yml
```

**Comment by mikefarah** [comment]
"$ref" is an OpenAPI specific convention - however I think I could add a `loadFile` operator that would work for OpenAPI as well as other conventions for including content from other files.

`

something like:

```
yq e ".components.schemas.Thing |= load_file(.$ref)" build/resolved-spec.yml
```

or to include all the refs:

```
yq e "(.[] | select(.== "$ref") |= load_file(.$ref)" build/resolved-spec.yml
```

**Comment by mikefarah** [comment]
Actually maybe `load_yaml` to load a file as yaml content, and `load_string` from string content 🤔

**Comment by mikefarah** [comment]
Scratch that load/ strload to match env/strenv

**Comment by mikefarah** [comment]
Hold on - I'm a little confused - is $ref a reference to another file? or to another node within this document?

If it's within the document - then yaml already supports that with aliases and anchors...

**Comment by mikefarah** [comment]
I've added a `load` operator -> https://mikefarah.gitbook.io/yq/operators/load - that can be used to load up referenced docs.

You can do something like https://mikefarah.gitbook.io/yq/operators/load#replace-all-nodes-with-referenced-file to find all the $refs and load them.

**Comment by zakcutner** [comment]
Thanks for adding this, and sorry to comment on an old issue! I was wondering if it's possible to do this recursively? For example, with the following files:
```yaml
# a.yaml
a: 100

# b.yaml
b:
  $ref: a.yaml

# c.yaml
c:
  $ref: c.yaml
```
The example linked above will give something like:
```sh
$ yq '(.. | select(has("$ref"))) |= load(.$ref)' c.yaml
c:
  b:
    $ref: a.yaml
```
But I would be looking for an output like:
```yaml
c:
  b:
    a: 100
```

**Comment by FelixZY** [comment]
I was able to resolve local refs (i.e. `{ "$ref": "#..." }` using the following query:

```sh
yq -p=json -o=json '(.. | select(has("$ref"))) |= (.$ref | split("/") | .[1:] | .[] as $segment ireduce (load("ref.json"); .[$segment]))' ref.json
```

```json
{
  "hello": "world",
  "who": {
    "$ref": "#/components/people/Person"
  },
  "what": {
    "$ref": "#/components/stuff/Thing"
  },
  "components": {
    "people": {
      "Person": {
        "name": "Felix"
      }
    },
    "stuff": {
      "Thing": {
        "dimensions": 3
      }
    }
  }
}
```

@mikefarah I used the [`load`](https://mikefarah.gitbook.io/yq/operators/load) operator in conjunction with [`reduce`](https://mikefarah.gitbook.io/yq/operators/reduce) to traverse the document. However, I can't help wishing for:

1. a way to reference the root of the current document without calling `load(self)`
2. a way to traverse using `["an", "array", "of", "path.segments"]` rather than via `reduce`

Have I missed something in the documentation or are these things that could be added?
