### ISSUE TITLE
Addition kubernetes annotations using yq

### ISSUE THREAD

**Issue by wheestermans31** [mikefarah/yq#1031]
I try the following syntax to add annotation alb.ingress.kubernetes.io/security-groups with value 'test'

yq eval  '.metadata.annotations.alb.ingress.kubernetes.io/security-groups" = "test"' test.yaml

But the result is:

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tme-ing-nginx-test
  namespace: test
  **```
annotations:
      alb:
        ingress:
          kubernetes:
            io/security-groups": test
```**
...

Instead of 

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tme-ing-nginx-test
  namespace: test
  **annotations:
    alb.ingress.kubernetes.io/security-groups: test**
...

How can I handle correctly?

**Comment by mikefarah** [comment]
Dots are special characters in `yq`, take a look how to do it here: https://mikefarah.gitbook.io/yq/operators/traverse-read#special-characters
