### ISSUE TITLE
Multi-line `eval` to change multiple places of an input YAML template file

### ISSUE THREAD

**Issue by tappoz** [mikefarah/yq#1035]
**Please describe your feature request.**

Cannot find a way to format the `eval` expression in multiline. We're working on some "simple" find/replace templating features for Kubernetes CronJob files (yes - trying to avoid huge leaps like Helm charts).

We have a `Makefile` target with the `yq` command like this:

```Makefile
deploy-my-etl:
	yq e \
		'.spec.schedule = "1 * * * *" | (.spec.jobTemplate.metadata.name, .metadata.name, .spec.jobTemplate.spec.template.spec.containers[0].name) = "my-etl-$(MY_FUNCTION)-c" | (.spec.jobTemplate.spec.template.spec.containers[0].env[] | select(.name == "MY_FUNCTION") | .value) = "$(MY_FUNCTION)" | (.spec.jobTemplate.spec.template.spec.containers[0].env[] | select(.name == "CONTAINER_NAME") | .value) = "etl-$(MY_FUNCTION)"' \
		$(PWD)/deployment/base/my-etl/my-etl.yaml \
		> $(PWD)/deployment/base/my-etl/my-etl-$(MY_FUNCTION).yaml
```

These :point_up: are a chain of 4 `OR`s with some nested `OR`s. Having multi-line between singe quotes `'***...***'` would increase readability.

**Describe the solution you'd like**

We could specify something like Python multi-line strings like 

```
"""
(1st complex find&replace)
(2nd complex find&replace)
(3rd complex find&replace)
(4th complex find&replace)
"""
```

**Describe alternatives you've considered**

The issue is to find a way to store half-done stages starting from 2 files:

- the initial YAML template file
- the output YAML with all the changes

Sometimes we don't want to change the original file (template) and we're trying to avoid
for loops in `Makefile`s where we find&replace at each iteration and flush to a temporary file
that is then used for the next iteration.

**Comment by mikefarah** [comment]
You mean like what's on the readme:

```
yq e -i '
  .a.b[0].c = "cool" |
  .x.y.z = "foobar" |
  .person.name = strenv(NAME)
' file.yaml
```

**Comment by tappoz** [comment]
Right - this might be an issue in between `Makefile` (GNU Make) and `bash`, if I follow that example in the readme, then I see:

```
yq e '
/bin/bash: -c: line 0: unexpected EOF while looking for matching `''
/bin/bash: -c: line 1: syntax error: unexpected end of file
```

Not sure if there's anything that could be done within `yq` to avoid the above

**Comment by mikefarah** [comment]
I see, I'm not expert in Makefiles, bash it definitely works. Best thing I can recommend is to pull it out into a little bash script and call the script from the Makefile...

**Comment by mikefarah** [comment]
There some advice here: https://stackoverflow.com/questions/10121182/multi-line-bash-commands-in-makefile

Either way - I don't think this is something would do anything about.

**Comment by pp-eyushin** [comment]
You can use the following pattern:
```bash
yq e '.a.b[0].c = "cool"' file.yaml > new_file.yaml
yq -i '.x.y.z = "foobar"' new_file.yaml
...
```
