### ISSUE TITLE
Error: "Unable to flush stdout: Broken pipe"

### ISSUE THREAD

**Issue by 8ear** [mikefarah/yq#1036]
**Describe the bug**
I get the error message: `Unable to flush stdout: Broken pipe`
I tried:
qm cloudinit dump 101 user | /usr/local/bin/yq read --exitStatus --printMode v --stripComments -- - 'ssh_authorized_keys[*]'
From the guide: https://wiki.geco-it.net/public:pve_fcos#en

On the end I try to pipe the output from one command throughj yq which does not work. i tried it first with the real old version 3.4.1 as mentioned in the guide. After that I tried it also with the up to date version 4.16.1 and got the same error.

This problem exists everytime I try to pipe the output.

For example:
`qm cloudinit dump 101 meta | /usr/local/bin/yq read --exitStatus --printMode v --stripComments -- - instance-id`

Output of `qm cloudinit dump 101 meta`:
instance-id: 70dd9eb946a21f849xxxxxxxxxxxxxxxx

Version of yq: 4.16.1 / 3.4.1
Operating system: linux Debian 11
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
instance-id: 70dd9eb946a21f849xxxxxxxxxxxxxxxx
```

**Command**
The command you ran:
```
qm cloudinit dump 101 meta | /usr/local/bin/yq read --exitStatus --printMode v --stripComments -- - instance-id
```

**Actual behavior**

```bash
Unable to flush stdout: Broken pipe
```

**Expected behavior**

```bash
70dd9eb946a21f849xxxxxxxxxxxxxxxx
```

**Additional context**

**Comment by mikefarah** [comment]
Looks like a `qm` problem to me

**Comment by mikefarah** [comment]
I'd play around with piping from another source into `yq` and see if you still get that error, and similarly pipe from `qm` to another process...
