### ISSUE TITLE
Processing of OpenAPI Specs with OData paths results in appearance of '?'

### ISSUE THREAD

**Issue by robot-accomplice** [mikefarah/yq#1055]
Reopens #1033 

It seems that any value for the environment variable "api" will work... 'potato' for instance
[yq.yaml.zip](https://github.com/mikefarah/yq/files/7789592/yq.yaml.zip)

When executing an eval statement against a target document, the lines described below are minutely transformed to include an unallowable '?' character.

Version of yq: 4.16.1/4.12.0
Operating system: mac/linux
Installed via: homebrew/git clone

**Input Yaml**
(apologies about indenting, the markup isn't playing nice)
data1.yml:
```yaml
          $ref: '#/components/responses/error'
 
 '/DocumentInfoRecordAttch(DocumentInfoRecordDocType=''{DocumentInfoRecordDocType}'',DocumentInfoRecordDocNumber=''{DocumentInfoRecordDocNumber}'',DocumentInfoRecordDocVersion=''{DocumentInfoRecordDocVersion}'',DocumentInfoRecordDocPart=''{DocumentInfoRecordDocPart}'')/DocumentInfoRecordToAttachmentNavigation':
    parameters:
      - name: DocumentInfoRecordDocType
```

**Command**
The command you ran:
```
unzip -p ${bundle} docs/openapi.yaml | yq e '.x-rlg-api = env(api)' - > $tmp_file
```

**Actual behavior**

```yaml
          $ref: '#/components/responses/error'
  ? "/DocumentInfoRecordAttch(DocumentInfoRecordDocType=''{DocumentInfoRecordDocType}'',DocumentInfoRecordDocNumber=''{DocumentInfoRecordDocNumber}'',DocumentInfoRecordDocVersion=''{DocumentInfoRecordDocVersion}'',DocumentInfoRecordDocPart=''{DocumentInfoRecordDocPart}'')/DocumentInfoRecordToAttachmentNavigation"
  : parameters:
```

**Expected behavior**

```yaml
          $ref: '#/components/responses/error'
 '/DocumentInfoRecordAttch(DocumentInfoRecordDocType=''{DocumentInfoRecordDocType}'',DocumentInfoRecordDocNumber=''{DocumentInfoRecordDocNumber}'',DocumentInfoRecordDocVersion=''{DocumentInfoRecordDocVersion}'',DocumentInfoRecordDocPart=''{DocumentInfoRecordDocPart}'')/DocumentInfoRecordToAttachmentNavigation':
    parameters:
```

**Comment by mikefarah** [comment]
You need to fix that indenting - it's not valid yaml and I don't understand how it's supposed to be structured.

I tried copying and pasting the content into http://www.yamllint.com/ and it removed most of your document.

**Comment by mikefarah** [comment]
BTW if I copy the '/Document....' key into yamllint, it to puts a leading '?' in there...

**Comment by robot-accomplice** [comment]
That's strange that you're finding the indenting is incorrect.  I just pasted the yaml into www.yamllint.com and go the following:

![image](https://user-images.githubusercontent.com/80694560/147910447-561520c1-ace3-4c81-8245-59db2c03d0ac.png)

**Comment by robot-accomplice** [comment]
To be clear, I am not the author of this document.  I run an API management team that is obliged to contend with a multitude of API producers.  Some of those producers exclusively publish OData services.  When I first set eyes on this OpenAPI spec I was certain that they were in violation of the YAML specification, but as near as I can tell they are not.

**Comment by mikefarah** [comment]
the document in the screenshot is completely different from what's in this issue - can you please supply that doc

**Comment by robot-accomplice** [comment]
Honestly, I think I'm just going to close this.  The parsing behavior is **absolutely ubiquitous** and since it's just one document out of hundreds suffering from this issue, we'll find a one-off work around and move on.

Thanks for you time, and sorry for the dead end.

**Comment by mikefarah** [comment]
Righteo, no problem
________________________________
