### ISSUE TITLE
/usr/local/bin/yq: line 1: Not: command not found yq

### ISSUE THREAD

**Issue by davidshare** [mikefarah/yq#1077]
**Describe the bug**
I installed yq in a docker container in with the following command:
```
ENV YQ_VERSION v4.17.2

RUN wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/bin/yq &&\
    chmod +x /usr/bin/yq
```

Version of yq: v4.17.2
Operating system: linux
Installed via: wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 -O /usr/bin/yq

**Command**
The command you ran: 
```
yq -v
```

**Actual behavior**
```
yq -V
/usr/local/bin/yq: line 1: Not: command not found
```

**Expected behavior**

It should show me the yq version

**Additional context**

**Comment by mikefarah** [comment]
You installed yq at `/usr/bin/yq` but the error is for `/usr/local/bin/yq` - what's that? perhaps remove that file

**Comment by koppor** [comment]
For someone hitting this issue. Try 

    head /usr/bin/yq

For debugging

The content here was

    Not Found

The URL I used is `https://github.com/mikefarah/yq/releases/latest/download/yq_linux_${TARGETARCH}`, but `TARGETARCH` was empty...

Right URL: https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
