### ISSUE TITLE
Missing windows zip files checksums

### ISSUE THREAD

**Issue by pican79** [mikefarah/yq#1078]
**Describe the bug**
The checksums file for the 4.16.x releases don't contain any yq_windows_arch.zip entries.
https://github.com/mikefarah/yq/releases/tag/v4.16.1
https://github.com/mikefarah/yq/releases/tag/v4.16.2
Instead, there are 2 yq_windows_arch.exe.tar.gz entries: yq_windows_amd64.exe.tar.gz & yq_windows_386.exe.tar.gz
NB: I haven't checked the older releases or the new one.

The sha256 & sha512 hashes don't match the zip files (I haven't bothered checking the other algorithms).
I guess they're for the *.exe.tar.gz files, wherever these are.

Version of yq: 4.16.x
Operating system: windows
Installed via: binary release

**Comment by mikefarah** [comment]
Oops - the same script run for 4.17.2 so that's also missing the checksums for the zips. The checksums for the binaries are present though - and so they can still be verified.

I have updated the checksum script to include the zips in the next release.

**Comment by mikefarah** [comment]
Okay they have been added to the 4.18.1 release (and will be in future releases too)

**Comment by pican79** [comment]
Thank you.
