### ISSUE TITLE
How to specify keys with dots?

### ISSUE THREAD

**Issue by smithbk** [mikefarah/yq#108]
Can someone tell me how to specify yaml keys with dots?   My yaml is as follows:

converters:
   "a.b": foo

and I'm getting the following error when trying to parse:    

'Converters[a]' expected type 'string', got unconvertible type 'map[string]interface {}'

**Comment by mikefarah** [comment]
Can you give me some more detail? I tried it locally and it seems to work:

sample.yaml
```yaml
converters:
  "a.b": foo
```

Then:
```
yaml r sample.yaml "converters[a.b]"
```

**Comment by smithbk** [comment]
My bad.  The problem is actually in viper.  The viper.AllKeys() function uses a "keyDelim" field which is set to "." with no way to change.   See https://github.com/spf13/viper/issues/170
