### ISSUE TITLE
Support for front matter files

### ISSUE THREAD

**Issue by iilyak** [mikefarah/yq#109]
Would it be possible to support [front matter](https://gohugo.io/content-management/front-matter/) files. Front matter file is a file where yaml is embedded into another file. For example:
```
---
title: "spf13-vim 3.0 release and new website"
description: "spf13-vim is a cross platform distribution of vim plugins and resources for Vim."
tags: [ ".vimrc", "plugins", "spf13-vim", "vim" ]
lastmod: 2015-12-23
date: "2012-04-06"
categories:
  - "Development"
  - "VIM"
slug: "spf13-vim-3-0-release-and-new-website"
---

SOMETHING SOMETHING
```

**Comment by mikefarah** [comment]
Not at this stage, what you could do is keep the yaml separate, modify it as you need using yq, then concatenate the files together using cat.

e.g:

```
yq w metadata.yml date "2012-04-24" |  cat - content.txt
```
