### ISSUE TITLE
Unable to read key with period in v4

### ISSUE THREAD

**Issue by wavemoran** [mikefarah/yq#1092]
**Describe the bug**
Similar to https://github.com/mikefarah/yq/issues/208 but in v4, I'm trying to read keys with periods. The bracket method mentioned previously doesn't seem to work.

Version of yq: 4.18.1
Operating system: MacOS
Installed via: homebrew

**Input Yaml**

```yaml
a:
  foo.bar: "sample"
```

**Command**
The command you ran:

```
yq '.a.[foo.bar]' file.yaml
```

**Actual behavior**

```bash
Error: Parsing expression: Lexer error: could not match text starting at 1:5 failing at 1:9.
	unmatched text: "foo."
```

**Expected behavior**

```yaml
foo.bar: "sample"
```

**Comment by mikefarah** [comment]
You need double quotes around `foo.bar` otherwise it tries to evaluate that as an expression - see https://mikefarah.gitbook.io/yq/operators/traverse-read#nested-special-characters

**Comment by mikefarah** [comment]
```
yq '.a.["foo.bar"]' file.yaml
```
