### ISSUE TITLE
Accessing missing key in variable breaks to_entries

### ISSUE THREAD

**Issue by dhain** [mikefarah/yq#1094]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.18.1
Operating system: mac
Installed via: homebrew

**Command**
The command you ran:
```
yq --null-input '{} as $v | $v["foo"] | $v | to_entries'
```

**Actual behavior**

```yaml
- key: foo
  value: null
```

**Expected behavior**

```yaml
[]
```

**Additional context**

**Comment by mikefarah** [comment]
This is where `yq` behaves a little differently from `jq` (for better or worse)...

`yq` will automatically create entries on the fly from the given path, so you can do things like:

```bash
yq --null-input '{} as $v | ($v | .foo.cat[0] = "dog") | $v'
foo:
  cat:
    - dog
```

whereas jq won't:
```bash
jq --null-input '{} as $v | ($v | .foo.cat[0] = "dog") | $v'
{}
```

and so by traversing into the map here `$v["foo"]` yq actually adds the `foo` key and sets it to null.

To get the same behaviour as `jq` - you'll need to filter out the variable when it doesn't have `foo`:

```bash
yq --null-input '{} as $v | ($v | select(has("foo")) | .foo ) | $v | to_entries'
[]
```

**Comment by mikefarah** [comment]
Further note, yq is smart enough _not_ to autocreate inside a select expression - so if it helps, you can also do this:

```bash
yq --null-input '{} as $v | ($v | select(.foo.cat.bar != null) | .foo ) | $v | to_entries
```
