### ISSUE TITLE
merge without adding new keys

### ISSUE THREAD

**Issue by hans-d** [mikefarah/yq#110]
Would be nice if we could merge, where adding new items will be prevented. This would result in that the first file supplied would act as a template, where the additional files would supply the actual values.

**Comment by mikefarah** [comment]
This has been fixed with the latest release (been a while I know): https://github.com/mikefarah/yq/releases/tag/3.0.1, see https://mikefarah.gitbook.io/yq/commands/merge#auto-create for more info.
