### ISSUE TITLE
write as update only

### ISSUE THREAD

**Issue by hans-d** [mikefarah/yq#111]
almost like #110, only being allowed to update values only (not adding new ones). Depending on some flag the update for a non-existent key should either result in an error or just be silently ignored.

**Comment by mkyc** [comment]
@hans-d I think it's implemented with `--overwrite --autocreate=false` as presented [here](https://mikefarah.gitbook.io/yq/commands/merge#auto-create).

**Comment by mikefarah** [comment]
This is now doable in yq version 4 (as well as @mkyc approach in v3)

**Comment by past-due** [comment]
> This is now doable in yq version 4 (as well as @mkyc approach in v3)

@mikefarah Forgive me, but how does one accomplish this in v4?

I was using:
`yq m --overwrite --autocreate=false "${file1}" "${file2}" > "${output}"` in v3
and:
`yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' "${file1}" "${file2}" > "${output}"` in v4
 adds new ones from file2
