### ISSUE TITLE
String manipulation

### ISSUE THREAD

**Issue by fboula** [mikefarah/yq#1111]
**Please describe your feature request.**
Hi, I would like `yq` to be able to manipulate strings to make them lowercase or uppercase, like jq does with:

```
 ascii_downcase
 ascii_upcase
```

**Describe the solution you'd like**
If we have data.yml like:

```yaml
a: Hello World
```

And we run a command:

```bash
yq '.a | ascii_downcase' data.yml
```

it could output

```yaml
a: hello world
```

**Comment by mikefarah** [comment]
Released in 4.21.1 [(https://mikefarah.gitbook.io/yq/operators/string-operators)](https://mikefarah.gitbook.io/yq/operators/string-operators#to-up-upper-case)
