### ISSUE TITLE
yq@3 marked as disabled on homebrew

### ISSUE THREAD

**Issue by Talador12** [mikefarah/yq#1113]
**Describe the bug**
https://formulae.brew.sh/formula/yq@3

When you run `brew install yq@3` you get `Error: yq@3 has been disabled because it is not maintained upstream! ` and it prevents the install. 

Version of yq: 3.X.X
Operating system: mac
Installed via: homebrew

**Additional context**
There are work arounds to get it installed, but it would be much better to provide if this was `enabled` on homebrew. If `yq@3` is to be entirely deprecated, please open up the license for yq@3 so someone else can maintain that project. If anyone did fork yq@3 to maintain it, the fork should remain as to give credit to @mikefarah

**Comment by mikefarah** [comment]
Yep - it's longer maintained here. I'd highly recommend upgrading to v4, if it helps there's an upgrade guide here: https://mikefarah.gitbook.io/yq/upgrading-from-v3

Anyone is more than welcome to fork v3 and maintain it if they wish - it's under the MIT license.

Note that you can still download the v3 releases from github directly, as well as the docker images from docker hub.
