### ISSUE TITLE
Snap package - stable for minor version

### ISSUE THREAD

**Issue by raj2202022** [mikefarah/yq#1118]
In snap, latest/stable is pointing to 4.20.1.

4.20.1 has a bug which you have fixed in 4.20.2. 4.20.2 is latest/edge.

So the upgrade from 4.18.1 to 4.20.1 release broke our CD.

Can you make a stable of minor version in snap?

**Comment by mikefarah** [comment]
Done!

**Comment by Gowlar** [comment]
@mikefarah  This has stopped working for me too  this morning - 4.20.2 - the cmd times out

**Comment by raj2202022** [comment]
@mikefarah I was looking for stable of minor version i.e. 4.18/stable would point to 4.18.1. So this way I control the upgrades. Below is an example of kubectl offering stable for minor version.

 latest/stable:    1.23.4         2022-02-19 (2341) 10MB classic
  latest/candidate: 1.23.4         2022-02-19 (2341) 10MB classic
  latest/beta:      1.23.4         2022-02-19 (2341) 10MB classic
  latest/edge:      1.23.4         2022-02-19 (2341) 10MB classic
  1.24/stable:      –
  1.24/candidate:   –
  1.24/beta:        –
  1.24/edge:        1.24.0-alpha.3 2022-02-16 (2333) 10MB classic
  1.23/stable:      1.23.4         2022-02-18 (2341) 10MB classic
  1.23/candidate:   1.23.4         2022-02-18 (2341) 10MB classic
  1.23/beta:        1.23.4         2022-02-18 (2341) 10MB classic
  1.23/edge:        1.23.4         2022-02-18 (2341) 10MB classic
  1.22/stable:      1.22.7         2022-02-18 (2338) 10MB classic
  1.22/candidate:   1.22.7         2022-02-18 (2338) 10MB classic
  1.22/beta:        1.22.7         2022-02-18 (2338) 10MB classic
  1.22/edge:        1.22.7         2022-02-18 (2338) 10MB classic

**Comment by mikefarah** [comment]
Yeah that would require more manual work on maintaining snap than I'm prepared to put in. I'm not sure why snap doesn't already allow you to specify previously released versions like other version managers. If you want control, I'd just download the releases from github directly :/

**Comment by mikefarah** [comment]
The latest version has been published to snap - please raise a separate issue if there are any issues with that version.
