### ISSUE TITLE
Usage of "-i" together with "," breaks in v4.17.2

### ISSUE THREAD

**Issue by zegl** [mikefarah/yq#1119]
**Describe the bug**

Starting with yq v4.17.2, the behaviour of `,` changed, and can now easily produce invalid yaml as the keys in the output are duplicated.

I don't know if the bug is the breakage of `,`, or the fact that you could use `,` in the first place. But I'm raising the issue anyway, to let you decide what to do. :-)

As a workaround, we've replaced `,` with `|` in the command(s) where we hit this bug, which might be how we should have used yq all along.

Version of yq: v4.17.2
Operating system: mac
Installed via: binary release

**Input Yaml**

example.yml:
```yaml
foo: foo
bar: bar
```

**Command**
The command you ran:

```
yq eval -i "
    .foo += \"add\",
    .bar += \"add\",
    .extra.this += \"add\"
  " example.yml
```

**Actual behavior**

```yaml
foo: fooadd
bar: baradd
extra:
  this: add
foo: fooadd
bar: baradd
extra:
  this: add
```

**Expected behavior**

```yaml
foo: fooadd
bar: baradd
extra:
  this: add
```

**Additional context**

I created a small program to test this input and command towards multiple versions of yq. Here is the program and it's output:

```bash
#!/usr/bin/env bash

cat <<EOF > original.yml
foo: foo
bar: bar
EOF

run() {
  version=$1

  echo ">>> yq ${version}"

  wget -q "https://github.com/mikefarah/yq/releases/download/${version}/yq_darwin_arm64" -O "yq_${version}"
  chmod +x "yq_${version}"

  cp original.yml "test-${version}.yml"
  "./yq_${version}" eval -i "
    .foo += \"add\",
    .bar += \"add\",
    .extra.this += \"add\"
  " "test-${version}.yml"

  echo
  cat "test-${version}.yml"
  echo

  echo ">>> yq ${version}"
}

run v4.20.2
run v4.17.2
run v4.16.2
run v4.9.0
````

*Output*

```
>>> yq v4.20.2

foo: fooadd
bar: baradd
extra:
  this: add
foo: fooadd
bar: baradd
extra:
  this: add

>>> yq v4.20.2
>>> yq v4.17.2

foo: fooadd
bar: baradd
extra:
  this: add
foo: fooadd
bar: baradd
extra:
  this: add

>>> yq v4.17.2
>>> yq v4.16.2

foo: fooadd
bar: baradd
extra:
  this: add

>>> yq v4.16.2
>>> yq v4.9.0

foo: foo
bar: bar

>>> yq v4.9.0
```

**Comment by mikefarah** [comment]
Yep for the examples you provided, your supposed to use '|'  :) The fact that it worked before is strange...but unintended.

The `,` operator is used for creating a union - primary if you wanted to create an array: [1,2,3] then you'd use comma to collect the individual numbers together.
