### ISSUE TITLE
JQ error through Shell Script Only

### ISSUE THREAD

**Issue by pablojmarti** [mikefarah/yq#112]
```
jq: error: r/0 is not defined at <top-level>, line 1:
r
jq: 1 compile error
yq: Error running jq: IOError: [Errno 32] Broken pipe.
```

I'm getting this from trying to parse a file through a shell script.
**Usage:**
```
parse_yaml(){
  $(yq r test.yml)
}
#
parse_yaml
```

However if i run that from the cli itself it is fine.

**Comment by mikefarah** [comment]
That's a strange error - not sure why it mentions jq as it has no dependency on it.

What's the test.yml file?

**Comment by mikefarah** [comment]
Wait $(yq r test.yml) will evaluate the result of test.yml then try to execute it in bash. 

In this case it will be trying to execute the yaml output in bash, causing that error
