### ISSUE TITLE
Decoding properties files and ignoring environment variables resolution

### ISSUE THREAD

**Issue by embee1981** [mikefarah/yq#1127]
Is it possible when decoding properties files to yaml using v4.21.x to ignore ${} usage and just output as is?

e.g.
`$ echo "the=${myenvnonexisting} meows" | yq -p=props | cat`
`the: meows`

when I'm expecting 

`the: ${mynenvnonexisting} meows`

I've some property files that I'd like to convert over using the new decoding feature but I can't work out how to defer trying to resolve potential environment variable substitution.

**Comment by mikefarah** [comment]
Ah yep - I hadn't noticed that the properties parser lib I'm using automatically interpolates those properties - will fix in the next release by turning that off (and forcing usage of yq's `envsubst` to interpolate)

**Comment by embee1981** [comment]
Thanks Mike :-)

**Comment by mikefarah** [comment]
Fixed in 4.22.1
