### ISSUE TITLE
Error: unknown command for all commands

### ISSUE THREAD

**Issue by trampster** [mikefarah/yq#1158]
yq doesn't seem to recognise any commands
```
yq '.a.b.c' sample.yaml
Error: unknown command ".a.b.c" for "yq"
```
```
yq '.a.b.c = "fred"' sample.yaml
Error: unknown command ".a.b.c = \"fred\"" for "yq"
```
Version of yq:  version 4.14.1
Operating system: alphine linux (docker container)
Installed via: apk

**Comment by trampster** [comment]
I thought maybe despite the reported version it was someone using the V3 vesion. .However the V3 commands don't work either.

**Comment by mikefarah** [comment]
Sorry for the confusion, prior to v4.18.x you must specify the 'eval (e) or eval-all (ea)' command. In 4.18+ 'e' became the default.

See https://github.com/mikefarah/yq/#notice-for-v4x-versions-prior-to-4181 for more details.

**Comment by trampster** [comment]
Oh I guess you don't follow simver, this is a breaking change without the major version rolling

**Comment by mikefarah** [comment]
IMO It's not  a breaking change as it's fully backwards compatible. The old commands still work as they were documented. It's a new feature that only works with new versions. 

Just like any other new features I add to `yq` - they're only available in the new versions.

Again, apologies for the confusion.

**Comment by GuyPaddock** [comment]
@mikefarah Your statement does not make sense. None of the documented commands for 4.x work with versions of 4.x before 4.18, and none of the documented commands for 3.x work with the 4.x version. So... what documentation are you referring to?

Also... could you please add a note to the top of all the 4.x documentation that states it only applies to versions after 4.18? There's no version selector that would enable someone to show only docs for 4.0 to 4.18, and the version in Ubuntu LTS is 4.16.2, so we run into this issue ALL the time and there is nothing in docs about it.

**Comment by dbsanfte** [comment]
So much time lost to this nonsense, again. Please, please update the docs.

**Comment by aryangosling** [comment]
Use 4.44 or a newer version
