### ISSUE TITLE
Split into files uses `.yml` file ending

### ISSUE THREAD

**Issue by Wikiwix** [mikefarah/yq#1165]
### Describe the bug

Files created by `--split-exp` use the `.yml` file ending althoguh `yaml` is the [recommended file ending](https://yaml.org/faq.html)

Version of yq: 4.24.2
Operating system: linux
Installed via: homebrew

###  Command
The command you ran:

```shell
echo '[1,2,3]' | yq '.[]' - --split-exp='"test-" + .'
```

### Actual behavior

The files

* `file-1.yml`,
* `file-2.yml` and
* `file-3.yml`

where created

### Expected behavior

The files

* `file-1.yaml`,
* `file-2.yaml` and
* `file-3.yaml`

are created

### Additional context
If there are other cases where `yq` creates new files, I suspect the `.yml` ending might be in use as well

**Comment by mikefarah** [comment]
Ah I see - I should have done that from the start. I'm reluctant to do this now as users already have scripts that assume '.yml'. 

Since this is seems to be only a preference of the standards and `.yml` is generally accepted I do not think it's worth adding a feature to toggle to '.yaml'.

**Comment by Wikiwix** [comment]
Hmm, so a change for `5.0` then 🙈.

When I noticed `.yml` files are created, I somehow expected using a filename like `"bla" + .a + ".yaml"` would "deactivate" the autogenerated file ending.

So perhaps a flag to disable the addition of a file ending would be a worthwhile addition?

Besides allowing the proper `.yaml` ending, this enables the use of other file endings for special use cases as well.

**Comment by mikefarah** [comment]
Actually that's not a bad idea - if the resulting contains ".yaml" or ".yml" then I can skip over adding a ".yml"

**Comment by Wikiwix** [comment]
Introducing that without a flag still might break some scripts though :/

Which is why I suggested a flag (which has the added benefit of allowing *any* file ending)

**Comment by joebowbeer** [comment]
I use the split feature to separate `kustomize build` and `helm template` output into separate files, but it would be even better for me and most k8s users if it would save with `.yaml` extension or allow me to choose this as an option.

**Comment by tschifftner** [comment]
@joebowbeer A workaround is to use [kubectl-slice](https://github.com/patrickdappollonio/kubectl-slice)

```bash
kubectl slice -f source.yaml -t '{{.metadata.name | lower}}.yaml' -o ./source
```

**Comment by mikefarah** [comment]
Fixed in v4.25.3 - if you have an extension in the split-file-exp it will no longer add '.yml'

**Comment by bluebrown** [comment]
> Fixed in v4.25.3 - if you have an extension in the split-file-exp it will no longer add '.yml'

so how do you use that? And how do you specify an output dir?

**Comment by Wikiwix** [comment]
@bluebrown By defining a path as part of the filename given in `--split-exp`. Be aware that the directory must exist already:

```console
$ mkdir dir/
$ echo '[1,2,3]' | yq '.[]' - --split-exp='"dir/test-" + . + ".yaml"'
$ ls dir/
test-1.yaml  test-2.yaml  test-3.yaml
```

**Comment by iosifnicolae2** [comment]
> @bluebrown By defining a path as part of the filename given in `--split-exp`. Be aware that the directory must exist already:
> 
> ```
> $ mkdir dir/
> $ echo '[1,2,3]' | yq '.[]' - --split-exp='"dir/test-" + . + ".yaml"'
> $ ls dir/
> test-1.yaml  test-2.yaml  test-3.yaml
> ```

Any idea how to let `yq` also create the directories? (we're generating the directories dynamically)
