### ISSUE TITLE
Show file name with output if the file path is a glob

### ISSUE THREAD

**Issue by 1Mark** [mikefarah/yq#1169]
**Please describe your feature request.**
`yq  ".a.b.c.d.e" *.yaml`
The output is only escaped by `---` but I have several files matching this.

**Describe the solution you'd like**
It would be better to mention the file name either by default or with a flag instead of `---`

**Comment by mikefarah** [comment]
You can use the 'filename' operator (documented https://mikefarah.gitbook.io/yq/operators/file-operators#get-filename) to get the filename.

`---` is a yaml standard for document separation.

If you like, you could do something like:


```
yq ".a.b.c.d.e |  (. lineComment .= filename)" *.yaml
```

This will add the filename as a comment to each match.

**Comment by 1Mark** [comment]
@mikefarah would you be open to an MR that adds this as a flag?

**Comment by 1Mark** [comment]
OK here is an example of it not working

a.yaml
```
a_nested_map:
  another_nested_map:
    hello: one
```

b.yaml
```
a_nested_map:
  another_nested_map:
    hello: two
```

```
yq ".a_nested_map.another_nested_map.hello |  (. lineComment |= filename)" *.yaml
```

Returns
```
one
---
two
```

Therefore it returns the same thing as

```
yq .a_nested_map.another_nested_map.hello *.yaml
```

What I expected it to return is

```
a.yaml
one
b.yaml
two
```

Format is not important but you should be able to differentiate between them.

**Comment by mikefarah** [comment]
Ah I see - in this case, the expression returned a scalar string value - which yq automatically unwraps and prints the raw value.

Normally that's what you'd want instead of seeing quoted strings, or any surrounding comments on values.

For this scenario, you could:

a) tell yq not to unwrap:
```
yq --unwrapScalar=false ".a_nested_map.another_nested_map.hello |  (. lineComment |= filename)"
```

```bash
one # examples/data1.yaml

---
two # examples/data2.yaml
```


or b) return some sort of structured response - you can get your expected format by doing:
```
yq --no-doc '.a_nested_map.another_nested_map.hello | (filename, .)' *.yaml
```

```bash
examples/data1.yaml
one
examples/data2.yaml
two
```

c) something like:

```
yq '.a_nested_map.another_nested_map.hello | [{"v": ., "f": filename}]' --no-doc *.yaml

- v: one
  f: examples/data1.yaml
- v: two
  f: examples/data2.yaml

```

Hope that helps!

**Comment by 1Mark** [comment]
It does indeed. Lastly is there a way to ensure the colour of the filename differs from the output to easily differentiate between them?

**Comment by 1Mark** [comment]
That's how I imagine yq. Filename is optional and then it searches recursively unless you give a filename. Then for each result it puts the filename above it in a separate colour. Exactly like ripgrep (rg)
