### ISSUE TITLE
build on linux fails with 'undefined: sort.SliceStable'

### ISSUE THREAD

**Issue by z00m1n** [mikefarah/yq#117]
user@host:~$ cat /etc/lsb-release 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"

    user@host:~$ sudo aptitude install -y golang-go
      ...

    user@host:~$ go version
    go version go1.6.2 linux/amd64

    user@host:~$ GOPATH=~/go go get github.com/mikefarah/yq
    # github.com/mikefarah/yq
    go/src/github.com/mikefarah/yq/data_navigator.go:199: undefined: sort.SliceStable

**Comment by mikefarah** [comment]
Hmm looks like it didn't install the dependencies :/

Can you try the following:

```
./scripts/devtools.sh
make local vendor
make local build
```

I think this needs to be streamlined a little

**Comment by kenjones-cisco** [comment]
The root cause is the version of Go.  `sort.SliceStable` was not added until Go v1.8 (https://golang.org/doc/go1.8#sort_slice)
