### ISSUE TITLE
error accessing dict value by key containing space

### ISSUE THREAD

**Issue by williamjoy** [mikefarah/yq#1170]
**Describe the bug**
Access dict value by key (containing space) getting errors

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.22.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
space in key: 123
no_space: 456
```

**Command**
The command you ran:
```
yq '."space in key"' data1.yaml
```

**Actual behavior**

```yaml
Error: parsing expression: Lexer error: could not match text starting at 1:9 failing at 1:11.
	unmatched text: "in"
```

**Expected behavior**

```yaml
123
```

**Additional context**
```bash
yq '."no_space"' data1.yml
456
```

`jq` is working `jq-1.6`

```
 yq  data1.yml -ojson | jq '."space in key"'
123
```

**Comment by mikefarah** [comment]
Interesting I didn't realise you could use that syntax with jq.

`yq` uses this syntax: https://mikefarah.gitbook.io/yq/operators/traverse-read#keys-with-spaces which is also supported by jq
