### ISSUE TITLE
There are no 4.24.* releases on the release page

### ISSUE THREAD

**Issue by miketimofeev** [mikefarah/yq#1173]
**Describe the bug**
Our team installs yq to the images used by GitHub actions and Azure pipelines hosted agents https://github.com/actions/virtual-environments
Recently we noticed that yq version has been downgraded on the image as versions 4.24.* are not presented on the releases page https://github.com/mikefarah/yq/releases
Is it intended?

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.24.*
Operating system: n\a
Installed via: n\a

**Actual behavior**

https://github.com/mikefarah/yq/releases contains 4.24.*

**Expected behavior**
https://github.com/mikefarah/yq/releases contains only 4.23.*

**Additional context**
n\a

**Comment by mikefarah** [comment]
I am looking into this - not sure what happened!

**Comment by mikefarah** [comment]
It looks like the github action bot never created the release - even though it appears to have completed successfully. I never received an email from it saying it created the release - and didn't notice! I'll try to get some time this week into fixing it up :/

**Comment by mikefarah** [comment]
Okay I've switched to another github release action and it seems to work well :)

**Comment by miketimofeev** [comment]
@mikefarah thank you!
