### ISSUE TITLE
Update a single doc with eval-all

### ISSUE THREAD

**Issue by bnason** [mikefarah/yq#1175]
Is there any way to search for and update a single doc with eval-all?

For instance, i'd like to update just the doc with `name == bar` and set some extra data:
```
---
name: foo
---
name: bar
```

```
---
name: foo
---
name: bar
alias: baz
```

**Comment by mikefarah** [comment]
Yep you can just:

```bash
yq '(select(.name == "bar") | .alias) = "baz"' file.yaml
```
