### ISSUE TITLE
Front matter extraction fails with error

### ISSUE THREAD

**Issue by eableson** [mikefarah/yq#1178]
Hi there, I'm looking to use yq to bulk extract the front matter from some markdown files in order to start normalising the key names. But I'm running into an issue with some files hard failing as they seem to be going outside the bounds of the front matter.

Running 
`yq --front-matter=extract *.md` 
returns 
`Error: bad file 'ewa-mbp.md': yaml: line 17: did not find expected <document start>`

The contents of the file are:

```
---
name: ewa-mbp
ip: 192.168.10.196
location: Office
is_vm: false
role: workstation
mac: "f0:2f:4b:02:45:d8"
---
## ewa-mbp

Primary work computer. 
- MacBook Pro (14-inch, 2021)
- serial number xxxxxxxx
- 32 GB RAM, 2TB internal SSD

Time Machine backup to the syn-office01 Synology

### System report
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro18,3
  Chip:	Apple M1 Pro
  Total Number of Cores:	8 (6 performance and 2 efficiency)
  Memory:	32 GB
  System Firmware Version:	7459.101.3
  OS Loader Version:	7459.101.3
  Serial Number (system):	xxxxxxxx
  Hardware UUID:	FA70D62A-9BA1-5516-928B-BB6B0FBA6674
  Provisioning UDID:	00006000-000258861ED8801E
  Activation Lock Status:	Disabled
```

Also on the files that pass the checks, it is outputting the entire file and not simply the YAML front matter.

Running version 4.24.2 on Monterey installed via brew

**Comment by mikefarah** [comment]
That's odd - the file works for me. What happens if you specify the file instead of using glob (though it worked with glob for me as well)? Can you give me the log when running with --verbose?

**Comment by eableson** [comment]
Interesting. When I run it directly (no globbing) it works as expected 
and only extracts the front matter. Globbing results in random files not 
working (although it seems linked to content that has lines that could 
be interpreted as key/value pairs) and the output includes the file 
content as well as the front-matter.

Verbose dump attached

On 14 Apr 2022, at 4:07, Mike Farah wrote:

> That's odd - the file works for me. What happens if you specify the 
> file instead of using glob (though it worked with glob for me as 
> well)? Can you give me the log when running with --verbose?
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/mikefarah/yq/issues/1178#issuecomment-1098638135
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>

***@***.*** Networking % yq --front-matter=extract *.md --verbose           
07:20:00 evaluateSequence [DEBU] pipingStdIn: false
07:20:00 evaluateSequence [DEBU] stat.Mode(): Dcrw--w----
07:20:00 evaluateSequence [DEBU] ModeDir: ----------
07:20:00 evaluateSequence [DEBU] ModeAppend: ----------
07:20:00 evaluateSequence [DEBU] ModeExclusive: ----------
07:20:00 evaluateSequence [DEBU] ModeTemporary: ----------
07:20:00 evaluateSequence [DEBU] ModeSymlink: ----------
07:20:00 evaluateSequence [DEBU] ModeDevice: D---------
07:20:00 evaluateSequence [DEBU] ModeNamedPipe: ----------
07:20:00 evaluateSequence [DEBU] ModeSocket: ----------
07:20:00 evaluateSequence [DEBU] ModeSetuid: ----------
07:20:00 evaluateSequence [DEBU] ModeSetgid: ----------
07:20:00 evaluateSequence [DEBU] ModeCharDevice: c---------
07:20:00 evaluateSequence [DEBU] ModeSticky: ----------
07:20:00 evaluateSequence [DEBU] ModeIrregular: ----------
07:20:00 evaluateSequence [DEBU] ModeType: Dc---------
07:20:00 evaluateSequence [DEBU] ModePerm: -rw--w----
07:20:00 evaluateSequence [DEBU] using front matter handler
07:20:00 Split [DEBU] yamlTempFile: /var/folders/wk/l8zxj_4x10d74580s9_lq80h0000gn/T/temp782943871
07:20:00 processArgs [DEBU] processed args: [CRS309-1.md /var/folders/wk/l8zxj_4x10d74580s9_lq80h0000gn/T/temp782943871 LINKSYS45474.md LINKSYS45959.md LINKSYS47324.md Printer Relay.md chambre-1er.md chambre-2eme.md gw-mmv2.infrageeks.lan.md gw.infrageeks.lan.md gwoffice.infrageeks.lan.md rax80.md séjour.md ubiquiti-home.md]
07:20:00 maybeFile [DEBU] checking 'CRS309-1.md' is a file
07:20:00 maybeFile [DEBU] error: <nil>, dir: false
07:20:00 maybeFile [DEBU] result: true
07:20:00 ParseExpression [DEBU] Parsing expression: []
07:20:00 ConvertToPostfix [DEBU] postfix processing currentToken )
07:20:00 ConvertToPostfix [DEBU] opstackLen: 0
07:20:00 ConvertToPostfix [DEBU] PostFix Result:
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 0, mappedDoc.Document: 0
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
name: csr309-1
location: Office
role: network
ip: 192.168.10.223
mac: c4:ad:34:e7:d3:66
admin_url: http://192.168.10.223/index.html#system
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 0, mappedDoc.Document: 1
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
|-
  Mikrotik 8 port 10GbE SFP+ switch for core office networking.
  Separate VLANs for the regular a storage network (VLAN 100).
  ![[backup.swb]]

07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 1, mappedDoc.Document: 0
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
name: infrageeksiot
location: Office
role: Network
ip: DHCP
mac: dc:a4:ca:5c:51:ed
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 0, mappedDoc.Document: 0
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
name: LINKSYS45474
ip: DHCP
location: House
room: Upstairs guest room
role: network
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 0, mappedDoc.Document: 1
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
Linksys Velop Wifi 6 Mesh base station. - configured in bridge mode - Note that they seem to have autogenerated IP addresses in the 192.168.20.0/24 subnet (maybe on a separate VLAN)
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 1, mappedDoc.Document: 0
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
name: LINKSYS45959
ip: DHCP
location: House
room: Electrical closet in the kitchen
role: network
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 0, mappedDoc.Document: 1
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
Linksys Velop Wifi 6 Mesh base station. - configured in bridge mode - Note that they seem to have autogenerated IP addresses in the 192.168.20.0/24 subnet (maybe on a separate VLAN?)
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 1, mappedDoc.Document: 0
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
name: LINKSYS47324
ip: DHCP
location: House
room: Dressing
role: network
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 0, mappedDoc.Document: 1
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
Linksys Velop Wifi 6 Mesh base station. - configured in bridge mode - Note that they seem to have autogenerated IP addresses in the 192.168.20.0/24 subnet (maybe on a separate VLAN?)
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 1, mappedDoc.Document: 0
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
name: printer-relay
location: Office
role: network
ip: DHCP
mac: 9c:7b:ef:86:37:bc
admin_url:
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 0, mappedDoc.Document: 1
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
Airport Express use to connect the HP printer to the Wifi network.
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 1, mappedDoc.Document: 0
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
name: CHAMBRE-1ER
location: House
room: Bedroom
ip: DHCP
role: network
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 0, mappedDoc.Document: 1
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
Apple AirPort Extreme: Airplay for the bedroom
MAC: 7c:d1:c3:c8:7d:53
MAC: 7c:d1:c3:d1:8b:76
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 1, mappedDoc.Document: 0
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
name: CHAMBRE-2EME
location: House
room: Upstairs guest room
ip: DHCP
role: network
07:20:00 PrintResults [DEBU] done printing results
07:20:00 GetMatchingNodes [DEBU] getMatchingNodes - nothing to do
07:20:00 PrintResults [DEBU] PrintResults for 1 matches
07:20:00 PrintResults [DEBU] -- print sep logic: p.firstTimePrinting: false, previousDocIndex: 0, mappedDoc.Document: 1
07:20:00 PrintDocumentSeparator [DEBU] -- writing doc sep
---
Apple AirPort Extreme: Airplay for the guest room
MAC: 8:37:37:40:fa:1c
MAC: 28:37:37:48:ba:f4
07:20:00 PrintResults [DEBU] done printing results
07:20:00 tryRemoveTempFile [DEBU] Removing temp file: /var/folders/wk/l8zxj_4x10d74580s9_lq80h0000gn/T/temp782943871
Error: bad file 'gw-mmv2.infrageeks.lan.md': yaml: line 13: mapping values are not allowed in this context
***@***.*** Networking %

**Comment by mikefarah** [comment]
Ok I see now - `yq` only processes the _first_ file for front matter. This ties in with how the write inplace flag works - it only writes to the first file. This makes more sense when working with 'process' instead of 'extract' - typically you'd want to write inplace the changes, and so you can only process one file at a time. To do what you need, you can use `find` with `yq`:

```bash
find -name  "*.md -exec yq --front-matter="extract" {} \;
```

**Comment by mikefarah** [comment]
I've updated the front-matter doc to include this info

**Comment by eableson** [comment]
Got it - so basically it treats the rest of the files as the 
continuation of the first file after the initial front matter.

Thanks!
