### ISSUE TITLE
Trailing zeroes stripped out of field

### ISSUE THREAD

**Issue by salazar** [mikefarah/yq#118]
Suppose you have a YAML file with a field such as `field: 1.30`; the trailing zero will be dropped:

```
> ./yq_darwin_amd64 r yaml field
1.3
``` 

Version:
```
> ./yq_darwin_amd64 -V
yaml version 1.14.0-dev
```

**Comment by salazar** [comment]
Reproduced as well with version 1.13.0.

**Comment by mikefarah** [comment]
Yep - that's because this reads the data as a number, processes it, then spits it out. It doesn't have the sophistication to remember the number of decimal places etc. 

At this time I don't intend on fixing this.
