### ISSUE TITLE
Updating a value doesn't work when there are comments in the YAML file

### ISSUE THREAD

**Issue by SladeRun14** [mikefarah/yq#119]
This command:
`export role_id=24c74020-4cb1-e693-b86a-b066eebfd6d3`
`yq w -i bootstrap.yml spring.cloud.vault.app-role.role-id $role_id`
[bootstrap.yml.txt](https://github.com/mikefarah/yq/files/1681729/bootstrap.yml.txt)

Removes those portions of a standard Spring bootstrap.yml  file that either are comments or follow comments. File attached.

**Comment by mikefarah** [comment]
Yep, sorry these are known issues. 
yq uses gopkg.in/yaml.v2 to parse the Yaml - and that package 
a) will strip out comments
b) only supports one yaml document per file though apparent a fix is on the way for this?
 (https://github.com/mikefarah/yq/issues/9)

**Comment by mikefarah** [comment]
Closing as dupes of https://github.com/mikefarah/yq/issues/19 and https://github.com/mikefarah/yq/issues/9
