### ISSUE TITLE
Strange formatting when the key size is greater than 128 characters

### ISSUE THREAD

**Issue by shoelzle** [mikefarah/yq#1192]
**Describe the bug**
The key size in dicts seems to be limited to 128 characters.

Version of yq: 4.24.5
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
values.yaml:
```yaml
# this is ok
THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS: "egal"
# too long
TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO: "egal"
```

**Command**
The command you ran:
```
yq . values.yaml
```

**Actual behavior**

```yaml
# this is ok
THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS: "egal"
# too long
? TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO
: "egal"
```

**Expected behavior**

```yaml
# this is ok
THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS_OK_THIS_IS: "egal"
# too long
TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO_LONG_TOO: "egal"
```

**Comment by mikefarah** [comment]
I can replicate this. This is caused by the underlying yaml parser go-yaml.

For what it's worth - it's still valid yaml, it's just a formatting choice by the library. I'm guessing to split the entry so that they key is on one line 🤷🏼 

See https://stackoverflow.com/questions/33987316/what-is-a-complex-mapping-key-in-yaml for more details. Feel free to raise an issue against go-yaml v3.

**Comment by shoelzle** [comment]
Thanks for taking care @mikefarah.
I raised an issue against go-yaml: https://github.com/go-yaml/yaml/issues/849
