### ISSUE TITLE
Using the function `type` raises a lexer exception

### ISSUE THREAD

**Issue by SebastienMichoy** [mikefarah/yq#1195]
**Describe the bug**
Using the function `type` raises a lexer exception:
```shell
Error: parsing expression: Lexer error: could not match text starting at 1:5 failing at 1:7.
	unmatched text: "ty"
```

Version of yq: 4.24.5
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
- "a string"
- "another string"
```

**Command**
The command you ran:
```
yq '. | type' data1.yml
```

**Actual behavior**

```yaml
Error: parsing expression: Lexer error: could not match text starting at 1:5 failing at 1:7.
    unmatched text: "ty"
```

**Expected behavior**

```yaml
"array"
```

**Additional context**
I've tried to compare with the output of [`jq`](https://github.com/stedolan/jq):
```Shell
$> yq --version
yq (https://github.com/mikefarah/yq/) version 4.24.5
$> jq --version
jq-1.6
$> echo '[0, false, [], {}, null, "hello"]' | yq '. | type'
Error: parsing expression: Lexer error: could not match text starting at 1:5 failing at 1:7.
	unmatched text: "ty"
$> echo '[0, false, [], {}, null, "hello"]' | jq '. | type'
"array"
```

**Comment by mikefarah** [comment]
Ah I see - in yaml _tags_ represent the type information https://yaml.org/spec/1.2.2/#3212-tags so there is a `tag` function.

That said - I should create an alias `type` that calls this, which I can do in the next release. Till then, use `tag`.

**Comment by SebastienMichoy** [comment]
Oh! Thanks for the explanation and the quick response!

**Comment by mikefarah** [comment]
Added alias in 4.25.1
