### ISSUE TITLE
[Feature Request] SortKeys custom user defined order.

### ISSUE THREAD

**Issue by andrewcrook** [mikefarah/yq#1199]
I would like to be able to define, either on command-line or by a referenced text file, the order in which keys should be sorted.
I have use a text file as an example but could be another yaml file or JSON. Notice how it deals with ‘dog’ which isnt in the original yaml file i.e if it was there it would be before ‘apple'.

Given a sample.yml file of:
```yaml
a: apple
a: banana
a: cat
```

Given order.txt
you can extend this to include other type of data/keys
```
a: 
banana
cat
dog
apple
b:
parrot
kewi
car
```

And we run a command:
```bash
yq 'sort_by_custom()’ order.txt sample.yml 
```

it could output
```yaml
a: banana
a: cat
a: apple
```
Anyway you get the gist?

**Comment by mikefarah** [comment]
You can kind of do this with pick: https://mikefarah.gitbook.io/yq/operators/pick#pick-keys-from-map
The keys could be extracted to an environment variable (use the env operator to load) or another yaml file (use `load` to ..load).

So you'd have:

my_map_key_order.yaml:
```yaml
- banana
- cat
- dog
```

```bash
yq '.myMap |= pick(load(my_map_key_order.yaml))' file.yml
```

**Comment by mikefarah** [comment]
Just though of a caviet - if the key order is missing keys from the map, then they won't appear. However - you can use `unique` (which keeps the original order) to do this:

```bash
yq '.myMap |= pick( (load(my_map_key_order.yaml) + keys) | unique )' file.yml
```

Hope that makes sense.

**Comment by nkkowa** [comment]
For anyone who stumbles across this trying to figure out how to, for example, sort a Kubernetes configmap generated with `kubectl create ... -o yaml --dry-run` in the standard order, you can use the following:

`yq -i e '. |= pick(["apiVersion", "kind", "metadata", "data"])' my-configmap.yaml`

**Comment by gurpartb** [comment]
powershell hack
```ps1
$importance=@("targetRevision","repoURL","path")
$custom_sort=(cat platform.yaml | yq '.platform | keys' -o json | convertfrom-json | sort-object{ -($importance.IndexOf($_)) })-join '","'
cat platform.yaml | yq ".platform |= pick([""$custom_sort""])"
```
