### ISSUE TITLE
Unknow command on Linux Alpine

### ISSUE THREAD

**Issue by meyverick** [mikefarah/yq#1203]
**Describe the bug**
`yq '.a.b.c = "fred"' sample.yaml` returns `Error: unknown command ".a.b.c = \"fred\"" for "yq"`

I found the command in [https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3#updating-writing-documents](https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3#updating-writing-documents)

Version of yq: 4.14.1
Operating system: Linux Alpine
Installed via: `apk add --no-cache yq`

**Comment by mikefarah** [comment]
Hey that's an old version of yq - prior to 4.18 you need to specify 'e/eval' (which has become the default)
So basically
```
yq e '.a.b.c = "fred"' sample.yaml
```
