### ISSUE TITLE
apk package only has 4.14.1-r1 ?

### ISSUE THREAD

**Issue by DarwinJS** [mikefarah/yq#1204]
**Describe the bug**
The apk package seems stuck at 4.14.1-r1 - unless I am doing the install incorrectly (I followed the read me instructions).

**Comment by mikefarah** [comment]
Yep - that version is kindly maintained by @rmescandon - however that's quite out of date. Until he updates it - I recommend using either the github release version, docker, snap or homebrew which are the official channels I release to.

**Comment by mikefarah** [comment]
The APK package is no longer supported - please use another way to download yq (see readme)
