### ISSUE TITLE
A Documentation Example of select with a shell variable

### ISSUE THREAD

**Issue by DarwinJS** [mikefarah/yq#1205]
**Please describe your feature request.**

The examples for environment variables do not have any for select and the examples for select do not have any that include environment variables.

I believe I finally figured it out as `select(. == "${myval}" |= envsubst)'` but I'd love to see other syntaxes.

A complication for me was that the apk package is stuck on 4.14.1-r1  (reported in #1204) and the environment substitution seems broken in that release - or at least my above syntax is broken using 4.14.1-r1

**Comment by mikefarah** [comment]
They are documented here: https://mikefarah.gitbook.io/yq/operators/env-variable-operators, but you'll need to upgrade to a newer version
