### ISSUE TITLE
Output JSON in Colors

### ISSUE THREAD

**Issue by mzagaja** [mikefarah/yq#1208]
**Please describe your feature request.**
I wish that yq would colorize json output in the terminal.

**Describe alternatives you've considered**
I can pipe the output of `yq` to `bat -l json` or similar, but I like just using yq!

**Additional context**
Current JSON output:
<img width="2544" alt="image" src="https://user-images.githubusercontent.com/565647/166982112-6e051a54-2941-4918-8890-03df9bcef22c.png">

With bat!
<img width="2535" alt="image" src="https://user-images.githubusercontent.com/565647/166982175-7c7ae611-3e60-4e32-904b-b055e5be38ca.png">

**Comment by mikefarah** [comment]
Oops - I never noticed that was missing. Will fix in the next release.

**Comment by mikefarah** [comment]
Fixed in 4.25.2
