### ISSUE TITLE
Multiline values are printed with yaml indentation

### ISSUE THREAD

**Issue by solsson** [mikefarah/yq#121]
Is this the expected behavior?

```bash
# echo "multiline: |-" > test.yaml
# echo "  line 1" >> test.yaml
# echo "  line 2" >> test.yaml
# yq r test.yaml multiline
|-
  line 1
  line 2
# yq r -j test.yaml multiline | jq -r .
line 1
line 2
```

I had expected `yq r` to have the same output as the last command.

**Comment by mrgleeco** [comment]
this variant hits it too
```
msg: |
  hello world
  goodbye world
```

**Comment by Alaith** [comment]
See issue 104, https://github.com/mikefarah/yq/issues/104 
`yq` is returning the YAML output of your multi-line string.

What `yq` needs is a "raw" output flag like you're using in `jq`.

**Comment by solsson** [comment]
I'm ok with closing this as a duplicate.

**Comment by mikefarah** [comment]
I've been thinking about this a little more seeing it comes up often - I think it does make more (practical) sense to print out the multiline string instead of the block scalar.

Fixed in https://github.com/mikefarah/yq/releases/tag/1.14.1

**Comment by lifeofguenter** [comment]
what do I do if I require the string to be inserted as multi-line?
