### ISSUE TITLE
Not as expected when update multiline value in place 

### ISSUE THREAD

**Issue by glongzh** [mikefarah/yq#1218]
**Describe the bug**
when update multiline value in place, only the last line is updated

Version of yq: 4.25.1
Operating system: linux
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
aaa: |
  line 1
  line 2
```

data2.txt:
```
line 3
line 4
line 5
```

**Command**
```
cat data2.txt | xargs -I {} yq -i '.aaa ="{}"' data1.yml
```

**Actual behavior**
cat data1.yml
```yaml
aaa: |-
  line 5
```

**Expected behavior**

cat data1.yml
```yaml
aaa: |-
  line 3
  line 4
  line 5
```

**Comment by mikefarah** [comment]
I'm not sure what's going there, however I'd recommend using `load_str` which takes a filename as a parameter and loads the contents:

https://mikefarah.gitbook.io/yq/operators/load

**Comment by glongzh** [comment]
Thanks, `load_str` works
```
# yq '.aaa |= load_str("data2.txt")' data1.yml
aaa: |
  line 3
  line 4
  line 5
```
