### ISSUE TITLE
Errors get ignored

### ISSUE THREAD

**Issue by NickeZ** [mikefarah/yq#1220]
**Describe the bug**
I would like to select certain data and create strings out of it. But when there are no values I either want an error code, or no output.

Version of yq: **4.25.1**
Operating system: **Ubuntu 22.04**
Installed via: **go install**
```
$ yq --version
yq (https://github.com/mikefarah/yq/) version 4.25.1
```

**Command**
The command you ran:
```sh
$ echo '{"a": {"num": 1, "char": "a"}, "b": {"num": 2, "char": "b"}}' | yq -e '.[] | [.char, .num] | join(" ")'; echo $?
a 1
b 2
0

yq -n -e '.[] | [.char, .num] | join(" ")'; echo $?

0

yq -n -e '.[]'; echo $?
Error: no matches found
1
```

**Actual behavior**

Even though there are 0 matches, it doesn't fail. And instead if outputs a single empty line.

**Expected behavior**

I would expect it to fail.

**Workaround**

I can work around it with `| sed '/^$/d'`. Essentially remove empty lines.

**Comment by mikefarah** [comment]
`-e` only sets exit status if there are no matches or null or false is returned. The expression you have returns an empty string so it does not trigger.

You can do this: 

'.[] | [.char, .num] | join(" ") | select(. != "")'

to only select the strings that are not empty :)
