### ISSUE TITLE
Consider migrating to yq npmjs.com name

### ISSUE THREAD

**Issue by woodcockjosh** [mikefarah/yq#1221]
I exchanged emails with the owner of this package namespace in npm https://www.npmjs.com/package/yq and they agreed to release it to this project. 

Please consider migrating to the `yq` namespace. This is especially important when installing with yarn because of binary naming restrictions. Eg, binary names can only be named what the package name is.

Thank you

If you need their contact information you can find it here: https://github.com/teabyii

**Comment by mikefarah** [comment]
Hi - thanks for looking into this. I'm not quite sure what you mean by migrating to the yq namespace?

**Comment by woodcockjosh** [comment]
Sorry the word "migrating" probably isn't the right word. I meant that it would be nice if we could install yq with npm or yarn. With yarn the binary name, eg "yq" must match the package name.

**Comment by mikefarah** [comment]
Isn't npm and yarn a package manager for javascript libraries and apps?
