### ISSUE TITLE
Feature request: YAML validator

### ISSUE THREAD

**Issue by IdanAdar** [mikefarah/yq#124]
The request is in the summary - an option to validate a YAML file.

**Comment by mikefarah** [comment]
You can almost get away with
```
yq r sample.yaml > /dev/null
```

which will fail given an invalid yaml file, but it doesn't print errors to STDERR

**Comment by jodh-intel** [comment]
It would be great do have a validator as currently `yq` seems pretty tolerant to input:

```
$ yq read /etc/fstab >/dev/null; echo $?
0
```

**Comment by mikefarah** [comment]
This has been added to the latest release https://github.com/mikefarah/yq/releases/tag/3.0.1 :)

Note that it still depends on the underlying parser for errors - so it's as tolerant as the https://godoc.org/gopkg.in/yaml.v3 library..

**Comment by mikefarah** [comment]
See https://mikefarah.gitbook.io/yq/commands/validate for docs

**Comment by ccxuy** [comment]
Is there a validator can validate the schema of yaml?
i.e.:

schema.yaml:
```
data:
   a: string
   b: numer
   c:
     type: int
     optional: false
```

yq validate data.yaml
```
data:
   a: abc
   b: 1
```
