### ISSUE TITLE
``to_entries[]`` is not supported

### ISSUE THREAD

**Issue by SuperSandro2000** [mikefarah/yq#1246]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.25.2
Operating system: maclinux
Installed via: NixOS

**Input Yaml**
data1.yml:
```yaml
values:
  - global.region: qa-de-1
```

**Command**
```bash
yq '.values[] | to_entries[]' data1.yml
```

**Actual behavior**

```yaml
Error: Bad expression, please check expression syntax
```

**Expected behavior**

```yaml
key: global.region
value: qa-de-1
```

**Additional context**
This can be worked around with ``yq '.values[] | to_entries | .[]' data1.yaml`` but it would be cool to have the alias to be jq compatible.

**Comment by mikefarah** [comment]
Fixed (finally) in 4.40.7
