### ISSUE TITLE
Feature request: Read in numeric values from an environment variable with validation

### ISSUE THREAD

**Issue by csdev** [mikefarah/yq#1259]
**Please describe your feature request.**
It would be nice to have a function for reading in numeric values from an environment variable, with validation.

**Describe the solution you'd like**
If we have data1.yml like:
(please keep to around 10 lines )

```yaml
foo_id: 1234
```

And we run a command:

```bash
NEW_ID=5678 yq -i '.foo_id = intenv(NEW_ID)'
```

it could output

```yaml
foo_id: 5678
```

However
```bash
NEW_ID='[]' yq -i '.foo_id = intenv(NEW_ID)'
```
would return an error

**Describe alternatives you've considered**
Using `env` to read numeric values from the environment (as shown in the documentation) is not a good option in situations where there is untrusted user input.
`strenv` is safe from yaml injection since it always parses the input as a string, but we can't use it if we need a literal number.

**Additional context**
`floatenv` and `boolenv` would also be nice to have

**Comment by mikefarah** [comment]
I think the best way to be able to do this is to add an `error` operator that lets you add whatever validation you want. Will be available in the next release, you'll be able to do something like:


```yaml
name: Bob
favouriteAnimal: cat
```
then
```bash
numberOfCats="3" yq '
	with(env(numberOfCats); select(tag == "!!int") or error("numberOfCats is not a number :(")) | 
	.numPets = env(numberOfCats)
' sample.yml
```
will output
```yaml
name: Bob
favouriteAnimal: cat
numPets: 3
```

It is more wordy than what you have, but you could add whatever additional validation in there aswell (e.g. ensure it's a positive number).

**Comment by mikefarah** [comment]
Added `error` operator in v4.26.1
