### ISSUE TITLE
Add Dockerfile for building publishable images

### ISSUE THREAD

**Issue by arbourd** [mikefarah/yq#126]
Hey there! 

Anyway you'd accept a PR that includes a `Dockerfile` intent on distributing `yq` as a container. My use-case is for CI (Circle CI and Concourse can base jobs on containers).

My guess as to your preferred approach might be to use the current build steps to build the binary, and copy it into an Alpine container.

**Comment by mikefarah** [comment]
Hey sorry for the delayed response, I was on holiday. 

Actually I would have thought that you could use one of the prebuilt binaries https://github.com/mikefarah/yq/releases for alpine? 

Half the reason I used go was its portability ;) no need to install an interpreter, or runtime environment or extra libs.

**Comment by arbourd** [comment]
No worries Mike! Thanks for getting back to me :)

That's exactly what I'm doing at this time, but I'd love to have a dependable image that builds with that artifact every time there is a new release. IE: you cut a new release, and there is a new image with a semver tag on https://hub.docker.com/r/mikefarah/

I'm doing this myself, but I'd love to have it "official" (makes it easier for my job too -- they question images that aren't built by project owners). If this isn't something you want to maintain though, I understand (and feel free to close this)

**Comment by mikefarah** [comment]
Ah I see - I leave this for now, though if it gets enough votes I'm happy to look at it further

**Comment by spawnia** [comment]
Building an official image would be quite nice. The Dockerfile should be straightforward, just dump the binary into an alpine container.

This would improve portability even further and enable this to be used even more easily. A major use case for me would be running this in CI pipelines, where the task runners only have docker installed.

**Comment by dotLou** [comment]
Same here - I've built my own image but would prefer not to have to manage that myself either.

**Comment by mikefarah** [comment]
The tribe has spoken 👍 

I'll accept a PR for dockerisation

**Comment by spawnia** [comment]
I am on it!

**Comment by dotLou** [comment]
@spawnia Try this instead:

```dockerfile
FROM golang:1.9 as builder

WORKDIR /go/src/mikefarah/yq

COPY . /go/src/mikefarah/yq

RUN scripts/devtools.sh
RUN make local build

# Choose alpine as a base image to make this useful for CI, as many
# CI tools expect an interactive shell inside the container
FROM alpine:3.7

COPY --from=builder /go/src/mikefarah/yq/yq /usr/bin/yq
RUN chmod +x /usr/bin/yq

WORKDIR /workdir
```
