### ISSUE TITLE
Add aarch64 suffix (yq_linux_aarch64)  to arm based yq builds

### ISSUE THREAD

**Issue by nickytd** [mikefarah/yq#1261]
**Please describe your feature request.**
On arm based linux hardware uname -m returns aarch64 as a family architecture, instead of arm. Is it possible to alias arm based builds with aarch64 suffix as well?

```bash
uname -m
aarch64
```
Thanks

**Comment by mikefarah** [comment]
The cross-compiler I'm using doesn't support that sorry :(

**Comment by mbrevda** [comment]
Does this help? https://github.com/mitchellh/gox/issues/92#issuecomment-866472275
