### ISSUE TITLE
Contribute to docs?

### ISSUE THREAD

**Issue by karlhorky** [mikefarah/yq#1262]
Hi there, thanks for `yq`, it's great! And it's installed by default on GitHub Actions, which makes it very useful for CI!

I wanted to contribute a fix for the docs (`--output-format` instead of `--outputformat` on [the Working with CSV, TSV page](https://mikefarah.gitbook.io/yq/usage/csv-tsv)) but I couldn't find where they are here on GitHub... 🤔

If they're not on GitHub, maybe you would consider adding them here? Either in this same repo (ideal, so that the docs and code can't drift too far apart) or in another repository? I would have 3 or 4 contributions that I would like to make where I couldn't find the correct syntax.

**Comment by karlhorky** [comment]
Great, thanks for the tip @bengentil ! Opened #1267 👍

**Comment by mikefarah** [comment]
Good point, I'll add notes to the CONTRIBUTE guide

**Comment by karlhorky** [comment]
Great, thanks! Happy to close this either now or when the guide gets updated.

**Comment by mikefarah** [comment]
Cheers- I've updated Contribute.md

**Comment by karlhorky** [comment]
Thanks!
