### ISSUE TITLE
This project appears to be violating the GPLv2

### ISSUE THREAD

**Issue by gotmax23** [mikefarah/yq#1264]
This package depends on github.com/timtadh/data-structures, which is licensed under the GPLv2. Thus, it seems that this package also needs to be licensed under the GPLv2 or at least be distributed under that license and have a copy of it in the repo (e.g. https://github.com/ansible/ansible-lint#licensing).

**Comment by mikefarah** [comment]
Hey thanks @gotmax23, I've reached out to the author to see if that library can be released under another licensing option (he says he's willing on the github page).

**Comment by gotmax23** [comment]
Thanks. I notched this while reviewing the package for Fedora. I also filed https://github.com/timtadh/lexmachine/issues/39 but have not received a response thus far.

**Comment by mikefarah** [comment]
Update: I'm looking at switching to a new lexer https://github.com/alecthomas/participle - which is MIT (and doesn't seem to have libs underneath it that are GPLv2).

**Comment by mikefarah** [comment]
Also I still haven't received anything from Tim...

**Comment by timtadh** [comment]
Hi, I was out of office but I am writing you a email now with details.

**Comment by gotmax23** [comment]
Feel free to CC me (gotmax@e.email).

**Comment by mikefarah** [comment]
Thanks @timtadh, @gotmax23 for looking into the licensing issue of your published libraries - however yq will be moving to a new lexer/parser (https://github.com/alecthomas/participle if you're interested).

Participle is already licensed under MIT (which is permissive like BSD-3) it has an active community and it has some sophistication I'm interested in adding to yq expression language.

This has been updated in v4.26.1
