### ISSUE TITLE
yq fail to evaluate simple document with simple query

### ISSUE THREAD

**Issue by mxchist** [mikefarah/yq#1275]
**Describe the bug**
`yq eval` not process queries, and truncates input pattern.

Version of yq: 4.25.3
Operating system: Linux Ubuntu 20.04.1
Installed via: snap

**Input Yaml from STDIN**
```
apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  <...>
```

**Command**
`yq 'items' -`

**Actual behavior**
```
Error: parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:3.
	unmatched text: "it"
```
Notice, an error message contains an _it_ pattern instead of _items_. Also, an _apiVesion_ pattern truncates to _ap_ in error message (2 letters, like an _it_ of _items_), but _spec_ pattern truncates to _spe_ (3 letters).

**Expected behavior**
Give me the `spec` node

**Additional context**
I'm want bypass output of kubectl command to yq. A yaml document above is output of kubectl command:
`kubectl get deployments -o custom-columns=IMAGE:. -o yaml`.
A full command in bash with kubectl and yaml is:
`kubectl get deployments -o custom-columns=IMAGE:. -o yaml | yq 'items' -`

**Comment by mikefarah** [comment]
That's not a valid expression :) try:

```
yq '.items' -
```

See https://mikefarah.gitbook.io/yq/operators/traverse-read for more details
