### ISSUE TITLE
Feature Request: Append list items instead of overwriting

### ISSUE THREAD

**Issue by spawnia** [mikefarah/yq#128]
Merging yaml lists currently treats the list as a single value and either uses the values of the first or last given file:

````bash
/workdir # cat a.yml
list:
- a
/workdir # cat b.yml
list:
- b
/workdir # yq merge a.yml b.yml
list:
- a
/workdir # yq merge -x a.yml b.yml
list:
- b
````

It would be useful to have the ability of merging lists in a way such that additional items are appended, the output for the example would be the following:
````yaml
list:
- a
- b
````

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/v2.1.0 :)

Merge now has a [-a / --append] flag
