### ISSUE TITLE
Podman and SELinux labels

### ISSUE THREAD

**Issue by almereyda** [mikefarah/yq#1289]
**Please describe your feature request.**

I would like the README to mention, that SELinux labels need to be set for Podman volume mounts, if SELinux is enabled.

The current command examples for Podman, which are present in the README to date, do not feature a flag to the volume mounts, which prevents *Access denied* errors caused by SELinux.

**Describe the solution you'd like**

Every Podman run command should feature the `:z` label on the volume mount.

    -v "${PWD}":/workdir

turns into

    -v "${PWD}":/workdir:z

and can easily be applied to the shell function, too.

**Describe alternatives you've considered**

I was thinking about adding those labels directly to README, but was unsure about

- whether a shared ( `:z`) or private (`:Z`) label should be used.
- whether SELinux is standard on all contemporary Linux distributions and can be assumed the default case.

**Additional context**

* [Volumes and rootless Podman – Just another Linux geek](https://blog.christophersmart.com/2021/01/31/volumes-and-rootless-podman/)
* [Podman volumes and SELinux – Just another Linux geek](https://blog.christophersmart.com/2021/01/31/podman-volumes-and-selinux/)
* [docker - Podman volume mounts: When to use the :z or :Z suffix? - Unix & Linux Stack Exchange](https://unix.stackexchange.com/questions/651198/podman-volume-mounts-when-to-use-the-z-or-z-suffix)

**Comment by mikefarah** [comment]
So - you should always have `:z` whether you're using SELinux or not? or is this just a SELinux thing? Like if you don't have SELinux enabled, would the `:v` cause any side effects?

**Comment by almereyda** [comment]
Thanks for the quick response. My understanding of SELinux labelling and Podman is not perfect, but I can try to relate to your questions:

- You should always have `:z` when using Podman on a SELinux enabled machine, yes. I cannot make any informed statements about non-SELinux machines, but would guess it wouldn't be needed there.
2. I don't know if the labelling mechanism and associated file system hooks are present on non-SELinux machines. Someone would have to try it out, which cannot be me right now, due to lacking such unequipped machines. Some time I might have a moment to test this in a VM.

**Comment by mikefarah** [comment]
Cool - I've updated the readme to note this. Thanks for the info
