### ISSUE TITLE
Join keys with "." in the name with join, not wrapping with double quotes

### ISSUE THREAD

**Issue by robinAwallace** [mikefarah/yq#1295]
**Describe the bug**

Hello,
Im in the process of migration from yq3 to yq4. 
Im trying to join a path with a key that has `.` in its name. 
In yq3 the key receives double quotes around it but this is not the case when using `join` in yq4.

I also tried to force every key part from `path` to receive double quotes by adding `style` -> `path | .. style="double" | join(".")`.
But join just strips the double quotes away. 

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.26.1
Operating system: linux
Installed via: release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
foo.bar: 
  bar: ""
```

**Command**
The command you ran:
yq3
```console
yq read sample.yaml --tojson --printMode p "**(.==*)"
"foo.bar".bar
```
yq4
```console
yq  '.. | select(. == "*") | (path | join("."))' sample.yaml
foo.bar.bar
```

**Actual behavior**

```yaml
foo.bar.bar
```

**Expected behavior**

```console
"foo.bar".bar
```

**Additional context**

**Comment by mikefarah** [comment]
Here's how you can do it in v4 - though it's not as succinct as v3 (I may add a specific yaml_path operator when I get time):

```bash
yq '.. | select(tag != "!!seq" and tag != "!!map") | path | 
  with(.[] | select(contains(".")); . = "\"" + . + "\"") | 
  join(".")
' file.yaml
``` 

Explanation:
1. `.. | select(tag != "!!seq" and tag != "!!map") | path` - finds the path of all the scalar nodes (not maps or sequences)
2. `with(.[] | select(contains(".")); . = "\"" + . + "\"")` processes all the path elements that have a ".", wraps in quotes
3. joins the strings.


Side note, I updated the title as there were no double quotes in the input to begin with.
