### ISSUE TITLE
inplace overwrites symlinks with file contents

### ISSUE THREAD

**Issue by stephengroat-dd** [mikefarah/yq#1306]
**Describe the bug**
the `-i` `inplace` flag overwrites symlinks with the file contents instead of modifying the root file

Version of yq: 4.27.2
Operating system: macOS
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
this: should really work
but: it strangely didn't
```

data2.yml:
symlink to data1.yml

**Command**
The command you ran:
```
yq eval-all 'sort_keys(..)' data1.yml data2.yml
```

**Actual behavior**

data1.yml:
```yaml
but: it strangely didn't
this: should really work
```

data2.yml:
```yaml
but: it strangely didn't
this: should really work
```

**Expected behavior**

data1.yml:
```yaml
but: it strangely didn't
this: should really work
```

data2.yml:
symlink to data1.yml

**Additional context**

**Comment by shakibamoshiri** [comment]
Same bug here

```bash
yq --version
yq (https://github.com/mikefarah/yq/) version v4.34.1
```
using `-i` flags overwrites symlinks with file contents

**Comment by bitdivine** [comment]
I am unable to replicate this with the commands provided.  What am I missing?
```
$ vi data1.yaml
$ ln -s data1.yaml data2.yaml
$ ls -l data*yaml
-rw-rw-r-- 1 max max 50 Apr 17 05:41 data1.yaml
lrwxrwxrwx 1 max max 10 Apr 17 05:41 data2.yaml -> data1.yaml
$ grep . data*yaml
data1.yaml:this: should really work
data1.yaml:but: it strangely didn't
data2.yaml:this: should really work
data2.yaml:but: it strangely didn't
$ yq eval-all 'sort_keys(..)' data1.yaml data2.yaml
but: it strangely didn't
this: should really work
---
but: it strangely didn't
this: should really work
$ grep . data*yaml
data1.yaml:this: should really work
data1.yaml:but: it strangely didn't
data2.yaml:this: should really work
data2.yaml:but: it strangely didn't
$ ls -l data*yaml
-rw-rw-r-- 1 max max 50 Apr 17 05:41 data1.yaml
lrwxrwxrwx 1 max max 10 Apr 17 05:41 data2.yaml -> data1.yaml
```

**Comment by stephengroat-dd** [comment]
@bitdivine I agree, cannot replicate anymore on `4.43.1` installed via `homebrew` on `macOS`

**Comment by baburciu** [comment]
Hi @bitdivine, but is this behavior of losing the symlink expected with `yq -i` 🤔 
```shell
$ cat > data1.yml
this: should really work
but: it strangely didn't
^C
$ yq --version
yq (https://github.com/mikefarah/yq/) version v4.43.1
$ ln -s data1.yml data2.yml
$ yq eval-all 'sort_keys(..)' data1.yml data2.yml
but: it strangely didn't
this: should really work
---
but: it strangely didn't
this: should really work
$ ls -lt . | grep data
lrwxrwxrwx  1 root root     9 Jul 12 13:30 data2.yml -> data1.yml
-rw-r--r--  1 root root    50 Jul 12 13:28 data1.yml
$
$ yq -i '.components += "test"' data2.yml
$ ls -lt . | grep data
-rw-r--r--  1 root root    67 Jul 12 13:32 data2.yml   # <==
-rw-r--r--  1 root root    50 Jul 12 13:28 data1.yml
$ cat data2.yml
this: should really work
but: it strangely didn't
components: test
$
```
sorry to bother - didn't know if I should open another issue as this one (and its https://github.com/mikefarah/yq/issues/1306#issuecomment-1766333966) seems to match exactly the symptom I'm looking at

**Comment by bitdivine** [comment]
I would generally hope that updates are atomic, which means writing to a new file and then renaming the new file to the destination.  The rename is atomic, so guarantees that I get either a complete output or no change.  For -i, that means that I would normally expect the new file to be a different file from the original.  But this is just my expectation.  I'm not the author. :-)
