### ISSUE TITLE
Please update yq to a version > 4.18 on the Ubuntu Launchpad ppa:rmescandon/yq for Ubuntu LTS 20.04 and 22.04

### ISSUE THREAD

**Issue by sebma** [mikefarah/yq#1308]
@rmescandon Hi, 
The current version of yq is 4.27.2.

But yq version > 4.18 of yq could not be found in ppa repo below: https://launchpad.net/~rmescandon/+archive/ubuntu/yq : 
```bash
$ apt policy yq
yq:
  Installed: 4.16.2
  Candidate: 4.16.2
  Version table:
 *** 4.16.2 500
        500 http://ppa.launchpad.net/rmescandon/yq/ubuntu focal/main amd64 Packages
        100 /var/lib/dpkg/status
```

The ppa repo should be updated to include yq version > 4.18

**Command** On Ubuntu 20.04 LTS, after adding the repository and installing yq, the version is 4.16.2 :

```
$ yq --version
yq (https://github.com/mikefarah/yq/) version 4.16.2
```

**Comment by f0def** [comment]
Sill relevant...

**Comment by htchien** [comment]
The latest yq is 4.30.8 but the verion in ppa:rmescandon/yq is still 4.16.2....

**Comment by ryenus** [comment]
Better to reach out to [Roberto Mier Escandon](https://launchpad.net/~rmescandon), who is the owner of the PPA https://launchpad.net/~rmescandon/+archive/ubuntu/yq

**Comment by mikefarah** [comment]
Robert is not longer support the debian package, please use another way to install yq (see readme for options)

**Comment by cielavenir** [comment]
Hi there, I was able to generate .deb for newer yq

1. checkout a release version of yq git repository
2. extract debian directory from http://ppa.launchpadcontent.net/rmescandon/yq/ubuntu/pool/main/y/yq/yq_4.16.2.tar.xz and paste it to the git
3. install newer version of golang, it has to be >=1.21, 1.24 is preferred[^1] and tested[^2]
4. change debian/control and debian/rules accordingly
5. /usr/lib/go-1.24/bin/go mod vendor
6. debuild -uc -us

[^1]: As denoted in https://github.com/mikefarah/yq/blob/v4.47.1/go.mod#L35
[^2]: You can download one from https://packages.debian.org/en/trixie/golang-1.24-go, thanks to golang being static binary, you should be able to install newer binary to older debian/ubuntu.

**Comment by cielavenir** [comment]
[yq4.47.1.zip](https://github.com/user-attachments/files/21395975/yq4.47.1.zip)

This file contains the binary(amd64) package and source package of my build~
