### ISSUE TITLE
No newline at the end of the file

### ISSUE THREAD

**Issue by matpen** [mikefarah/yq#131]
First of all, thanks for a great tool.

I just started to use it on an ubuntu server (release [1.14.1](https://github.com/mikefarah/yq/releases/download/1.14.1/yq_linux_amd64) for linux amd64) with 
```
yq merge -xi file1.yml file2.yml
```
It seems that the resulting "file1.yml" has no newline at the end.

**Comment by mikefarah** [comment]
There's a trim flag which is true by default, you can turn it off by

```
yq merge -t=false -xi file1.yml file2.yml
```

**Comment by matpen** [comment]
@mikefarah thank you for your reply and sorry for late reaction: I do not seem to find the flag documented, however its name makes me think that its purpose is to `trim` the value for each key?

In any case, I do not think that a text file without ending newline is ever desirable. Apart from ugly output (think of `cat file` in a terminal) it can lead to incorrect results when appending to it (think `echo 'key: value' >> file`): see [here](https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file) and [here](https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file).
