### ISSUE TITLE
Split loses root node

### ISSUE THREAD

**Issue by vr333dev** [mikefarah/yq#1313]
Hello, we are looking to split a large YAML file into more manageable files, And the following command works partially:

yq '.[]' -s '"file_" + $index' config.yaml

This splits settings into multiple files, but looses rootNode1 and rootNode2:

rootNode1:
  childNode1: value1
  childNode2: value2
rootNode2:
  childNode1: value1
  childNode2: value2

Is there a way to split data into multiple files and keep root nodes please? This is necessary because after processing smaller chunks, we'd like to combine files into a single file, again.

Thanks

Vlad

**Comment by mikefarah** [comment]
Sure - the issue is `.[]` will give back the child values, without the keys. Instead:

```bash
yq 'to_entries | .[] | {.key: .value}' -s '"file_"+$index' file.yaml
```

Explanation:
- `to_entries` converts the map to an array of key, value pairs
- `.[]` splat the map into individual nodes
- `{.key: .value}` convert each node into a map with a single entry

**Comment by vr333dev** [comment]
That works, thanks!
