### ISSUE TITLE
yq m (yq merge) -- any option to support in 4.X.X version

### ISSUE THREAD

**Issue by git-abhijit** [mikefarah/yq#1315]
**Describe the bug**

The merge option is not working

The command  yq m -x data1.yaml data2.yaml

m and -x option doesn't seem to be there; it's not showing in yq --help also.

Requirement : is to merge keys from file2 to file 1 ; which are common to be overwritten and the ones which are not there in file1 to get added from file2

Version of yq: 4.27.2
Operating system: linux
Installed via: binary release

using below command:
wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq && chmod +x /usr/bin/yq

**Input Yaml**

Used the example mention under this section:
https://mikefarah.gitbook.io/yq/v/v2.x/merge#overwrite-values

**Command**
The command you ran:
```
yq m -x data1.yaml data2.yaml
```
https://mikefarah.gitbook.io/yq/v/v2.x/merge#overwrite-values
**Actual behavior**

```
Error: unknown shorthand flag: 'x' in -x
Usage:
  yq eval [expression] [yaml_file1]... [flags]

Aliases:
  eval, e

Examples:

# Reads field under the given path for each file
yq e '.a.b' f1.yml f2.yml 

```

**Expected behavior**

```
It should merge and overwrite values of common keys from data2.yml to data1.yml
```

**Additional context**

**Comment by git-abhijit** [comment]
Merge option was supported in 2.x , is there any equivalent to support the same in 4.X.X version

**Comment by git-abhijit** [comment]
Have found yq eval-all --inplace 'select(fileIndex == 0) * select(fileIndex == 1)' 1.yml 2.yml

But this merges at the top level, if want to do for second level how it can be handled.

Like need to merge the values in second level keys. like a.b in file1 with a.b in file 2

File1
a:
 b: hello
 c: how

File 2 
a:
 b: Hellooooo
 d: how are you

Result : 
a:
 b: Hellooooo
 c: how
 d: how are you

**Comment by mikefarah** [comment]
I'm guessing your example is meant to be nested? It's hard to tell as you dont have white space.

```bash
yq eval-all --inplace '.a.b = ((select(fi == 0) | .a.b) * (select(fi == 1) | .a.b)) | select(fi==0)' 1.yml 2.yml
```

Explanation:
- you want to set `a.b` to the merged result of `a.b` from file 1 and file 2 ,so start with `.a.b = (exp)`
- in exp, we merge the elements from file 0 and file 1
- finally, we select only the file 0 results (otherwise both files will be output)

**Comment by mikefarah** [comment]
Oh (and I'll update the docs with this) there is a shorter way to do this using the `load` operator:

```bash
yq '.a.b *= (load("2.yaml") | .a.b)' 1.yaml
```

Basically it removes the need to select the documents by file

**Comment by mikefarah** [comment]
https://mikefarah.gitbook.io/yq/upgrading-from-v3#merging-documents Updated docs

**Comment by git-abhijit** [comment]
Thank you Mike for your guidance and the help, I will try out the suggestions and check. If I face any difficulties or queries will ask .

**Comment by gurpartb** [comment]
For yaml in powershell variables try:
```
$y0="
a:
  b: val
  c: val
"
$y1="
a:
  c: val2
  d: val2
" | yq -o json
$y0=$y0 | yq -o json
$y1=$y1 | yq -o json
yq --null-input "$y0 * $y1" | Out-String
```
