### ISSUE TITLE
Inconsistent output with merge command in v3 -> v4 upgrade instructions

### ISSUE THREAD

**Issue by biggianteye** [mikefarah/yq#1318]
**Describe the bug**
I am trying to migrate some uses of yq from v3 to v4 using the [Upgrading from v3](https://mikefarah.gitbook.io/yq/upgrading-from-v3) guide and I can see inconsistent output with the suggestion for merging documents.

Here's the guidance from the upgrade doc:

> **Merging documents**
> Like `jq`, merge is done via the multiply operator. You will need to use the eval-all command to load all documents into memory at once, and then use the file operator to select the file nodes to merge.
>
> yq eval-all 'select(fileIndex == 0) * select(filename == "file2.yaml")' file1.yaml file2.yaml

Version of yq: 4.27.2 / 3.4.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
These are the two files from the [v3 merge example](https://mikefarah.gitbook.io/yq/v/v3.x/commands/merge)

data1.yml:
```yaml
a: simple
b: [1, 2]
```

data2.yml:
```yaml
a: other
c:
  test: 1
```

**Command**

```
# v3: From the v3 merge docs
yq merge data1.yaml data2.yaml

# v4: From the upgrade doc
yq eval-all 'select(fileIndex == 0) * select(filename == "data2.yaml")' data1.yaml data2.yaml
```

**Actual behavior**

v3
```yaml
a: simple
b: [1, 2]
c:
  test: 1
```

v4:
```yaml
a: other
b: [1, 2]
c:
  test: 1
```

`b` and `c` are fine. The problem is with `a`.

**Expected behavior**

Unclear. I don't know which behaviour is supposed to be "correct". My expectation is that the guidance from the upgrade doc would produce the same results as v3 (or explain any expected difference).

**Additional context**

The Quick Start Guide on the [main documentation page](https://mikefarah.gitbook.io/yq/) suggests this pattern for merging documents.

```
yq ea '. as $item ireduce ({}; . * $item )' path/to/*.yml
```

This produces the same output as the v3 merge command. Should this be in the upgrade guidance instead?

**Comment by mikefarah** [comment]
Thanks for pointing that out, I've updated the v3 upgrade guide: https://mikefarah.gitbook.io/yq/upgrading-from-v3#merging-documents

Basically you need to use the `n` merge flag to only merge in new fields (which is the default behaviour in v3, but not v4, mainly to keep compatibility with jq).

**Comment by mikefarah** [comment]
FYI that pattern for merging a list of documents, I'm guessing that worked because it happened to first merge data2 and then data1.

**Comment by biggianteye** [comment]
> Thanks for pointing that out, I've updated the v3 upgrade guide: https://mikefarah.gitbook.io/yq/upgrading-from-v3#merging-documents
> 
> Basically you need to use the `n` merge flag to only merge in new fields (which is the default behaviour in v3, but not v4, mainly to keep compatibility with jq).

Thanks for the update and the clarification.
