### ISSUE TITLE
Can't use spaces in path variable

### ISSUE THREAD

**Issue by ImDevinC** [mikefarah/yq#1319]
When trying to use spaces in the path of a yaml, `yq` fails unexpectedly.

Here's a working example of what I'm trying to do:

```
name="My" src=".data.${name}" dest="test" yq -n 'eval(strenv(src)) = strenv(dest)'
data:
  My: test
```

But this example fails:
```
name="My Path: Test" src=".data.${name}" dest="test" yq -n 'eval(strenv(src)) = strenv(dest)' 
Error: 1:10: invalid input text "Path: Test"
```

In this second example, I would expect the following output:
```
data:
  "My Path: Test": test
```

Version of yq: 4.27.2
Operating system: linux
Installed via: release

**Comment by mikefarah** [comment]
The yq expression given to eval needs to use the syntax for special characters: https://mikefarah.gitbook.io/yq/operators/traverse-read#special-characters. Something like:
```
src=".data.[\"${name}\"]"
```

**Comment by ImDevinC** [comment]
Thank you, don't know how I missed that
