### ISSUE TITLE
Support for sequence keys

### ISSUE THREAD

**Issue by matpen** [mikefarah/yq#132]
I noticed that support for "sequence keys" (see [here](https://stackoverflow.com/questions/39507595/yaml-key-consisting-of-a-list-of-elements)) is not (yet) implemented (at least with release [1.14.1](https://github.com/mikefarah/yq/releases/download/1.14.1/yq_linux_amd64)). The error is
```
yaml: invalid map key
```

Being new to `yq`, I do not know what the underlying yaml library is, but I know that [ruaml.yaml](https://pypi.python.org/pypi/ruamel.yaml/) (python) and [js-yaml](https://github.com/nodeca/js-yaml) (node) support them. If I am not mistaken, they are part of the [1.2 specs](http://www.yaml.org/spec/1.2/spec.html).

**Comment by mikefarah** [comment]
This is using https://github.com/go-yaml/yaml - couldn't find anything about 'sequence keys' though...

**Comment by mikefarah** [comment]
This should be fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1 as it supports custom tags...
