### ISSUE TITLE
Release is missing of new version `4.27.3`

### ISSUE THREAD

**Issue by MuhammadRazaAslam** [mikefarah/yq#1320]
**Describe the bug**
Release is missing of new version `4.27.3`
<img width="1585" alt="image" src="https://user-images.githubusercontent.com/19810462/187155058-7bbe9454-e86b-4691-b17f-4eafe522c93c.png">
<img width="1596" alt="image" src="https://user-images.githubusercontent.com/19810462/187155086-8f3636bd-aebd-4fdd-97b7-51da40bde80f.png">

**Comment by mikefarah** [comment]
Fixed!
