### ISSUE TITLE
Sort Keys reverse

### ISSUE THREAD

**Issue by christiangoudreau** [mikefarah/yq#1324]
I wish I could use yq to sort keys by reverse order. There's already a sort keys that sort only in one direction.

Note:
- how to questions should be posted in the discussion board and not raised as an issue.
- V3 will no longer have any enhancements.

**Describe the solution you'd like**
If we have data1.yml like:
(please keep to around 10 lines )

```yaml
a: a
b: b
c: c
```

And we run a command:

```bash
yq 'sort_keys(.) | reverse' test.yml
```

it could output

```yaml
c: c
b: b
a: a
```

**Comment by mikefarah** [comment]
You can do this using `to_entries` to convert the map to an array of key value pairs, sort as you like, then convert back. This is a good question - I'm going to add it to the docs as an example:

```bash
yq 'to_entries | sort_by(.key) | reverse | from_entries' file.yaml
```
