### ISSUE TITLE
Null elements in arrays are elided during conversion to JSON

### ISSUE THREAD

**Issue by soraismus** [mikefarah/yq#1327]
**Describe the bug**
Arrays/lists containing `null` are valid constituents of both YAML expressions and JSON expressions.

However, during conversion of a YAML expression to JSON, all `null`values in any input array are omitted from the array's respective output.

Version of yq: 4.13.5
Operating system: NixOS
Installed via: nixpkgs.yq-go, nix-channel nixos-21.11

**Input Yaml**
data1.yml:
```yaml
- 10
- null
- 30
```

**Command**
```
yq eval --output-format json data1.yml
```

**Actual behavior**

```json
[
  10,
  30
]
```

**Expected behavior**

```yaml
[
  10,
  null,
  30
]
```

**Comment by mikefarah** [comment]
Using a newer version of yq (4.27.3) does not have this issue
