### ISSUE TITLE
yq breaks json spec - inserts unquoted object keys

### ISSUE THREAD

**Issue by netikras** [mikefarah/yq#1338]
```
netikras@netikras-xps:~/received$ echo '{"path":null}' | var=aaa val=bbb ./yq_linux_amd64 '.auths.[strenv(var)].auth=strenv(val)'
{"path": null, auths: {aaa: {auth: bbb}}}
netikras@netikras-xps:~/received$ echo '{"path":null}' | var=aaa val=bbb ./yq_linux_amd64 '.auths.hellooo.auth=strenv(val)'
{"path": null, auths: {hellooo: {auth: bbb}}}
netikras@netikras-xps:~/received$  ./yq_linux_amd64 --version
yq (https://github.com/mikefarah/yq/) version 4.27.5
```

ref: https://www.json.org/json-en.html
A JSON object key must be a string. According to JSON spec:
> A string is a sequence of zero or more Unicode characters, wrapped in double quotes, using backslash escapes

And YQ does not wrap keys with double-quotes, ending up in a malformed JSON

Version of yq: <=4.27.5
Operating system: linux

**Comment by mikefarah** [comment]
`yq` defaults to `yaml` output not json. To get json output, you need to specify the output format: `-o=json`

```bash
echo '{"path":null}' | var=aaa val=bbb ./yq '.auths.[strenv(var)].auth=strenv(val)' -o=json
{
  "path": null,
  "auths": {
    "aaa": {
      "auth": "bbb"
    }
  }
}
```

To get a single line JSON, specify an indent of 0 `-I=0`

```bash
echo '{"path":null}' | var=aaa val=bbb ./yq '.auths.[strenv(var)].auth=strenv(val)' -o=json -I=0
{"path":null,"auths":{"aaa":{"auth":"bbb"}}}
```

**Comment by netikras** [comment]
@mikefarah So you're saying that if I don't specify `-o=json`, the output will be yaml? 

I think this is not valid YAML. Is it..? Considering the paths I've specified in the yq script.
```
{"path": null, auths: {hellooo: {auth: bbb}}}
```

**Comment by netikras** [comment]
Silly me, I didn't study the YAML spec and didn't know a json/pseudo-json is a valid YAML...

Thanks
