### ISSUE TITLE
Colorize the output?

### ISSUE THREAD

**Issue by tadayosi** [mikefarah/yq#134]
Is there way to colorize the output of yq on terminal like jq does?

**Comment by mikefarah** [comment]
not yet!

**Comment by Frodox** [comment]
Heavy plus!
Can't find any cli tools for colorize output of yml

**Comment by pawel-swiecki-saucelabs** [comment]
+1

**Comment by risentveber** [comment]
Seems like one should use this https://github.com/goccy/go-yaml#ycat

**Comment by risentveber** [comment]
@tadayosi see my pr please)

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.2.0 (thanks @risentveber !!)

See https://mikefarah.gitbook.io/yq/usage/output-format#colorize-output
