### ISSUE TITLE
When to expect release builds upon go1.19.1

### ISSUE THREAD

**Issue by WarheadsSE** [mikefarah/yq#1348]
## Summary

When could we expect a minor or patch revision which includes https://github.com/mikefarah/yq/pull/1330 bumping the toolchain in use to golang 1.19.1? This would reduce noise in some of our automated scanning pipelines which are complaining in regards to `< 1.19.1`

I know this is a bit of "please", but it would be much appreciated :bow:

**Comment by mikefarah** [comment]
yq is a command line tool for processing files on disk - it doesn't use net/http. Will update the go compiler in the next release regardless

**Comment by mikefarah** [comment]
Fixed in 4.28.1

**Comment by WarheadsSE** [comment]
@mikefarah We can appreciate that, but ... have some compliance requirements. Thank you for your efforts :bow:
