### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by kxuanCeltik** [mikefarah/yq#135]
I execute inside script.sh this:

yq write --inplace kubeconfig-"${ClusterName}.yaml" clusters.cluster.server $Cluster_Endpoint --verbose
yq write --inplace kubeconfig-"${ClusterName}.yaml" clusters.cluster.certificate-authority-data $Cluster_CA --verbose
yq write --inplace kubeconfig-"${ClusterName}.yaml" users.user.auth-provider.config.cluster-id $ClusterName --verbose

It write new variables fine but I lost two fields and obtain "Segmentation Fault" Error.

What kind of issue could be it ?
How can I close the file in good way?

Thanks,

**Comment by mikefarah** [comment]
there's not enough information here to help - how am I supposed to recreate the issue?

I need the input and output. If the information is sensitive, then desensitise it or make a example yaml fail.
