### ISSUE TITLE
Integer becomes string when using envsubst for variable substitution

### ISSUE THREAD

**Issue by zhouxiaofu** [mikefarah/yq#1367]
test.yaml
```yaml
number: ${number}
```

`number=5 yq '(.. | select(tag == "!!str")) |= envsubst' test.yaml`

print:
`number: "5"`

My desired output is : 
`number: 5`

**Comment by mikefarah** [comment]
envsubst is a _string_ interpolation operator - however you can wrap this in an `eval` to parse the value as the right type:

```bash
number=5 yq '(.. | select(tag == "!!str")) |= eval(envsubst)' test.yaml
```

This will work for other types as well (e.g. boolean, dates) provided the right format is used.
