### ISSUE TITLE
Line comment on empty array key break outputted yaml

### ISSUE THREAD

**Issue by landure** [mikefarah/yq#1372]
When applying a line comment to the key of a empty array ([]), the line comment is successfully applied, but the [] is outputted on next line.

Version of yq: 4.27.5
Operating system: Ubuntu 22.04 Jammy Jellyfish
Installed via: binary release.

**Input Yaml**

data1.yml:
```yaml
root: {}
```

**Command**

```
yq --inplace eval 'with(.root;
    .value = []
    | ( .value | key ) line_comment = "Some comment"
  )' 'data1.yml'
```

**Actual behavior**

data1.yml contents:

```yaml
root:
  value: # Some comment
[]
```

**Expected behavior**

```yaml
root:
  value: [] # Some comment
```

This is probably a bug of the underlying go library, but in case it is not...
This issue is a follow up of issue #1365 .

Thank you for your work.

**Comment by mikefarah** [comment]
This is another strange behaviour of the underling library - you actually need to put the comment on the `value` node... :| 

I've just put up a handy little script in the [help docs](https://mikefarah.gitbook.io/yq/operators/comment-operators#where-is-the-comment-map-key-example) to find where the comments are being attached - as it's not straight forward :/ if you run that script against the expected doc, you will see:

```
...
- p: root.value
  isKey: false
  hc: ""
  lc: Some comment
  fc: ""
```
It's set as a line comment (lc) on the root.value, isKey is false so it's the value node. Note that this script will only work for 4.28+ as it uses a new 'is_key" operator.

**Comment by landure** [comment]
Shouldn't that script to identify the placement of line comment be integrated to yq functionment ? Should'nt yq output be more predictable ?
