### ISSUE TITLE
a scalar starting with 00 (double zero) is interpreted as octal number

### ISSUE THREAD

**Issue by rafalkrupinski** [mikefarah/yq#1376]
**Describe the bug**
A scalar starting with 00 (double zero) is interpreted as octal number

Version of yq: 3.1,0
Linux
Installed via: pipx

**Input Yaml**
data1.yml:
```yaml
009
```

**Command**

```
yq . data1.yml
```

**Actual behavior**

```
yq: Error running jq: ValueError: invalid literal for int() with base 8: '009'.
```

**Expected behavior**

```yaml
009
```

**Additional context**
yq tries to read the input starting with 00 (zero zero) as octal number.
According the Yaml 1.2.2 spec (2.4, 3.2.1.3), octal numbers start with 0o (zero oscar)

**Comment by rafalkrupinski** [comment]
works in yq4

**Comment by mikefarah** [comment]
Gday - the `yq` 3 isn't mine - it's this one: https://kislyuk.github.io/yq/ which is a wrapper around jq. Feel free to raise the issue there.
