### ISSUE TITLE
[github actions] The `set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by guihkx** [mikefarah/yq#1382]
I'm getting this warning while using `mikefarah/yq@v4.28.1` on my GitHub actions manifest

![image](https://user-images.githubusercontent.com/626206/196010954-6dad9373-0d7e-4633-b37e-a2972479bd2a.png)

Here's the URL to the blog post: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mikefarah** [comment]
👀

**Comment by mikefarah** [comment]
Thanks for the tip, will fix in the next release

**Comment by guihkx** [comment]
Thanks. I see you already pushed a [commit](https://github.com/mikefarah/yq/commit/dee0c94346ee3810e741b663c7b043dc3aa66af4) related to this, and I was wondering if it the contents of `$RESULT` shouldn't be assigned to a lowercase `result` variable instead, in order not to break existing workflows? I.e.:

```bash
echo "result=$RESULT" >> $GITHUB_OUTPUT
```

**Comment by mattphelps-8451** [comment]
@guihkx @mikefarah I opened a fix PR here https://github.com/mikefarah/yq/pull/1383.

**Comment by mattphelps-8451** [comment]
@mikefarah 

My tea discovered but resolved another bug introduced as a result of `set-output` deprecation. It relates to multiline output in the new Github output file. 

Reference: https://github.com/orgs/community/discussions/26288#discussioncomment-3876281

The fix PR here: #1390

**Comment by mikefarah** [comment]
Thanks again @mattphelps-8451 !

**Comment by mikefarah** [comment]
Going to leave this open till its confirmed its working
