### ISSUE TITLE
Bump need replace 'set-output ' to ' >>GITHUB_OUTPUT'

### ISSUE THREAD

**Issue by floralatin** [mikefarah/yq#1391]
**Describe the bug**
`set-output` Once deprecated, many github actions will break across repos.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mattphelps-8451** [comment]
@floralatin See #1382.

**Comment by floralatin** [comment]
> If you're referring to set-output that affects downstream workflows, that's resolved in https://github.com/mikefarah/yq/issues/1382 and you can take a look at the new entry point script https://github.com/mikefarah/yq/blob/master/github-action/entrypoint.sh.

**Comment by floralatin** [comment]
> So maybe you're referring to the release workflow which still has `set-output` and only affects this repo? https://github.com/mikefarah/yq/blob/master/.github/workflows/release.yml

No, I just use the repo.

**Comment by guihkx** [comment]
Release v4.28.2 probably fixed this already, just bump the version number.

**Comment by mikefarah** [comment]
Yeah should be fixed...let me know if you are still having issues (and if you are, the details to replicate....)
