### ISSUE TITLE
Install via Nix

### ISSUE THREAD

**Issue by br4ch1st0chr0n3** [mikefarah/yq#1392]
**Please describe your feature request.**
I wish there were a section in README on how to install your program via Nix. It can be as simple as `nix profile install nixpkgs#yq-go` ([docs](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-profile-install.html))

**Comment by mikefarah** [comment]
Cool - happy to do that. How is this maintained - like when new versions of yq are released?

**Comment by br4ch1st0chr0n3** [comment]
Well, idk who is the maintainer, but the latest version of yq is at [nixpkgs](https://search.nixos.org/packages?channel=unstable&show=yq-go&from=0&size=50&sort=relevance&type=packages&query=yq-go) .

**Comment by mikefarah** [comment]
Done, thanks!
