### ISSUE TITLE
`contains`: false positive

### ISSUE THREAD

**Issue by seub** [mikefarah/yq#1407]
**Describe the bug**

When using `contains` on an array, it returns "true" in the type of scenario shown below. Perhaps this is a feature and not a bug, but I doubt it.

Version of yq: 4.*

**Input Yaml**
data.yml:
```yaml
- cat
- dog
- monkey
```

**Command**
The command you ran:
```
yq 'contains ["monk"]' data.yml
```

**Actual behavior**

```yaml
true
```

**Expected behavior**

```yaml
false
```

**Additional context**
Note that `contains`, in the case of a list (array), is supposed to determine whether another list is a sublist of the given list. For instance, `yq 'contains ["cat", "monkey"]' test.yml` outputs `true` as expected. I think it does not make sense to say that `["monk"]` is a sublist here, just because `monk` is a substring of one of the elements.

**Comment by mikefarah** [comment]
Yeah the substring seemed strange to me as well, but it's actually how `jq` operates so I kept that behavior: see https://stedolan.github.io/jq/manual/#contains(element).

To get what you want, you could do something like:
```
yq '[.[] == "monk"] | any' file.yaml
```

**Comment by mikefarah** [comment]
Actually this reads better IMO: `yq 'map(. == "monk") | any'`

**Comment by seub** [comment]
Thank you!
