### ISSUE TITLE
Option `-r` not working with `yq -oj`

### ISSUE THREAD

**Issue by ryenus** [mikefarah/yq#1409]
**Describe the bug**
The option `-r` doesn't work when the output format is json.

Version of yq: 4.29.2
Operating system: mac
Installed via: homebrew

**Command**
The command you ran:
```
echo '["a", "b"]' | yq -r -oj .[]
```

**Actual behavior**

```
"a"
"b"
```

**Expected behavior**

```
a
b
```

**Additional context**
With `-r` specified to print the data without quote, it works as expected when the output format is yaml. However when the output format is json, the quotes are still printed.

**Comment by mikefarah** [comment]
I've got mixed feelings about this one, in `yq` `-r` defaults to true. When specifying json output, if the values are unwrapped, then it's no longer valid json...

What's the scenario for this? Perhaps I could add a json specific unwrap flag, defaulting to false, so as to avoid breaking existing behavior...

**Comment by ryenus** [comment]
> I've got mixed feelings about this one, in `yq` `-r` defaults to true. When specifying json output, if the values are unwrapped, then it's no longer valid json...

Basically when the array is unwrapped by `.[]` the output is already no longer valid json, or even yaml.

Nevertheless, since quotes are optional in yaml, but not in json, so the semantic of the `-r` option cannot be the same, in the sense that it's possible to keep produce valid yaml, but not possible to produce valid json. Based on that I believe it's ok for the `-r` option to have slightly different semantic depending on the output format.

> What's the scenario for this? Perhaps I could add a json specific unwrap flag, defaulting to false, so as to avoid breaking existing behavior...

For my use case, I'd like to let `yq -r ...` produce something to be processed by other CLI utilities like grep/awk etc, rather than being reused for json/yaml parsing.

**Comment by mikefarah** [comment]
Fixed in 4.30.1 :)
