### ISSUE TITLE
Do not split long lines option

### ISSUE THREAD

**Issue by nbonamy** [mikefarah/yq#142]
Hello,

I am using yq to edit inplace some configuration files where one value is a long string on one line.

After running through yq the value becomes:
```
key: "line1
  line2
  line3"
```

I am not a YAML expert but the PHP Symfony parser does not like this syntax.

Is there a way to disable the split over multiple lines and keep the value as:
`key: "line1 line2 line3"`

Thanks,
Nicolas

**Comment by mikefarah** [comment]
There isn't a way to do this atm, besides it is valid yaml (https://yaml-multiline.info/) I'd raise a bug against the parser library you are using...

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/issues/143
