### ISSUE TITLE
--version is broken

### ISSUE THREAD

**Issue by hego-fdc** [mikefarah/yq#1434]
**Describe the bug**
The "--version" flag returns "yq (https://github.com/mikefarah/yq/) version" without any actual version

Version of yq: v4.30.3
Operating system: linux
Installed via: snap or `go install`

**Comment by ianrobrien** [comment]
Thanks for your fast work here @mikefarah!

Just a heads up, the previous version output was:

```
yq (https://github.com/mikefarah/yq/) version 4.30.1
```

but now it looks like it is with a `v` before the version number:

```
yq (https://github.com/mikefarah/yq/) version v4.30.4
```

Is this change intentional? I can create an issue to track this if you'd like to change it back to remove the `v`.

**Comment by andmos** [comment]
Related to https://github.com/mikefarah/yq/issues/1433, where the version number disappeared.
No bigge for us if the `v` now comes in front.

**Comment by ianrobrien** [comment]
It broke our CI as we check the output of `--version` to start with `4.`. It's not a big deal for us to change our tests. I just wanted to raise this as it was possibly unintentional.

**Comment by andmos** [comment]
Hehe we had a similar case @ianrobrien :D

**Comment by mikefarah** [comment]
Apologies again! It is unintentional :( 

For the sake of not releasing yet again, and seeing it doesn't seem to be a big issue I'm going to leave it as is. This way it always matches the Github tag. Good news is the new script I've written should ensure that the version is consistent going forward!

**Comment by andmos** [comment]
I'll be changing our version check then 👌

**Comment by ianrobrien** [comment]
Thanks for the clarification and the good communication here @mikefarah! We appreciate the fast response 👏
