### ISSUE TITLE
[xml] error: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by ryenus** [mikefarah/yq#1438]
**Describe the bug**
XML input containing map-alike xml comment would cause yq to fail with below error:

    Error: bad file 'data.xml': yaml: line 2: mapping values are not allowed in this context

Version of yq: 4.30.4
Operating system: mac
Installed via: homebrew

### Input ~Yaml~ XML
data1.xml:
```xml
<p>
  <a>1</a> <!-- comment: message -->
</p>
```

data2.xml:
```xml
<p>
  <a>1</a> <!-- comment message -->
</p>
```

**Command**
```
yq 'from_xml' data1.xml
```

**Actual behavior**
```
Error: bad file 'data1.xml': yaml: line 2: mapping values are not allowed in this context
```

**Expected result**
```yaml
p:
  a: "1"
  # comment message
```

**Additional context**
The comment in data2.xml doesn't have a colon (`:`), meanwhile data1.xml DOES have it, which seems to confuse yq and caused it failing to process the xml.

Meanwhile it would be nice for yq to provide an CLI option so that I can tell yq to bypass all the xml comments when processing the input, and exclude comments in the output.

**Comment by ryenus** [comment]
> `yq -p=x '... comments=""' file.xml`

Ah, so `yq `from_xml` file.xml` is not treating the input as xml? Definitely a TIL for me 😂

**Comment by mikefarah** [comment]
Yeah sorry about that warning - there's no way to ignore it (ill take that as a note for next time I need to do something like that). Next release I'll have it removed anyway
