### ISSUE TITLE
load cannot load files passed as env vars

### ISSUE THREAD

**Issue by danielferromeral** [mikefarah/yq#1442]
**Describe the bug**
I'm trying to load a file using a env var to merge with another file (also as env var), with the next line of code in a script:

```sh
echo $PLUGIN
yq -i '. *d load(strenv(PLUGIN))' $GENERATED
```
And I get the next result:
````
./originals/plugins/client.yaml
Error: Failed to load : open : no such file or directory
````
If I try to use env, instead of strenv, I got the next message:
````
Error: Value for env variable 'PLUGIN' not provided in env()
````
And, if I just paste the path directly like this
```sh
yq -i '. *d load("./originals/plugins/client.yaml")' $GENERATED
```
It works.

I have checked that there are files there, that the vars have values, everything seems to works except, the load method with the strenv inside.

Version of yq: 4.30.4
Operating system: mac
Installed via: homebrew

**Comment by mikefarah** [comment]
you need to either `export` the variable in bash to make it available to child processes, or explicitly set it on the child process:

```
PLUGIN=${PLUGIN} yq -i '. *d load(strenv(PLUGIN))
```
