### ISSUE TITLE
Access nodes using the variable operator

### ISSUE THREAD

**Issue by Kopfbremse** [mikefarah/yq#1444]
**Version of yq**: 4.30.2
**Operating system**: linux
**Installed via**: binary release

**Feature description**
I want to access a node in an object using a variable that contains the path.
I can't figure out how to do this in `yq`.
The [manual](https://mikefarah.gitbook.io/yq/operators/variable-operators) has no example for this use case. Is it possible?
`jq` is able to do this (see example 3).

```bash
INPUT='
Angel:
  Address: Heaven
'

echo ---yq (expected)---
yq '.Angel.Address |= "Cloud 9"' <<< "$INPUT"

echo ---yq (unexpected / feature wish)---
yq '. as $doc | "Address" as $path | $doc.Angel[$path] |= "Cloud 9"' <<< "$INPUT"

echo ---jq (expected)---
jq '. as $doc | "Address" as $path | $doc.Angel[$path] |= "Cloud 9"' <<< '{"Angel": {"Address": "Heaven"} }'
```

**Output yq (expected)**
```yaml
Angel:
  Address: Cloud 9
```

**Output yq (unexpected / feature wish)**
```yaml
Angel:
  Address: Heaven
```

**Output jq (expected)**
```json
{
  "Angel": {
    "Address": "Cloud 9"
  }
}
```

**Comment by mikefarah** [comment]
Hey - the `eval` function will do this: https://mikefarah.gitbook.io/yq/operators/eval

**Comment by Kopfbremse** [comment]
Thank you for the hint about the `eval` function.
Wouldn't it be cool to have the above abbreviation in `yq` as well instead of the `eval` function?

**Comment by mikefarah** [comment]
yep it would
