### ISSUE TITLE
Invalid output from stdin

### ISSUE THREAD

**Issue by svnpenn** [mikefarah/yq#145]
This is a valid YAML file:

~~~yml
$ cat example.yml
- alfa
- bravo
- charlie
~~~

YQ produce valid output from file:

~~~yml
$ yq r example.yml
- alfa
- bravo
- charlie
~~~

but not from stdin:

~~~yml
$ cat example.yml | yq r -
null
~~~

**Comment by mikefarah** [comment]
Latest version fixes this.

**Comment by mabushey** [comment]
Not at all
```
✗  yq -V
yq version 4.6.1
```
`...| base64 --decode | yq r -`
```
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
```

**Comment by tis-rpage** [comment]
> Not at all
> 
> ```
> ✗  yq -V
> yq version 4.6.1
> ```
> 
> `...| base64 --decode | yq r -`
> 
> ```
> Error: unknown command "r" for "yq"
> Run 'yq --help' for usage.
> ```

base64 is now native to yq: https://github.com/mikefarah/yq/issues/1112#issuecomment-1052899816
