### ISSUE TITLE
arm architecture

### ISSUE THREAD

**Issue by nemchik** [mikefarah/yq#146]
Hi,

Thanks very much for your awesome yq tool! I have been using it a lot the past week, specifically from https://hub.docker.com/r/mikefarah/yq/ but I've found that there is no arm version available on docker hub. Would it be possible for you to add an arm version either as a separate image or as a tag to the existing image or something like that?

**Comment by nemchik** [comment]
p.s. not sure if it helps, but https://github.com/v2tec/watchtower this tool seems to have arm builds as tags https://hub.docker.com/r/v2tec/watchtower/tags/

**Comment by mikefarah** [comment]
Had a look at watchtower - they have 3 separate docker images but they're all actually the same. There doesn't appear to be any difference between the images 🤔 

I'm a bit confused as to why you'd need an arm version tbh - I thought the point of docker is that you can run arbitrary images...

**Comment by nemchik** [comment]
I've got a project using yq here https://github.com/GhostWriters/DockSTARTer and a few weeks ago around the day I opened this issue I switched from using the docker container for yq to installing the binary locally and handling the arch as needed. I made that switch because a user of my project couldn't use the yq docker image on a raspberry pi. Came to find out was because the yq docker image isn't compatible with arm.

**Comment by mikefarah** [comment]
Right I see - that's actually the reason I wrote this in Golang, producing portable binaries for different architectures ;)

That said, if you're particular keen and can get a yq docker image working for a Pi I'd happily take a pull request. Wouldn't add to much work to the releasing process to have two docker files instead of one.

**Comment by nemchik** [comment]
At this point I no longer have a true need for it because of this https://github.com/GhostWriters/DockSTARTer/blob/master/scripts/install_yq.sh so as far as I'm concerned we can close this issue unless you consider having an arm image a goal for your project, in which case certainly keep this issue open to track that.

I personally don't know how to make dockerfiles, so it won't be me coming up with a PR anytime in the near future (maybe a few months from now if it comes back up).

**Comment by nemchik** [comment]
I've come to a point where it would now be significantly beneficial for my project to be able to use docker images instead of local binaries for your yq distribution. I've started running into issues where users already have and depend on https://github.com/kislyuk/yq but my project depends on your yq and the two are not directly interchangeable. I could adjust my project to detect which yq is available and use each one accordingly, but it would be much simpler if your yq were available as a docker image for arm and arm64 (arm can use arm64 if you don't want to maintain two extra images or tags).

Here is an example of another project that has multi-arch images available in what seems to be a very clean way:
https://lab.mediabutler.io/MediaButler/API/blob/master/.gitlab-ci.yml
https://lab.mediabutler.io/MediaButler/API/blob/master/Dockerfile
Take note of the `IMAGE_ARCH` variable in both links. There may be easier ways of doing this, but the multi-arch tags and the manifest make it so that end users can simply use one image regardless of which architecture they are on and docker will pull the proper image for their architecture from the hub.

I've forked your repo just for the sake of giving it a shot on my own (to make a PR) but I don't think I'm making any decent headway.

Would you consider reopening this request and pushing docker images for multiple architectures?

**Comment by nemchik** [comment]
FYI Here is a first attempt at piecing together what you have VS what the repo I linked has.
https://github.com/mikefarah/yq/compare/master...nemchik:docker-arm
I have not tested it.

This is a bit larger than what the linked repo has because they only keep a `latest` tag for each architecture while you have `latest` and `${VERSION}`. I also don't know if the `docker login` would be used here (I didn't see it anywhere else in your repo so I'm assuming you push the builds manually?).
