### ISSUE TITLE
Object addition not working

### ISSUE THREAD

**Issue by nhavens** [mikefarah/yq#1463]
**Describe the bug**
Object addition does not work as documented in the `jq` [manual](https://stedolan.github.io/jq/manual/v1.6/#Builtinoperatorsandfunctions).

Version of yq: 4.30.5
Operating system: linux
Installed via: docker

**Input Yaml**
null input

**Command**
The command you ran:
```
docker run mikefarah/yq:latest --null-input '{a: 1} + {b: 2} + {c: 3} + {a: 42}'
```

**Actual behavior**

```yaml
Error: 1:2: invalid input text "a: 1} + {b: 2} +..."
```

**Expected behavior**

```yaml
a: 42
b: 2
c: 3
```

**Comment by Kopfbremse** [comment]
Add double quotes to the keys to make it work
```
yq --null-input '{"a": 1} + {"b": 2} + {"c": 3} + {"a": 42}'
```
