### ISSUE TITLE
yq returns inconsistent results for assignment operator with different spacings

### ISSUE THREAD

**Issue by yokaze** [mikefarah/yq#1469]
**Describe the bug**
yq returns inconsistent results for assignment operator with different spacings, while jq returns a consistent result.

Version of yq: 4.30.5
Operating system: linux
Installed via: binary release (from GitHub)

**Input Yaml**
Not needed

**Command**
The command you ran:
```
yq -n '.a=1 | .a=.a*10'
yq -n '.a=1 | .a=.a* 10'
yq -n '.a=1 | .a=.a * 10'
```

**Actual behavior**

```yaml
a: 1
```
```text
Error: bad expression, please check expression syntax
```
```yaml
a: 10
```

**Expected behavior**

```yaml
a: 10
```
```yaml
a: 10
```
```yaml
a: 10
```

**Additional context**

jq returns a consistent result for the commands.

```
$ jq -cn '.a=1 | .a=.a*10'
{"a":10}

$ jq -cn '.a=1 | .a=.a* 10'
{"a":10}

$ jq -cn '.a=1 | .a=.a * 10'
{"a":10}
```

**Comment by mikefarah** [comment]
This is a legacy thing from the v3 days - yq v4 still supports wildcards (*) for traversing, so the middle example it's takes `.a*` as an expression to find keys that start with `a`.
