### ISSUE TITLE
YQ truncating files with multiple "documents"

### ISSUE THREAD

**Issue by svnpenn** [mikefarah/yq#147]
These 2 valid files:

~~~yml
$ cat alfa.yml
# Ranking of 1998 home runs
---
- Mark McGwire
- Sammy Sosa
- Ken Griffey

# Team ranking
---
- Chicago Cubs
- St Louis Cardinals
~~~

~~~yml
$ cat bravo.yml
---
time: 20:03:20
player: Sammy Sosa
action: strike (miss)
...
---
time: 20:03:47
player: Sammy Sosa
action: grand slam
...
~~~

YQ is not producing valid output - it is truncating in both cases:

~~~yml
$ yq r alfa.yml
- Mark McGwire
- Sammy Sosa
- Ken Griffey
~~~

~~~yml
$ yq r bravo.yml
time: "20:03:20"
player: Sammy Sosa
action: strike (miss)
~~~

http://yaml.org/spec/1.2/spec.html#id2760395

**Comment by mikefarah** [comment]
Hi,

This is a known issue - (#9), and someone has started a pull request to address it (#137) - though it has been silent for some time now :(

But yes this is a big missing feature from this library

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/issues/144

**Comment by svnpenn** [comment]
https://github.com/mikefarah/yq/issues/16
