### ISSUE TITLE
prettyprint changes qouting

### ISSUE THREAD

**Issue by kitu-sbruce** [mikefarah/yq#1472]
**Describe the bug**
When using pretty print quotes are not preserved as-is,

Version of yq: 4.30.5
Operating system: Ubuntu 20.04 (Windows 11 WSL)
Installed via: binary

**Input YAML**
```yaml
---
example: "{{ somevar['somekey'] }}"
```
Output YAML
```yaml
---
example: '{{ somevar[''somekey''] }}'
```

**Command**
```
yq -P example.yml
```

**Actual behavior**
_See Output YAML_

**Expected behavior**
In this example the output shouldn't have changed from the input.

**Additional context**
The example above is using Jinja templates within YAML.

**Comment by mikefarah** [comment]
Pretty print is supposed to change quoting.

What are you trying to do?
