### ISSUE TITLE
Outputting parsed xml loses comment location

### ISSUE THREAD

**Issue by venison** [mikefarah/yq#1475]
**Describe the bug**
When parsing an xml document and outputting it back into xml, if a comment exists in an xml-array, it will be placed at the end of the array in the resulting output, rather than in the original location.

Version of yq: 4.30.5
Operating system: linux
Installed via: snap 

**Input xml**
test.xml
```xml
<root>
  <cats>
    <cat>soft</cat>
    <!-- kitty_comment -->
    <cat>squishy</cat>
  </cats>
</root>
```

**Command**
The command you ran:
```
yq -o=xml -p=xml '.' test.xml
```

**Actual behavior**

```xml
<root>
  <cats>
    <cat>soft</cat>
    <cat>squishy</cat><!-- kitty_comment -->
  </cats>
</root>
```

**Expected behavior**

```xml
<root>
  <cats>
    <cat>soft</cat>
    <!-- kitty_comment -->
    <cat>squishy</cat>
  </cats>
</root>
```

**Additional context**
We were able to add a failing acceptance test in a PR in the hopes that might help and are still looking for the right place to make a possible change to fix it.  However we're not go engineers so it's taking us a bit longer than we imagine it would take the experts.  :D
https://github.com/mikefarah/yq/pull/1474

**Comment by mikefarah** [comment]
Fixed in v4.30.6! Thanks for the test case :)

**Comment by payallmoney** [comment]
Same problem , not work on windows 
Version of yq: v4.40.3
Operating system:  windows 11
Installed via: download exe file

**Comment by PayBas** [comment]
@mikefarah it seems this bug has returned.

```sh
#!/bin/bash
yq --version
echo
cat >test.xml <<EOL
<root>
  <cats>
    <cat>soft</cat>
    <!-- kitty_comment -->
    <cat>squishy</cat>
  </cats>
</root>
EOL
yq -px -ox test.xml
echo
yq -px -ox '(.root.cats | key) head_comment="wrong place"' test.xml
```
Returns:
```txt
yq (https://github.com/mikefarah/yq/) version v4.52.4

<root>
  <cats>
    <cat>soft</cat><!-- kitty_comment -->
    <cat>squishy</cat>
  </cats>
</root>

<root><!--wrong place -->
  <cats>
    <cat>soft</cat><!-- kitty_comment -->
    <cat>squishy</cat>
  </cats>
</root>
```

p.s. Thank you for this awesome tool!
