### ISSUE TITLE
How to recursively using `sort_by` and `pick`

### ISSUE THREAD

**Issue by shoekstra** [mikefarah/yq#1479]
Hi!

I'm trying to sort a file so that keys are sorted, key value pairs are sorted by their `name` value, and `name` is the first key in an array (when it exists). This is proving to be challenging.

I'm able to recursively sort using `sort_keys`, but cannot dynamically use `sort_by(.name)`, I need to specify the path to each array that contains these key pairs -- is there a way to look this up dynamically?

Additionally I want to make `name` the first key in an array when present. I'm about to do this by specifying the path and ` |= pick(["name"] + keys | unique )` -- is it possible to do this dynamically too?

Thanks in advance!

**Comment by mikefarah** [comment]
Sure:

```bash
yq 'with(.. | select(tag == "!!seq" and length > 0 and (.[0] | has("name"))); 
    . |= (sort_by(.name) | 
    (.[] |= pick(["name"] + keys | unique)) )
)' file.yaml
```

Explanation:
1. Find all the arrays that have a first object with a name field `.. | select(tag == "!!seq" and length > 0 and (.[0] | has("name")))`
2. with those, sort them by name, and apply the `pick` to all the children

Hope that helps!
