### ISSUE TITLE
cannot open files with sudo

### ISSUE THREAD

**Issue by gildas** [mikefarah/yq#148]
Seems like opening a "root-only" file does not work with sudo.

E.g.:

```
$ sudo yq r /etc/netplan/50-cloud-init.yaml network.version
open /etc/netplan/50-cloud-init.yaml: permission denied
```

**Comment by mikefarah** [comment]
I can't replicate this - can you double check that you can 'cat' the file?

**Comment by gildas** [comment]
Well, no I cannot `cat` the file. But if I `sudo cat` the file,  I can.

**Comment by mikefarah** [comment]
Closing this - haven't heard anything and no one else has reported a similar issue.

**Comment by jeking3** [comment]
I am seeing this after using "snap install yq":
```
jking@dvm:~/tutools$ yq r catalog.yml cloud-init-x64.sha256
a18c19ed5b462bd5728f5789c51b41e3f5436c27f103bad921c1822cfb723d5b
jking@dvm:~/tutools$ sudo yq r catalog.yml cloud-init-x64.sha256
Error: open catalog.yml: permission denied
Usage:
  yq read [yaml_file] [path] [flags]

Aliases:
  read, r

Examples:

yq read things.yaml a.b.c
yq r - a.b.c (reads from stdin)
yq r things.yaml a.*.c
yq r -d1 things.yaml a.array[0].blah
yq r things.yaml a.array[*].blah


Flags:
  -d, --doc string   process document index number (0 based, * for all documents) (default "0")
  -h, --help         help for read
  -j, --tojson       output as json

Global Flags:
  -t, --trim      trim yaml output (default true)
  -v, --verbose   verbose mode

12:31:12 main [ERRO] open catalog.yml: permission denied
jking@dvm:~/tutools$ sudo yq r /home/jking/tutools/catalog.yml cloud-init-x64.sha256
Error: open /home/jking/tutools/catalog.yml: permission denied
Usage:
  yq read [yaml_file] [path] [flags]

Aliases:
  read, r

Examples:

yq read things.yaml a.b.c
yq r - a.b.c (reads from stdin)
yq r things.yaml a.*.c
yq r -d1 things.yaml a.array[0].blah
yq r things.yaml a.array[*].blah


Flags:
  -d, --doc string   process document index number (0 based, * for all documents) (default "0")
  -h, --help         help for read
  -j, --tojson       output as json

Global Flags:
  -t, --trim      trim yaml output (default true)
  -v, --verbose   verbose mode

12:31:27 main [ERRO] open /home/jking/tutools/catalog.yml: permission denied
jking@dvm:~/tutools$ ls -ls catalog.yml
4 -rw-rw-r-- 1 jking jking 659 Oct 16 12:09 catalog.yml
```

**Comment by jeking3** [comment]
@mikefarah this should be reopened.

**Comment by h00130372** [comment]
I can reproduced this problem no matter with/without sudo, how I can resolve this?

**Comment by mikefarah** [comment]
Done some digging - this is a snapcraft confinement issue (https://docs.snapcraft.io/snap-confinement/6233), currently yq has 'strict' confinement and it really needs 'classic'.

I can't actually set it to 'classic' myself, I have to raise a forum request and get an admin to allow it, which I have done so here: https://forum.snapcraft.io/t/requesting-classic-confinement-for-yq/10559

**Comment by mikefarah** [comment]
btw - as a workaround if you install yq from the github release binaries then it should work...

**Comment by mikefarah** [comment]
Looks like this is they way snap is intended to work.

I've added some 'snap' specific instructions on how to access root files to the project readme as per the issue in the snapcraft forum

**Comment by MaurGi** [comment]
still reproing for me right now

**Comment by pkandarpa-cs** [comment]
Same

**Comment by Nenzyz** [comment]
Please check apparmor settings on the system.
Haven't figured out how to proceed yet, but dmesg shows that yq was denied.

**Comment by robstoll** [comment]
Same here, tried to install with `--classic` but seems like it is still installed as strict

**Comment by jessehu** [comment]
Hi @mikefarah can we remove the guide for `snap install yq` in README.md if it doesn't work as described in this ticket?

**Comment by falloutphil** [comment]
The instructions aren't quite right for the workaround (https://mikefarah.gitbook.io/yq/ under "Snap notes"):

```
sudo cat /etc/myfile | yq -r - somecommand
```

The is no -r flag.

Also the issue doesn't just occur with explicit sudo like this.  If you sudo to another user's account or non-interactive accounts (eg jenkins) also see the problem when running scripts with yq.

I use the following workaround:

```
yq <command> - <path_expression> <new value> < input.yaml
```

So replace input.yaml with "-" to take stdin pipe as input and then use the redirection operator at the end of the expression.

**Comment by mikefarah** [comment]
Thanks @falloutphil I've fixed the docs.

Are the snap workaround instructions working? As far as I can tell, in principal, they should. Basically snap doesn't let yq have sudo access - so you need to pipe in restricted fiel (or fiels from another account).

I guess if snap is more trouble than it's worth for folks I can remove the snap build entirely *shrug*

**Comment by parmentelat** [comment]
hiya

trying to use yq in a kubernets context, under fedora35, and running as root as this is all about setting up the cluster

because yq is not exposed as a standalone rpm from fedora - as far as I can tell - I went to snap-installing it
however I run into more trouble than what I bargained for, the simplest file operations are not working

```
 /tmp # cat a.yaml
a: 1
b: 2
 /tmp # yq . a.yaml
Error: open a.yaml: no such file or directory
```

bottom line is, as far as this use case is concerned, snap seems to make yq unusable, which is a pity...

what are the other options to install on f35 ?

thanks !
