### ISSUE TITLE
Inplace edit combines arguments, does not inplace edit each separately

### ISSUE THREAD

**Issue by scop** [mikefarah/yq#1483]
**Describe the bug**

In my opinion, inplace edits should edit each filename argument inplace, and not do any concatenation. Currently the behavior is to concatenate all argument file contents to the first file, inplace editing only that one.

In my usecase (see additional context) this is unexpected and an annoyance with YAML, but it's actually much more serious with JSON (`-i -o json`) because the output of two JSON documents concatenated is likely to be invalid JSON. Therefore I think this is a bug and not a feature request.

Version of yq: current from master branch
Operating system: linux
Installed via: source

**Input Yaml**

data1.yml:
```yaml
this : should really work
```

data2.yml:
```yaml
but : it strangely didn't
```

**Command**
The command you ran:
```
yq -iP data1.yml data2.yml
```

**Actual behavior**

```shellsession
$ cat data1.yml  # data1.yml got everything concatenated into it (and prettyprinted)
this: should really work
---
but: it strangely didn't
$ cat data2.yml  # data2.yml was left unmodified
but : it strangely didn't
```

**Expected behavior**

```shellsession
$ cat data1.yml  # no concatenation, just inplace prettyprinting
this: should really work
$ cat data2.yml  # no concatenation, just inplace prettyprinting
but: it strangely didn't
```

**Additional context**

Thinking about using yq as a pretty printer with [pre-commit](https://pre-commit.com), hitting a few issues.

**Comment by mikefarah** [comment]
`yq` takes multiple files in order to update the first w.r.t the others (e.g. merge). If you want to update several, you can use find (or xargs) - e.g.:

```bash
find data1.yaml data2.yaml -exec yq '. += "cow"' -i {} \;
```
