### ISSUE TITLE
Reuse input format as output

### ISSUE THREAD

**Issue by scop** [mikefarah/yq#1484]
**Please describe your feature request.**

An option to use the input format as the output format when pretty printing (instead of defaulting output to YAML) would be useful.

When inplace editing (#1483), the input/output mapping should be preserved for each file separately.

**Additional context**

Thinking about using yq as a pretty printer with [pre-commit](https://pre-commit.com/), hitting a few issues.

This one could be worked around by defining separate hooks to format JSON, YAML, ... instead of doing all in one.

**Comment by mikefarah** [comment]
in v4.32.2 if you don't supply a input or output format, and a file with a identifiable extension is given (e.g. json, xml...) then yq will process that file using the appropriate input and output formats. So if it's an XML file, it will parse and output XML...
