### ISSUE TITLE
Use yq from within go

### ISSUE THREAD

**Issue by fvogl** [mikefarah/yq#1486]
I use yq since quite a while now in bash scripts and I love it.
Now I've started to look into replacing some of my bash scripts with go binaries and now I struggle with doing there what I did with yq for manipulating yaml data. Is there a way to import yq and use it in go?

**Comment by abhimanyu003** [comment]
I would love to see the support for this so that this can be used in GO projects, by exposing some of the API's or some way to run commands directly from a string input.

**Comment by Zilkos** [comment]
This would be a really nice feature ! It's often that I get stuck with other lib for complex mapping.

**Comment by mikefarah** [comment]
You can use yq as a go library - although I have not (yet) released the library as a separate project with its own documentation as versioning. Start with the StringEvaluator (yq/pkg/yqlib/string_evaluator.go) file to run an expression against string content...

**Comment by mikefarah** [comment]
Note that although the yq interfaces are quite stable - as the API is not a separate project with its own semantic versioning - I don't provide guarantees that the interface may change a little.

**Comment by fvogl** [comment]
Thanks for the hint @mikefarah. I'll work with that but still hope you release an official library.
