### ISSUE TITLE
Control front-matter output

### ISSUE THREAD

**Issue by williamboman** [mikefarah/yq#1495]
**Please describe your feature request.**
If I have a YAML document like the following one:

```yaml
---
headers: here
---
contents: here
```

Running `$ yq -o j < data.yaml` yields output to stdout containing two JSON documents:

```json
{
  "headers": "here"
}
{
  "contents": "here"
}
```

This can be somewhat complicated to parse through JSON tooling.

**Describe the solution you'd like**

I'd like to be able to control the front-matter output a bit more. There's `yq -f extract < data.yaml` which allows me to only extract front-matter contents - but what's the inverse of this (only the document contents)? I think it'd be nice with a `yq -f ignore` or alternatively the ability to control to which fd the frontmatter output is written to, like `yq -o j --front-matter-output=/dev/stderr > contents.json 2> front_matter.json`. The latter would allow me to only run `yq` once to extract what I need. FWIW I currently only use `yq` to transform YAML to JSON, there's no filtering involved.

**Describe alternatives you've considered**
Piping JSON output from `yq` to `jq` and parse the documents through it instead (e.g. via `--slurp`).

**Comment by mikefarah** [comment]
Front matter processing is used when the content (after the yaml) is some sort of document in another incompatible format that yq ignores (like a jekyll template). The example you provide is a multi document yaml file - which is part of the yaml standard and yq supports it out of the box.

So you can use the built in `documentIndex/di` operator to select the document you are interested in:

```
yq 'select(di == 1)' -o=j examples/data1.yaml
```

**Comment by williamboman** [comment]
Ah, I had a feeling I was doing something goofy. Thanks for explaining!
