### ISSUE TITLE
Failure on ‘make install’

### ISSUE THREAD

**Issue by Pennyzct** [mikefarah/yq#150]
When you build binary from source code by `make install`, yq couldn't be installed in` $GOPATH/bin` as expected.
**CURRENT OUTPUT:**
```
docker run --rm -e LDFLAGS=" -X main.GitCommit=0d68bea -X main.GitDescribe=1.15.0-3-g0d68bea" -e GITHUB_TOKEN="" -v /home/penny/GoProjects/src/github.com/mikefarah/yq/vendor:/go/src -v /home/penny/GoProjects/src/github.com/mikefarah/yq:/yq/src/github.com/mikefarah/yq -w /yq/src/github.com/mikefarah/yq yq_dev go install
penny@penny-VirtualBox:~/GoProjects/src/github.com/mikefarah/yq$ yq
yq: command not found
```
For now, we built a container to` go install`, however we didn't bind mount the $GOPATH/bin dir into container. Expected output couldn't be brought back to the host.
Maybe we can change the command as follows:
```
docker run --rm -e LDFLAGS=" -X main.GitCommit=0d68bea -X main.GitDescribe=1.15.0-3-g0d68bea" -e GITHUB_TOKEN="" -v /home/penny/GoProjects/src/github.com/mikefarah/yq/vendor:/go/src -v /home/penny/GoProjects/src/github.com/mikefarah/yq:/yq/src/github.com/mikefarah/yq -v /home/penny/GoProjects/bin:/yq/bin -w /yq/src/github.com/mikefarah/yq yq_dev go install
```
Or just `go install` without container after `make build`.

@mikefarah

**Comment by Pennyzct** [comment]
@weichen81

**Comment by mikefarah** [comment]
I haven't actually used yq in docker ;) but I believe @kenjones-cisco has - perhaps he can help if he has the time...

**Comment by Pennyzct** [comment]
you maybe misunderstood what i said.
I was saying that when you build yq from source code and want to install it under $GOPATH/bin, you didn't carry the $GOPATH/bin dir into container, leading that the binary `yq` not brought back to host.
how about changing the variable `DOCKERRUN` in makefile.variables as follows:
```
DOCKRUN := docker run --rm \
	                                 -e LDFLAGS="${LDFLAGS}" \
	                                 -e GITHUB_TOKEN="${GITHUB_TOKEN}" \
                                         -e GOPATH="${GOPATH}"
                                         -v "${GOPATH}/src/${IMPORT_PATH}":"${GOPATH}/src/${IMPORT_PATH}"
                                         -v  "${GOPATH}/bin":"${GOPATH}/bin"
                                         -w  "${GOPATH}/src/${IMPORT_PATH}" \
	                                 ${DEV_IMAGE}
```
@mikefarah

**Comment by kenjones-cisco** [comment]
The use of the Docker.dev is so that everything happens within the container and nothing is installed locally. If you want to have the results happen locally, all you to do is include `local` as part of any make command.
ex.
```
make local install
```

This will result in the `DOCKERUN` variable being unset so that the actual command run is actually:
`go install`

**Comment by Pennyzct** [comment]
Hi~ @kenjones-cisco 
correct me if I'm wrong, for now, after running `make build && make install`, there were no yq binary created. or the correct command should be `make build && make local install`?

**Comment by kenjones-cisco** [comment]
The `install` task in the Makefile depends on the `build` task therefore it will be run first, and then `install` task is executed.

If the goal is to have a copy of the generated binary, I typically run `make xcompile` as it will generate the binaries and then select the one based on your OS to use.

I personally don't use `local`. I switch between multiple languages during a day so having a simple Makefile and Dockerfile.dev within each project allows me to switch easily.

I add the `local` to help those who prefer to just run the standard `go` commands and operate locally w/o docker.
