### ISSUE TITLE
Not as expected when replace node with referenced file as string

### ISSUE THREAD

**Issue by xianzheTM** [mikefarah/yq#1506]
**Describe the bug**
https://mikefarah.gitbook.io/yq/operators/load#replace-node-with-referenced-file-as-string
Unlike what this document describes, I use the load_str command to produce not multiple lines of text, but plain strings.

Version of yq: 4.30.6
Operating system: ubuntu(WSL)&windows.
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
1.yml:
```yaml
values: |
  abc
```

2.yml:
```yaml
image:
  tag: "0.0.1"
```

**Command**
The command you ran:
```
yq -i '.values |= load_str("2.yaml")' 1.yml
```

**Actual behavior**
1.yaml
```yaml
values: "image:\r\n  tag: \"0.0.1\""
```

**Expected behavior**
1.yaml
```yaml
values: | -
  image:
    tag: "0.0.1"
```

**Additional context**
Without`-i`:
output:
```yaml
values: "image:\r\n  tag: \"0.0.1\""
```

**Comment by mikefarah** [comment]
Might be a windows thing - especially given that there is a `\r` on your new line.

You can try forcing it by doing this:
```
yq -i '.values |= load_str("2.yaml") | .values style="flow"' 1.yml
```

**Comment by xianzheTM** [comment]
> Might be a windows thing - especially given that there is a `\r` on your new line.
> 
> You can try forcing it by doing this:
> 
> ```
> yq -i '.values |= load_str("2.yaml") | .values style="flow"' 1.yml
> ```
It is indeed the reason for the "CRLF".
CRLF：
```
$ yq -i '.values |= load_str("2.yaml") | .values style="flow"' 1.yml
values: "image:\r\n  tag: \"0.0.1\""
```
LF:
```
$ yq '.values |= load_str("2.yaml")' 1.yml
values: |-
  image:
    tag: "0.0.1"
```

**Comment by mikefarah** [comment]
Looking into this it seems like its a yaml spec thing: https://github.com/go-yaml/yaml/pull/124 and https://yaml.org/spec/1.2.2/#54-line-break-characters.
