### ISSUE TITLE
Error when merging using JSON output

### ISSUE THREAD

**Issue by mrballcb** [mikefarah/yq#151]
I have two simple yaml files.  I'm attempting to merge them and output the result as JSON.  The merge and output as yaml works fine, but output as JSON throws an error.

```
$ yq m -j pvalues-prod.yaml pvalues.yaml
Error: error printing yaml as json: json: unsupported type: map[interface {}]interface {}
```
Here are the yaml files I'm using as input:
```
$ cat pvalues.yaml
replicaCount: 2
maxReplicaCount: 4
proxy:
  servicePort: 8080

$ cat pvalues-prod.yaml
us-east-1:
  service:
    stackDomain: prod.example.com
    elb:
    - name: proxy
      externalPort: 443
      elbCertificateArn: arn:aws:acm:us-east-1:000000000000:certificate/abcdefgh-abcd-1234-abcd-123456789012
```
It is very specifically complaining about the array after the "elb" map item (array of ELB items).

**Comment by mikefarah** [comment]
Looks like a bug, as a temporary work around this seemed to work:
```
yq m pvalues-prod.yaml pvalues.yaml | yq r -j -
```

**Comment by mikefarah** [comment]
Ok latest version only supports JSON output for read (for multi document support in yaml).

Closing issue as this feature is no longer supported in merge.

**Comment by gsf** [comment]
Just trying yq out and was surprised `-j` didn't work for write. Are there plans to make `-j` global again or will the documentation be updated?
