### ISSUE TITLE
Prepend to list

### ISSUE THREAD

**Issue by holmesb** [mikefarah/yq#1513]
Hi,

I would like to use yq to prepend to a list.

If we have data1.yml like:
```yaml
- b
- c
- d
```

And we run a command:

```bash
yq '. += "a"' data1.yaml
```

it appends:
```yaml
- b
- c
- d
- a
```

and if I try:
```bash
yq '.[0] = "a"' /tmp/t.yaml
```
It replaces the first list item:
```yaml
- a
- c
- d
```

I would like to have:
```yaml
- a
- b
- c
- d
```

Is there already some way of achieving?

Many thanks

**Comment by mikefarah** [comment]
Yep just do:
```
yq '. = ["a"] + .' data1.yaml
```
