### ISSUE TITLE
Some values used as constant functions can replace entire value stream

### ISSUE THREAD

**Issue by kanwren** [mikefarah/yq#1515]
Values such as `1`, `"foo"`, or `[]` may be used as constant-valued functions that ignore their input and return the value. However, some types of constant values, like numbers and strings, will replace the whole multi-valued (or empty) input stream piped to them, instead of each value in the stream. Other types of constant values, like arrays or objects, will correctly replace each individual value.

- Version of yq: tested with 4.30.6 (unexpected behavior) and 3.1.0 (expected behavior)
- Operating system: tested on macOS and Linux
- Installed via: tested with homebrew (`yq`) and nix (`yq-go` and `yq` in nixpkgs)

**Input Yaml**

`data1.yml`:
```yaml
- 1
- 2
- 3
```

**Command**

```
yq eval '.[] | "foo"' data1.yml
```

**Actual behavior**

The whole stream of three values is replaced with a single value:
```yaml
foo
```

**Expected behavior**

Each of the values from the stream should have been replaced individually:
```yaml
foo
foo
foo
```

**Additional context**

The expected behavior is the result given by yq 3.1.0 as well as jq. yq 4 will even replace an empty stream with a value, so that `yq -n '[] | map(5)'` gives `[5]`.

It should be noted that only some constant-valued functions give this result. For example, running `yq eval '.[] | {}' data1.yml` on the above input gives the expected result of one empty object per value:

```yaml
{}
{}
{}
```

The same holds true for arrays used as constant values, like `[]` or `[1]`.

**Comment by mikefarah** [comment]
Thanks for raising, will fix in next release!

Fixing the replace empty stream is a bit trickier - (atm) yq doesn't know the difference between an expression like this '[] | .[] | 5' (i.e an empty value stream is passed in to the value operator); and '5' (the value stream starts empty and is given to the value operator).

In both cases, by the time it gets to the value operator, it just sees an empty value stream 🤔

**Comment by mikefarah** [comment]
Fixed in 4.30.7

**Comment by kanwren** [comment]
Should I split the empty stream into a separate issue? It doesn't look like that was fixed, and that was the thing that caused me to notice this issue in the first place

**Comment by mikefarah** [comment]
Yes please :)
