### ISSUE TITLE
Undefined vars/fonction in yaml

### ISSUE THREAD

**Issue by kratisto** [mikefarah/yq#152]
I don't know if the error come from this lib or yaml.v2. 
But when i go get yq , i have undefined var in yaml. 

```
jeffrey@MacBook-Pro-de-PC ~ $ go get github.com/mikefarah/yq
# github.com/mikefarah/yq
go/src/github.com/mikefarah/yq/yq.go:39:2: undefined: yaml.DefaultMapType
go/src/github.com/mikefarah/yq/yq.go:281:55: undefined: yaml.Encoder
go/src/github.com/mikefarah/yq/yq.go:282:23: undefined: yaml.Decoder
go/src/github.com/mikefarah/yq/yq.go:357:16: undefined: yaml.NewEncoder
go/src/github.com/mikefarah/yq/yq.go:406:2: undefined: yaml.DefaultMapType
go/src/github.com/mikefarah/yq/yq.go:407:17: undefined: yaml.DefaultMapType
go/src/github.com/mikefarah/yq/yq.go:500:26: undefined: yaml.Decoder
go/src/github.com/mikefarah/yq/yq.go:518:21: undefined: yaml.NewDecoder
go/src/github.com/mikefarah/yq/yq.go:522:44: undefined: yaml.Decoder
```

**Comment by mikefarah** [comment]
Ugh I think this is because I had to fork yaml.v2. Hopefully the PR will be merged. 

I used govendor to manage the dep and create a vendor.json - but it seems like `go get` did not use it. :(

I'll have to read up on the docs. In the mean time you can either download a binary, or you should be able to clone the repo manually and run 

```
make local vendor
make local install
```

**Comment by codevulture** [comment]
@mikefarah : I am getting errot for DefaultMaptype only now, I think the actual reference is (defaultMapType) https://github.com/go-yaml/yaml/blob/86f5ed62f8a0ee96bd888d2efdfd6d4fb100a4eb/decode.go#L237 but (DefaultMapType) is used which is not present , maybe add another another var/or make is exportable in yaml, I may be wrong though.

**Comment by mikefarah** [comment]
Ok read up on go get, and why https://gopkg.in/ exists :)

I think it's fixed now - give it a go.

Note that you should:
```
go get gopkg.in/mikefarah/yq.v1
```

instead of the github version. Basically gopkg allows you to route to a specific version of a package

**Comment by mikefarah** [comment]
Haven't heard back - I'm assuming this is fixed? Will reopen if not..

**Comment by kratisto** [comment]
Sorry I didn't see the github notification. 
The gopgk.in solution fix the problem !

Thanks

**Comment by mikefarah** [comment]
Great :)
