### ISSUE TITLE
Lexer Error Happening 

### ISSUE THREAD

**Issue by rishabhsharma3617** [mikefarah/yq#1538]
**Describe the bug**
In my .sh file i am using yq to convert a yml data in json for that i am storing the path of file in a variable . I am aware about operators for special characters but does they have a relation with this as well ? @mikefarah  I am suspecting that it must be happening because my directory name is .gitlab starting with a (.) and yq is unable to parse it somehow
ex -
` path = "../../.gitlab/ci/example-config.yml"`
when i execute the below command it throws lexer error 
`config_data=$(yq -o=json $path)`
Error - 
```
parsing expression: Lexer error: could not match text starting at 1:3 failing at 1:5.
	unmatched text: "/."
```

Version of yq: 4.25.1
Operating system: mac/linux/amd-64/....
Installed via:  wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -O /usr/bin/yq \
  && chmod +x /usr/bin/yq

**Comment by mikefarah** [comment]
Hi! It looks like it's trying to parse your path argument as an expression - I suspect that's probably because it can't find the file. 

If you like, try running `yq` like this:

config_data=$(yq -o=json '.' $path -v)

**Comment by mikefarah** [comment]
Closing - feel free to raise a new issue if this is still a problem
