### ISSUE TITLE
JavaScript engine to write little extension scripts

### ISSUE THREAD

**Issue by sandreas** [mikefarah/yq#1546]
It would be nice to have a small JavaScript engine / API to process and transform data that is hard to work with integrated features.

Simplified example:

```bash
echo '[1,2,3,4,5,6,7]' | yq --func='a => a.filter(x => x%2===0).sort().reverse().map(y => "value "+y)'
# [ "value 6", "value 4", "value 2" ]
```

Maybe [otto](https://github.com/robertkrimen/otto) would work?!

**Comment by mikefarah** [comment]
This could be a good idea for an alternative tool to yq - as it would make yq own expression language redundant. That said, you would need to bundle in a javascript engine - which could get cumbersome.
