### ISSUE TITLE
Implement the "complex mapping key" from YAML spec

### ISSUE THREAD

**Issue by peruzzof** [mikefarah/yq#1559]
**Please describe your feature request.**
Implement the "complex mapping key", per YAML spec (https://yaml.org/spec/1.2.2/ Example 2.11)

**Describe the solution you'd like**
If we have data1.yml like:
(please keep to around 10 lines )

```yaml
? - Detroit Tigers
  - Chicago cubs
: - 2001-07-23
```

And we run a command:

```bash
yq '.' data1.yml
```

it could output

```yaml
? - Detroit Tigers
  - Chicago cubs
: - 2001-07-23
```

**Describe alternatives you've considered**

**Additional context**
I found this limitation while trying to use a tool called "oasdiff", but the generated YAML is not properly parsed by yq. I raised an issue  (https://github.com/Tufin/oasdiff/issues/94) with the tool itself and they pointed me to the specification.

**Comment by mikefarah** [comment]
As fas as I can tell, this is what yq does already?

```bash
yq '.' data1.yaml 
? - Detroit Tigers
  - Chicago cubs
: - 2001-07-23
```
