### ISSUE TITLE
Writing in-place with docker doesn't work in 2.0.0

### ISSUE THREAD

**Issue by volbach** [mikefarah/yq#156]
![bildschirmfoto 2018-06-21 um 15 56 54](https://user-images.githubusercontent.com/18092644/41723575-c4a41d72-756b-11e8-8a59-398d5e4a78c1.png)

I use your docker image to change my settings.yml file in a git project. With version 2.0.0 it doesen´t work. The older version works (1.15.0) fine.

**Comment by mikefarah** [comment]
Ok found the issue - can't rename the file to move the temporarily file to the original yaml as that going from the internal docker file system to the mounted file system, instead I'll have gracefully degrade to copying the contents (https://stackoverflow.com/questions/21060945/simple-way-to-copy-a-file-in-golang).

Should have a fix in the next couple of days

**Comment by mikefarah** [comment]
Fixed by https://github.com/mikefarah/yq/releases/tag/2.0.1
