### ISSUE TITLE
comments at top of xml is unparsable back to yaml

### ISSUE THREAD

**Issue by gwythaint** [mikefarah/yq#1563]
comment at top of yaml produced by yq considered invalid by yq

yq --version
yq (https://github.com/mikefarah/yq/) version v4.30.8

sample.xml contents contains an xml comment on the second line below xml version declaration

![Screenshot2023_02_19_181858](https://user-images.githubusercontent.com/4960483/219994759-c5de5f3b-097e-44a2-927a-8133f2623aa8.jpg)

yq -p=xml sample.xml | yq -o=xml
Error: xml: EncodeToken of ProcInst xml target only valid for xml declaration, first token encoded

**Comment by mikefarah** [comment]
Hmm I see - I'll look into this - although regardless I recommend running the command like so (which does work)

```
yq -p=xml -o=-xml sample.xml
```

Also - for next time can you please dump the xml contents in a code block instead of an image - can copy paste text from an image :)

**Comment by gwythaint** [comment]
Yes, "yq -p=xml -o=-xml sample.xml" works.. but... ?!?! it's kinda degenerate.  I want the the intermediate yaml. Did I fail to detect sarcarsm?

**Comment by mikefarah** [comment]
...it's a workaround till I get free personal time to work on the open-source project...feel free to raise a PR if you would like it sooner

**Comment by mikefarah** [comment]
Fixed in v4.31.2
