### ISSUE TITLE
No pretty print by default on JSON, compared to jq and python yq

### ISSUE THREAD

**Issue by sputnick-dev** [mikefarah/yq#1568]
When you run the python version of `yq`, the default is to pretty print JSON. Like `jq` too.

Related: https://stackoverflow.com/a/27238477/465183

Version of yq: 4.30.5
Operating system: Linux Mint
Installed via: go

**Input JSON**

```json
{"type":"Bar","id":"1","title":"Foo"}
```

**Command**
The command you ran:
```
$ echo '{"type":"Bar","id":"1","title":"Foo"}' | yq .
{"type": "Bar", "id": "1", "title": "Foo"}
```

I find no way to pretty print a JSON.

The `-P` switch display the values, not the whole object

**Comment by mikefarah** [comment]
One of yq's features is that it (tries) to keep the formatting of the original document - which is why it doesn't format by default. That said, the `-P` flag should work (and does for me):

```bash
~/dev/yq> echo '{"type":"Bar","id":"1","title":"Foo"}' | yq . -P
type: Bar
id: "1"
title: Foo
```

What do you mean it displays the values?

**Comment by mikefarah** [comment]
Oh maybe you mean pretty print JSON output (it assumes yaml, which is a superset of JSON), in that case you can specify JSON output using the `-o/--output-format` format flag:

```bash
>echo '{"type":"Bar","id":"1","title":"Foo"}' | yq . -oj
{
  "type": "Bar",
  "id": "1",
  "title": "Foo"
}

```

**Comment by sputnick-dev** [comment]
Why it's not the default like family tools `jq `, Python `yq .`... ?

**Comment by mikefarah** [comment]
Default output to JSON? Cause it was firstly developed as a yaml processor.

**Comment by sputnick-dev** [comment]
Yes, that's the behavior of the Python implementation of `yq`.

If input is JSON, then output to JSON pretty printed.
