### ISSUE TITLE
Ability to read multiple documents in a single file

### ISSUE THREAD

**Issue by deitch** [mikefarah/yq#157]
As discussed [here](https://github.com/mikefarah/yq/issues/9#issuecomment-402021912), the latest release of `yq` has the ability to read multiple documents from a single file, using:

```
yq r -d1  examples/multiple_docs.yaml user.surname
```

But not to read from multiple documents, e.g.

```
yq r -d'*'  examples/multiple_docs.yaml user.surname
```

This creates an issue when you do not know in advance how many documents are in a multi-document file. 

Use case: you are processing a directory with 3 yml files, 2 of which are "normal" single-document files, and the 3rd is a multi-document file. E.g. you need to extract the `name` and `location` property from each of them, or perhaps convert them to `json` for processing by some other system. You can use a `for` loop to select each file independently and `yq` to process it, but when it comes to the 3rd file, you are stuck.

* you cannot use `yq -d'*' r third_file.yml` because it does not support processing all documents
* you cannot loop through (e.g. `for i in $doc_count; do yq -d $I read third_file.yml; done`) because you have no way of knowing how many documents are in that file

I think the first (multi-document) is better, but anything that gets us moving is good.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/v2.1.0 :)

you can now
```
yq r -d'*'  examples/multiple_docs.yaml user.surname
```

**Comment by deitch** [comment]
Amazing @mikefarah ! Thank you.

**Comment by alexharv074** [comment]
@mikefarah I have version 2.10.0 and yet do not seem to have this feature?

```
▶ yq --version 
yq 2.10.0
```

```yaml
# example.yml
---
foo: bar
---
foo: baz
---
foo: qux
```

```
▶ yq r -d'*' example.yaml 
jq: Unknown option -d*
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```

Similar with all the other usage examples I can find.

**Comment by mikefarah** [comment]
v2 is no longer supported - please try the latest v4

**Comment by alexharv074** [comment]
> v2 is no longer supported - please try the latest v4

@mikefarah Is this feature in v4 though? It doesn't appear to be.
