### ISSUE TITLE
error with env variables from another sh scripts

### ISSUE THREAD

**Issue by LuKtdf** [mikefarah/yq#1572]
**Describe the bug**
The env() function doesn't work with variable imported from the source command.

Version of yq: 4.31.1
Operating system: linux alpine
Installed via: binary release

**Input Yaml**
empty

**Command**
```sh
source test.sh        # contains test='a'
echo $test              # prints a
yq -n "env(test)"   # Error: Value for env variable 'test' not provided in env()
```

**Comment by tinpont** [comment]
I have same problem, how did you solve this?
