### ISSUE TITLE
`split_doc` fails with a Lexer error

### ISSUE THREAD

**Issue by justinmchase** [mikefarah/yq#1594]
**Describe the bug**
`split_doc` fails with a Lexer error

https://mikefarah.gitbook.io/yq/operators/split-into-documents

Version of yq:  4.16.2
Operating system: linux
Installed via: https://github.com/mikefarah/yq#on-ubuntu-1604-or-higher-from-debian-package

**Input Yaml**
```yaml
- a: "a"
- b: "b"
```

**Command**
The command you ran:
```
cat data1.yml | yq e '.[] | split_doc' -
```

**Actual behavior**

```
Error: Parsing expression: Lexer error: could not match text starting at 1:12 failing at 1:13.
        unmatched text: "_"
```

**Expected behavior**

```yaml
a: "a"
---
b: "b"
```

**Additional context**

I'm just trying to take an array and split it into multiple documents. It appears to be erroring on the `_` of the command `split_doc`, but the documentation seems to indicate that it is a valid function so I don't know whats going on.

**Comment by justinmchase** [comment]
This issue seems legit still but after looking in the code here:
https://github.com/mikefarah/yq/blob/2c14c9840898a01052e8e53d1455b1655cb1e048/pkg/yqlib/lexer_participle.go#L99

I can see there is a workaround to use `splitDoc` instead. I'm not sure if this is a legit issue or if there is some fundamental misunderstanding about the way this is supposed to work that I'm unaware of but it would be pretty helpful to update the docs if the latter is true.

**Comment by mikefarah** [comment]
Both splitDoc and split_doc work - the issue is that `yq` version is old and needs @rmescandon to update :( 

If you need that operator you should download the latest yq via github/snap/docker/brew

**Comment by rmescandon** [comment]
sorry, I'm not maintaining deb package anymore. Please find somebody to do such labor. Feel free to retire the deb support and instructions from the project. Thanks

**Comment by mikefarah** [comment]
Alright, thanks for your work :)

________________________________

**Comment by mikefarah** [comment]
@rmescandon I'll update the instructions - is it possible to remove it from debian, or have a deprecated warning?

**Comment by justinmchase** [comment]
Thanks for the update, I didnt have wget so I thought if I'm going to get a package I may as well get the one I want rather than take an extra step, thus I went with the deb package.

Removing it from the main readme would probably help.
