### ISSUE TITLE
yq eval: no such file or directory

### ISSUE THREAD

**Issue by nithinj** [mikefarah/yq#1605]
**Describe the bug**
Hello,

I am facing an issue while using the "yq eval" command to access a YAML file. Below is the command I am trying to run:

yq eval '.path.to.value' /path/to/your/file.yaml

However, I am receiving an error message that says:

Error: open /path/to/your/file.yaml: no such file or directory

I have verified that the file exists and that I have read permissions for it. Additionally, I have checked the syntax of the YAML file, and it appears to be valid.

Can you please suggest a solution to resolve this issue?

Version of yq: 4.31.2
Operating system: Ubuntu 22
Installed via: snap

**Command**
The command you ran: 
```
yq eval '.path.to.value' /path/to/your/file.yaml
```

**Actual behavior**

```yaml
/var/spool/lqs
```

**Expected behavior**

```yaml
Error: open /path/to/your/file.yaml: no such file or directory
```

**Additional context**

**Comment by nithinj** [comment]
seems like an issue with snap installed yq version.
downloading from releases solve the issue.
sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.31.2/yq_linux_amd64 -o ./yq

**Comment by jglick** [comment]
Common problem with the Snap. Try e.g.

```bash
yq eval '.path.to.value' </path/to/your/file.yaml
```
