### ISSUE TITLE
Release version tags changed to add v

### ISSUE THREAD

**Issue by deitch** [mikefarah/yq#162]
The tags for everything prior to `2.1.0` were just the numbers, e.g. https://github.com/mikefarah/yq/releases/download/2.0.1/yq_linux_amd64 

Version `2.1.0` added the inconsistent `v` at the beginning, e.g.
https://github.com/mikefarah/yq/releases/download/v2.1.0/yq_linux_amd64

It is ok to do either, but prob should be consistent

**Comment by mikefarah** [comment]
Yep good point - I've been playing with https://gopkg.in/ which uses the v* format - but happy to tag both formats for backwards compatibility.

**Comment by deitch** [comment]
Thanks!

**Comment by nemchik** [comment]
This caused some issues for me as well. I'm still only seeing a tag with the v. Had to adjust a script to add the v, but I'll have to adjust the script again to take it out...

**Comment by mikefarah** [comment]
Oh crud

**Comment by nemchik** [comment]
Sorry for the trouble!
