### ISSUE TITLE
Feature request: Allow eval expression to be read from stdin (or a file)

### ISSUE THREAD

**Issue by landure** [mikefarah/yq#1622]
`yq` eval expressions can be quite complex, but `yq` does not allow to read eval "script" from file or from stdin.

For example, I use `yq` to programmatically edit `docker-compose.yml` files. Currently, one of the simplest command I use is:

```bash
command yq --inplace 'eval' \
  'with( .volumes.mongodb-data ;
    . = { "driver" : "local" }
    | . head_comment="MongoDB data volume"
  )' \
  "${compose_project_path}/docker-compose.yml"
```

I would like to be able to do:

```bash
command yq --inplace 'eval' -
  "${compose_project_path}/docker-compose.yml" << EOF
with( .volumes.mongodb-data ;
  . = { "driver" : "local" }
  | . head_comment="MongoDB data volume"
)
EOF
```

or creating a `yq` command file:

```bash
tee '/tmp/volumes.yq' << EOF
with( .volumes.mongodb-data ;
  . = { "driver" : "local" }
  | . head_comment="MongoDB data volume"
)
EOF
```

And use it in a inplace eval:

```bash
command yq --inplace '/tmp/volumes.yq'  "${compose_project_path}/docker-compose.yml"
```

In addition, I would like to sometime create a yq script (but this should be quite complex to implement without breaking changes):

```yq
command tee 'yq-volume-script.bin' << EOF
#!/usr/bin/env yq

# Add docker volume definition.
with( .volumes.mongodb-data ;
  . = { "driver" : "local" }
  | . head_comment="MongoDB data volume"
)
EOF
command chmod +x 'yq-volume-script.bin'
./yq-volume-script.bin  "docker-compose.yml"
```

It would be fine to create a new action `eval-file` to differentiate with the default `eval` action. Using - with eval is really the feature I'm after.

Thank you for your work.

**Comment by mikefarah** [comment]
You actually can, you can using the 'eval' operator: run:

```
yq 'eval(load_str("yq-volume-script.bin"))'
```

or from an environment variable:

```
yq 'eval(strenv(EXPRESSION))'
```

See https://mikefarah.gitbook.io/yq/operators/eval for more info

**Comment by landure** [comment]
Thank you, it unwieldy, but it works. May be add this example to eval operator documentation:

```bash
pathEnv=".a.b[0].name"
valueEnv="moo" 
yq 'eval(load_str("/dev/stdin"))' sample.yml << EOF
${pathEnv} = "${valueEnv}" 
EOF
```
