### ISSUE TITLE
Yq not recognized on Ubuntu Server

### ISSUE THREAD

**Issue by gogo199432** [mikefarah/yq#163]
So I tried installing yq on a Ubuntu Server (VM) both with apt and snap. The installation goes through both times and says that it installed successfully. However when I try to just simply type yq as a command afterwards, it throws the following line into my face:

/usr/local/bin/yq: line 1: Not: command not found

**Comment by mikefarah** [comment]
Hmm when I snap install it on my Ubuntu VM it installs it under:
```
/snap/bin/yq -> /usr/bin/snap
```
Have you checked those folders, and if they're in the path?

**Comment by gogo199432** [comment]
For the /snap/bin/yq , I do have it, in the PATH variable too. The other folder however doesn't seem to exist, unless you mean that the snap at the end is the command itself. Since I can use "snap" wherever I assume it is there.

Here is my current PATH config: 
![kepkivagas](https://user-images.githubusercontent.com/9107561/42624960-ea84a852-85c6-11e8-8622-406a8de79a0e.PNG)

**Comment by mikefarah** [comment]
what happens when you run /snap/bin/yq directly?

where did /usr/local/bin/yq come from?

**Comment by gogo199432** [comment]
Okay, so here is an interesting thing. When I go into the snap/bin folder and do ./yq it seems to work, I get the expected help log. However if, in the same folder, I just type yq it says the same error as before. Is there a way to make the ./yq command into the simpler yq one?

As to how this came about, the only reason I'm trying to use this is because I wanted to try out [this](https://github.com/GhostWriters/DockSTARTer) project, which uses yq. I assume it tried to install yq at some point of the setup process.

**Comment by mikefarah** [comment]
Ok - there's actually another 'yq' that I'm suspecting you have installed (https://github.com/kislyuk/yq), this one requires python and jq to be installed.

To fix your './yq' you'll need to either remove that yq in your /usr/local/bin/yq, or keep it and install python + jq. Not sure if it would conflict with 'DockSTARTer' though.

I haven't registered this 'yq' into apt, so perhaps apt get remove?

Name confusion ftw

**Comment by gogo199432** [comment]
Actually I believe it uses your repo, and it especially installs it into the local directory. I found the script that does the installing I believe.

https://github.com/GhostWriters/DockSTARTer/blob/master/scripts/install_yq.sh

**Comment by gogo199432** [comment]
After I manually copied over the yq file inside the snap directory to the /usr/local/bin I can issue the yq  command without error. I think something might be wrong with the way the script is launched on the DockSTARTer side

**Comment by nemchik** [comment]
My approach with DockSTARTer is to grab the binaries from this repo directly and avoid dependencies completely.

If someone had another yq from another source installed prior that would probably cause issues. I can add some error handling to my installer to report a little more.

**Comment by nemchik** [comment]
@mikefarah  if I'm grabbing the binaries directly from your repo, is there another folder your recommend installing the binary to? I only picked /usr/local/bin because the official docker compose install instructions also use that location.

**Comment by mikefarah** [comment]
No not particularly :)

Perhaps it didn't download the file properly @gogo199432 if you cat the yq binary do you see a binary file or something else?

E.g. When I'm at work we use a proxy and if it's not configured properly then accessing a link like that will return 200 OK but a HTML page telling me to login the proxy instead of the binary ;)

Or maybe the binary the script downloaded isn't the right one for your architecture?

**Comment by gogo199432** [comment]
Sorry, I already overwritten the original incorrect file, but I tried to open both the faulty and the correct one with nano before. The good one gives me a lot of random characters which I assume is the binary file. The faulty one however only had one cleanly readable line starting with Not or Nothing, can't remember.

**Comment by nemchik** [comment]
@gogo199432 two days ago when yq 2.1.0 released DS had an issue installing (brought to you by the letter v). It got fixed same day I believe. https://github.com/mikefarah/yq/issues/162

**Comment by mikefarah** [comment]
Seems like the curl didn't work. Either a script problem @nemchik or a problem with your machine curling. 

Closing the issue :)

**Comment by nemchik** [comment]
@mikefarah sorry for the issue bleed over from DockSTARTer! We're very grateful for your yq!

@gogo199432 if you're still having trouble we can continue looking into your issue with https://github.com/GhostWriters/DockSTARTer/issues/95

**Comment by mikefarah** [comment]
no worries :)
