### ISSUE TITLE
Output to shell variables

### ISSUE THREAD

**Issue by giorgiga** [mikefarah/yq#1632]
It would be helpful if yq could output values as VARIABLE=VALUE lines to be sourced in bash.

The format would be similar to the existing props one, but keys should be sanitized (no dots, no hyphens ...) and values should be properly escaped.

A variant that outputs fish `set` commands instead of posix VARIABLE=VALUE would also be great, but there are utilities that convert posix to fish.

Suppose we have:

```yaml
country: 
  name: Australia
  capital: Camberra
```

And we run a command:

```bash
yq -o shvars
```

it could output

```yaml
COUTNRY_NAME='Australia'
COUNTRY_CAPITAL='Camberra'
```

**Comment by mikefarah** [comment]
Ill accept a PR for this - in the meantime you can get a similar result by:

```
yq '.. | select(tag == "!!str") |  (path | join("_") | upcase) + " = " + .' examples/data1.yaml
```
