### ISSUE TITLE
executing a query while a file with the same name exist returns the file content and not the query for the file you are querying

### ISSUE THREAD

**Issue by capoeirabg** [mikefarah/yq#1644]
**Describe the bug**
When evaluating an object from a file and a file with the same name exist the yq returns the content of the file with the same name and not the query from the one that you are providing!

Version of yq: 4.X.X
Operating system: linux/windows
Installed via: none

**Input Yaml**
Chart.yaml:
```yaml
apiVersion: v2
version: 0.0.1
appVersion: "01.06.09.00_AWS.01"
name: sis
type: application
```

**Command**
The command you ran:
```
yq '.version' ./helm/Chart.yaml
```

**Actual behavior**

```yaml
01.06.09.00_AWS
```

**Expected behavior**

```yaml
0.0.1
```

The result the query returns is the content of a hidden file .version that is in the same folder that I execute the yq command and if I remove it everything work as expected but with a file names .version it always reads the file and print it's content.  Even it I pipe the file content with:
```
cat ./helm/Chart.yaml | yq '.version'
```

**Comment by mikefarah** [comment]
You need to use the `--expression` flag to force it to recognise that its an expression:

```
cat ./helm/Chart.yaml | yq --expression '.version'
```
