### ISSUE TITLE
`yq -oy` and `yq -Poy` provides different output from json input.

### ISSUE THREAD

**Issue by starleaffff** [mikefarah/yq#1646]
**Describe the bug**
Given a json input, the `yq -oy` or `yq --output-format=yaml` command prints a oneline json. `yq -Poy` prints in yaml format.
Without the `-P` flag, the output should still be in yaml format.

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.33.3
Operating system: mac
Installed via: homebrew

**Input Yaml**
```
% jq -n '.a="asdf"|.b="uijk"'
{
  "a": "asdf",
  "b": "uijk"
}
% jq -n '.a="asdf"|.b="uijk"' | yq -oy
{"a": "asdf", "b": "uijk"}
% jq -n '.a="asdf"|.b="uijk"' | yq -Poy
a: asdf
b: uijk
```

**Comment by mikefarah** [comment]
JSON is a subset of YAML which is why you need the `-P` flag to pretty print it in idiomatic YAML.

yq has been built to try and preserve the original document as much as possible, this includes styling information. The `-P` flag basically tells it to discard that info.
