### ISSUE TITLE
go install error

### ISSUE THREAD

**Issue by go-slark** [mikefarah/yq#1659]
Hi, here are a problem
excute: go install github.com/mikefarah/yq/v4@latest, then go\pkg\mod\github.com\mikefarah\yq\v4@v4.33.3\cmd\evaluate_all_command.go:6:2: //go:build comment without // +build comment

win10
thx

**Comment by mikefarah** [comment]
Go install is not a supported mechanism for `yq`. If you want to build from source, use go get and go build.

If you still have issues raise another bug with which go compiler you are using and the error message.
