### ISSUE TITLE
yq merge incorrect

### ISSUE THREAD

**Issue by go-slark** [mikefarah/yq#1660]
Version of yq: 4.33.3
Operating system: windows
Installed via: go install

**Input Yaml**
data1.yml:
tags:
    - name: Topic

data2.yml:
tags:
    - name: User

**Command**
yq ea '. as $item ireduce ({}; . * $item )' infra/api/proto/topic/*.yaml infra/api/proto/user/*.yaml> open.yaml

**Actual behavior**
tags:
    - name: User

**Expected behavior**
tags:
    - name: Topic
    - name: User

**Comment by mikefarah** [comment]
You need to use the "+" merge flag to get it to append arrays, see docs here: https://mikefarah.gitbook.io/yq/operators/multiply-merge#merge-flags
