### ISSUE TITLE
strenv(yes) should be quoted

### ISSUE THREAD

**Issue by TJM** [mikefarah/yq#1663]
**Describe the bug**

`strenv()` should quote the value, especially if the value may be parsed incorrectly, but should probably just unconditionally quote it.

Version of yq: `4.33.3`
Operating system: mac/linux/windows/.... `macos 13`
Installed via: docker/binary release/homebrew/snap/... `brew`

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
(null)

**Command**
The command you ran:
```console
$ myenv="yes" yq --null-input '.value = strenv(myenv)'
```

**Actual behavior**

```yaml
value: yes
```

**Expected behavior**

```yaml
value: "yes"
```

**Additional context**

This is almost exactly the same example as the docs: https://mikefarah.gitbook.io/yq/operators/env-variable-operators#read-boolean-environment-variable-as-a-string .. except that apparently yq doesn't know `yes` is boolean?

**Comment by mikefarah** [comment]
So "yes" is interpreted as a boolean in the _1.1_ yaml standard, but that was dropped in 1.2 https://yaml.org/spec/1.2.2/ !

The standard the the underlying yaml library yq uses is 1.2 - which means `prop: yes` is the string "yes".

**Comment by mikefarah** [comment]
I thought I had that documented somewhere but can't find it - will add

**Comment by TJM** [comment]
It still seems like **str**env should just quote the value, instead of leaving it up to the client that is interpreting the yaml. In our case, we are applying the value to a metadata value of a kubernetes secret. Is there some other way to get the quoted string "yes" to show up? We were having a heck of a time with it. :)

**Comment by mikefarah** [comment]
You can force quotes by using the style operator if you wish - there's an example here: https://mikefarah.gitbook.io/yq/operators/with#update-and-style

the style operator is documented here: https://mikefarah.gitbook.io/yq/operators/style#set-double-quote-style

so you'd have something like:

```
with(.value; . = strenv(myenv) | . style="double")
```

**Comment by RONNCC** [comment]
@mikefarah  Q: wondering if there's any context why `style="double"` goes inside the string rather than as a `yq` command line arg?

**Comment by mikefarah** [comment]
It's because you're setting the style property on that particular node
