### ISSUE TITLE
Error: unknown command

### ISSUE THREAD

**Issue by roipoussiere** [mikefarah/yq#1683]
I tried many examples provided in the documentation, but I get the same error:

```
> echo 'foo: bar' > test.yml
> yq test.yml '.'
Error: unknown command "test.yml" for "yq"
```

Same thing when using stdin, or testing another file.

yq v4.16.2 on Ubuntu 22.04.2 LTS.

**Comment by mikefarah** [comment]
You need to give the expression before the file - see readme/docs
