### ISSUE TITLE
Only update affected keys

### ISSUE THREAD

**Issue by varac** [mikefarah/yq#171]
Given this yaml file:

```
» cat test.yml 
---
a:
  - 1
  - 2
c: foo
```

When I like to update `c` with a new value, I would expect that only this key would be modified.
But at least the indentation of other keys are touched, which complicates seeing changes with diff/git:

```
⏻  /tmp  » yq write test.yml c "bar" > test2.yml
⏻  /tmp  » diff test.yml test2.yml 
1d0
< ---
3,5c2,4
<   - 1
<   - 2
< c: foo
---
> - 1
> - 2
> c: bar
```

Please let yq only touch affected keys, if possible.

**Comment by varac** [comment]
The wrong indentation issue is reported already here: #25

**Comment by mikefarah** [comment]
Hi varac, 

Thanks for raising these points, and I agree it would be better if it did what you are suggesting.

However, the way ``yq`` works (atm) is to slurp in the yaml using https://github.com/go-yaml/yaml apply the transforms and then output it again, using https://github.com/go-yaml/yaml.

This is why the formatting changes when using yq, and it's also why comments are discarded (which is also annoying).

So unless go-yaml has an update where we can specify formatting or something, then there's no real way of getting this fixed without completely rethinking how ``yq`` works.

**Comment by mikefarah** [comment]
Just released a new version of yaml that fixes this - it's a pretty significant update so it's still in beta: https://github.com/mikefarah/yq/releases/tag/3.0.0-beta

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
