### ISSUE TITLE
inconsistent result when concatenating string with null

### ISSUE THREAD

**Issue by ryenus** [mikefarah/yq#1712]
**Describe the bug**
The result of string concatenation with null varies depending on the order:

Command | Output
--------|--------
`yq -n '"str" + null' -oj` | "strnull"
`yq -n 'null + "str"' -oj` | "str"
`jq -n '"str" + null'` | "str"
`jq -n 'null + "str"'` | "str"

So when `null` was appended a string it end up as the string literal `"null"`, but when appending a string to `null`, it end up as an empty string.

Meanwhile as a comparison, jq turns both `null` into `""`, namely empty strings.

**Version of yq**: 4.34.1
**Operating system**: mac
**Installed via**: homebrew

**Expected behavior**
I'd expect when converting `null` to a string, the result should be consistent in both case, regardless the order of the operands.

**Comment by mikefarah** [comment]
Thanks for raising - will update so that "str" + null = "str" :)

**Comment by mikefarah** [comment]
Fixed in 4.35.2
