### ISSUE TITLE
merge two files Yaml

### ISSUE THREAD

**Issue by anouarbouayad** [mikefarah/yq#1715]
### Discussed in https://github.com/mikefarah/yq/discussions/1713

<div type='discussions-op-text'>

<sup>Originally posted by **anouarbouayad** June 28, 2023</sup>
I want to merge two yaml files file_dest.yml and file_source.yml. 
"file_dest.yml"
---
type: PortalConfiguration
fields:
  apiregAuthenticationPolicies: /Policies/YAML_PROJECT_120623/SECU_YAML_PROJECT_120623

"file_source.yml"
---
type: PortalConfiguration
fields:
  apiregAuthenticationPolicies:
    - /Policies/COMMUN/SECURITE/API_KEY/SECU_APIKEY_SECRET
    - /Policies/BIG/SECURITY_POLICIES/SECU_BIG
    
I use one the following query:
yq eval-all 'select(fileIndex == 0) *+ select(fileIndex == 1)' "file_dest.yml" "file_source.yml"

yq ea '. as $item ireduce ({}; . * $item )' "file_dest.yml" "file_source.yml"

The result of this request is 
---
type: PortalConfiguration
fields:
  apiregAuthenticationPolicies: /Policies/YAML_PROJECT_120623/SECU_YAML_PROJECT_120623

I want to produce the following file the merge of two files.

---
type: PortalConfiguration
fields:
  apiregAuthenticationPolicies:
    - /Policies/COMMUN/SECURITE/API_KEY/SECU_APIKEY_SECRET
    - /Policies/BIG/SECURITY_POLICIES/SECU_BIG
    - /Policies/YAML_PROJECT_120623/SECU_YAML_PROJECT_120623

Help me</div>

**Comment by mikefarah** [comment]
Sorry missed this - updated the discussion with the answer.
