### ISSUE TITLE
run a yaml file within a bash script

### ISSUE THREAD

**Issue by Overcraft90** [mikefarah/yq#1724]
Hi there I'm new to this approach but what I basically need to do is to read in a _.sh_ script a _.yaml_ file for a job array. The _.yaml_ looks like this
```
# input vcf with variants to be genotyped
vcf: $d/decomposed_and_filtered.vcf

# reference genome
reference: /path/to/hg38.fna

# path to reads (FASTA/FASTQ format, uncompressed)
# for each sample that shall be genotyped
reads:
 HG002: /path/to/HG002.fastq

# path to PanGenie exectuable
pangenie: /path/to/PanGenie

# name of the output directory
outdir: $d/genome_inference
```
First of all, would be great if there was a way to read all the five fields at once with `yq`; secondly, my job array accesses directories (**_$d_**) based on a `name.list` file with the paths to those folders. 
So, it will be useful/necessary to be able to link this information within the script parsing the _.yaml_ file. Any suggestion. or insight is appreciated, thanks in advance!

**Comment by mikefarah** [comment]
This is better suited as a stackoverflow question, please raise there.
