### ISSUE TITLE
Yaml output not working

### ISSUE THREAD

**Issue by arren-ru** [mikefarah/yq#1735]
**Describe the bug**
Tried to convert simple json to yaml, but it just outputs the same json again

Version of yq: 4.34.2
Operating system: mac
Installed via: homebrew

**Command**
The command you ran:
```
yq <test.json -o yaml .
```

**Comment by Boerseth** [comment]
Recall that YAML is a superset of JSON, which means that any valid JSON is also valid YAML[1]. So technically speaking, `yq` actually gave you what you asked for.

I am guessing your input was small enough that `yq` did not end up needing to format it in the more YAML-like way, but I am basing that guess off of almost nothing. It would perhaps be helpful if you added some more details to your example.

[1] http://yaml.org/spec/1.2-old/spec.html#id2759572

**Comment by mikefarah** [comment]
Yep - That's right, JSON is a subset of YAML, and as `yq` tries to keep the formatting as untouched as possible by default, it does nothing. To get idiomatic yaml - you can use the pretty print flag:

```
yq <test.json -o yaml -P
```
