### ISSUE TITLE
Q: how to avoid quotes on setting key value

### ISSUE THREAD

**Issue by glebsts** [mikefarah/yq#1757]
Hello,
My need: having yml file for certain process, I want to replace certain key value with another gomplate/helm instruction to work with result down the flow.
So I run
```
yq '.myKey ="{{ include \"included-file\" }}"' input.yml
```
but ofc get result of 
```
mykey: '{{ include "included-file" }}'
```
and I'd like it to be (mind the missing single quotes).
```
mykey: {{ include "included-file" }}
```

Tried playing with `style` but no success. Without quotes in replace statement command is invalid.
Any chance it is possible?
Thank you.

**Comment by mikefarah** [comment]
The problem is that without the quotes it isn't valid yaml, so yq won't produce it. This is because help templates aren't valid yaml.
