### ISSUE TITLE
Output raw Front Matter

### ISSUE THREAD

**Issue by szepeviktor** [mikefarah/yq#1766]
**Please describe your feature request.**

I'd like to output unprocessed (byte-by-byte) raw Front Matter.
`yamllint` does not support linting Front Matter. I would use yq to extract Front Matter from Markdown documents and lint it with `yamllint` but yq outputs reformatted YAML.

**Describe the solution you'd like**

```bash
yq --front-matter=raw
```

Cc @adamlaki

**Comment by mikefarah** [comment]
Do you have a short example to show what you mean?

**Comment by szepeviktor** [comment]
I would like to get this part
https://github.com/conedevelopment/cone-site/blob/main/src/contact.md?plain=1#L2-L8
of the document.

**Comment by mikefarah** [comment]
Yeah I see - the thing is, the way yq works is it slurps up the data into it's own data model, runs the expression against the data, then outputs it again. It tries its best to preserve whitespace and general styling, but some is inevitably lost.

If you want byte-by-byte no reformatting you'll need to use something else, maybe sed?

**Comment by szepeviktor** [comment]
One work/around is to remove document contents so the front matter remains.
https://github.com/conedevelopment/cone-site/blob/main/.github/workflows/test.yml#L58-L65
