### ISSUE TITLE
Question: Cleaner method to use `contains`

### ISSUE THREAD

**Issue by planeiii-te** [mikefarah/yq#1769]
**Please describe your feature request.**
I would like a way to get a boolean or cleaner response from `contains` usage. It doesn't appear that setting the exit codes is supported so I'm looking for alternative solutions.

**Describe the solution you'd like**

data1.yml:
```yaml
name: catpants
```

data2.yml:
```yaml
name: catpants
```

data3.yml:
```yaml
name: foobar
```

And we run a command:

```bash
meh="$(yq --exit-status '.name | contains(["foobar"])' *.yml && echo 'yes' || echo 'no')"
```

It could exit with status code of `0` if found and `1` if not found (this is comparable to `grep`).

**Describe alternatives you've considered**

Currently I'm currently adding `grep` into the mix to set the exit code as expected.

```shell
meh="$(yq '.name | contains(["foobar"])' *.yml | grep --quiet 'true' && echo 'yes' || echo 'no')"
```

**Comment by mikefarah** [comment]
exit-status works for me - I think you need to drop the square brackets:

```
yq --exit-status '.name | contains("foo")' examples/data1.yaml examples/data2.yaml >/dev/null && echo "yes" || echo "no"
yes

```
