### ISSUE TITLE
make build fails due to gosec

### ISSUE THREAD

**Issue by dgomezleon** [mikefarah/yq#1777]
**Describe the bug**
Build fails due to `gosec` validation.

It has failed since `gosec` 2.17.0 added rule: [G601 - Implicit memory aliasing of items from a range statement](https://github.com/securego/gosec#usage)

Version of yq: 4.35.1
Operating system: linux

**Command**
```
make local build
```
**Actual behavior**

```
[/tmp/yq-4.35.1/src/github.com/mikefarah/yq/pkg/yqlib/decoder_json.go:70] - G601 (CWE-118): Implicit memory aliasing in for loop. (Confidence: MEDIUM, Severity: MEDIUM)
    69:         for _, keyValuePair := range data.kv {
  > 70:                 yamlValue, err := dec.convertToYamlNode(&keyValuePair.V)
    71:                 if err != nil {



Summary:
  Gosec  : 2.17.0
  Files  : 118
  Lines  : 12811
  Nosec  : 8
  Issues : 1
```

**Expected behavior**
Binary is built.

**Additional context**
[CWE-118](https://cwe.mitre.org/data/definitions/118.html)
[Gosec 2.17.0 changelog](https://github.com/securego/gosec/releases/tag/v2.17.0)

**Comment by mikefarah** [comment]
Should be fixed now

**Comment by dgomezleon** [comment]
Nice. Thanks for letting me know.

Do you plan to release a new version soon?

**Comment by mikefarah** [comment]
Yep - later this week hopefully
