### ISSUE TITLE
Anchors not working

### ISSUE THREAD

**Issue by caub** [mikefarah/yq#178]
```sh
yq r - <<EOF
serv:
  lol:
    <<: &s
      bar: ko
    foo: ok
  wat: *s
EOF

serv:
  lol:
    foo: ok
  wat:
    bar: ko

```

it should give

```sh
serv:
  lol:
    bar: ko
    foo: ok
  wat:
    bar: ko
```

**Comment by mikefarah** [comment]
Yep can confirm, looks like its an issue in the underlying yaml library I'm using - and they won't fix it until v3 comes out.

https://github.com/go-yaml/yaml/issues/184#issuecomment-371859215

**Comment by cup** [comment]
https://github.com/mikefarah/yq/issues/206

**Comment by cup** [comment]
https://github.com/drone/drone/issues/2323
https://github.com/drone/drone-cli/pull/103
https://github.com/go-swagger/go-swagger/issues/1193
https://github.com/go-yaml/yaml/issues/184
https://github.com/go-yaml/yaml/issues/344
https://github.com/go-yaml/yaml/issues/91

https://github.com/mikefarah/yq/issues/178
https://github.com/mikefarah/yq/issues/206

**Comment by Trane9991** [comment]
go-yaml.v3 is available [[blogpost here]](https://blog.ubuntu.com/2019/04/05/api-v3-of-the-yaml-package-for-go-is-available)!

**Comment by ssoerensen** [comment]
Any update on this issue?

**Comment by thelangley** [comment]
we're bumping into this too and have to use fun python scripts to work around this functionality.

Not a biggy but would be ace if it could follow anchors

**Comment by galindro** [comment]
@mikefarah Do you have an ETA for fix this problem?

**Comment by mikefarah** [comment]
The problem is that to use the v3 library I basically need to rewrite yq. Just don't have the time for that atm :(

**Comment by galindro** [comment]
Ok man, I completely understand you. Take your time.

**Comment by jk2K** [comment]
duplicate of https://github.com/mikefarah/yq/issues/264

**Comment by jk2K** [comment]
> The problem is that to use the v3 library I basically need to rewrite yq. Just don't have the time for that atm :(

I will try to support this feature

**Comment by mikefarah** [comment]
Just released a new version of yaml that fixes this - it's a pretty significant update so it's still in beta: https://github.com/mikefarah/yq/releases/tag/3.0.0-beta

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
