### ISSUE TITLE
yq of the version 4.2.0 can't recognize environment variables

### ISSUE THREAD

**Issue by cyxinda** [mikefarah/yq#1796]
**Describe the bug**

yq can't recognize environment variables .
I run the example refer to https://mikefarah.gitbook.io/yq/operators/env-variable-operators.
It is like:
```bash
[root@sc-master-1 ~]# yq -V
yq version 4.2.0
[root@sc-master-1 ~]# myenv="cat meow" yq --null-input '.a = env(myenv)'
Error: unknown command ".a = env(myenv)" for "yq"
Run 'yq --help' for usage.
```
or
```bash
[root@sc-master-1 ~]# myenv="cat meow" yq --null-input eval '.a = env(myenv)'
Error: Parsing expression: Lexer error: could not match text starting at 1:6 failing at 1:8.
        unmatched text: "en"
```

I run the same command with the version of 4.18.1,It is normal:
```bash
cyxinda@oldsix:~$ yq -V
yq (https://github.com/mikefarah/yq/) version 4.18.1
cyxinda@oldsix:~$ myenv="cat meow" yq --null-input eval '.a = env(myenv)'
a: cat meow
cyxinda@oldsix:~$ myenv="cat meow" yq --null-input  '.a = env(myenv)'
a: cat meow
cyxinda@oldsix:~$ 
```
![截图 2023-09-22 19-08-09](https://github.com/mikefarah/yq/assets/7237898/21474857-83c8-46ea-8c61-d29049f4e78c)

so it is a bug ??
** Version Info **
yq version 4.2.0
Operating system: Linux (rocky 9.2 or ubuntu22.04)
Installed via: [Download the latest binary](https://github.com/mikefarah/yq/releases/latest)

**Comment by mikefarah** [comment]
Please download the latest version and try again.

**Comment by cyxinda** [comment]
> Please download the latest version and try again.

ok,it works.
thanks.
