### ISSUE TITLE
delete node at a path

### ISSUE THREAD

**Issue by davidkhala** [mikefarah/yq#18]
Is there possible to support write key with empty value like that:
```
networks:  
    networkName:
```

**Comment by mikefarah** [comment]
Not at the moment - though not sure what the value of that would be?

There was some discussion of being able to delete a node - would that make more sense? Though that also has not been done - happy to take Pull Requests!

**Comment by davidkhala** [comment]
This requirement occurs when I tried to using yaml to generate docker-compose file.
Some examples show that no data or value under the key 'networkName'. But after testing, it seems those examples cannot work perfectly. 
So never mind. Deleting a node is a more reasonable feature.

**Comment by mikefarah** [comment]
Cool - I'll keep this issue but rename it to delete a node.

**Comment by atbentley** [comment]
I can look into putting together a PR for this if you're open to it, @mikefarah

There's the question of the interface though. How about adding a --delete/-d or --remove/-r flag to the write command to indicate removing, or maybe adding a new delete/remove command. What are your thoughts?

**Comment by JonathanTech** [comment]
I'm interested in this feature. I like the suggestion of a --delete/-d or --remove/-r on the cli, but i'm thinking the way this depends on the gopkg.in/yaml.v2 library for scripts that it might look like this for the scripted updates:
```
yq w -s update_instructions.yaml --delete-script delete_instructions.yaml
yq w -s update_instructions.yaml -ds delete_instructions.yaml
```
That or something like it or things will have to get far more complicated (like functions in jq) in order to make it work. 
Ideas?

**Comment by JonathanTech** [comment]
As it is, my workaround for today will probably involve outputting to json, using the jq delpaths() function, and then re-importing that json through yq
