### ISSUE TITLE
JSON strings with boolean values are not quoted when reading from a file 

### ISSUE THREAD

**Issue by khaled** [mikefarah/yq#1802]
**Describe the bug**
Strings with boolean values are not quoted in the output when JSON input is read from a file.   Quoting *does* occur as expected when reading from standard input.

Version of yq: 4.35.1
Operating system: linux
Installed via: nix

**Input Yaml**
```json
[{"x": "no"}, {"x": "yes"}]
```

**Command**

The following script reproduces the bug:

```bash
set -x
echo '[{"x": "no"}, {"x": "yes"}]' > foo.json
# read from stdin
cat foo.json | yq -P -oy '.'
# read from file
yq -P -oy '.' foo.json
```

**Actual behavior**

Read from stdin (correct):
```yaml
- x: "no"
- x: "yes"
```

Read from file (incorrect)
```yaml
- x: no
- x: yes
```

Note that this will also occur with other values treated as yaml booleans, such as on/off.

**Expected behavior**

Both outputs are the same

**Comment by mikefarah** [comment]
As of yaml 1.2, only true/false are boolean values - and that's what yq supports.

The reason you are getting the quoting differences is a little subtle - when you pipe the file into yq `cat foo.json | yq -oy` it doesn't know the content type, so it assumes it's yaml, the yaml parser is used and the formatting is preserved. 

When you pass in the file `yq -oy file.json` it sees the JSON extension and uses the JSON parser to read the content. To the JSON parser, yes/no is a regular string. As part of converting that to yaml `-oy` it drops the quotes. If you like, you could force the YAML parse by `yq -py -oy -P file.json` and get what you want.

**Comment by khaled** [comment]
@mikefarah thanks for the follow-up! Definitely confusing but I think I get it after a couple of reads :) I ran into this while trying to massage some kubernetes manifests, and sadly kubernetes is somewhere in [between 1.1 and 1.2](https://github.com/kubernetes/kubernetes/issues/34146#issuecomment-255821722) in terms of YAML support :(
