### ISSUE TITLE
I get 'no such file or directory' but the file exists

### ISSUE THREAD

**Issue by GiorgosBetsos** [mikefarah/yq#1808]
**Describe the bug**
I have installed yq using snap. I am using Ubuntu 18.

Following command:
` yq '.a.b[0].c' /srv/myapp/config/app_settings.yaml`

gives:

> Error: open /srv/myapp/config/app_settings.yaml: no such file or directory

But the file does exist.

Note: My version of yq is 4.30.5

**Comment by mikefarah** [comment]
This is because snap runs the app in its "strict confinement" mode, see https://github.com/mikefarah/yq#snap-notes for details.

**Comment by GiorgosBetsos** [comment]
I have tried:

```
sudo cat /srv/myapp/config/app_settings.yaml |  yq e .AUTOSTART.NOENTRY /srv/myapp/
/config/app_settings.yaml
```

but still get the same error.

**Comment by mikefarah** [comment]
No need to give the filename to yq if you're piping it in

```sudo cat /srv/myapp/config/app_settings.yaml |  yq  .AUTOSTART.NOENTRY```

**Comment by NicolasGoeddel** [comment]
This is annoying as heck. I'd like to have a DEB package for that. I use `yq` inside a bash script and when I run that script with `sudo` is can not read files. I don't want to use a big clunky docker overhead here. Isn't there just a binary available I can just copy to `/usr/local/bin` and that's it?

**Comment by mikefarah** [comment]
Yep it really is annoying - yes binaries are available here: https://github.com/mikefarah/yq/releases

**Comment by OnkelTem** [comment]
Unfortunately there is no **deb** among releases. And AppImage as well. It doesn't feel right to manually download a binary for Ubuntu, then manually copying it somewhere, renaming it or making it a symlink. No to mention its manual update cycle and security issues :-/

**Comment by OnkelTem** [comment]
But hey! It's not a complain!
Mike, my respects! I really appreciate what you're doing and I don't mean you should spend your time on deb packages.
 I'm just whining a little :) Sorry for that.

**Comment by Rohlik** [comment]
@OnkelTem I was able to install `yq` via `$ sudo apt install yq` on my Ubuntu 24.04.
It works, but versioning is quite broken:
```bash
$ yq --version
yq 0.0.0
```

**Comment by NicolasGoeddel** [comment]
> [@OnkelTem](https://github.com/OnkelTem) I was able to install `yq` via `$ sudo apt install yq` on my Ubuntu 24.04. It works, but versioning is quite broken:
> 
> $ yq --version
> yq 0.0.0

Same for me, but also look at the version differences:
```
~$yq
Command 'yq' not found, but can be installed with:
sudo snap install yq  # version v4.49.2, or
sudo apt  install yq  # version 3.1.0-3
See 'snap info yq' for additional versions.
```
Or like this:
```
$ apt list yq
Listing... Done
yq/noble,noble 3.1.0-3 all

$ snap search yq
Name                  Version  Publisher            Notes    Summary
yq                    v4.49.2  mikefarah            -        A lightweight and portable command-line YAML processor
```
Keep that in mind.
