### ISSUE TITLE
How to edit JSON inside YAML?

### ISSUE THREAD

**Issue by IdanAdar** [mikefarah/yq#181]
Assuming the following YAML: 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: worker-recovery-checks
  namespace: kube-system
data:
  checkpod.json: |
    {
      "Check":"KUBEAPI",
      "Resource":"POD",
      "namespace":"",
      "PodFailureThresholdPercent":0,
      "FailureThreshold":30,
      "CorrectiveAction":"RELOAD",
      "CooloffSeconds":900,
      "IntervalSeconds":30,
      "TimeoutSeconds":10,
      "Enabled":true
    }
```

How can I use `yq` to add a value to the `namespace` key inside the `checkpods.json` entry?

**Comment by IdanAdar** [comment]
* I can grab just the JSON part using `test=$(yq r autorecovery.yaml 'data[checkpod.json]')`
* I can then edit it using `echo $test | jq -r '.namespace |= "test"'`
* But how to I insert this back into the YAML so that it will appear exactly like in the original, plus the updated `namespace`?

In general, I don't like it broken to several commands like that, so if it _is_ possible with yq in a single go (or two)...

**Comment by mikefarah** [comment]
I think that's as good as it gets,  note that you can update json using yq too, if you don't have jq installed (though it isn't anywhere near as feature rich)

```
updatedCheckpod=$( echo $checkpod | yq w - namespace ${myProp} | yq r -j -)
```

**Comment by willzhang** [comment]
> I think that's as good as it gets, note that you can update json using yq too, if you don't have jq installed (though it isn't anywhere near as feature rich)
> 
> ```
> updatedCheckpod=$( echo $checkpod | yq w - namespace ${myProp} | yq r -j -)
> ```

this help me

**Comment by jeffrey4l** [comment]
```
yq '.data."checkpod.json" |= (.|@jsond|.namespace="test"|tojson)' a.yaml
```

oneline solution
