### ISSUE TITLE
Nested pipe not working

### ISSUE THREAD

**Issue by tsouza** [mikefarah/yq#1832]
**Describe the bug**
Nested pipe syntax does not seems to be working

Version of yq: 4.35.2
Operating system: mac
Installed via: homebrew

**Input Json**

test.json:
```json
[{"test":1}, {"test": "1.1"}]
```

**Command**

```bash
yq -p json '.[] | { "test": (.test | tonumber) }' < test.json
```

**Actual behavior**

```bash
Error: 1:26: invalid input text "tonumber) }"
```

**Expected behavior**

This is what I get with `jq`:
```json
{
  "test": 1
}
{
  "test": 1.1
}
```

**Comment by mikefarah** [comment]
tonumber has been added in 4.40.3 :)
