### ISSUE TITLE
4.35.2 cannot handle yaml with all contents commented out like in version 3

### ISSUE THREAD

**Issue by luckeyca** [mikefarah/yq#1850]
**Describe the bug**
In version 3.x, yq query works fine with empty result and return code zero even if the whole yaml file is commented out.
In version 4.x(tested between 4.0.0 and 4.35.2 for more than 10 different versions), got different errors depending on the versions.
See examples below

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.35.2 (or any 4.x versions)
Operating system: ubuntu 22.04
Installed via: binary release downloaded from github release page.

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)

data.yml: **(all lines in the file are commented out).**
```yaml
# resources:
#   resource2:
#    version: 0.2.0
#   resource3:
#    version: latest
```

**Working version 3.x Command with empty result and return code zero**
```
$ yq --version
yq 3.2.2
$ yq -r '.resources | keys | .[]' ./data.yml 
```

**NOT working version 4.x Command with non-zero return code**
```
$ yq --version
yq (https://github.com/mikefarah/yq/) version v4.35.2
$ yq e '.resources | keys | .[]' ./data.yml
Error: Cannot get keys of !!null, keys only works for maps and arrays
```

**Expected behavior**
yq version 4.x should work like in version 3 when it comes to yaml files with all contents commented out. just ignore the comments and output empty results.

**Actual behavior**
from the command output above, version 4.x error out when it comes to yaml files with all content commented out.

**Comment by mikefarah** [comment]
v4 was changed to better match what `jq` did (I think someone raised a similar issue where they _expected_ an error if you try to get keys from null...).

**Comment by mikefarah** [comment]
fwiw, you can get the same behavior first filtering out null:

```
yq 'select(.resources) | .resources | keys | .[]'
```
