### ISSUE TITLE
delete not working

### ISSUE THREAD

**Issue by drduker** [mikefarah/yq#186]
Original test.txt File:
```
a:
b:
- c: test2
  - 1
  - 2
  - 3
- d: test3
  - 1
  - 2
  - 3
```

Command:
```
yq d test.txt 'b[c:test2]'
or
yq d test.txt 'b[c]'
```

Expected output:
```
a:
b:
 -d: test3
   - 1
   - 2
   - 3

```
Actual result in both cases:
```
13:16:40 main [ERRO] Error reading document at index 0, yaml: line 3: did not find expected key: yaml: line 3: did not find expected key
```

I would expect this to work.  Otherwise the delete function is useless without nested commands.  I can't use this tool until it can do things like this.

yq for macos mojave

**Comment by mikefarah** [comment]
B is an array, so you need to provide the numeric index of what you want to delete.

```
yq d test.text 'b[0]'
```

Note that atm there is no feature to search in the array to find the instance that has a particular condition (https://github.com/mikefarah/yq/issues/173)
