### ISSUE TITLE
malformed json produced by in-place update with multiple input files

### ISSUE THREAD

**Issue by ryenus** [mikefarah/yq#1879]
**Describe the bug**

> -i, --inplace                       update the file in place of first file given.

Even though `yq help` states that in-place update only update the first file, but when multiple input files are provided, rather than reading and writing ONLY the first file, it goes an extra mile by also processing the rest of the input files and append the result into the first file, hence causing the first file to become a malformed json.

Version of yq: 4.40.2
Operating system: mac
Installed via: homebrew

**Input**
a.json:
```json
{"x":"A","n":1}
```

b.json:
```yaml
{"x":"B","n":2}
```

**Command**
The command you ran:
```
yq -i -oj .n=0 a.json b.json
```

**Actual behavior**

a.json:
```json
{
  "x": "A",
  "n": 0
}
{
  "x": "B",
  "n": 0
}
```

b.json:
```json
{"x":"B","n":2}
```

**Expected behavior**

I'd expect yq to either stick to its claim and only update the first file, just without even reading the other input files, or rather to process each input file individually without such surprising concatenation. And it doesn't feel right to stand in-between and produce malformed json.

a.json:
```json
{
  "x": "A",
  "n": 0
}
```

b.json:
```json
{
  "x": "B",
  "n": 0
}
```

**Additional context**
I tried the same but with 3 input files and the behavior is similar, the first file would be updated with data from the 2nd and the 3rd files.

**Comment by mikefarah** [comment]
This is the intended behavior - the purpose of reading the other files is to do things like merge, or have multiple JSON documents in a single file (e.g. NJSON). 

You can definitely create malformed JSONs using 'in-place', even with a single file - consider just reading a single scalar value (say `.x` in your example) and saving that.
