### ISSUE TITLE
'bad flag syntax' error when value starts with hyphens

### ISSUE THREAD

**Issue by bharatgoelharness** [mikefarah/yq#1885]
**Describe the bug**
['bad flag syntax' error when value starts with hyphens](https://github.com/mikefarah/yq/issues/230)
When value is starting with -- then parsing is ot happening.

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.40.3
Operating system: mac/linux/windows/....
Installed via: docker/binary release/homebrew/snap/...

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
this: should really work
```

data2.yml:
```yaml
but: it strangely didn't
```

**Command**
The command you ran:
```
yq eval-all 'select(fileIndex==0) | .a.b.c' data1.yml data2.yml
```

**Actual behavior**

```yaml
cat: meow
```

**Expected behavior**

```yaml
this: should really work
but: it strangely didn't
```

**Additional context**

**Comment by mikefarah** [comment]
Please fill in the bug report properly - I don't know what the issue is or how to reproduce it. The issue you linked to has the solution for it..
