### ISSUE TITLE
Scalar following document start indicator parsed incorrectly

### ISSUE THREAD

**Issue by m-dango** [mikefarah/yq#1896]
**Describe the bug**

YAML can have scalar data following the start of the document, without requiring a new line. When passing this data into `yq`, the scalar data is omitted.

Version of yq: 4.40.3
Operating system: mac
Installed via: homebrew

**Input Yaml**
```yaml
--- text
...
```
Example taken from YAML spec: https://yaml.org/spec/1.2.2/#example-directive-indicator

**Command**
The command you ran:
```
echo '--- text' | yq .
```

**Actual behavior**

```yaml
---
```

**Expected behavior**

```yaml
---
text
```

**Additional context**
Some YAML producers output scalar content in this way.

**Comment by mikefarah** [comment]
Thanks for raising, will be fixed in the next release

**Comment by mikefarah** [comment]
Fixed in 4.40.5
