### ISSUE TITLE
Can you update docs to clarify yq doesn't work on windows?

### ISSUE THREAD

**Issue by parisologist** [mikefarah/yq#1897]
As per https://github.com/langchain-ai/langchain/issues/4396, jq can't be installed on windows; which means you can't really use yq to perform queries. Can you add a note under your windows section that it's currently not a supported OS; it will save a lot of us some considerable time. Thanks!

**Comment by mikefarah** [comment]
`yq` doesn't need jq - and it definitely works in windows. Check out the releases page to download a binary.

**Comment by sergeevabc** [comment]
`yq` does not work on Windows 7 since you switched to @golang 1.21

``` console
$ yg.exe
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        /opt/hostedtoolcache/go/1.21.5/x64/src/runtime/sys_windows_amd64.s:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x46ce95
rax     0x0
rbx     0xd86f20
rcx     0xddaba0
rdi     0x7fffffde000
rsi     0x22fea0
rbp     0x22fde0
rsp     0x22fc78
r8      0x0
r9      0x22fee0
r10     0xdaca78
r11     0x21
r12     0x22fec0
r13     0x1
r14     0xd868c0
r15     0x0
rip     0x0
rflags  0x10293
cs      0x33
fs      0x53
gs      0x2b
```
