### ISSUE TITLE
Provide installation instructions from Alpine

### ISSUE THREAD

**Issue by Lukenickerson** [mikefarah/yq#190]
The [installation instructions](https://github.com/mikefarah/yq/#install) for Linux assume Ubuntu, but some users may want to use yq on things like [Alpine](https://alpinelinux.org/) which don't have `snap`, `apt`, or `go`. What would be the best installation process for gettin yq working while also minimizing dependencies/size?

**Comment by kenjones-cisco** [comment]
`wget -O /usr/local/bin/yaml "https://github.com/mikefarah/yq/releases/download/${YAML_BIN_VERSION}/yq_linux_amd64"`

That is what I use in all of my Dockerfiles based on alpine.

**Comment by deitch** [comment]
Any chance of getting it added to the official `apk` packages at https://pkgs.alpinelinux.org/ so we can just do `apk add yq` ?

**Comment by mikefarah** [comment]
That'd be really cool - I personally don't have the time at the moment to investigate though

**Comment by deitch** [comment]
> I personally don't have the time at the moment to investigate though

The instructions are [here](https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package) . It isn't too bad, I just am in the same boat as you. :-)

I image you would just have a `make alpine` or `make apk` target in your [Makefile](https://github.com/mikefarah/yq/blob/master/Makefile) , just like you have `make snap` .

How do you actually call `make snap`, since it isn't in the Travis `.travis.yml` as far as I can tell? Similar question for homebrew and others?

**Comment by IdanAdar** [comment]
+1 here for integrated apk support.

**Comment by cbeardsmore** [comment]
+1

**Comment by ShonaliB** [comment]
+1

**Comment by bigdot** [comment]
Hmm. Just stumbled on this one cause i need it. I might take on it this weekend.
@mikefarah any Contributor notes/guide/etc somewhere ? didn't find any yet

**Comment by EvertonSA** [comment]
I would like to see this feature as `apk add yq`

**Comment by MrSimonEmms** [comment]
```
wget $(curl -s https://api.github.com/repos/mikefarah/yq/releases/latest | grep browser_download_url | grep linux_amd64 | cut -d '"' -f 4) -O /usr/bin/yq
chmod +x /usr/bin/yq
```

I've been using this command to download the latest version to my alpine containers. Would be nice to have it in apk, but this is fine as a workaround

**Comment by weibeld** [comment]
If you also have `jq` on your Alpine image, you can install the latest version of `yq` with:

```bash
wget -q -O /usr/bin/yq $(wget -q -O - https://api.github.com/repos/mikefarah/yq/releases/latest | jq -r '.assets[] | select(.name == "yq_linux_amd64") | .browser_download_url')
chmod +x /usr/bin/yq
```

**Comment by maxice8** [comment]
as of 2020-08-01 yq is now in Edge/Testing, when moved to community/ it will be available once 3.13 is released

**Comment by mshivanna** [comment]
apk add py-pip; pip install yq

**Comment by mikefarah** [comment]
> 
> 
> apk add py-pip; pip install yq

Nah that's for a different the python implementation of yq that wraps jq. This yq is has native binaries

**Comment by mshivanna** [comment]
> > apk add py-pip; pip install yq
> 
> Nah that's for a different the python implementation of yq that wraps jq. This yq is has native binaries

yeah agree with you. found out the hard way :(

**Comment by maxice8** [comment]
The instructions are:

1. Enable community repo by adding `$MIRROR/alpine/v$VERSION/community` to `/etc/apk/repositories`
2. Update database index with `apk update`
3. Install `yq` with `apk add yq`

**Comment by mshivanna** [comment]
Thank you Mike

**Comment by mikefarah** [comment]
Wow that's awesome! This seems like something I should put on the Github README.md. 

What's the process for updating that when I release a new version of `yq`?

**Comment by maxice8** [comment]
When upstream (you in this case) releases a new version an Alpine Linux contributor has to update the APKBUILD in Alpine Linux's aports which makes the builders build the new version and upload it.
 
for the end-user just:

1. `apk update`
2. `apk upgrade`

in EDGE we (Alpine Linux) always track the latest upstream, or latest stable branch which will make way into a stable Alpine Linux release.

**Comment by mikefarah** [comment]
Awesome - are you happy to volunteer to keep the Alpine build up to date when new releases are made? I'll raise a github issue for Alpine like https://github.com/mikefarah/yq/issues/533

**Comment by maxice8** [comment]
APKBUILDs have a Maintainer: to denote the one responsible for the package.

The current maintainer is ` Tuan Hoang <tmhoang@linux.ibm.com>`

**Comment by mikefarah** [comment]
Ace - cheers.

**Comment by guicholeo** [comment]
To add it from the edge community repo

`echo "http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories`
`apk update`
`apk add yq --no-cache`

**Comment by maxice8** [comment]
Mixing EDGE and versioned repositories is not supported, although there is a high chance of it working because yq only uses the libc.

**Comment by guicholeo** [comment]
Would this be the best way to add? 
`apk add yq --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main`

**Comment by glensc** [comment]
use `FROM alpine:edge` to avoid mixing distro versions
