### ISSUE TITLE
brew install yq@3: No available formula with the name "yq@3". Did you mean yq?

### ISSUE THREAD

**Issue by bitsofinfo** [mikefarah/yq#1909]
Yes there are still some CI systems out there relying on 3.x... just rebuilding a node and `brew install yq@3` yields 

```
No available formula with the name "yq@3". Did you mean yq
```

where can we get 3.4.1?

**Comment by bitsofinfo** [comment]
i get 3.x is no longer maintained, but the 3x versions should still be available out there for people to use.

**Comment by mikefarah** [comment]
It's still available to download in the github release pages. Brew didn't want to publish v3 unless I was going to provide support for it..
