### ISSUE TITLE
Cannot convert json to yaml: jq: 1 compile error

### ISSUE THREAD

**Issue by marcellodesales** [mikefarah/yq#191]
Convert fails with `jq: 1 compile error`...  Tried to convert and got the following

```
$ yq r sample.json
jq: error: r/0 is not defined at <top-level>, line 1:
r
jq: 1 compile error
```

* Using `jq 1.5_3` 

```
$ yq --version
yq 2.4.1

$ jq --version
jq-1.5
```

**Comment by mikefarah** [comment]
Unfortunately this repo has the same name as https://github.com/kislyuk/yq which seems like the yq you are using.

I'd raise an issue there.

**Comment by marcellodesales** [comment]
@mikefarah my bad... thank u!
