### ISSUE TITLE
yq --null-output produces two json documents instead of one

### ISSUE THREAD

**Issue by ngirard** [mikefarah/yq#1917]
Using yq v4.40.5 on Ubuntu 23.04.

```sh
yq --null-input -oj '.a=1, .b=false, .c="Aaa"'
```
produces
```json
{
  "a": 1,
  "b": false,
  "c": "Aaa"
}
{
  "a": 1,
  "b": false,
  "c": "Aaa"
}
```
instead of the expected
```json
{
  "a": 1,
  "b": false,
  "c": "Aaa"
}
```

Happy new year and thanks for your work !

Cheers

**Comment by mikefarah** [comment]
`,` is the union operator, which is not quite what you want, to get the expected result you need to use the '|' or pipe operator:

```
yq --null-input -oj '.a=1 | .b=false | .c="Aaa"'
```

The difference being, `|` will take the current result and use it as input into the next operation (which in this case is the map `{a: 1}` is given as input to the operation ` .b = false` and so it will add that `b` key.

Where as union `,` will collect a bunch of different results into a set. Not quite sure why it's making two sets like that, and I'll look into it as a side node, though it would be a strange use of union to do what you have there).

**Comment by mikefarah** [comment]
Also thanks for the appreciation! Happy new year to you as well :)
