### ISSUE TITLE
tag uses object and not field

### ISSUE THREAD

**Issue by jduepmeier** [mikefarah/yq#1929]
**Describe the bug**

I want to get a field from an array of objects and want to convert to number to a str:

Version of yq: 4.40.5
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
test.yml:
```yaml
---
- number: 42
```

**Command**
The command you ran:
```
yq eval '.[] | {"n": (.number tag="!!str")}' test.yaml
```

**Actual behavior**

```yaml
n:
  number: "42"
```

**Expected behavior**

```yaml
n: 42
```

**Additional context**
Workaround:
```
yq eval '.[] | {"n": (.number | . tag="!!str")}' test.yaml
```

**Comment by mikefarah** [comment]
That's actually expected behavior, `(.number tag="!!str")` is an assignment operator, so it will return the passed in context updated with that expression, which in this case is ` number: "42"`.

The second expression you have is correct, you want to grab the `number` value, and change its tag.
