### ISSUE TITLE
replaceability of pip yq?

### ISSUE THREAD

**Issue by clux** [mikefarah/yq#193]
We use a lot of the [pip version](https://github.com/kislyuk/yq) of `yq` because it actually feels like just `jq` for yaml (same handling of flags etc). However, there's a lot of confusion because the default version on brew is this, but on linux it's the python one, and there are incompatibilities. Here's the first one we hit:

- `python-yq` supports `-r` for reading raw value
- `jq` supports `-r` for reading raw value
- this project needs `r` as a subcommand

Any thoughts on possibly consolidating the CLI api for these things?

Edit: I know this is a big ask and probably should just be insta-closed. I was just wondering what you guys thought on this issue.

**Comment by mikefarah** [comment]
I like the idea of that, having the same CLI api - hadn't actually thought of it.

At the moment I'm using the cobra go lang package to handle arguments, which is where is gets that subcommand syntax. Mind you I think that's actually more typical of cli apps to have '-' arguments as flags to a command/subcommand rather than subcommands - but anyway as you say that how both jq and the other yq work.

Have to give this some thought.

**Comment by gsemet** [comment]
I prefere this yq interface, but it lacks YAML anchor support :( It is possible for both project to work on redefining the name so there is no conflict (I install this yq in /usr/local/bin/yyq)?

**Comment by voiski** [comment]
So, can we just bring the same solution of the mentioned kislyuk/yq version? He just wraps jq inside it, so it is why it has all the jq flags. You can use the jq filter feature for now and try to port later.

**Comment by voiski** [comment]
For anyone that reaches this card, here is a workaround:
```bash
yq r -j file.yq | jq $filter_command | yq -
```

**Comment by mikefarah** [comment]
The (albeit moonshot) point of yq is to have it dependency free - so I don't want to wrap jq (there are other utilities that do this already.

That said, if you already have jq (or don't mind installing it) piping totally works

**Comment by voiski** [comment]
I saw this similar discussion in jq issues and they have some other solutions. One is quite interesting and owe attention.
https://github.com/stedolan/jq/issues/467#issuecomment-511160790

**Comment by voiski** [comment]
So, checking the latest it has standalone binaries that will make your live easier. Forget pip.
https://github.com/stedolan/jq/releases

```bash
wget -O jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
chmod +x jq
yq r -j file.yq | jq $filter_command | yq -
```

**Comment by Blacksmoke16** [comment]
> I saw this similar discussion in jq issues and they have some other solutions. One is quite interesting and owe attention.
> [stedolan/jq#467 (comment)](https://github.com/stedolan/jq/issues/467#issuecomment-511160790)
> 
> EDIT:
> 
> > Sorry, I got it wrong thinking it made jq portable together with the wrapper =(

The binary itself requires `jq` to work.  However if you install it via [snap](https://snapcraft.io/oq) then `jq` gets installed as well since I made it a dependency.

**Comment by mikefarah** [comment]
Latest v4 version now supports jq like syntax (though not everything jq can do yet)

**Comment by elibroftw** [comment]
If you use `-r` in a CI environment, it fails without telling you the problem. Really wish the consistency was added 2 years ago.
