### ISSUE TITLE
indent problem with arrays

### ISSUE THREAD

**Issue by exocode** [mikefarah/yq#194]
When I try to add something to an array, I get the wrong intendation:
`yq -V # yq version 2.1.2`

How can I solve that?

Command: `yq w -i $USERDATA  "foo[+]" "bar"`

Current output
```
foo:
- bar # 0 spaces
```
expected output
```
foo:
  - bar # 2 spaces
```

**Comment by mikefarah** [comment]
Arrays items don't actually need indentation in yaml see http://yaml.org/spec/1.2/spec.html, "10.1.1.2. Generic Sequence" (for what it's worth, it seems weird to me too).

Anyway the underlying [yaml library](https://github.com/go-yaml/yaml) yq uses outputs yaml like that.

**Comment by mikefarah** [comment]
Related bug in underlying parser: https://github.com/go-yaml/yaml/issues/559

**Comment by mikefarah** [comment]
Fixed in 3.3.1

**Comment by zhaogaolong** [comment]
I have some problem.

system: macos 10.15.7
yq version: 3.4.0

cc @mikefarah
