### ISSUE TITLE
v4.42.1: unfortunate change in the yqlib.NewYamlEncoder( ) API

### ISSUE THREAD

**Issue by rudo-thomas** [mikefarah/yq#1964]
**Describe the bug**
Two problems I see with the v4.42.1 version of yqlib:
 - [coming from v4.41.1](https://pkg.go.dev/github.com/mikefarah/yq/v4@v4.41.1/pkg/yqlib#NewYamlEncoder), the yqlib.NewYamlEncoder function [changed its parameters](https://pkg.go.dev/github.com/mikefarah/yq/v4@v4.42.1/pkg/yqlib#NewYamlDecoder)
   - while cleaner, this is quite unfortunate in a minor release because it breaks user code
 - the new function no longer takes `indent` and `colorise`, these are now in the passed [`YamlPreferences`](https://pkg.go.dev/github.com/mikefarah/yq/v4@v4.42.1/pkg/yqlib#YamlPreferences)
   - however, the [`NewDefaultYamlPreferences`](https://pkg.go.dev/github.com/mikefarah/yq/v4@v4.42.1/pkg/yqlib#NewDefaultYamlPreferences) have the coloring turned on -- which means when porting to the new version, extra effort needs to be performed because the defaults don't work (edit: I'm saying "don't work," because with the defaults the encoder is not producing valid YAML, but a "colored YAML")

Version of yq: 4.42.1

**Expected behavior**

 - No API breakage in minor versions.
 - When user code needs to be changed, the defaults should be more user-friendly.

**Comment by rudo-thomas** [comment]
Just to clarify: The actual fix on the user code side is trivial, it's just it is surprising it had to be done, and that the default was not working well because of the coloring.

**Comment by leviliangtw** [comment]
IOM, setting the `colorise` to be false in default is ideal and intuitive. 
If I were a newbie implementing something with `yqlib`, I would expect a most clean output. 
(Same idea for the Json preference)

**Comment by mikefarah** [comment]
Yeah fair call, I'll change the default to false for when using the library.

The semantic versioning atm is for the CLI - and I'd only increment the major version for a breaking CLI interface change. 

I really should extract the lib parts to another go package and then that can have its own semantic versioning. Just haven't got around to it sorry!

**Comment by mikefarah** [comment]
Fixed in v4.43.1
