### ISSUE TITLE
Cannot get yq with modules enabled

### ISSUE THREAD

**Issue by tommyknows** [mikefarah/yq#197]
When trying to download yq, respectively its dependency `gopkg.in/mikefarah/yaml.v2`, I get the following error:
```
> go get gopkg.in/mikefarah/yaml.v2
go: gopkg.in/mikefarah/yaml.v2@v2.3.0: parsing go.mod: unexpected module path "gopkg.in/yaml.v2"
go: error loading module requirements
```

(the same error occurs when just `go get`ing yq).

I think the reason lies in the `go.mod` file in `mikefarah/yaml.v2`:
```
module "gopkg.in/yaml.v2"

require (
	"gopkg.in/check.v1" v0.0.0-20161208181325-20d25e280405
)
```

So basically, I think it should be enough if the `go.mod` file replaces the module line with
```
module "gopkg.in/mikefarah/yaml.v2"
```

However, I'm not too familiar with go modules and gopkg.
It could also be that I'm missing something, any help would be appreciated then :-)

**Comment by mikefarah** [comment]
Hmm yeah I haven't read about Go's modules - and I find go's dependency management to be terribly confusing.

Haven't had time to look at this yet sorry - perhaps in the new year.

I'm tempted to remove support for ``go get`` as an installation method, it has been nothing but trouble.

I'm assuming the precompiled binaries work fine?

**Comment by tommyknows** [comment]
I think it's worth reading into modules - good new year's resolution :-)

So I forked `yq` and `yaml` and fixed it.
I haven't worked with `gopkg.in` yet - I don't think it is needed anymore with go modules.
Here's what I did:
1) Cloned the `yaml` fork locally.
2) Replaced the `module "gopkg.in/yaml.v2"` with `module "github.com/tommyknows/yaml/v2"`.
3) Tag it (i made two commits, so i tagged it with `v2.3.2`) and push it.
4) Clone `yq` fork locally and run a `go build`. With modules enabled, it automatically generates a `go.mod` file (and fails)
5) Replace all occurrences of `yaml "gopkg.in/mikefarah/yaml.v2"` with my fork `yaml "github.com/tommyknows/yaml/v2"`.  (in all `.go` files)
6) Set the module path in `go.mod` to `module github.com/tommyknows/yq/v3`.
7) Replace the dependency `gopkg.in/mikefarah/yaml.v2 v2.3.0` with my fork `github.com/tommyknows/yaml/v2 v2.3.2` in `go.mod`
8) Run `go build `. This should work, although for me it created a binary called `v3`. (`go install` has fixed [this](https://github.com/golang/go/issues/27283) bug, but `go build` isn't fixed yet)
9) If all works fine, tag it with `v3.0.0` and push it. (notice here that if you want to tag it with `v2.2.1` or `v2.3`, the `module` directive inside `go.mod` should be `github.com/tommyknows/yq/v2`)

Running `go get` now works:
```
> go get -u github.com/tommyknows/yq/v3
go: finding github.com/tommyknows/yq/v3 v3.0.0
go: finding github.com/pkg/errors v0.0.0-20180311214515-816c9085562c
go: finding github.com/inconshreveable/mousetrap v1.0.0
go: finding github.com/tommyknows/yaml/v2 v2.3.2
go: finding github.com/spf13/pflag v0.0.0-20180601132542-3ebe029320b2
go: finding gopkg.in/spf13/cobra.v0 v0.0.3
go: finding gopkg.in/op/go-logging.v1 v1.0.0-20160211212156-b2cb9fa56473
go: finding gopkg.in/imdario/mergo.v0 v0.3.5
go: finding github.com/pkg/errors v0.8.0
go: finding github.com/spf13/pflag v1.0.3
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: finding gopkg.in/imdario/mergo.v0 v0.3.6
go: finding gopkg.in/op/go-logging.v1 latest
go: finding gopkg.in/check.v1 latest
go: downloading github.com/tommyknows/yq/v3 v3.0.0
go: downloading github.com/tommyknows/yaml/v2 v2.3.2
go: downloading github.com/pkg/errors v0.0.0-20180311214515-816c9085562c
go: downloading gopkg.in/op/go-logging.v1 v1.0.0-20160211212156-b2cb9fa56473
go: downloading gopkg.in/spf13/cobra.v0 v0.0.3
go: downloading gopkg.in/imdario/mergo.v0 v0.3.6
go: downloading github.com/spf13/pflag v1.0.3
```

You can find the forks [here](github.com/tommyknows/yq) and [here](github.com/tommyknows/yaml).
If you have questions, I'd be happy to try and answer them :-)

**Comment by mikefarah** [comment]
Cool I see how it works 👍  Now just need a bit of time to apply and test it :)

**Comment by mikefarah** [comment]
Almost got it working - ran into an issue with the linter though

https://github.com/alecthomas/gometalinter/issues/564

Seems like go modules is still pretty fresh - might try again later

**Comment by JoshKCarroll** [comment]
@tommyknows fyi your fork seems to be breaking now too

```
$ go get -u github.com/tommyknows/yq/v3
go: finding github.com/tommyknows/yq/v3 v3.0.0
go: finding github.com/spf13/pflag v0.0.0-20180601132542-3ebe029320b2
go: finding github.com/pkg/errors v0.0.0-20180311214515-816c9085562c
go: finding github.com/inconshreveable/mousetrap v1.0.0
go: finding github.com/tommyknows/yaml/v2 v2.3.2
go: finding gopkg.in/imdario/mergo.v0 v0.3.5
go: finding gopkg.in/op/go-logging.v1 v1.0.0-20160211212156-b2cb9fa56473
go: finding gopkg.in/spf13/cobra.v0 v0.0.3
go: finding gopkg.in/check.v1 latest
go: finding gopkg.in/op/go-logging.v1 latest
go: finding gopkg.in/imdario/mergo.v0 v0.3.7
go: finding gopkg.in/spf13/cobra.v0 v0.0.5
go: gopkg.in/spf13/cobra.v0@v0.0.5: go.mod has non-....v0 module path "github.com/spf13/cobra" at revision v0.0.5
go get: error loading module requirements
```

**Comment by tommyknows** [comment]
Yup. Just fixed this - I don't really understand gopkg, and with modules it's not needed anyway.
Switched to the github package instead, that fixed the issue.

Decided to also update all dependencies while I'm at it.

Just FYI: I'm not planning on actually maintaining that fork. I did a rebase now because I saw that it was behind upstream, but don't expect any "automatic" updates 🙂

**Comment by mikefarah** [comment]
Fixed see https://github.com/mikefarah/yq/issues/289
