### ISSUE TITLE
RFE: parent(n) to get n-th parent

### ISSUE THREAD

**Issue by ryenus** [mikefarah/yq#1970]
**Please describe your feature request.**

Allow [parent](https://mikefarah.gitbook.io/yq/operators/parent) to take an optional number argument , to return the nth parent, so `. | parent(2)` would be the same as `. | parent | parent`

**Describe the solution you'd like**
If we have data1.yml like:
(please keep to around 10 lines )

```yaml
a:
  b:
    c: 1
```

And we run a command:

```bash
yq '.a.b.c | parent(2)'
```

it could output

```yaml
b:
  c: 1
```

**Describe alternatives you've considered**

`parent(2)` should work just the same as `parent | parent`, similarly  `parent(n)` would be the same as `parent | parent | ... | parent`, just much more concise and clean than the latter.

**Comment by mikefarah** [comment]
I like it - will be available in the next release

**Comment by mikefarah** [comment]
Fixed in v4.43.1 :)
