### ISSUE TITLE
`@yamld` fails while `from_yaml` doesn't

### ISSUE THREAD

**Issue by lukasz-mitka** [mikefarah/yq#1979]
**Describe the bug**
`@yamld` fails while `from_yaml` doesn't
Error message:
> Error: parsing expression: Lexer error: could not match text starting at 1:17 failing at 1:19.
        unmatched text: "d "

Version of yq: 4.24.2
Operating system: linux
Installed via: homebrew

**Input Yaml**
test.yml:
```yaml
dependencies:
  - name: dep1
    repository: url1
  - name: dep2
    repository: url2
```

**Command**
The command you ran:
```bash
for dependency in $(yq '.dependencies[] | @yaml | @base64' "test.yaml"); do
    echo "$dependency" | yq '@base64d | from_yaml | .name'
    echo "$dependency" | yq '@base64d | @yamld | .repository'
done
```

**Actual behavior**

```
dep1
Error: parsing expression: Lexer error: could not match text starting at 1:17 failing at 1:19.
        unmatched text: "d "
dep2
Error: parsing expression: Lexer error: could not match text starting at 1:17 failing at 1:19.
        unmatched text: "d "
```

**Expected behavior**

```
dep1
url1
dep2
url2
```

**Additional context**
Looks like `@yaml` is matched first and then tries to encode `d ` string.

**Comment by mikefarah** [comment]
Hi, can you try using the latest version of yq

**Comment by lukasz-mitka** [comment]
Hi Mike, thank you for responding.
Not really sure how it happened. When posting this bug I noticed I was using old version -> upgraded -> tested -> still failing -> forgot to update the description.
Tested again today with what I had last time (`v4.42.1`) and ... now it's working 🤷
