### ISSUE TITLE
Error: unknown flag: --variation with shell-completion command.

### ISSUE THREAD

**Issue by sheeeng** [mikefarah/yq#1987]
**Describe the bug**

According to [documentation](https://mikefarah.gitbook.io/yq/commands/shell-completion), we should be able to generate shell-completion file with `yq shell-completion --variation=zsh` command.

```console
$ which yq
/opt/homebrew/opt/yq@4/bin/yq
$ yq --version
yq (https://github.com/mikefarah/yq/) version v4.42.1
$ echo $SHELL
/bin/zsh
```

**Command**
The command you ran:
```shell
yq shell-completion --variation=zsh
```

**Actual behavior**

```console
$ yq shell-completion --variation=zsh
Error: unknown flag: --variation
Usage:
  yq shell-completion [bash|zsh|fish|powershell]
....
```

**Expected behavior**

```console
$ yq shell-completion zsh
#compdef yq
compdef _yq yq
....
```

**Comment by mikefarah** [comment]
Thanks for pointing that out, updated the docs
