### ISSUE TITLE
Any way to list top level keys only?

### ISSUE THREAD

**Issue by jmreicha** [mikefarah/yq#20]
Is it currently possible to have the CLI only list the top level keys?  For example, given the following yaml file:

```
a:
  b:
    c:
    - 'test'
    - "test2"
  d:
  e:
```

Is there a way to only list `b`, `d` and `e` and no other subkeys with something like `yaml r test.yml a`?

**Comment by mikefarah** [comment]
Not at the moment sorry - happy to take a pull request for this.

Alternatively, you could pipe it out to json (-j), use jq then convert it back to yaml (yaml will take a json file and output yaml)

**Comment by jmreicha** [comment]
Thanks, I might take a stab at it.

**Comment by simoniz0r** [comment]
You could also pipe the output into a `grep -v` to get rid of they subkeys you don't want to see.  For example, `test` and `test1` will both have multiple spaces before them in the output, so if you pipe yaml's output into a `grep -v '  .*'`, this will output everything that does *not* start with two spaces.

Ex:

```
yaml r ./yamltest a
b:
  c:
  - test
  - test2
d: null
e: null
```

```
yaml r ./yamltest a | grep -v '  .*'
b:
d: null
e: null
```

**Comment by sumanthkumarc** [comment]
i had to do this to remove the : at last.
yq r test.yml my_key | grep -v '  .*' | sed 's/.$//'

**Comment by jlumbroso** [comment]
Expanding on @sumanthkumarc's one-liner:
```
yq r test.yml my_key | grep -v '^ .*' | sed 's/:.*$//'
```
This deals with several edge-cases, such as:
- when the key's tree is empty;
- there are spaces in the key name.

**Comment by Sylvain303** [comment]
What would be the `yq` syntax for extracting keys?

Like in `jq`?

```
yq r file.yml 'path.to.top_key|keys[]'
```

Suggestion from @mikefarah to use `jq` for that:

give this input

```yaml
---
a:
b:
  c:
    - test
    - test2
d:
e:
f:
  key1: value1
  key2: value
```

filtering

```bash
yq.v2 r -j a.yml | jq '.f|keys[]'
```

Alternative filtering from yaml (`jq` like root key naming `.f` is not supported by `yq`)

```bash
yq.v2 r -j a.yml f | jq '.|keys[]'
```

both outputs:

```
"key1"
"key2"
```

add `-r` to `jq` for bash compatible extraction.

```bash
yq.v2 r -j a.yml f | jq -r '.|keys[]'
```

**Comment by Sylvain303** [comment]
Workaround staying with `sed` only solution, based on the fact that `yq` trim keys on left:

GNU sed:
* `-n` no print
* `/^\([^ ]\([^:]\+\)\?\):/` match left anchored keys: non-space, followed optionally by non-colon
* `s/:.*/` remove colon plus end of the line
* `p`   print (behave like grep filtering)

```bash
yaml_keys () 
{ 
    yq r "$1" "$2" | sed -n -e '/^\([^ ]\([^:]\+\)\?\):/  s/:.*// p'
}
```

Use with the same previous comment input:

```bash
yaml_keys a.yml f
```
outputs

```
key1
key2
```

**Comment by mikefarah** [comment]
Just released a new version of yaml that fixes this - it's a pretty significant update so it's still in beta: https://github.com/mikefarah/yq/releases/tag/3.0.0-beta

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1

check https://mikefarah.gitbook.io/yq/commands/read#path-only for more info

**Comment by eldada** [comment]
Anyway to do it in v4?

**Comment by eldada** [comment]
> Anyway to do it in v4?

Got it... simple! 
```
yq e '. | keys' example.yaml
```

**Comment by leonarac** [comment]
I'm working in bash, and I have a value stored in a variable obtained with yq, how can I use that variable in another yq query?

**Comment by ShaneMellwig** [comment]
> Is it currently possible to have the CLI only list the top level keys?  For example, given the following yaml file:
> 
> ```
> a:
>   b:
>     c:
>     - 'test'
>     - "test2"
>   d:
>   e:
> ```
> 
> Is there a way to only list `b`, `d` and `e` and no other subkeys with something like `yaml r test.yml a`?
