### ISSUE TITLE
File contents printed instead of key value when key matches file name

### ISSUE THREAD

**Issue by mateuszkozakiewicz** [mikefarah/yq#2010]
**Describe the bug**
When the file name shadows the path of the key (in my example file name is `.release` and key is `release`) it fails to get the value instead prints the file contents again.
Workaround is to use " ".

Version of yq: 4.43.1
Operating system: linux
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
.release:
```yaml
release: 123
something-else: asd
```

**Command**
The command you ran:
```
❯ yq e '.release' .release
```

**Actual behavior**

```yaml
release: 123
something-else: asd
---
release: 123
something-else: asd
```

**Expected behavior**

```yaml
123
```

**Additional context**
```
❯ yq e '.release' .release
release: 123
something-else: asd
---
release: 123
something-else: asd

❯ yq e '.something-else' .release
asd

❯ yq e '."release"' .release
123

❯ mv .release release
❯ yq e '.release' release
123
```

**Comment by mikefarah** [comment]
Use the `--expression` flag to force it to recognise that you're giving it an expression :)

```
yq --expression '.release' .release
```
