### ISSUE TITLE
Make use of --trim clearer in documentation

### ISSUE THREAD

**Issue by stumo** [mikefarah/yq#203]
The documentation doesn't explain how to turn --trim off, or what it does.

I've found that you can turn it off with --trim=falase from https://github.com/mikefarah/yq/blob/77c8f22a791f879a3eeec7f1217ed30267d74298/commands_test.go#L323 - but it's still not clear what it does (I was hoping it would retain comments, which isn't the case)

**Comment by BrainStone** [comment]
I would also like to know what this flag is supposed to do.  
And I'm also looking for a way to retain formatting and comments

**Comment by mikefarah** [comment]
No longer relevant for v3 - and it retains formatting
