### ISSUE TITLE
underscores in numbers cause json output to fail

### ISSUE THREAD

**Issue by zellyn** [mikefarah/yq#2039]
**Describe the bug**
`yq` has trouble serializing numbers containing underscores to json.

Version of yq: 4.44.1
Operating system: mac
Installed via: homebrew

**Command**
The command you ran:
```
echo 'foo: 12_000' | yq -o=json
```

**Actual behavior**

```
Error: json: error calling MarshalJSON for type *yqlib.CandidateNode: json: error calling MarshalJSON for type *yqlib.CandidateNode: strconv.ParseInt: parsing "12_000": invalid syntax
```

**Expected behavior**

```json
{
  "foo": 12000
}
```

**Comment by mikefarah** [comment]
Fixed in v4.44.2
