### ISSUE TITLE
merge key

### ISSUE THREAD

**Issue by ghost** [mikefarah/yq#206]
Input:

~~~yml
alfa:
   charlie: 2
   <<: &gr
      delta: 4
      echo: 5
      foxtrot: 6
bravo:
   charlie: 3
   <<: *gr
~~~

Expected result:

~~~yml
alfa:
   charlie: 2
   delta: 4
   echo: 5
   foxtrot: 6
bravo:
   charlie: 3
   delta: 4
   echo: 5
   foxtrot: 6
~~~

Actual result:

~~~yml
alfa:
   charlie: 2
bravo:
   charlie: 3
~~~

another example here:

https://wikipedia.org/wiki/YAML#Advanced_components

These tools give correct output:

- https://github.com/0k/shyaml
- https://github.com/dbohdan/remarshal
- https://github.com/martinlindhe/validyaml

documentation:

https://yaml.org/type/merge

**Comment by mikefarah** [comment]
This is an issue with the underlying Yaml library :(

https://github.com/mikefarah/yq/issues/178

**Comment by cup** [comment]
https://github.com/drone/drone/issues/2323
https://github.com/drone/drone-cli/pull/103
https://github.com/go-swagger/go-swagger/issues/1193
https://github.com/go-yaml/yaml/issues/184
https://github.com/go-yaml/yaml/issues/344
https://github.com/go-yaml/yaml/issues/91
https://github.com/mikefarah/yq/issues/178

https://github.com/mikefarah/yq/issues/206

**Comment by mikefarah** [comment]
The latest version now preserves anchors (https://github.com/mikefarah/yq/releases/tag/3.0.1), see https://mikefarah.gitbook.io/yq/commands/read#anchors-and-aliases for more info
