### ISSUE TITLE
Ubuntu 24.04 LTS support

### ISSUE THREAD

**Issue by elasticdotventures** [mikefarah/yq#2081]
**Describe the bug**
@rmescandon Hi,

similar to issue #1308 there is now ubuntu 24.04 LTS noble numbat which is not listed in the ppa. thanks!

```
Err:12 https://ppa.launchpadcontent.net/rmescandon/yq/ubuntu noble Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done

```

**Comment by elasticdotventures** [comment]
I think the ppa is abandoned by @rmescandon, so as a work around in my system init I've started using `eget` and it works fine for my use case. 👍🏻

```

curl https://zyedidia.github.io/eget.sh | sh
mv eget ~/.local/bin/eget
./eget mikefarah/yq --upgrade-only --tag v4.44.6
```

**Comment by gsmet** [comment]
For people coming here using GitHub Actions, the default Ubuntu runners on GitHub Actions now include `yq` so you don't have to install it by yourself.
