### ISSUE TITLE
Quotes Removed or Added multiple quotes around the value

### ISSUE THREAD

**Issue by skumarcse** [mikefarah/yq#209]
Hi - Trying to add single or double quotes around the replaced new value as original value had single quotes.
Example:
foo:
  bar: 'q'
$ yq w -i input.yaml foo.bar 'h'
this command update bar value is h(single quotes removed)

$ yq w -i input.yaml foo.bar \'h\'
this command update bar value is '''h'''

Is that bug ? YAML library issue ?

**Comment by mikefarah** [comment]
wait are you saying the same command sometimes has quotes and sometimes doesn't?

I'd expect it to remove the quotes as they are not required. FWIW this is what the underlying yaml library does, and there is an existing issue opened for leaving quotes when requried (https://github.com/mikefarah/yq/issues/19#issuecomment-412320544)

**Comment by skumarcse** [comment]
Sorry for typo. With escape character, one or more quotes.
Example:
$ yq w -i input.yaml foo.bar \'h\'
this command update bar value as '''h'''

**Comment by skumarcse** [comment]
Oh comment remove back slash (\) after submitted.

**Comment by mikefarah** [comment]
The latest version should fix this I think. Otherwise use a comment block in your examples to avoid markdown interpreting your quotes.

```
yq w -i input.yaml foo.bar '"h"'
yq w -i input.yaml foo.bar "'h'"
```

**Comment by djmills64** [comment]
I've got the file:
`clientinfo::mappings:
  'a':
    key: 12345
  'c':
    key: 23456
`
and want to add
`  'b':
    key: 34567`

I tried:
`/usr/local/bin/yq -i ".[\"clientinfo::mappings\"].'b'.hkey1=34567" hieradata/reference/clientinfo.yaml`

but this results in
`  '''b''':
    hkey1: 34567`
How do I get it to add just one single quote either side of b?
