### ISSUE TITLE
2.2.1 yq_linux_386 build in ppa is wrong architecture

### ISSUE THREAD

**Issue by gharris999** [mikefarah/yq#211]
After adding the ppa:rmescandon/yq apt repository and installing yq on an i686 machine, the yq binary fails to execute, yielding this error message:

# /usr/bin/yq --help
-bash: /usr/bin/yq: cannot execute binary file: Exec format error

file /usr/bin/yq yields:
# file /usr/bin/yq
/usr/bin/yq: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64                                                                                  .so.2, with debug_info, not stripped

Machine tested on:
# cat /etc/issue
Ubuntu 18.04.2 LTS
# uname -a
Linux squeezenas 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:27:25 UTC 2019 i686 i686 i686 GNU/Linux

**Comment by gharris999** [comment]
The binary downloaded directly from:

https://github.com/mikefarah/yq/releases/download/2.2.1/yq_linux_386

..executes as expected on that i686 machine.

**Comment by mikefarah** [comment]
@rmescandon any thoughts?
