### ISSUE TITLE
keep empty objects when converting yaml to props

### ISSUE THREAD

**Issue by devopsmash** [mikefarah/yq#2124]
I have the this yaml file `foo.yaml` with the following content:
```
a:
  aa: "foo"
  ab: {}
  ac: 123
  ad: []
```

When I'm trying to convert it to `props` it seems that `yq` ignores empty objects/lists.

Example:
```
yq -o=props foo.yaml
a.aa = foo
a.ac = 123
```

expected results:
```
yq -o=props foo.yaml
a.aa = foo
a.ab = ""
a.ac = 123
a.ad = ""
```

Is it something acceptable and achievable? 

version: `v4.40.2`

**Comment by mikefarah** [comment]
Sure, take a look here: https://mikefarah.gitbook.io/yq/usage/properties#encode-properties-include-empty-maps-and-arrays
