### ISSUE TITLE
new cmd-line option 'l' (list all the matching paths) enhancement

### ISSUE THREAD

**Issue by seetamraju** [mikefarah/yq#213]
Example cmdline:
`yq l swagger.yaml 'components.schemas.*.xml' `
(Unlike 'r' command) Instead of dumping the elements/tags UNDER the matched path, 'l' command will SIMPLY LIST all the matching paths.
 -------------------------
Specifically, 'l' will Not produce the output "- null" .. ..  ever!
Like jq/sed/grep, no matches means empty output.
Example output (for above example cmdline):-
```
components.schemas.Orders.xml
components.schemas.Category.xml
components.schemas.Pet.xml
```
 -------------------------
This will allow us to save the list(output) to a file and create scripts to take action on each line item (in the above output).
This is aiming to replicate the flexibility that sed/grep allow --- to obtain either filenames or patterns(to search).. .. which in turn is used as input for other commands like awk/perl/python.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1, see https://mikefarah.gitbook.io/yq/commands/read#printing-matching-paths :)
