### ISSUE TITLE
yq passing invalding json

### ISSUE THREAD

**Issue by AtzeDeVries** [mikefarah/yq#2138]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.44.3
Operating system: mac
Installed via: homebrew

**Input JSON**
test.json which is invalid json
```json
{
  "a": "x",
  "b": "y",
}
```

**Command**
The command you ran:
```
cat test.json | yq -o json
```
returns
```
{
  "a": "x",
  "b": "y"
}
```
but running with `jq`
```
 cat test.json | jq
```
returns 
```
jq: parse error: Expected another key-value pair at line 4, column 1
```

**Additional context**
To my knowledge the `test.json` is invalid and i guess should be shown as invalid by `yq`.

**Comment by mikefarah** [comment]
This is something the underlying json parser is doing - I don't have control over it.
