### ISSUE TITLE
[Feature Request] Lint a YAML File

### ISSUE THREAD

**Issue by SukkaW** [mikefarah/yq#216]
Malformed YAML will crash the parser(#174).

If `yq` support `lint` features that to check whether YAML given is malformed or not, we can use `yq lint` to check YAML before using `yq` to manipulate it.

`yq lint` can work like this:

```bash
$ yq lint correct.yml
ok

$ yq l malformed.yaml
error
```

**Comment by mikefarah** [comment]
Fixed in Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1, see https://mikefarah.gitbook.io/yq/commands/validate

**Comment by shoce** [comment]
looks like the validate command disappeared as of v4.30.8

**Comment by Lenormju** [comment]
Accidentally (?), editing a file in-place with an empty expression does essentially the same thing as a linting (with automatic fixing). Here is the (Bash) command I use :
```bash
docker run \
    --rm \
    -u "$$(id -u):$$(id -g)" \
    -v "$${PWD}/my_target_file.yaml:/local/file.yml" \
    mikefarah/yq:latest \
    --input-format yaml \
    --output-format yaml \
    -i \
    '' \
    /local/file.yml
```
I use a Docker container but I guess it should work with any other packaging method.

**Comment by shoce** [comment]
for linting i do 
```
LintOk=true
yq "$f" >/dev/null || LintOk=false
echo "$f LintOk:$LintOk"
```
