### ISSUE TITLE
Docker pull failed in gh action

### ISSUE THREAD

**Issue by boukendesho** [mikefarah/yq#2160]
Error message:

> Pull down action image 'mikefarah/yq:4-githubaction'
>   /usr/bin/docker pull mikefarah/yq:4-githubaction
>   Error response from daemon: Head "https://registry-1.docker.io/v2/mikefarah/yq/manifests/4-githubaction": unauthorized: incorrect username or password
>   Warning: Docker pull failed with exit code 1, back off 1.872 seconds before retry.
>   /usr/bin/docker pull mikefarah/yq:4-githubaction
>   Error response from daemon: Head "https://registry-1.docker.io/v2/mikefarah/yq/manifests/4-githubaction": unauthorized: incorrect username or password
>   Warning: Docker pull failed with exit code 1, back off 1.528 seconds before retry.
>   /usr/bin/docker pull mikefarah/yq:4-githubaction
>   Error response from daemon: Head "https://registry-1.docker.io/v2/mikefarah/yq/manifests/4-githubaction": unauthorized: incorrect username or password
> Error: Docker pull failed with exit code 1

githubaction.yaml

>     - name: get current version
>         id: current
>         uses: mikefarah/yq@master
>         with:
>           cmd: yq '.version' 'snap/snapcraft.yaml'
>

**Comment by Scotchester** [comment]
@boukendesho This just started happening to us. Did you do anything to resolve it, or did it resolve itself?

**Comment by aprettyloner** [comment]
@mikefarah this is happening across the board for us, issue should probably remain open @boukendesho

**Comment by Scotchester** [comment]
Adding that we're not users of yq, it was happening to us just trying to pull a public Postgres image in our GitHub Actions workflow. We decided to bypass the check and merge anyway, and now it's failing to pull docker/github-actions:v1 on the action that the merge triggers, to build a new image.

**Comment by aprettyloner** [comment]
Actually there is an active incident https://www.dockerstatus.com/

**Comment by aprettyloner** [comment]
Docker has issued a fix, retry on my failed GHA succeeded ✅ 

> September 27, 2024 21:10 UTC
[Identified] Issue identified and fix applied, error rates are slowly returning to normal.
