### ISSUE TITLE
The repository 'http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial InRelease' is not signed.

### ISSUE THREAD

**Issue by neutron92** [mikefarah/yq#217]
```
root@s:~# sudo add-apt-repository ppa:rmescandon/yq
 yq is a portable command line processor created by Mike Farah

See code at:
https://github.com/mikefarah/yq
 More info: https://launchpad.net/~rmescandon/+archive/ubuntu/yq
Press [ENTER] to continue or ctrl-c to cancel adding it


gpg: keyring `/tmp/tmp1pkwgj4v/secring.gpg' created
gpg: keyring `/tmp/tmp1pkwgj4v/pubring.gpg' created
gpg: requesting key CC86BB64 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp1pkwgj4v/trustdb.gpg: trustdb created
gpg: key CC86BB64: public key "Launchpad PPA for Roberto Mier Escandn \xee\x83\xbf" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
'ascii' codec can't decode byte 0xc3 in position 108: ordinal not in range(128)

root@s:~# sudo apt update
Hit:1 http://archive.canonical.com/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:4 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial InRelease [18.0 kB]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:6 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial InRelease [18.0 kB]
Get:7 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial InRelease [2522 B]
Err:6 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6657DBE0CC86BB64
Get:8 https://ubuntu.bigbluebutton.org/xenial-200 bigbluebutton-xenial/main amd64 Packages [42.8 kB]
Get:9 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main amd64 Packages [12.1 kB]
Get:10 http://ppa.launchpad.net/jonathonf/ffmpeg-4/ubuntu xenial/main Translation-en [7252 B]
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 6657DBE0CC86BB64
E: The repository 'http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@s:~# sudo apt install yq -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  yq
0 upgraded, 1 newly installed, 0 to remove and 143 not upgraded.
Need to get 1410 kB of archives.
After this operation, 5431 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  yq
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
```

**Comment by satyaakam** [comment]
i saw the same error used snap to install yq for now

**Comment by rmescandon** [comment]
Seems that the key is not added to your local store. Try this:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6657DBE0CC86BB64
sudo apt update
sudo apt install -y yq
```

**Comment by rmescandon** [comment]
@satyaakam Can you please paste more information about the snap installation?. AFAIK This signing key is only used for the .deb, so looks weird to me that same error happens with snap version

**Comment by satyaakam** [comment]
@rmescandon following are the steps did to install yq first tried adding the repo it failed then did a install using Snap

# add-apt-repository ppa:rmescandon/yq -y
gpg: keyring `/tmp/tmps54vvbhc/secring.gpg' created
gpg: keyring `/tmp/tmps54vvbhc/pubring.gpg' created
gpg: requesting key CC86BB64 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmps54vvbhc/trustdb.gpg: trustdb created
gpg: key CC86BB64: public key "Launchpad PPA for Roberto Mier Escand�n \xee\x83\xbf" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
'ascii' codec can't decode byte 0xc3 in position 108: ordinal not in range(128)
root@meet:~# snap install yq
yq 2.3.0 from 'mikefarah' installed

**Comment by satyaakam** [comment]
> Seems that the key is not added to your local store. Try this:
> 
> ```
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6657DBE0CC86BB64
> sudo apt update
> sudo apt install -y yq
> ```

let me uninstall and try this method as well

**Comment by lyzhang1999** [comment]
> Seems that the key is not added to your local store. Try this:
> 
> ```
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6657DBE0CC86BB64
> sudo apt update
> sudo apt install -y yq
> ```

it work for me in ubuntu

**Comment by tmaior** [comment]
not working in Debian 9

root@c04dcf6da872:/# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.8 (stretch)
Release:        9.8
Codename:       stretch

**Comment by mafrosis** [comment]
Looks like the python code for `add-apt-repository` is not handling UTF8 properly in the string "Launchpad PPA for Roberto Mier Escand�n \xee\x83\xbf".

@rmescandon If you can rename the PPA to include just ascii chars this problem will likely go away.

**Comment by mafrosis** [comment]
Another alternative install:

```
curl -L https://github.com/mikefarah/yq/releases/download/2.4.0/yq_linux_amd64 -o /usr/local/bin/yq
chmod +x /usr/local/bin/yq
```

**Comment by rahulosp** [comment]
LC_ALL=C.UTF-8 add-apt-repository -y ppa:rmescandon/yq

The above works for me for Dockerfile as well as ubuntu 16.04

**Comment by rmescandon** [comment]
Hey guys. Forgot to attend this. Just updated my launchpad display name for not including any non-ascii char on my name. Please, give it a go.

Besides, there are newer versions of the debian packages, matching last releases
