### ISSUE TITLE
Support numeric keys

### ISSUE THREAD

**Issue by BigCheeZ** [mikefarah/yq#219]
Support creation of a YML document like:

test:
  "12": key_is_string_number
  13: key_is_number

What I've seen so far is:

1. yq can read test.12 but it cannot read test.13.
2. yq cannot create either of the keys shown under test. 

```bash
yq n test."12" key_is_string_number
test:
- null
- null
- null
- null
- null
- null
- null
- null
- null
- null
- null
- null
- key_is_string_number
```

I've tried different variations of wrapping the command in single and double quotes and cannot get the desired result. The closest I've been able to get is:

```bash
yq n "test.'12'" 0
test:
  '''12''': 0
```

which is still not what I'm looking for.

Is there a way to escape numeric keys or string-of-numbers keys?

**Comment by firebus** [comment]
Me too! I also tried key lookup syntax

```yq r foo.yaml 'bar[1234]'``` without any luck

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/2.4.0
