### ISSUE TITLE
toml/yaml: did not find expected <document start> for certain files

### ISSUE THREAD

**Issue by mrchief** [mikefarah/yq#2198]
**Describe the bug**
Unless the toml file starts with a simple key-value, parsing fails.

Version of yq: 4.27.5
Operating system: linux (WSL)
Installed via: wget

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.toml:
```yaml
[owner.contact]
name = "Tom Preston-Werner"
age = 36
```

data2.toml:
```yaml
bug = "exists"
[owner.contact]
name = "Tom Preston-Werner"
age = 36

```

**Command**
The command you ran:
```
yq -oy '.' data1.toml
```

**Actual behavior**

```yaml
[owner.contact]
Error: bad file 'data1.toml': yaml: line 1: did not find expected <document start>
```

**Expected behavior**

```yaml
[owner.contact] name = "Tom Preston-Werner" age = 36
```

**Additional context**
Adding a dummy key to the file works.

```
yq -oy '.' data2.toml
```

outputs

```
|-
  bug = "exists"
  [owner.contact] name = "Tom Preston-Werner" age = 36
```

**Comment by mikefarah** [comment]
I have bumped the version of the toml parser, should now work in 4.44.5
