### ISSUE TITLE
Gomodule builds and gets fail

### ISSUE THREAD

**Issue by swizzley** [mikefarah/yq#221]
`GO111MODULE=on go get gopkg.in/mikefarah/yq.v2`

build gopkg.in/mikefarah/yq.v2: cannot load gopkg.in/mikefarah/yaml.v2: cannot find module providing package gopkg.in/mikefarah/yaml.v2

**Comment by udhos** [comment]
I have created a pull-request fixing this issue:

https://github.com/mikefarah/yaml/pull/2

**Comment by chaimleib** [comment]
mikefarah/yaml#2 was merged, but I'm getting a similar error still:
```
% GO111MODULE=on go get gopkg.in/mikefarah/yq.v2
go: downloading gopkg.in/mikefarah/yaml.v2 v2.4.0
go: downloading gopkg.in/spf13/cobra.v0 v0.0.5
build gopkg.in/mikefarah/yq.v2: cannot load gopkg.in/mikefarah/yaml.v2: cannot find module providing package gopkg.in/mikefarah/yaml.v2
```

**Comment by chaimleib** [comment]
To make things work, I had to install like this:
```
% GO111MODULE=off go get gopkg.in/mikefarah/yq.v2
```

**Comment by mikefarah** [comment]
Fixed see https://github.com/mikefarah/yq/issues/289

**Comment by maelvls** [comment]
For anyone using Go 1.16:

```
go install github.com/mikefarah/yq/v4@latest
```

will properly install `v4.8.0`.
