### ISSUE TITLE
please exit 1 on NULL

### ISSUE THREAD

**Issue by tibers** [mikefarah/yq#223]
Simple ask: Please exit 1 on NULL so I can trap for a filter or key that doesn't work or exist.

**Comment by mikefarah** [comment]
Hmm I can do that with an optional flag - however it will also exit 1 if the yaml happens to have null for that entry 🤔 

Having it return 1 for a missing key in the path is a bigger refactor (and I don't really have time atm)...

**Comment by mikefarah** [comment]
Also there's a reasonably clean workaround:

```
test $(yq r examples/data1.yaml d) != "null"
```

**Comment by tibers** [comment]
oh boy I forgot I opened this... I'm not actually sure if that's technically an error to ask yaml for a key that doesn't exist or if null is correct, but since you jogged my memory, thanks for the workaround!

**Comment by ndeloof** [comment]
I wish I could distinguish "no match" and "explicitly set to null"
i.e.
data1.yaml
```yaml
foo:
   bar: ~
   zot: qix
```

I expect `yq '.foo.bar'` to return `null`, exit code 0: path was find, and value is explicitly set to `null` by user

data2.ayml
```yaml
foo:
   zot: qix
```

I expect `yq '.foo.bar'` to let me distinguish this scenario as "not set". Could obviously require an additional flag for backward compatibility.

**Comment by ndeloof** [comment]
afaict this would mean we get an option to set `DontAutoCreate` on context
