### ISSUE TITLE
yq_linux_s390x is missing in release 2.3

### ISSUE THREAD

**Issue by alicefr** [mikefarah/yq#225]
Hi,

in the release 2.3 the the version `yq_linux_s390x` is missing. Do you plan do built it for the latest version? It was already present in the previous release. Thanks!

**Comment by rajivnathan** [comment]
`yq_linux_ppc64le` is missing from the 2.3 release as well. Would like to know if it's planned for this release as well please.

**Comment by mikefarah** [comment]
My bad - not sure what happened, re-uploaded and it's there now :)

**Comment by alicefr** [comment]
Thanks!
