### ISSUE TITLE
'bad flag syntax' error when value starts with hyphens

### ISSUE THREAD

**Issue by bruxelles86** [mikefarah/yq#230]
Hi. We're using yq 2.3.0 on Ubuntu 18.04.2.

We've noticed that when trying to set a value that starts with hyphens (such as a certificate or RSA key), `yq` seems to interpret this as a flag and gives us an error. For example:

```
$ yq new privkey "$(cat private_key.pem)"
Error: bad flag syntax: -----BEGIN PRIVATE KEY-----
```

Is there a way round this?

Many thanks!

**Comment by mikefarah** [comment]
Yep (sorry for the delay) this is happening because the flag library is trying to parse that argument as a flag.

You need to add '--' to stop the flag parser:


```
> yq new thing -- "----"
thing: '----'
```

**Comment by bruxelles86** [comment]
Ahh right, many thanks!

Sent from Yahoo Mail on Android 
 
  On Mon, 29 Apr 2019 at 7:56, Mike Farah<notifications@github.com> wrote:   
Yep (sorry for the delay) this is happening because the flag library is trying to parse that argument as a flag.

You need to add '--' to stop the flag parser:
> yq new thing -- "----"
thing: '----'
