### ISSUE TITLE
Debian build step missing?

### ISSUE THREAD

**Issue by ottomata** [mikefarah/yq#231]
I'm trying to build yq for Debian Stretch and Debian Buster.  I believe there is a step missing that is failing to install go dependencies.  What I tried:

1. Modified debian/control to use golang-1.11-go from stretch backports
2. Modified debian/rules to set `GOVERSION := 1.11`
3. Modified debian/changelog to build new stretch release version

I'm building with pbuilder like:

`GIT_PBUILDER_AUTOCONF=no DIST=stretch BACKPORTS=yes gbp buildpackage -sa -us -uc --git-builder=git-pbuilder`

But am getting:

```
...
# build go code
(cd /build/yq-2.2.wmf0/_build/src/github.com/mikefarah/yq && go install ./...)
yq.go:13:2: cannot find package "github.com/pkg/errors" in any of:
	/build/yq-2.2.wmf0/_build/src/github.com/mikefarah/yq/vendor/github.com/pkg/errors (vendor tree)
	/usr/lib/go-1.11/src/github.com/pkg/errors (from $GOROOT)
	/build/yq-2.2.wmf0/_build/src/github.com/pkg/errors (from $GOPATH)
...
```

for all go vendor dependencies.

Is there a step missing from debian/rules that should populate the `vendor` directory?

**Comment by mikefarah** [comment]
Old issue for yq v2, no longer supported
