### ISSUE TITLE
Don't use black for "null" colourisation

### ISSUE THREAD

**Issue by stephen-dexda** [mikefarah/yq#234]
Given that some very large fraction of terminals have a black background ;)

**Comment by mikefarah** [comment]
yq doesn't have any colourisation?

**Comment by stephen-dexda** [comment]
Maybe it's something to do with a JSON pretty-printing lib. yq uses then? E.g. a minimal test case of `echo - foo | yq .` produces:

```
[
  "foo"
]
```

with `"foo"` coloured green, whereas `echo - foo | yq -y .` produces `- foo` with no colourisation.

**Comment by mikefarah** [comment]
Nope - I'm thinking you have a different yq, https://github.com/kislyuk/yq perhaps?

**Comment by stephen-dexda** [comment]
Ugh, you're right sorry :) Didn't realise there are two completely separate projects with the same name, and looks like it's kislyuk's fault that's the case since you started yours two years earlier ;)
