### ISSUE TITLE
[Feature request] return empty result when read input is empty

### ISSUE THREAD

**Issue by goober** [mikefarah/yq#236]
I was expecting a behavior where `echo "" | yq r -` would return an empty result instead of throwing an error. More like the behavior of jq. I.e `echo "" | jq` returns an empty result with `0` as exit code.

This is especially useful when using yq for piping a result that could be empty.

Is this already supported or is it something that would be of interest?

My current solution is to use the `-d*` flag and then pipe it to jq for processing

```bash
$  echo "" |  yq r -j -d* - | jq '.[]'
```

**Comment by mikefarah** [comment]
Done! https://github.com/mikefarah/yq/releases/tag/3.1.0
