### ISSUE TITLE
how to select items recursively

### ISSUE THREAD

**Issue by mrtylerzhou** [mikefarah/yq#243]
If i wan to get a containers image in kubernetes yaml,i have to use` kubectl get po consul-0 -oyaml|yq r - spec.containers.*.image` But it is so verbose and users must know clearly the structure of the yaml to query.Most of the times,I just want to get all the values of the image field without knowing its struecture. Kubernetes jsonpath can use ` kubectl get po consul-0 -ojsonpath='{..image}'` to get all image fields's value.How to archive it in yq?

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1 see https://mikefarah.gitbook.io/yq/usage/path-expressions#deep-splat
