### ISSUE TITLE
support for compact mode to make things more bash friendly

### ISSUE THREAD

**Issue by rverma-nikiai** [mikefarah/yq#246]
From jq docs
--compact-output / -c:

By default, jq pretty-prints JSON output. Using this option will result in more compact output by instead putting each JSON object on a single line.

This would be useful when the result in an array e.g.
```
- a
- b 
- c 
```
and we want to convert this to 
a
b
c
to use some bash scripts.

**Comment by mikefarah** [comment]
This is now the default behavior for scalar results in v3 https://github.com/mikefarah/yq/releases/tag/3.0.1

**Comment by malthe** [comment]
FWIW, using `-I0` makes the output compact – without spaces or newlines.

**Comment by scila1996** [comment]
> FWIW, using `-I0` makes the output compact – without spaces or newlines.

This work for me, tks a lot

**Comment by nparry-zymergen** [comment]
I would love to see a jq like shortcut to make `-c` act like `-I0`. I spent a fair amount of time searching for the jq `-c` equivalent, and setting the "indent level" to "0" was not intuitive and I was lost until I found this issue/comments. Just my $0.002 on the matter. :) Thanks all!
