### ISSUE TITLE
How to query when yaml root is an array

### ISSUE THREAD

**Issue by peijianju** [mikefarah/yq#249]
Hi, could you add in the doc on how to do the read query when the root of the yam is an array?
```
- a: "hello"
     b: "hi"
     c: "hi again"
```
How can I use `yq r` to get `hi again`?

**Comment by mikefarah** [comment]
just pass in the path in quotes (otherwise you shell tries to interpret it)

```sh
yq r "[0].a.c
```

that should do the trick
