### ISSUE TITLE
Inline Script

### ISSUE THREAD

**Issue by jcguu95** [mikefarah/yq#250]
I understand we can use the option `-s` to read an instruction script. Can we make that script inline? For example,
```
yq w FILE.yaml -s 'do-this; do-that'
```

This is an analogue of `sed`'s
```
sed -e 'do-this' -e 'do-that'
```

**Comment by mikefarah** [comment]
ooh that'd be cool - but no it can't do that atm.

**Comment by jcguu95** [comment]
glad you like it!

**Comment by javadba** [comment]
Along similar lines: I want to pipe a heredoc to yq instead of reading from a file: is that possible?

```
echo """field1: field1_val
field2: field2_val""" | yq r  field1
```

**Comment by mikefarah** [comment]
yes - you can read from stdin http://mikefarah.github.io/yq/read/#from-stdin

**Comment by javadba** [comment]
ah! I borked the usage of stdin : tried `--` but is `-`

**Comment by mikefarah** [comment]
For the record, '--' in bash normally means 'stop processing the next args as flags'

**Comment by mikefarah** [comment]
yq v4 supports complex path expressions with multiple operations in a single cli command
