### ISSUE TITLE
adding value beginning wih -- failed

### ISSUE THREAD

**Issue by jia2** [mikefarah/yq#251]
When I try to update a yaml file with
`yq w -i alb-ingress-controller.yaml spec.template.spec.containers[0].args[+] '--cluster-name=myCluster'`

I got the error: `unknown flag: --cluster-name`

It seems that value beginning with double dash "--" is not accepted. How can I escape them?

**Comment by mikefarah** [comment]
(note: this is common for other bash commands too), you have to indicate that the remaining arguments are not flags, this is done with '--' after the last flag to yq:


```
yq w -i -- alb-ingress-controller.yaml spec.template.spec.containers[0].args[+] '--cluster-name=myCluster'
```
