### ISSUE TITLE
Add node

### ISSUE THREAD

**Issue by andye2004** [mikefarah/yq#255]
Would be good to be able to add a node with sub elements in the same way delete will delete a node. E.g. give the snippet from `node.yaml`:-
```yaml
c:
  d: hamster
```
and the sample.yaml file:-
```yaml
a:
  b: cat
```
Using a new `add` command _somehow_, e.g. maybe using a combination of read / path from another file we'd end up with:-

`yq r node.yaml c | yq a sample.yaml a`

Then the result would be:-
```yaml
a:
  b: cat
  c:
    d: hamster
```

**Comment by mikefarah** [comment]
you should be able to do that using the prefix command (to move c under a) and the merge command

**Comment by andye2004** [comment]
Thanks @mikefarah, will give it a try.

**Comment by flanksaul** [comment]
How can this be done in v4?

**Comment by mikefarah** [comment]
```
yq ea 'select(fi==1) * {"a": select(fi==0)}' node.yaml sample.yaml
```

- `fi ==1` is short for `fileIndex == 1`, which selects the 2nd file
- we merge that again the first file, with `a` prefixed to make it match the schema
