### ISSUE TITLE
Example alias for Docker image does not work

### ISSUE THREAD

**Issue by dead10ck** [mikefarah/yq#259]
In the `README.md`, it says:

>It can be useful to have a bash alias to avoid typing the whole docker command:
>
>```bash
>alias yq="docker run --rm -v ${PWD}:/workdir mikefarah/yq yq"
>```

This actually doesn't work, since the `${PWD}` is only evaluated at the shell startup, so it will always just be the user's home directory. An alternative that would work is using a bash function, e.g.:

```bash
yq() {
  docker run --rm -i -v ${PWD}:/workdir mikefarah/yq yq $@
}
```

**Comment by mikefarah** [comment]
good point, cheers :)
