### ISSUE TITLE
How to create multiple keys inside array

### ISSUE THREAD

**Issue by vk496** [mikefarah/yq#260]
Hello,

I have this `create_instructions.yaml`:
```yaml
test[+].a: a
test[+].b: b
```

Which returns me this:

```yaml
test:
- a: a
- b: b
```

But I would like 1 array with multiple elements. Something like this:

```yaml
test:
- a: a
  b: b
```

How should I do it?

**Comment by mikefarah** [comment]
The only way of doing this (atm) is to explicitly put the position in the array for 'b':

```
test[+].a: a
test[0].b: b
```

yields

```
yq n --script instructions.yml
test:
- a: a
  b: b
```

**Comment by sdrose** [comment]
And in this above example, how does one read value test.a: and test.b: individually?   I have tried:
yq r a.yaml test.a
yq r a.yaml test.b
yq r a.yaml 'test[0]'

and none work.  The a.yaml is the file I wrote the array to ...

thank you
-dave

**Comment by fmehrdad** [comment]
Please add this to the examples in docs.  I almost gave up.

**Comment by sdrose** [comment]
@fmehrdad @mikefarah 
$ yq r a.yaml
test:
- a: a
- b: b

$ yq r a.yaml test[0].a
a

$ yq r a.yaml test[0].b
null

**Comment by mikefarah** [comment]
It's in the docs already http://mikefarah.github.io/yq/read/#arrays unless I'm missing something?
which version of 'yq' are you using? just tried it and it works fine

**Comment by sdrose** [comment]
$ yq --version
yq version 2.2.1

Using on Ubuntu in Linux for Windows.

**Comment by WarpRat** [comment]
As a feature request, it would be great if we were able to do something like:

`cat test.yml | yq w - test[a][+].b "b"`

**Comment by keithy** [comment]
This works:
```
passwd.groups[+]:
  name: eternal  
  gid: 777
```
produces
```
passwd:
  groups:
  - name: eternal
    gid: 777
```

**Comment by mikefarah** [comment]
Just released a new version of yaml that fixes this - it's a pretty significant update so it's still in beta: https://github.com/mikefarah/yq/releases/tag/3.0.0-beta

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
Check out https://mikefarah.gitbook.io/yq/commands/write-update#using-a-script-file-to-update for more info

**Comment by agates4** [comment]
> Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
> Check out https://mikefarah.gitbook.io/yq/commands/write-update#using-a-script-file-to-update for more info

Link broken

**Comment by agates4** [comment]
> It's in the docs already http://mikefarah.github.io/yq/read/#arrays unless I'm missing something?
> which version of 'yq' are you using? just tried it and it works fine

Another link broken

**Comment by mikefarah** [comment]
This issue is very old - and refers to a deprecated versions of yq (v2 and v3). The docs for those version have moved here: https://mikefarah.gitbook.io/yq/v/v3.x/ - though I'd _highly_ recommend using v4 (https://mikefarah.gitbook.io/yq/) as those versions are no longer supported.
