### ISSUE TITLE
Prefix a specific node

### ISSUE THREAD

**Issue by ajilk** [mikefarah/yq#263]
Add support for prefixing of a specific node

Given `sample.yaml`:
```
a:
  b:
    d: something
```

Running:
`yq p sample.yaml a.b` 

should prefix what is under `a.b` and produce:
```
a:
  b:
    c:
      d: something
```
---
This works but requires manually updating the original file
`yq r sample.yaml a.b | yq p - c` 

produces: 
```
c:
  d: something
```

**Comment by mikefarah** [comment]
This is now possible in v4 of yq, using the collect object operation to create a new object based on old
