### ISSUE TITLE
Preserve boolean encodings of original file

### ISSUE THREAD

**Issue by mvaldesdeleon** [mikefarah/yq#267]
Not really an issue, but rather a feature request.

As you probably know, the [YAML spec supports a wide variety of boolean values](https://yaml.org/type/bool.html) (See the "regexp" section).

When processing a YAML file with booleans, it appears the output file has the boolean values normalised to either `true` or `false`. While this is completely fine for spec-compliant tools, sadly that's not my case.

I'm dealing with a non-compliant tool (I know...) that considers values such as `N` not to be booleans, and will not accept `false` as a valid replacement, and I would love to use `yq` to manipulate some other keys in these files, without having the `N` values modified.

Would it be possible to provide a way to disable boolean normalisation, so that values are kept AS-IS in the output file?

**Comment by mikefarah** [comment]
That's a bummer - unfortunately the yaml parser I'm using (https://gopkg.in/yaml.v2) doesn't support that level of control - the new version v3 does, as well as a bunch of other neat features, but that requires I rewrite of yq which I don't have time for :(

Only thing/hack I can think of is coming up with a 'sed' command to replace all ': false' to ': N'.

**Comment by mvaldesdeleon** [comment]
Oh well.

I will see if I can raise an issue to the upstream tool so that it preserves quotes around those N values, or otherwise try to deal with this before it reaches `yq`.

Sadly I cannot guarantee that there will not be any actual `false` values on the file, so replacing all `false` by `N` would potentially break other parts of the processing.

Thanks for taking the time to look into this! I will close the issue.
