### ISSUE TITLE
Keep json convertion unsorted

### ISSUE THREAD

**Issue by galindro** [mikefarah/yq#274]
It would be nice if the json conversion keeps the order of the objects from the original yaml file.

**Comment by cnrmck** [comment]
`oq` is a nice alternative to `yq` that won't change the order of your yaml file. 

`cat yourFile.yaml | oq -i yaml` then use the features of `jq` that you're used to.

If you use some of the fancier yaml features, I don't think that oq can handle it. But if your yaml file is essentially a nice looking JSON file then you're good to go. 

https://github.com/Blacksmoke16/oq

**Comment by GeraldLoeffler** [comment]
the link to `oq` in the previous comment is incorrect -the correct one is: https://github.com/Blacksmoke16/oq
(sorry to post a link to an alternative tool here, but it keeping the order of keys when converting between JSON and YAML is a sufficiently important missing feature in `yq` to warrant this.)

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1 :)

**Comment by cnrmck** [comment]
Wow thank you!
