### ISSUE TITLE
How to phrase yaml file to json with AQL syntax

### ISSUE THREAD

**Issue by arielman** [mikefarah/yq#277]
Hi
can I use this tool to convert YAML file to JSON with AQL (artifactory-query-lang) syntax? like writing a script that parses through the YAML file with yq and using the needed values with AQL
for example, this content:
  - name: attachment-attachment
    version: ">=0.1.0-0"
    repository: http://XXXX:XXXX@illinXXXX.corp.amdocs.com:XXXX/repository/helm-release/attachment-attachment
    releaseName: attachment-attachment-release
    dockerImageName: attachment-attachment-service

**Comment by mikefarah** [comment]
Sorry I have no idea what you are trying to do...
