### ISSUE TITLE
ppa package old, does not contain disco, eoan series

### ISSUE THREAD

**Issue by msplival** [mikefarah/yq#279]
Hi.

I see that you offer installing yq via ppa's, but those don't seem to be updated recently. Would you be able to push the latest changes to ppa, and also build the package for disco and eoan?

I'm glad to help with this, if needed.

I'd really prefer not to use snap version, as snaps just create issues on my system (silly annoyances like ~/snap directory, tons of squashfs mounts, auto updates, etc, etc).

Thank you :)

**Comment by mikefarah** [comment]
Hey, @rmescandon is the one that set this up - I'm not really sure on the details...

**Comment by rmescandon** [comment]
@msplival There's an update on deb package. An Eoan deb version. Please give it a go

**Comment by msplival** [comment]
Thank you! I can finally remove the snap! :D
