### ISSUE TITLE
Root `.`, `keys` does not behave as expected 

### ISSUE THREAD

**Issue by xkortex** [mikefarah/yq#286]
`yq_linux_amd64 2.4.0`
`ubuntu 18.04`

I'm getting nulls from what I thought are features that should work. 

#52 makes me think these functions should work. Or is that a wontfix? 

```bash
wget https://raw.githubusercontent.com/mikefarah/yq/master/examples/sample.json
wget https://raw.githubusercontent.com/mikefarah/yq/master/examples/sample.yaml  
```
` $ cat sample.json | jq '.'       `

> {
>   "a": "Easy! as one two three",
>   "b": {
>     "c": 2,
>     "d": [
>       3,
>       4
>     ],
>     "e": [
>       {
>         "name": "fred",
>         "value": 3
>       },
>       {
>         "name": "sam",
>         "value": 4
>       }
>     ]
>   }
> }
> 

` $ cat sample.yaml | yq r - '.'   `
> null

` $  cat sample.json | jq 'keys' ` 

> [
>   "a",
>   "b"
> ]

` $ cat sample.yaml | yq r - 'keys' `
> null

Is this a bug or am I missing something obvious? Thanks

**Comment by mikefarah** [comment]
Ah yep - sorry I did an github issue cleanup as there were many issues created to add features to better support 'jq' like functionality, (which would be great for yq), but they made it harder to sift through to find issues people were actually raising.

I'll reopen that one (and close this)
