### ISSUE TITLE
Checksums

### ISSUE THREAD

**Issue by mamercad** [mikefarah/yq#295]
Mind publishing checksums for the releases?

**Comment by mikefarah** [comment]
That would be good to do - not sure how to, I'm using https://github.com/mitchellh/gox to compile the binaries...

**Comment by 030** [comment]
@mikefarah You could issue a sha512 on the files that were created.

**Comment by 030** [comment]
What binary gets installed when snap is used? I was assuming that linux amd64 would be used.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.2.1
