### ISSUE TITLE
Merging into an Empty file

### ISSUE THREAD

**Issue by abdiriman** [mikefarah/yq#298]
I've got two Yml files which hypothetically are example.yml and example2.yml.

The example.yml file has 
> ES:
>   port: *port*

The example2.yml file is empty.

I am trying to merge the contents of example.yml into example2.yml file which is empty.

The command I am running is yq m -i example2.yml example.yml

Error I get: Error: asked to process document index 0 but there are only 0 document(s)

**Comment by abdiriman** [comment]
Also how would i install your version of yq correctly in a docker-file? I noticed there is a-lot of versions of "yq" out there.

**Comment by mikefarah** [comment]
yq has prebuilt docker image, or you can build your own. Take a look at the Dockerfile in github

**Comment by mikefarah** [comment]
Done! https://github.com/mikefarah/yq/releases/tag/3.1.0
