### ISSUE TITLE
Can't delete array entry with string key

### ISSUE THREAD

**Issue by davidmichaelkarr** [mikefarah/yq#299]
I may be missing something obvious, but I'm unable to delete array entries that are keyed with strings, not integers.

I'm working with a sample yaml like this:

```
apiVersion: ...
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
	...
  creationTimestamp: "2019-11-14T18:54:33Z"
  generation: 1
  name: ...
  namespace: ...
  resourceVersion: "183949398"
  selfLink: ...
  uid: 32749caa-0710-11ea-90a2-fa163e8e4620
spec:
  hosts:
  - ...
  http:
  - match:
    - uri:
        prefix: /msapi/...
    route:
    - destination:
        host: ...
        port:
          number: 80
        subset: blue
```

I'm trying to experiment with what pieces I can remove with what expressions.  Initially, I want to delete the "route" and perhaps the "match", but only if the "subset" in the destination is named "blue".  All the variations I've tried to match "match" or "route" fails with "Invalid syntax".

**Comment by mikefarah** [comment]
I'm not sure what you mean by array keyed by string - surely that's a map? 

For instance, the value of http is an array. The first entry of that is a map, which has two keys, 'match' and 'route'.

At the moment yq does not have functionality to search for matching nodes - you'd be better off using 'jq' and one of the many wrappers available to convert yaml to json and back.

**Comment by mikefarah** [comment]
Similar to https://github.com/mikefarah/yq/issues/257, need to be able to have complex path expressions for finding nodes based on children

**Comment by mikefarah** [comment]
The latest version has complex path expressions https://mikefarah.gitbook.io/yq/usage/path-expressions that will be able to do that :)
