### ISSUE TITLE
Support Tags and String Styles

### ISSUE THREAD

**Issue by elmpp** [mikefarah/yq#303]
It would be really great if we could perform writes whilst preserving [string styles](https://yaml-multiline.info/) and [tags](https://camel.readthedocs.io/en/latest/yamlref.html#tags)

This library gives a good use case of supporting CloudFormation templates here [here](https://github.com/kislyuk/yq#preserving-tags-and-styles-using-the--y---yaml-roundtrip-option)

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
