### ISSUE TITLE
Print values of keys with dot in it

### ISSUE THREAD

**Issue by jeunii** [mikefarah/yq#304]
I have a yaml file with the following format
```
---
users:
  foo1.bar1@email.com:
    - roles/role1
    - roles/role2
    - roles/role3

  foo2.bar2@email.com:
    - roles/role4
    - roles/role5
    - roles/role6
```

Now I would like to print the roles for `foo1.bar1@email.com`

Im trying to do the following

```
cat permissions.yaml | yq '.users[ foo1.bar1@email.com]'
jq: error: syntax error, unexpected FORMAT (Unix shell quoting issues?) at <top-level>, line 1:
.users[ foo1.bar1@email.com]
jq: 1 compile error
```
Is there a work around to this ?

**Comment by mikefarah** [comment]
yup http://mikefarah.github.io/yq/read/#keys-with-dots

**Comment by mikefarah** [comment]
From the error (it mentions jq) I think you're using a different yq.
Using mikefarah/yq this works fine:

```
cat permissions.yaml | yq - 'users[foo1.bar1@email.com]'
```

**Comment by gggeek** [comment]
For anyone mixing up the two different "YQ" implementations: this is the closest bug (& response) that deals with the same problem in kysliuk/yq: https://github.com/kislyuk/yq/issues/32

**Comment by ALutchko** [comment]
Hi Mike,
I believe I'm using this `yq` 
```
yq -V
yq version 4.9.6 #imho it'd make sense to add "by mikefarah" here

```
but the example above does not work for me. Using the same file, I have:
```
cat 1.yml | yq - 'users[foo1.bar1@email.com]'
Error: unknown command "users[foo1.bar1@email.com]" for "yq"
Run 'yq --help' for usage.
```
Also I tried
```
 yq e 'users[foo1.bar1@email.com]' 1.yml
Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:3.
        unmatched text: "us"
```
Just to make sure we're on the same page:
```
 cat 1.yml
---
users:
  foo1.bar1@email.com:
    - roles/role1
    - roles/role2
    - roles/role3

  foo2.bar2@email.com:
    - roles/role4
    - roles/role5
    - roles/role6

```
So what am I doing wrong, how to do it now?

Thank you in advance.
