### ISSUE TITLE
[feature request] Script to support delete operations as well

### ISSUE THREAD

**Issue by saadlu** [mikefarah/yq#305]
First of all `yq` is brilliant - thank you so much

Using the script to write new values is great! Wish the script support allowed for deleting as well. Could we have script file like

    write:
       - b.c: 3
       - b.e[+].name: Howdy Partner
    delete:
       - b.d

which, when applied to a YAML:

    b:
      c: 2
      d: 3

will produce:

    b:
      c: 3
      e:
        - name: Howdy Partner

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1,
see the delete in https://mikefarah.gitbook.io/yq/commands/write-update#using-a-script-file-to-update
