### ISSUE TITLE
Empty script file fails

### ISSUE THREAD

**Issue by keithy** [mikefarah/yq#307]
If a script file happens to be empty (ish) yq doesnt apply the null case, but rather complains. Requiring code in a script to dodge this case.
```
YQ_HAPPY=false
echo "$input" | yq w -s "$script" - 2&> /dev/null && YQ_HAPPY=true
```

**Comment by mikefarah** [comment]
Fixed with the latest release https://github.com/mikefarah/yq/releases/tag/3.0.1
