### ISSUE TITLE
Option to retain comments and formatting when modifying the data

### ISSUE THREAD

**Issue by BrainStone** [mikefarah/yq#308]
It would be very beneficial if there was an option to keep comments and formatting when updating the data for example with `yq w ...`.

**Comment by mikefarah** [comment]
Yup - the new version of the yaml parser I'm using does this - but it requires a significant rewrite of yq...which is in progress :)

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
