### ISSUE TITLE
delete node same level but different nested key

### ISSUE THREAD

**Issue by nat2k5us** [mikefarah/yq#312]
I would like to delete the nodes which have a matching nested key for example schema which has description but not schema that has $ref
```
paths:
  /xxxxxxx/symbols/{symbols}:
    get:
      description: Fetches symbol 
      operationId: GetSymbols
      parameters:
      - description: List of symbols 
        in: path
        name: symbols
        required: true
   =>   schema:
          description: List of symbols
          type: string <= delete this
        type: string
      responses:
    =>     schema:
            $ref: '#/definitions/ErrorResponse' <= don't delete this
```
   what i have tried;
`#yd d -i swagger.yaml "paths.[*].[*].[*].[*].schema" `
deletes both - any way to delete only the schema node that have an underlying node as description?

**Comment by nat2k5us** [comment]
was able to get it working with the below

`yq d -i swagger.yaml "paths.[*].[get].[parameters].[*].schema"`

**Comment by mikefarah** [comment]
Similar to https://github.com/mikefarah/yq/issues/257, need to be able to have complex path expressions for finding nodes based on children

**Comment by mikefarah** [comment]
This has been fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1, see https://mikefarah.gitbook.io/yq/usage/path-expressions#search-by-children-nodes
