### ISSUE TITLE
Add square bracket to value

### ISSUE THREAD

**Issue by nat2k5us** [mikefarah/yq#313]
I am looking to add 
yq w -i swagger.yaml 'definitions.OrderType.enum' [LIMIT,STOPMARKET,MARKET,STOPLIMIT]

This generates 
```
...
  ...
    enum: '[LIMIT,STOPMARKET,MARKET,STOPLIMIT]'
```
but I need it with out the single or double quotes as it become invalid - I think the problem is with the square brackets

**Comment by mikefarah** [comment]
at the moment you can do this with consecutive commands for each entry, in v3 of yaml I'm hoping to change this:

```
yq w -i swagger.yaml 'definitions.OrderType.enum[+]' LIMIT
yq w -i swagger.yaml 'definitions.OrderType.enum[+]' STOPMARKET
// etc
```

You could also use a write script

**Comment by nat2k5us** [comment]
yq w -i swagger.yaml definitions.OrderType.enum [LIMIT,STOPMARKET,MARKET,STOPLIMIT]
cat swagger.yaml | sed "s/\'\[LIMIT,STOPMARKET,MARKET,STOPLIMIT\]\'/\[LIMIT,STOPMARKET,MARKET,STOPLIMIT\] /g" > temp.yaml ; mv temp.yaml swagger.yaml


Did it as above - but would prefer yours - if it does not need so many line :)

I have more than 100 enum values
