### ISSUE TITLE
yq write numbers as exponent instead integer

### ISSUE THREAD

**Issue by tnimni** [mikefarah/yq#314]
When i run a command to replace a value in yaml
for example 
yq w fileName.yaml global.containerTags.site 1212121 > values.new
expected value is
gloabl:
  containerTags:
    site: 1212121

actual value is 1.212121e+06

this only happen if i try to write a number with 7 digits or more 6 digits or less works fine

**Comment by mikefarah** [comment]
This will be fixed in v3

**Comment by gharris999** [comment]
Same as #245

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.0.1
