### ISSUE TITLE
Show the source file of the specific value in merge output

### ISSUE THREAD

**Issue by gitmik** [mikefarah/yq#317]
It would be helpful for the merge feature to get an option to show the source filename for each value.

If you merge few files and want to easily track where did the specific value came from it could be printed just after the value as a comment. The tricky part is to skip the not simple values containing yml objects.

For instance one could invoke merge:
`yq -s merge file-a.yml file-b.yml file-c.yml `
or
`yq  --showSource merge file-a.yml file-b.yml file-c.yml `

where option `-s` or `--showSource` could indicate to print the value source

output:
<pre>a:
  z: 5  # file-a.yml
  x: 6  # file-b.yml
b:
  name: "Abcd"  # file-c.yml</pre>

**Comment by mikefarah** [comment]
This would be neat, and shouldn't be hard to do in v3...

Happy to accept a PR, otherwise I'll get to it when I can.

**Comment by mikefarah** [comment]
You can do this using v4:

```bash
yq ea '(..  lineComment |= filename + ":" + line) | select(fi==0) * select(fi==1)' examples/data1.yaml examples/data2.yaml
```
results in:
```bash
a: mike # examples/data1.yaml:1
b: meow # examples/data2.yaml:3
c:
  d: hamster # examples/data2.yaml:2
```
