### ISSUE TITLE
CI has been disabled

### ISSUE THREAD

**Issue by RyanSiu1995** [mikefarah/yq#321]
The latest pull request and commit doesn't trigger travis ci process.

**Comment by mikefarah** [comment]
Ah travis-ci + github is in some sort of funny state, github services are deprecated, there's a new travis ci 'GitHub App' for *travis-ci.com• which is beta - but my apps are in the (old?) travis-ci.org.
I think they're planning on merging everything into travisci.com.

There's a migration option but it's disabled. Played with the configs / integrations settings but no go. 

Might try again when they sort their issues out

**Comment by RyanSiu1995** [comment]
Yes, it looks pretty good now. I will close this issue now.
