### ISSUE TITLE
Remove the "-" prefix when outputting items of a list

### ISSUE THREAD

**Issue by aegershman** [mikefarah/yq#322]
In order to more effectively leverage `yq` in shell scripts to iterate over list items (which often get piped into other binaries), when the `read` command captures a list, it'd be nice to have a way to print out only the results rather than have a `-` key in front of it

## background

when using yq to iterate over items in a list, the output is prepended with `-` like so:

```yml
# example.yml
mylist:
- name: aaron
- name: erin
- name: erran
```
...
```sh
yq r example.yml 'mylist[*].name'
```
which results in
```
- aaron
- erin
- erran
```
but would be nice to have it output like this
```
aaron
erin
erran
```
so the results could be captured into a shell variable, or fed into other programs, without having to first strip off the leading dash. 

there are bash hacks to have the `-` removed from each entry, but they add a lot of lines of code && often use some funky `sed`. I feel it'd make shell scripts cleaner if there was a way `yq` could output the results.

thoughts, advice, suggestions, etc. welcome. Don't mean to sound demanding or anything, just sharing my experience and wondering whether there's something I'm missing? and thanks so much for all you do and making `yq` available to everyone

**Comment by mikefarah** [comment]
Hey - the latest release (still in beta) fixes this: https://github.com/mikefarah/yq/releases/tag/3.0.0-beta

**Comment by aegershman** [comment]
```sh
./yq_darwin_amd64 read example.yml 'mylist[*].name'
aaron
erin
erran%    
```

right on. thank you 🙏
