### ISSUE TITLE
Refactor the yq.go

### ISSUE THREAD

**Issue by RyanSiu1995** [mikefarah/yq#323]
Currently, all the cmd methods are placed within `yq.go`.
It is pretty messy if we start to implement more features for yq v3.
I suggest we can refactor the `yq.go` like this.
```
cmd
├── help.go
├── merge.go
├── new.go
├── prefix.go
├── read.go
├── root.go
└── write.go
yq.go
```
This shares the same cobra command structure as in many projects, like `helm` and `kubectl`.
The extensibility of the cli will be better.

@mikefarah

**Comment by mikefarah** [comment]
I like it - if you like have a go of changing that in the v3 branch...

**Comment by RyanSiu1995** [comment]
Just want to make sure that the v3 branch and master has been caught up first.
I have the refactor ready but I am afraid that it will be a disaster if v3 branch and master are out of sync.
The code catch-up action will be really difficult after this refactor has been merged.

**Comment by RyanSiu1995** [comment]
Never mind, I just directly refactor the v3 code instead of master.
Let me assume the master branch as a legacy code.

**Comment by mikefarah** [comment]
Thanks @RyanSiu1995 :)
