### ISSUE TITLE
input_filename is always <stdin>

### ISSUE THREAD

**Issue by qistoph** [mikefarah/yq#325]
I would expect `input_filename` to work like it does in jq, with yq however it always outputs `<stdin>`.

Actual result:
```
$ yq 'input_filename' */problem.yaml
"<stdin>"
"<stdin>"
"<stdin>"
"<stdin>"
"<stdin>"
"<stdin>"
```

Expected result:
```
$ yq 'input_filename' */problem.yaml
"project_alpha/problem.yaml"
"project_zero/problem.yaml"
"questions/problem.yaml"
"research/problem.yaml"
"stuff/problem.yaml"
"test/problem.yaml"
```

**Comment by mikefarah** [comment]
Sorry it does not work like that  - not sure what you are trying to do, make sure you take a look at the docs (http://mikefarah.github.io/yq/)

**Comment by qistoph** [comment]
Sorry, I ended up posting this issue in completely the wrong repo. I should've post at https://github.com/kislyuk/yq. Sorry for any trouble.

**Comment by stagnation** [comment]
I would like to have the `input_filename` work as well.
