### ISSUE TITLE
RFC 6902 compatibility

### ISSUE THREAD

**Issue by dobesv** [mikefarah/yq#327]
I noticed you are switching to a new script format that is very similar to [RFC 6902 - JSON Patch](https://tools.ietf.org/html/rfc6902)

The main incompatibility seems to be the use of `op` instead of `command` and slight differences in the name of the commands/ops (`replace` vs `update`)

I wonder if it would make sense to either (1) adopt that format as-is or (2) support it as an alternative

Not to say that RFC 6902 is some kind of famous standard with wide-spread adoption, but it is used in `kustomize` which is fairly popular for kubernetes users.  If `yq` supported the same patch format then `kustomize` users could use `yq` to run an RFC 6902 patch as a way to preview its effects.

If you adopted it as a standard you could potentially publish your own RFC - YAML Patch.

**Comment by mikefarah** [comment]
Neat - never knew that existed. Changing to 'op' is a simple thing to do - the main complexity is that their path format is different to mine, with forward slashes instead of dot notation. 

Hmmm

**Comment by mikefarah** [comment]
I've opted to use `jq` like syntax instead in the latest v4 release.
