### ISSUE TITLE
Version 3 has different handling of double quoted values

### ISSUE THREAD

**Issue by dobesv** [mikefarah/yq#329]
In https://github.com/mikefarah/yq/issues/107#issuecomment-575660454 @hassbert points out that the version 3 of `yq` handles double-quoted values differently from the currently released version.

In the currently released version if you pass in a value with double quotes around it, it takes the characters between the quotes as a string.  In version 3 it is treating the entire value, including the double quotes, as a string.

It might be nice if `yq` were backwards compatible in this regard.

On the other hand, the double-quotes are kind of a hack, and are handled inconsistently from single quotes (which are not removed in either version).  It might be nice to adopt a new, more consistent and elegant approach to handling input values.

Two such approaches come to mind:

1. Always parse values as a string (no quote removal), unless a special option is provided that says the value should be parsed as yaml text.  e.g. `yq n b -y true` --> `b: true` and `yq n b true` --> `b: "true"`
2. Always parse values as yaml text, unless a special option is provided that says the value should be always considered a string, e.g. `yq n b true` --> `b: true` and `yq n b -s true` --> `b: "true"`

See also https://github.com/mikefarah/yq/issues/107

**Comment by mikefarah** [comment]
Yep - I've written up some docs on this for v3 - although reading this makes me realise I should also put it in breaking changes.

https://mikefarah.gitbook.io/yq/usage/value-parsing

**Comment by mikefarah** [comment]
Updated breaking changes:
https://mikefarah.gitbook.io/yq/upgrading-from-v2#parsing-values-from-the-cli

**Comment by dobesv** [comment]
I think your solution with the `--tag` solves this nicely.
