### ISSUE TITLE
Tabulator is valid json.

### ISSUE THREAD

**Issue by poelzi** [mikefarah/yq#330]
currently yq fails when converting json to yaml if \t is part of an object.
yq -y legacy.json > better.yaml
`
yq: Error running jq: ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "legacy.json", line 16, column 1.
`

\t should be treated like space in json.

**Comment by mikefarah** [comment]
Wrong yq sorry - my yq handles tabs fine :D (as far as I can tell).

Looks like this is for https://github.com/kislyuk/yq
