### ISSUE TITLE
Print default value when reading and there are no matches

### ISSUE THREAD

**Issue by yannickdenimal** [mikefarah/yq#331]
yq r undefined_variables file

in V2: return 'null'

in V3: return empty

should be documented as breaking 

should be nice to have default value or to document this feature

**Comment by mikefarah** [comment]
Good pick up, updated the docs:
https://github.com/mikefarah/yq/releases/tag/3.0.0-beta

I'll make sure to include it in the user docs I'm writing up too.

**Comment by yannickdenimal** [comment]
is there a default value for non existing in yq read?

**Comment by mikefarah** [comment]
Not at this stage, makes sense as a feature I think.

Till then you could use a couple of bash lines to do it

```bash
x=$(yq r examples/sample.yaml frog)
[[ ! -z "$x" ]] && echo $x || echo "default value"
```

**Comment by mikefarah** [comment]
Done! check out the latest release https://github.com/mikefarah/yq/releases/tag/3.1.0 and doc https://mikefarah.gitbook.io/yq/commands/read#default-values
