### ISSUE TITLE
V3 merge error

### ISSUE THREAD

**Issue by yannickdenimal** [mikefarah/yq#332]
yq merge "${FILES[@]}" > ${temp_helm}/values-merged.yaml

when FILES contains 3 yaml files:
 helm/xxxx/dev/values.yaml
 helm/xxxx/values.yaml
 .tmp/helm/values.yaml

fatal error: runtime: out of memory
 runtime stack:
 runtime.throw(0x650139, 0x16)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/panic.go:774 +0x72
 runtime.sysMap(0xc0bc000000, 0x4000000, 0x819f18)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/mem_linux.go:169 +0xc5
 runtime.(*mheap).sysAlloc(0x802780, 0x2000, 0x2000, 0xc00005ded8)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/malloc.go:701 +0x1cd
 runtime.(*mheap).grow(0x802780, 0x1, 0xffffffff)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/mheap.go:1255 +0xa3
 runtime.(*mheap).allocSpanLocked(0x802780, 0x1, 0x819f28, 0x7fedaee64e60)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/mheap.go:1170 +0x266
 runtime.(*mheap).alloc_m(0x802780, 0x1, 0x450004, 0x7fedaee64e60)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/mheap.go:1022 +0xc2
 runtime.(*mheap).alloc.func1()
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/mheap.go:1093 +0x4c
 runtime.systemstack(0x0)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/asm_amd64.s:370 +0x66
 runtime.mstart()
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/proc.go:1146
 goroutine 1 [running]:
 runtime.systemstack_switch()
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/asm_amd64.s:330 fp=0xc0001364e8 sp=0xc0001364e0 pc=0x455200
 runtime.(*mheap).alloc(0x802780, 0x1, 0x20302f00010004, 0x0)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/mheap.go:1092 +0x8a fp=0xc000136538 sp=0xc0001364e8 pc=0x42531a
 runtime.(*mcentral).grow(0x802c38, 0x0)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/mcentral.go:255 +0x7b fp=0xc000136578 sp=0xc000136538 pc=0x41726b
 runtime.(*mcentral).cacheSpan(0x802c38, 0x20302e)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/mcentral.go:106 +0x2fe fp=0xc0001365d8 sp=0xc000136578 pc=0x416d8e
 runtime.(*mcache).refill(0x7fedbb973008, 0x204)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/mcache.go:138 +0x85 fp=0xc0001365f8 sp=0xc0001365d8 pc=0x416835
 runtime.(*mcache).nextFree(0x7fedbb973008, 0x4, 0x18, 0x605ec0, 0x20302e)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/malloc.go:854 +0x87 fp=0xc000136630 sp=0xc0001365f8 pc=0x40b617
 runtime.mallocgc(0x10, 0x5fd1c0, 0x1, 0xc0bbff92c0)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/malloc.go:1022 +0x793 fp=0xc0001366d0 sp=0xc000136630 pc=0x40bf53
 runtime.newobject(0x5fd1c0, 0x0)
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/malloc.go:1151 +0x38 fp=0xc000136700 sp=0xc0001366d0 pc=0x40c348
 github.com/mikefarah/yq/v3/pkg/yqlib.guessKind(0xc0003aab6d, 0x8, 0xc0003c04f0, 0x0, 0x1, 0xc000000000, 0x8)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/lib.go:65 +0x6f fp=0xc000136768 sp=0xc000136700 pc=0x56e34f
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseArray(0xc0003d3e50, 0xc0003cbae0, 0xc0003aab6d, 0x8, 0xc0003c04f0, 0x0, 0x1, 0xc0003d6540, 0x2, 0x2, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:239 +0xe9 fp=0xc000136838 sp=0xc000136768 pc=0x56c149
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurse(0xc0003d3e50, 0xc0003cbae0, 0xc0003aab6d, 0x8, 0xc0003c04f0, 0x0, 0x1, 0xc0003d6540, 0x2, 0x2, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:77 +0x871 fp=0xc000136960 sp=0xc000136838 pc=0x56a141
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).doTraverse(0xc0003d3e50, 0xc0003cbae0, 0xc0003aab65, 0x7, 0xc0003c04e0, 0x1, 0x2, 0xc0003d6540, 0x2, 0x2, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:51 +0x2b1 fp=0xc000136aa0 sp=0xc000136960 pc=0x5692e1
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseMap(0xc0003d3e50, 0xc0003cb860, 0xc0003aab65, 0x7, 0xc0003c04e0, 0x1, 0x2, 0xc0003d8370, 0x1, 0x1, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:128 +0x4b3 fp=0xc000136c40 sp=0xc000136aa0 pc=0x56a723
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurse(0xc0003d3e50, 0xc0003cb860, 0xc0003aab65, 0x7, 0xc0003c04e0, 0x1, 0x2, 0xc0003d8370, 0x1, 0x1, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:69 +0x628 fp=0xc000136d68 sp=0xc000136c40 pc=0x569ef8
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).doTraverse(0xc0003d3e50, 0xc0003cb860, 0xc0003aab60, 0x4, 0xc0003c04d0, 0x2, 0x3, 0xc0003d8370, 0x1, 0x1, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:51 +0x2b1 fp=0xc000136ea8 sp=0xc000136d68 pc=0x5692e1
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseMap.func1(0xc0000d0b00, 0x10, 0x10, 0xe, 0xc0003d46c0, 0x3)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:105 +0x762 fp=0xc000137060 sp=0xc000136ea8 pc=0x571d62
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).visitDirectMatchingEntries(0xc0003d3e50, 0xc00013d400, 0xc0003aab60, 0x4, 0xc0003c04d0, 0x2, 0x3, 0xc0001376b0, 0x0, 0x0, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:141 +0x1fd fp=0xc0001370f0 sp=0xc000137060 pc=0x56ae7d
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).visitMatchingEntries(0xc0003d3e50, 0xc00013d400, 0xc0003aab60, 0x4, 0xc0003c04d0, 0x2, 0x3, 0xc0001376b0, 0x0, 0x0, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:157 +0x1ba fp=0xc000137248 sp=0xc0001370f0 pc=0x56b0ea
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurseMap(0xc0003d3e50, 0xc00013d400, 0xc0003aab60, 0x4, 0xc0003c04d0, 0x2, 0x3, 0xc0001376b0, 0x0, 0x0, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:93 +0x158 fp=0xc0001373e8 sp=0xc000137248 pc=0x56a3c8
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).recurse(0xc0003d3e50, 0xc00013d400, 0xc0003aab60, 0x4, 0xc0003c04d0, 0x2, 0x3, 0xc0001376b0, 0x0, 0x0, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:69 +0x628 fp=0xc000137510 sp=0xc0001373e8 pc=0x569ef8
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).doTraverse(0xc0003d3e50, 0xc00013d400, 0x0, 0x0, 0xc0003c04c0, 0x3, 0x4, 0xc0001376b0, 0x0, 0x0, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:51 +0x2b1 fp=0xc000137650 sp=0xc000137510 pc=0x5692e1
 github.com/mikefarah/yq/v3/pkg/yqlib.(*navigator).Traverse(0xc0003d3e50, 0xc00013d2c0, 0xc0003c04c0, 0x3, 0x4, 0x0, 0x1)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/data_navigator.go:29 +0xd8 fp=0xc0001376c0 sp=0xc000137650 pc=0x568f78
 github.com/mikefarah/yq/v3/pkg/yqlib.(*lib).Update(0xc00008a7e0, 0xc00013d2c0, 0x64c0be, 0x6, 0xc0003aab60, 0x15, 0xc00012b040, 0x0, 0x1, 0x0, ...)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/pkg/yqlib/lib.go:138 +0x31c fp=0xc000137790 sp=0xc0001376c0 pc=0x56ee8c
 main.updateDoc.func1(0xc00013d2c0, 0x0, 0xc00013d2c0, 0x0)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/yq.go:552 +0x281 fp=0xc000137890 sp=0xc000137790 pc=0x5d4331
 main.mapYamlDecoder.func1(0xc0003ae2a0, 0xc0003ae2a0, 0x600)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/yq.go:426 +0x1c9 fp=0xc000137990 sp=0xc000137890 pc=0x5d3b69
 main.readStream(0x7ffcd45c3324, 0x19, 0xc00024a940, 0x0, 0x0)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/yq.go:710 +0x256 fp=0xc000137ab0 sp=0xc000137990 pc=0x5d2e96
 main.readAndUpdate(0x696e20, 0xc0000b0008, 0x7ffcd45c3324, 0x19, 0xc00017d1d0, 0x0, 0x0)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/yq.go:601 +0x298 fp=0xc000137bd8 sp=0xc000137ab0 pc=0x5d1378
 main.updateDoc(0x7ffcd45c3324, 0x19, 0xc0003ba000, 0x41, 0x80, 0x696e20, 0xc0000b0008, 0x80, 0x40)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/yq.go:560 +0xd6 fp=0xc000137c30 sp=0xc000137bd8 pc=0x5d1076
 main.mergeProperties(0xc0000c5900, 0xc00008d170, 0x3, 0x3, 0x0, 0x0)
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/yq.go:468 +0x431 fp=0xc000137d60 sp=0xc000137c30 pc=0x5cfe81
 github.com/spf13/cobra.(*Command).execute(0xc0000c5900, 0xc00008d050, 0x3, 0x3, 0xc0000c5900, 0xc00008d050)
 	/Users/mikefarah/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460 fp=0xc000137e38 sp=0xc000137d60 pc=0x5c1c50
 github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c4a00, 0x4055ff, 0xc000088058, 0x0)
 	/Users/mikefarah/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb fp=0xc000137f10 sp=0xc000137e38 pc=0x5c269b
 github.com/spf13/cobra.(*Command).Execute(...)
 	/Users/mikefarah/dev/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
 main.main()
 	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq-v3/yq.go:39 +0x2b fp=0xc000137f60 sp=0xc000137f10 pc=0x5ccb7b
 runtime.main()
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/proc.go:203 +0x21e fp=0xc000137fe0 sp=0xc000137f60 pc=0x42ea6e
 runtime.goexit()
 	/usr/local/Cellar/go/1.13.3/libexec/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc000137fe8 sp=0xc000137fe0 pc=0x457151

**Comment by mikefarah** [comment]
I can't replicate this when merging 3 yaml files.
Are you able to provide '--verbose' output, and, even better, the files you are trying to merge?

**Comment by yannickdenimal** [comment]
i have replicate the bug with:
yq merge helm/frlm/dev/values.yaml helm/frlm/values.yaml helm/values.yaml

the last output:
team:
  name: ce-cicd
  members:
  -
  -
  -
  -
  -
  -
  -
  -
  -
  -


the last file contains:
team:
  name: ce-cicd
  members:
    001: "toto"
    002: "titi"

and can send you the 3 files in private

**Comment by mikefarah** [comment]
Yeah that didn't come out very well, I still can't replicate it sorry. You'll either need to craft a simple example that similarly fails and you can share - or send me the files privately...

**Comment by mikefarah** [comment]
Closing issue until I get more info. Newer versions may have fixed this issue..
