### ISSUE TITLE
Search by child nodes does not work

### ISSUE THREAD

**Issue by nicholasdille** [mikefarah/yq#335]
When following the documentation for path expressions the example in the section [search by children nodes](https://mikefarah.gitbook.io/yq/usage/path-expressions#search-by-children-nodes) does not work.

# Sample data

`sample.yml`:

```yaml
a:
  - b:
      c: thing0
      d: leopard
    ba: fast
  - b:
      c: thing1 # MATCHES
      d: cat
    ba: meowy
  - b:
      c: thing2
      d: caterpillar
    ba: icky
  - b:
      c: thing3 # MATCHES
      d: cat
    ba: also meowy
```

# Steps to reproduce

```bash
$ yq r sample.yaml 'a.(b.d==cat).b.c'
Error: Error reading path in document index 0: Error parsing array index '(b' for 'a': strconv.ParseInt: parsing "(b": invalid syntax

# Details

```bash
$ yq --version
yq version 3.0.0-beta
```

**Comment by mikefarah** [comment]
Oh right - I need to make a new release of v3 for that feature :embarrassed-face:

I'll get onto it soon

**Comment by nicholasdille** [comment]
The example works in 3.0.1 and my use case also works. Thanks for the quick response!
