### ISSUE TITLE
Deletion of non existing key results in addition

### ISSUE THREAD

**Issue by 030** [mikefarah/yq#338]
yq version: yq version 3.0.1

aaa.yml

```
a: 1
```

**Expected outcome**

```
yq d -i aaa.yml 'c.d'
```

should result in:

```
a: 1
```

**Actual outcome:**

```
a: 1
c:
```

**Comment by mikefarah** [comment]
Good pick up - will fix in the next release

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.1.0 :)
