### ISSUE TITLE
Anchor dereferencing fails with yq 3.0.1

### ISSUE THREAD

**Issue by jodh-intel** [mikefarah/yq#340]
Assuming the following test file:

```sh
$ cat >foo.yaml<<EOT
value: &value-pointer the value
pointer: *value-pointer
EOT
```

With previous versions of `yq`, we'd see the expected behaviour:

```sh
$ yq r foo.yaml value
the value
$ yq r foo.yaml pointer
the value
```

However, with `yq` version 3.0.1:

```sh
$ yq r foo.yaml value
the value
$ yq r foo.yaml pointer
*value-pointer
```

Oddly, this works in JSON mode:

```sh
$ yq -j r foo.yaml pointer
"the value"
```

Sounds like this is related to #339.

**Comment by mikefarah** [comment]
Nice pick up - will have a fix in the next release

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.1.0 see https://mikefarah.gitbook.io/yq/commands/read#exploding-anchors :)

**Comment by jodh-intel** [comment]
Thanks @mikefarah ! :smile:
