### ISSUE TITLE
Casting yes/no to string does not produce a string value

### ISSUE THREAD

**Issue by dsharp-pivotal** [mikefarah/yq#341]
"yes" and "no" are boolean values in yaml when unquoted. If these strings are left unquoted by yq, then it's not possible to create the values "yes" and "no" as strings.

Here's the (large!) list of values that YAML treats as booleans:
https://yaml.org/type/bool.html
>  y|Y|yes|Yes|YES|n|N|no|No|NO
> |true|True|TRUE|false|False|FALSE
> |on|On|ON|off|Off|OFF

### Actual

Taken from [the doc on casting booleans](https://mikefarah.gitbook.io/yq/usage/value-parsing#casting-booleans), but replace "true" with "yes":

```
$ yq new --tag '!!str' key yes
key: yes
```

### Expected
```
yq new --tag '!!str' key yes
key: "yes"
```

**Comment by mikefarah** [comment]
I was reading up on yaml - the 1.1 spec allowed for those values - however that had a whole bunch of issues in different applications so in the 1.2 spec the dropped back to just true/false (https://yaml.org/spec/1.2/spec.html#id2803629, https://github.com/go-yaml/yaml/issues/214)

**Comment by mikefarah** [comment]
For the record, v3.x of yq uses the v3 yaml parser, so this applies https://github.com/go-yaml/yaml/tree/v3#compatibility

**Comment by dsharp-pivotal** [comment]
I see. Good to know. However, it seems that since there are still many apps that consume YAML 1.1 booleans (Kubernetes included, it seems, as that is the consumer in our case), the most compatible thing to do would be to output "yes", "no", etc with quotes when it is requested that they be strings (`--tag "!!str"`). That would work correctly for both 1.1 and 1.2 parsers.

**Comment by mikefarah** [comment]
yeah good idea - I'll put in a special condition for --tag '!!str' to force quotes around values.

**Comment by dsharp-pivotal** [comment]
@mikefarah I just made a PR to go-yaml. If accepted, I think you may not need to add a condition.

https://github.com/go-yaml/yaml/pull/574

**Comment by mikefarah** [comment]
I think this will have a workaround in the upcoming --style flag, whereby you can force a double or single quotes with the tag flag.

**Comment by dsharp-pivotal** [comment]
I tested it with yq 3.3.0, and that'll work for us. Thanks!

```
$ yq new --style double key yes
key: "yes"
```
