### ISSUE TITLE
Yaml merge splits keys containing dots

### ISSUE THREAD

**Issue by gisql** [mikefarah/yq#345]
Example:

```
$ cat a.yaml 
test:
  a.b.c:
    foo: bar
$ cat b.yaml 
test:
  a.b.c:
    boo: goo
$ yq merge a.yaml b.yaml
test:
  a.b.c:
    foo: bar
  a:
    b:
      c:
        boo: boo
```

Just to be clear, the expected output is (which is what used to happen for version 2.xx):
```
test:
  a.b.c:
    boo: boo
    foo: bar
```

I tried quoting the `"a.b.c"` in the `b.yaml` --- the same.  It's clearly a bug: even if, for whatever reason, `yq` should split keys on dots, this should happen for both the `a.yaml` and the `b.yaml`.

**Comment by mikefarah** [comment]
Can confirm it's a bug - luckily this PR https://github.com/mikefarah/yq/pull/342 by @coryrc fixed it! Will be out in the next release

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.1.0 :)
