### ISSUE TITLE
Array values get split into separate keys when using merge in append mode.

### ISSUE THREAD

**Issue by d0x2f** [mikefarah/yq#346]
Minimal example:

foo.yml:
```
people:
  - name: Barry
    age: 21
```

bar.yml:
```
people:
  - name: Roger
    age: 44
```

output of `yq m -a foo.yml bar.yml`:
```
people:
- name: Barry
  age: 21
- name: Roger
- age: 44
```

output of `yq m -a bar.yml foo.yml`:
```
people:
- name: Roger
  age: 44
- name: Barry
- age: 21
```

See how the array element from the second file gets split into two.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.1.1 :)

**Comment by belalgalal** [comment]
Still exists with version 3.1.1

**Comment by mikefarah** [comment]
I can't replicate it in the latest version....

```
yq m -a examples/data1.yaml examples/data2.yaml
```

results in

```yaml
people:
- name: Barry
  age: 21
- name: Roger
  age: 44
```
