### ISSUE TITLE
Merge option returns different output when switching order of merging files

### ISSUE THREAD

**Issue by codbfilip** [mikefarah/yq#347]
yq version 3.1.0

When I merge two files with append option i got two different results based on order of files.

Input files:

first.yml

    volumes:
      app: {}
      app-cache:
        driver_opts:
          type: none

second.yml
 
     volumes:
          backups:
            driver_opts:
              type: none

Command: `yq m -a first.yml second.yml > output.yml` (returns correct output)

    volumes:
      app: {}
      app-cache:
        driver_opts:
          type: none
      backups:
        driver_opts:
          type: none

Command: `yq m -a second.yml first.yml > output.yml`

    volumes:
      backups:
        driver_opts:
          type: none
      app-cache:
        driver_opts:
          type: none

Expected result: the output should contain all keys regardless of the order of the files

**Comment by mikefarah** [comment]
Looks like ``app`` gets skipped because its ``{}``. Interestingly it works if its ``null`` or empty...

**Comment by mikefarah** [comment]
Related to https://github.com/mikefarah/yq/issues/355

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.1.2
