### ISSUE TITLE
yq w should optionally accept file instead of scalar

### ISSUE THREAD

**Issue by coryrc** [mikefarah/yq#350]
I implemented this behavior with a script:

```bash
yq p "${yaml_name}" '[0].value' | yq w - '[0].command' update | yq w - '[0].path' "${path}"
```

If you like it, I could probably write the code in two weeks.

**Comment by mikefarah** [comment]
Cool idea - pretty straight forward to implement too, will be out in the next release :)

**Comment by mikefarah** [comment]
Added in https://github.com/mikefarah/yq/releases/tag/3.1.1 :)
