### ISSUE TITLE
yq compare exit code depending of comparison

### ISSUE THREAD

**Issue by Perdjesk** [mikefarah/yq#360]
When using yq to compare file it would be useful to get a different exit code whether the files compared are the same or not.

From diff manpage (http://man7.org/linux/man-pages/man1/diff.1.html)
> Exit status is 0 if inputs are the same, 1 if different, 2 if trouble.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.2.0
