### ISSUE TITLE
keys unquoted during merge

### ISSUE THREAD

**Issue by hobti01** [mikefarah/yq#363]
With yq 3.1.1 we're noticing a change in behavior from yq v2.  It's unexpected that the quoted key is parsed into an array.

```
$ rm -rf out.yaml ; touch out.yaml 
$ echo "'key[bracket]': value" > in.yaml
$ cat in.yaml 
'key[bracket]': value
$ yq merge -i out.yaml in.yaml
$ cat out.yaml 
key:
  bracket: value
```

we expect the behavior of yq v2
```
$ echo 'cannot: merge-empty' > out.yaml
$ echo "'key[bracket]': value" > in.yaml
$ cat in.yaml 
'key[bracket]': value
$ yq merge -i out.yaml in.yaml
$ cat out.yaml
cannot: merge-empty
'key[bracket]': value
```

How can we accomplish this in yq v3?

Similar to https://github.com/mikefarah/yq/issues/345 but for brackets.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.1.2
