### ISSUE TITLE
In-place update of the value 

### ISSUE THREAD

**Issue by koskinep** [mikefarah/yq#365]
Hi,

Using yq 2.10.0 (latest from the pip installation) and trying to update values in my yaml file:

´yq w -i values.yaml foo.deploy true´ as told here: https://mikefarah.gitbook.io/yq/v/v2.x/write-update

Gives me an error: ´yq: -i/--in-place can only be used with -y/-Y´

When using ´yq w -yi values.yaml foo.deploy true´

Gives ´yq: -i/--in-place can only be used with filename arguments, not on standard input´

What is a filename argument and how do I use it?

**Comment by mikefarah** [comment]
Hey - can you try with the latest 2.x version, 2.4.1.

Tried that version with docker (mikefarah/yq:2) and the example works for me...

**Comment by koskinep** [comment]
Hi,

Thanks for the reply! So, which one is is later: 2.10.0 from pip or 2.4.1 with docker? Sorry forgot to write the whole version in my original question.

**Comment by mikefarah** [comment]
Ah I don't have a 2.10 in pip - this must be https://github.com/kislyuk/yq

**Comment by mabushey** [comment]
Anyone know how to do this with yq V4? These yq versions are a nightmare that usually makes me just use sed; there's not 50 different versions to dilute the knowledge pool into fog.

**Comment by Jayashree138** [comment]
I am facing the same issue, first gives error :  `yq: -i/--in-place can only be used with -y/-Y` then, `yq: -i/--in-place can only be used with filename arguments, not on standard input` with yq V4, could someone please help with this issue.
