### ISSUE TITLE
How to uninstall the yq from ubuntu 18.04 

### ISSUE THREAD

**Issue by abhisamant7** [mikefarah/yq#369]
Hi Team,

I want to remove the yq from my sytem which is ubuntu 18.04. 
I found everywhere however could not getting it.

Please assist me on above request if you have any soluntion

Thanks 
Abhijeet

**Comment by mikefarah** [comment]
This is kind of out of scope for this project - it would depend on how you installed it (download a binary vs package manager).

If you downloaded a binary - then obviously it's straight forward. If it's via a package manager then you would need to use their own uninstall mechanism (e.g. snap remove)
