### ISSUE TITLE
go modules support

### ISSUE THREAD

**Issue by 030** [mikefarah/yq#371]
I would like to contribute and I would like to see that go modules is supported.

**Comment by mikefarah** [comment]
Cool - I thought it was working tbh...very confused by go modules

**Comment by 030** [comment]
@mikefarah I just checked the repository again and I saw that there is a go.mod and go.sum. After running `go mod tidy` a couple of changes were applied.

**Comment by 030** [comment]
@mikefarah I see that the CI is broken for a while?

**Comment by mikefarah** [comment]
Ah Travis CI passes - in the middle of attempting to port across to github workflow...

**Comment by mikefarah** [comment]
Should be working now - may need to rebase from master
