### ISSUE TITLE
Print properties in the top of structure and more than one selection in the deep

### ISSUE THREAD

**Issue by aguytech** [mikefarah/yq#380]
**I need to print properties in the top of structure and select properties in the deep, so is that why I search a solution with loops**
I precise that properties not in the continuous flow but in branches:
  / b - d:cat
a - e - f - g:bird
   \ p (pint)

I don't know if its a request of feature or I miss understand the documentation...

It seems to me that the only way to select value is inside a loop (I tried other ways):
`a.(b.d==cat).b.c`

I found the way to have a condition in two loops if structure permit it:
`(a.b.mtu==1500).a.b.c.addresses.(family==inet)`
but only in sequential mode: 'top -> deep'

Is there a way to have more than one condition in the loop ? something like that:
`a.((b.d==cat)e.f.g==bird).p`
or
`a.(b.d==cat and e.f.g==bird).p`

**Comment by mikefarah** [comment]
Sorry I don't understand that sample you have at the top and what you are trying to do. Could you please provide the input yaml in a markdown block format to make sure it prints properly?

currently it doesn not support multiple conditions in the path expression segment...would be neat though

**Comment by aguytech** [comment]
Ok thanks for your answer
I have append an export of 'lxc list' wich I work on it with yq
[lxc-list.yaml.tar.gz](https://github.com/mikefarah/yq/files/4283579/lxc-list.yaml.tar.gz)


1. I can find for all containers the ip for 'inet' interface with:
`yq r /tmp/lxc-list.yaml '.state.network.*.addresses(family==inet).address'`
2. The name of containers :
`yq r /tmp/lxc-list.yaml '.name'`

Then here is an example of my problem:
3. I want to have the name of containers which have an 'inet' interface
something like that:
`yq r /tmp/lxc-list.yaml '(state.network.*.addresses(family==inet).address).name'`

But the name is higher in the tree than my selection on family, I can not rewind the selection 'state.network.*.addresses(family==inet).address' to the first node to select after the name. Unlike example 1. where I 'go down' in the tree

Another example of the missing of double conditions of selection:
**I want to have the name of containers which used the profile 'stock' ??**
- to print the used profiles:
`yq r /tmp/lxc-list.yaml '.profiles(.==stock)'`

May be use something like that:
`yq r /tmp/lxc-list.yaml '(profiles(.==stock)).name'`

Like to get the name of running containers:
yq r /tmp/lxc-list.yaml '(status==Running).name'

I hope I'm enough clear in my explanations ?

Good luck for your hard work ;o)

**Comment by mikefarah** [comment]
For the first example:
```
yq r /lxc-list.yaml '(state.network.*.addresses.*.family==inet).name'
```

**Comment by mikefarah** [comment]
You should be able to follow the same pattern, put the deep path in the `()` then you can continue to work from the level you were at before the brackets...

**Comment by aguytech** [comment]
Ok thanks, I understood that it's for why my first example was this tree:
`a.((b.d==cat)e.f.g==bird).p`
for
```
  / b - d:cat
- a - e - f - g:bird
  \ p (pint)
```
More than one condition in the deep of tree

Thanks for your advices !

**Comment by mikefarah** [comment]
I see - yep I don't have that feature yet, but you should be able to do it by filtering the yaml twice.

```
yq r lxc-list.yaml (expression1) | yq r - (expression2)
```

**Comment by aguytech** [comment]
Yes it helps in many cases but unfortunately not in all cases.

For my case of LXC containers, if I want the name of container with a specified profile.
yq syntax to select a string in the list:
`.profiles(.==myitem)`
do not allows to stay in the top of the tree, it returns items in selected level.
I can not access to the name which is in the same level than the profile (list of string)

**Comment by mikefarah** [comment]
Cool - makes sense. I'll get to this when I have time, quite busy atm

**Comment by mikefarah** [comment]
This is now possible in v4 of yq, which uses jq like syntax :)
