### ISSUE TITLE
yq doesn't remove the quote anymore

### ISSUE THREAD

**Issue by tsao-chi** [mikefarah/yq#381]
**Describe the bug**
yq doesn't remove the quote anymore

**Input Yaml**
a.yml:
```yaml
a: 'a'
```

**Command**
The command you ran:
```
yq r a.yml a
```

**Actual behavior**

3.2.0
```
'a'
```

**Expected behavior**

3.1.2
```
a
```

**Comment by nemchik** [comment]
I can confirm this issue with 3.2.0, and it also does it with double quotes. 3.1.2 works as expected.

**Comment by mikefarah** [comment]
Oops - will have a fix out shortly

**Comment by analytically** [comment]
Breaks for us too.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.2.1

**Comment by nemchik** [comment]
Confirmed. 3.2.1 fixed it for me.
