### ISSUE TITLE
Regression: Version 3+ Doesn't Parse "Null" keywords correctly

### ISSUE THREAD

**Issue by apeschel** [mikefarah/yq#388]
**Describe the bug**

Since version 3, yq seems to handle YAML null keywords as strings rather than as null values. This causes problems when using anything other than the literal keyword `null`.

The list of null keywords that no longer work with the version 3 release include the following:

- `~`
- `Null`
- `NULL`

Using any of these keywords causes the corresponding json output to be invalid, which breaks any json conversion using these keywords.

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
```yaml
~
```

data2.yml:
```yaml
Null
```

**Command**
The command you ran:
```
$ echo "~" | yq r -j -
```

**Actual behavior**

```yaml
~
```
Above is invalid json.

**Expected behavior**

```yaml
null
```
Above is valid json.

**Additional context**

This is a new issue since the 3.0.1 release. This bug does not exist in the 2.4.1 release, which handled all null keywords correctly.

**Comment by mikefarah** [comment]
Replicated, will fix in next version

**Comment by apeschel** [comment]
@mikefarah Appreciated, thank you!
