### ISSUE TITLE
Yaml stream identity operation?

### ISSUE THREAD

**Issue by derrickburns** [mikefarah/yq#391]
Is there a way to read a YAML stream, pretty print it, and output it as a YAML stream?

```
yq r -d* foo.yaml 
```

strips the document separators.

**Comment by mikefarah** [comment]
not sure what you mean by yaml stream?

**Comment by derrickburns** [comment]
Hi @mikefarah, I mean  a document list this:
```
---
foo: bar
---
doc: second
+++
```

**Comment by derrickburns** [comment]
If the document above were given as input in `x.yaml`, then I would expect that this would be idempotent:

```
yq r -d'*' x.yaml
```
However it produces:
```
foo: bar
doc: second
```

**Comment by mikefarah** [comment]
Ah I see, makes sense. No there isn't one for multi-doc atm

**Comment by aeneasr** [comment]
Is there a known workaround for this?
