### ISSUE TITLE
yq 3.2.1 does not quote strings when using `read --tojson`

### ISSUE THREAD

**Issue by orirawlings** [mikefarah/yq#392]
I expect `--tojson` to output quoted strings as earlier version of `yq` used to. This allows the output to be passed into another tool like `jq` for further parsing/processing.

```
$ echo 'name: orirawlings' | yq2.4.0 read - name --tojson
"orirawlings"
$ echo 'name: orirawlings' | yq3.2.1 read - name --tojson
orirawlings
```

I also have the same problems for strings that kind of look like numerics, but aren't:
```
$ echo 'version: 1.2.3' | yq2.4.0 read - version --tojson
"1.2.3"
$ echo 'version: 1.2.3' | yq3.2.1 read - version --tojson
1.2.3
```

**Comment by mikefarah** [comment]
yeah that was purposefully done so that it's easier to use yq on its own with other tools like xargs and what not. 

If needed, you can still wrap the values by doing something like:

```
echo "Mike" | echo "\"$(cat)\""
```

**Comment by orirawlings** [comment]
I understand how this can be intentional for normal usage, but it doesn't make sense when I've explicitly asked the tool to output valid JSON with `--tojson`.

The work-around you propose isn't feasible in all situations. In some situations, we don't know for sure if the value coming out of the YAML at the query location is a string or some more complicated structure, we just want that value to be converted to the equivalent JSON no matter what it might be.

For example, here is a use case that I have where a version number might be specified with increasing levels of granularity based on environment and region. I don't know ahead of time which type yq will be outputting.

```
#! /bin/bash

cat <<EOF | yq3.2.1 read - --tojson version | jq -r '(.prod? | .["us-west-2"]?, .), . | select(type=="string")'
version: 1.2.3
EOF

cat <<EOF | yq3.2.1 read - --tojson version | jq -r '(.prod? | .["us-west-2"]?, .), . | select(type=="string")'
version:
  prod: 1.2.3
EOF

cat <<EOF | yq3.2.1 read - --tojson version | jq -r '(.prod? | .["us-west-2"]?, .), . | select(type=="string")'
version:
  prod:
    us-west-2: 1.2.3
EOF
```
Expected output:
```
1.2.3
1.2.3
1.2.3
```
Actual output:
```
parse error: Invalid numeric literal at line 2, column 0
1.2.3
1.2.3
```
In the first case, invalid JSON is output so `jq` can not parse it successfully.

**Comment by mikefarah** [comment]
I see. Thinking hat on. Perhaps I need a flag for outputting scalar values in yaml/json depending on the output format. 

Hardest bit is to come up with a name.
--raw ?

**Comment by orirawlings** [comment]
I think you already have a name `--tojson` is already suitable. I think the reasonable expectation for any user would be that in all scenarios `--tojson` only outputs a sequence of bytes that are parsable as JSON. If that means there needs to be special paths in the code for scalar values when `--tojson` is specified, it should be done.

**Comment by mikefarah** [comment]
I'm going to go with `--unwrapScalars=false`. This will use the JSON/YAML encoder to print the value node.

In JSON this will quote strings if it's a string. 

In YAML it will print quotes if there are any in the original document, as well as any comments on the node.
