### ISSUE TITLE
Support ARM docker images through manifests

### ISSUE THREAD

**Issue by NickBusey** [mikefarah/yq#395]
**Is your feature request related to a problem? Please describe.**

You can't run this via docker on a raspberry pi. You get `standard_init_linux.go:211: exec user process caused "exec format error"`

**Describe the solution you'd like**

Creating a manifest file and using properly tagged images will allow users to deploy across architecture types with no changes needed on their end. More info: https://developer.ibm.com/linuxonpower/2017/07/27/create-multi-architecture-docker-image/

**Describe alternatives you've considered**

To simplify things we could not create a manifest and simply create a tagged :arm version that would work on raspberry pi's and other ARM platforms.

**Additional context**

I see this old issue https://github.com/mikefarah/yq/issues/146 from last year, I would be willing to submit a PR to fix this if @mikefarah would like this issue fixed.

**Comment by mikefarah** [comment]
Interesting - I thought the whole point of docker was to abstract from that. Also, you can run docker on rasberry pis! 

How would this fix work? Would I still just docker build and push?

**Comment by NickBusey** [comment]
Yes that is the point of docker, but it can't get around the fundamental differences in how processors work on ARM vs x86 etc. I'm not an expert on this, I just now this image doesn't work on pi's and it would be great if it did.

I believe so. I will try and get it working on my end and then push to you what I end up with, with directions. Thanks!

**Comment by NickBusey** [comment]
Actually, I think you just need to download the edge version of Docker, and build it again. I just re-built it with Edge Docker and pushed it to `nickbusey/yq` with no changes to the Dockerfile and that does work on the pi.

**Comment by NickBusey** [comment]
An update, it seems it may not be quite so simple, but pretty close. https://medium.com/@bamnet/building-multiarch-docker-images-8a70002b3476

Working on it.

**Comment by jmb** [comment]
Is there any progress on this? I’m trying to get @NickBusey ’s HomeLabOS scripts working on a Raspberry Pi and this is a sticking point it seems! :)

**Comment by mikefarah** [comment]
I think this has been fixed - the release process publishes a multi-arch docker image
