### ISSUE TITLE
Yq breaks yamllint

### ISSUE THREAD

**Issue by micheelengronne** [mikefarah/yq#397]
**Describe the bug**
Yamllint gives warning  missing document start "---"  (document-start) when a valid yaml file is altered by yq.

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
for a correctly yamlinted data1.yml:
```yaml
---
lint: test
```

yq gives an incorrect data1.yml:
```yaml
lint: test2
```

**Command**
The command you ran:
```
yq w -i data1.yml lint test2
```

**Comment by 030** [comment]
#351

**Comment by micheelengronne** [comment]
Indeed
