### ISSUE TITLE
Crash on negative list index - could traverse backwards instead

### ISSUE THREAD

**Issue by krangerich** [mikefarah/yq#398]
**Describe the bug**
When you specify a negative list index, for example "yr r data1.yaml foo[-1]", the program crashes with a stack trace

**Input Yaml**
data1.yml:
```yaml
foo:
- bar: baz
```

**Command**
The command you ran:
```
yq r data1.yaml foo[-1]
```

**Actual behavior**

runtime error with stack trace

**Expected behavior**

Print an error message 
OR 
implement new feature like "-1 means last item of the list"

**Comment by mikefarah** [comment]
Ooh I like negative indexes for going backwards, that would be cool.
