### ISSUE TITLE
JSON loading only working with -X from 3.0.0 onwards

### ISSUE THREAD

**Issue by laidbackware** [mikefarah/yq#402]
**Describe the bug**
From version 3.0 onwards json will only display as yaml if using the -X (explode anchors flag) option. Is this expected behaviour?

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data.json:
```json
{"test": "123"}
```

**Actual behavior**

```bash
bash-5.0# yq r out1.json
{"test": "123"}
```

```bash
bash-5.0# yq r out1.json -X
test: "123"
```

**Expected behavior**

```bash
bash-5.0# yq r out1.json
test: "123"
```

**Additional context**
The expected behaviour happened at 2.4.1, but switched at 3.0.0.

**Comment by mikefarah** [comment]
As JSON is a subset of YAML, and yq 3.0 keeps yaml formatting, it will no longer reformat JSON docs to look like idiomatic yaml by default. Instead you will need to explicitly pass in a prettyPrint flag: https://mikefarah.gitbook.io/yq/usage/output-format#pretty-print
