### ISSUE TITLE
Docs incorrectly represent output of reading multiple documents

### ISSUE THREAD

**Issue by komish** [mikefarah/yq#406]
**Describe the bug**
The documentation [here](https://mikefarah.gitbook.io/yq/commands/read#read-from-all-documents) implies that the default behavior while parsing a file with multiple documents will return an array containing the queried values, but Idon't think that is the case in the 3.x release. You would need to `-c` for that behavior.

**Input Yaml**
The same as in the documentation.

```
name: Fred
age: 22
---
name: Stella
age: 23
---
name: Android
age: 232
```

**Command**
The same as the documentation.

```
yq r -d'*' sample.yaml name
```

**Actual behavior**

```yaml
Fred
Stella
Android
```

**Expected behavior**
What's above is correct, just a matter of representing it correctly in the documentation.

**Additional context**
I believe the pre-3.x version functioned how the documentation represents now which is probably why the documentation shows it this way today (i.e. leftover from the previous versions).

Happy to help with a PR but I didn't see the right place.

**Comment by mikefarah** [comment]
Oops yep, cheers :)
