### ISSUE TITLE
Formatting Issues which is not understandable by Docker.

### ISSUE THREAD

**Issue by avinashGuptaIos** [mikefarah/yq#408]
Script file in txt format is here:
[Untitled-1.txt](https://github.com/mikefarah/yq/files/4468980/Untitled-1.txt)

Tempfile generated after running script is here:
[tempFile.txt](https://github.com/mikefarah/yq/files/4468985/tempFile.txt)

echo $(cat $FILE_NAME.yaml |
yq w - number \"4\")
i m trying to execute this
its never printing  number: "4"

this is the result i m getting from Yq
number: '"4"'

but   echo "\"5\""
is printing "5" in terminal.

i m expecting the result as
number: "4"

There is a formatting issues also there, like spacing issues . 
I want it to generate a .yaml file in Docker Composable format, where its formatting should be understandable by Docker .
Its yaml data formatting should follow the Docker Compose Guidelines.

can u please check once.

**Comment by mikefarah** [comment]
None of this makes sense to me - please follow the standard bug (or enhancement) template and provide simple examples that demonstrate your issue. I'm not going to read and fix your code for you.
