### ISSUE TITLE
double quotes removed

### ISSUE THREAD

**Issue by prawen** [mikefarah/yq#412]
**Describe the bug**
How to persist double quotes

**Input Yaml**
Empty file

**Command**
The command you ran:
```
export VERSION="3"
touch test.yml
cat test.yml | yq w - version ${VERSION}
```

**Actual behavior**

```
version: 3
```

**Expected behavior**

```
version: "3"
```

**Additional context**
yq version 3.2.1

**Comment by mikefarah** [comment]
as it's a number, you'll need to specify the tag to force it to a string (https://mikefarah.gitbook.io/yq/usage/value-parsing#using-the-tag-field-to-override)
```
yq n --tag '!!str' version 3
```
