### ISSUE TITLE
Persisting Single quote issue

### ISSUE THREAD

**Issue by avinashGuptaIos** [mikefarah/yq#413]
**Describe the bug**
Want to persist single quote.

**Command**
The command you ran:
```
yq n 'boolValue' --tag '!!str' false
```

**Actual behavior**

```
boolValue: "false"
```

**Expected behavior**

```
boolValue: 'false'
```

**Additional context**
https://mikefarah.gitbook.io/yq/usage/value-parsing#using-the-tag-field-to-override

Casting booleans
yq new --tag '!!str' key true
results in
key: 'true'

as mentioned it is not working.

**Comment by mikefarah** [comment]
Thanks @avinashGuptaIos, that's a good find, I'll update the docs.

As quote styles seems to a common request, I'm also going to add a 'style' flag that maps roughly to https://godoc.org/gopkg.in/yaml.v3#Style
