### ISSUE TITLE
Unknown style flow

### ISSUE THREAD

**Issue by ngirard** [mikefarah/yq#417]
Using yq 3.3.0.

[Documentation](https://mikefarah.gitbook.io/yq/usage/value-parsing#the-style-flag) lists `flow` among acceptable values for `--style` flag, yet
```sh
yq n thing cat --style=flow
```
gives
```
Parse [ERRO] Unknown style flow, ignoring
```

Also, providing the docs with an example for all values would be useful.

**Comment by mikefarah** [comment]
Oops missed that, will fix soon, thanks :)
