### ISSUE TITLE
[question] why v3 script format so awful?  

### ISSUE THREAD

**Issue by Slach** [mikefarah/yq#419]
instead of 1 line of code, I need add 3-5 lines of yaml code

I have around 10 *.yq files 30-40 lines in each yq script file
and need completely rewrite this exists *.yq files without improving any kind of functionality
do we have any option or method to convert old v2 script format to new v3 script format?

**Comment by mikefarah** [comment]
Wait so you want my help and you're being rude? Try again.

**Comment by Slach** [comment]
sorry for my emotional and rude message ;(
No, I don't need help 
I rewrote my *.yq scripts and thanks you for your work

**Comment by mikefarah** [comment]
:) Cheers mate - glad it worked out for you
