### ISSUE TITLE
Question: Output structured yaml? 

### ISSUE THREAD

**Issue by zurvan2** [mikefarah/yq#420]
**Is your feature request related to a problem? Please describe.**
I would like to use the query aspects of yq to print out the portion of a yaml file in the same format that it was input, but with only the selected values. Is this already possible? 

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
state:
  country: 
    city: foo
```

And we run a command:

```bash
yq r data1.yml state.**(.==foo)
```

it could output

```yaml
state:
  country: 
    city: foo
```

**Describe alternatives you've considered**
I've tried various ways of combining the input with yq r, which sometimes outputs the original format, but apparently only when outputting the original file. It does not appear to convert between formats. 

**Additional context**
Also: is it possible to query by *value* only? Like, print all matches where the *value* contains a particular string? (not just prefix).

**Comment by mikefarah** [comment]
The closest command that works at the moment is:
```
yq r examples/sample.yaml '(*.city==fo*)'
```

However, that won't display the top level node. Note that you can search for matching values with a prefix. I think I should make an update to allow the root node to be included in the results, something like:

```
yq r examples/sample.yaml '(**.city==fo*)'
```

**Comment by mikefarah** [comment]
This is now possible in v4, which uses `jq` like syntax
