### ISSUE TITLE
yq write automatically simple quote field when use ": " (colon space) char sequence

### ISSUE THREAD

**Issue by jmchantrein** [mikefarah/yq#424]
**Describe the bug**
In yq write mode, the characters sequence ": " (colon follow by space) automatically quote the field.

yq version: 3.1.2

**Actual behavior**
```
yq write things.yaml 'site.[+]' "url:\"http://test.example.com\""
```
give you:
```yaml
site:
- url:"http://test.example.com"
```
But if you need a space after the colon:
```
yq write things.yaml 'site.[+]' "url: \"http://test.example.com\""
```
give you:
```yaml
site:
- 'url: "http://test.example.com"'
```

**Expected behavior**
```
yq write things.yaml 'site.[+]' "url: \"http://test.example.com\""
```
give you:
```yaml
site:
- url: "http://test.example.com"
```

**Additional question**
Also, here is a way to force indent the field in output to obtain

```yaml
site:
  - url: "http://test.example.com"
```

**Comment by mikefarah** [comment]
looks like you should be doing:

```
yq write things.yaml 'site.[+].url' "http://test.example.com"
```

**Comment by jmchantrein** [comment]
Thanks for the answers, but:

```
yq write things.yaml 'site.[+].url' "http://test.example.com"
```
give :
```
site:
- url: http://test.example.com
```
and 
```
yq write things.yaml 'site.[+].url' "\"http://test.example.com\""
```
give :
```
site:
- url: '"http://test.example.com"'
```
And my expected behavior are always:
```
site:
- url: "http://test.example.com"
```
or

```
site:
  - url: "http://test.example.com"
```

As you can see, there are always a trouble of quote ;-)

**Comment by mikefarah** [comment]
Ah missed that, if you want to control qoutes, use the style flag https://mikefarah.gitbook.io/yq/usage/value-parsing#double

**Comment by jmchantrein** [comment]
Ok, thank you very much, you are doing a great job.

For information, this feature need version 3.3: https://github.com/mikefarah/yq/releases/tag/3.3.0
Documentation indicate 3.x

I'm actually in version 3.1.2 with @rmescandon yq apt-repository, so I don't have the style flag options.

**Comment by rmescandon** [comment]
@jmchantrein just updated deb to 3.3-0 on #428 and in repositories. Give it a go and let me know if that --style flag works.

**Comment by jmchantrein** [comment]
@rmescandon Yes, I have updated to 3.3.0 and --style flag works fine. Thank you.
