### ISSUE TITLE
yqlib: allow to configure logger

### ISSUE THREAD

**Issue by jeanlucmongrain** [mikefarah/yq#432]
I'm using yqlib in my golang project instead of yq CLI.

It's great, the only thing is that the logger behavior is hardcoded. I suggest there should be a method like:

```golang
func GetLogger() *logging.Logger {
  return log
}
```

to allow something like

```golang
yqlib.GetLogger().SetBackend(...)
```

**Comment by mikefarah** [comment]
I'll accept a PR for this..
