### ISSUE TITLE
JSON conversion (still) does not preserve object order

### ISSUE THREAD

**Issue by erhhung** [mikefarah/yq#435]
**Describe the bug**

It seems from #274 having been fixed that conversion to JSON should now be preserving object order, but that's not what I'm seeing.

**Input Yaml**
data1.yml:
```yaml
foo: a
bar: b
```

**Command**
```
yq r -jP data1.yaml
```

**Actual behavior**
```json
{
  "bar": "b",
  "foo": "a"
}
```

**Expected behavior**
```json
{
  "foo": "a",
  "bar": "b"
}
```

**Additional context**
yq version 3.3.0 on macOS 10.15.3

**Comment by mikefarah** [comment]
Last time I had a look at this I could not work out why it was happening :(

I'll take a fresh look when I have time

**Comment by mikefarah** [comment]
Ok finally found out what's happening, the underlying Golang JSON encoder sorts the keys!

It's documented here: https://golang.org/pkg/encoding/json/#Marshal

I won't be able to fix this issue unless another json encoder is used

**Comment by erhhung** [comment]
Thanks for looking into this. I assume you have read about possible alternatives?
https://github.com/golang/go/issues/27179

Go isn't my forte nor have I looked at your implementation, so hopefully you can do something before relying on the standard library to change.

**Comment by mikefarah** [comment]
Something like that could possible work.
