### ISSUE TITLE
yq-s390x : runtime error: invalid memory address or nil pointer dereference occurs 

### ISSUE THREAD

**Issue by apasrini** [mikefarah/yq#436]
yq w command fails with runtime error: invalid memory address or nil pointer dereference 

**Input Yaml**
sample.yaml file fails

b:
  c: 2

**Command**
yq w sample.yaml b.c cat

**Actual behavior**

Error occurs

root@zLinux-jenkins-slave1:~# yq w sample.yaml b.c cat
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14fb86]

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc00003ba00)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/yaml.go:276 +0xae
panic(0x259da0, 0x474330)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x132
gopkg.in/yaml%2ev3.yaml_parser_parse_node(0xc0000b8000, 0xc0000b82b0, 0x100000000000080, 0x33)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/parserc.go:564 +0x496
gopkg.in/yaml%2ev3.yaml_parser_state_machine(0xc0000b8000, 0xc0000b82b0, 0x3ff922cae40)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/parserc.go:170 +0x1a4
gopkg.in/yaml%2ev3.yaml_parser_parse(0xc0000b8000, 0xc0000b82b0, 0x3ff922c0108)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/parserc.go:129 +0x82
gopkg.in/yaml%2ev3.(*parser).peek(0xc0000b8000, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/decode.go:102 +0x3c
gopkg.in/yaml%2ev3.(*parser).parse(0xc0000b8000, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/decode.go:141 +0x36
gopkg.in/yaml%2ev3.(*parser).parseChild(0xc0000b8000, 0xc000079f40, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/decode.go:186 +0x2a
gopkg.in/yaml%2ev3.(*parser).document(0xc0000b8000, 0x300000000000030)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/decode.go:195 +0xa6
gopkg.in/yaml%2ev3.(*parser).parse(0xc0000b8000, 0xc00007bc70)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/decode.go:151 +0x13a
gopkg.in/yaml%2ev3.(*Decoder).Decode(0xc00001caa0, 0x26aa00, 0xc000079ea0, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/yaml.go:123 +0xfe
github.com/mikefarah/yq/v3/cmd.mapYamlDecoder.func1(0xc00001caa0, 0xc00001caa0, 0x600)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:274 +0x166
github.com/mikefarah/yq/v3/cmd.readStream(0x3ffde17f7f2, 0xb, 0xc00000c5c0, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:520 +0x20e
github.com/mikefarah/yq/v3/cmd.readAndUpdate(0x2ed0e0, 0xc00000e018, 0x3ffde17f7f2, 0xb, 0xc000057530, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:393 +0x28a
github.com/mikefarah/yq/v3/cmd.updateDoc(0x3ffde17f7f2, 0xb, 0xc000057500, 0x1, 0x1, 0x2ed0e0, 0xc00000e018, 0x1, 0x1)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:348 +0xdc
github.com/mikefarah/yq/v3/cmd.writeProperty(0xc00008b080, 0xc000057410, 0x3, 0x3, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/write.go:58 +0x100
github.com/spf13/cobra.(*Command).execute(0xc00008b080, 0xc0000573e0, 0x3, 0x3, 0xc00008b080, 0xc0000573e0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/github.com/spf13/cobra/command.go:842 +0x3c4
github.com/spf13/cobra.(*Command).ExecuteC(0xc00008a580, 0x2, 0xc000057260, 0xc000054058)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/github.com/spf13/cobra/command.go:950 +0x2da
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/yq.go:13 +0x60

**Expected behavior**
yaml should be written with below

b:
  c: cat

**Comment by apasrini** [comment]
Locally from my mac i see the below command works-
yq w sample.yaml b.c cat
b:
  c: cat

**Comment by apasrini** [comment]
@mikefarah Could you please check this as the basic functionality of write seem to be not working on zlinux

**Comment by apasrini** [comment]
@mikefarah I have tried with go version 1.10.2 and 1.12.3 still hitting with the same issue.

**Comment by mikefarah** [comment]
Looks like this is related to https://github.com/mikefarah/yq/issues/394

**Comment by apasrini** [comment]
@mikefarah root@zLinux:~# yq r sample.yaml 'b.imagePullSecrets.(name==my-secret).name'
Error: Error reading path in document index 0: error accessing array: strconv.ParseInt: parsing "(name==my-secret)": invalid syntax
Usage:
  yq read [yaml_file] [path] [flags]

Aliases:
  read, r

Examples:

yq read things.yaml a.b.c
yq r - a.b.c (reads from stdin)
yq r things.yaml a.*.c
yq r -d1 things.yaml a.array[0].blah
yq r things.yaml a.array[*].blah
yq r -- things.yaml --key-starting-with-dashes
      

Flags:
  -d, --doc string   process document index number (0 based, * for all documents) (default "0")
  -h, --help         help for read
  -j, --tojson       output as json

Global Flags:
  -t, --trim      trim yaml output (default true)
  -v, --verbose   verbose mode

04:26:30 main [ERRO] Error reading path in document index 0: error accessing array: strconv.ParseInt: parsing "(name==my-secret)": invalid syntax
root@zLinux~# vi sample.yaml
root@zLinux:~# yq -V
yq version 2.4.1


sample.yaml file content :

b:
  imagePullSecrets:
      - name: "my-secret"



With version 2.4.1 of yq, I dont hit with panic: runtime error: invalid memory address or nil pointer dereference [recovered] but the above issue is present which is stopping the progress. 

I am on the latest version of go. 

root@zLinux:~# go version
go version go1.14.2 linux/s390x

**Comment by alicefr** [comment]
@apasrini please try to build yq with an older version of go as suggested here https://github.com/mikefarah/yq/issues/394#issuecomment-604979539

**Comment by mikefarah** [comment]
Is this still an issue with the latest build Fixed https://github.com/mikefarah/yq/releases/tag/3.2.3 (uses 1.15.1 go compiler)

**Comment by jschintag** [comment]
As mentioned in #502 it is fixed in `3.2.3`
