### ISSUE TITLE
Virustotal (false?) positives in Windows/386 build

### ISSUE THREAD

**Issue by vasily-codefresh** [mikefarah/yq#438]
Hi,

While reviewing yq 3.3.0 on Chocolatey, Choco people found out a huge number of virustotal.com  alarms on the Windows/386 binary. Discussion and virus total links are on [this page](https://chocolatey.org/packages/yq/3.3.0) for reference.

I actually believe virustotal.com will go mad over any Go/Windows 386 binary, but I was requested to ask from Choco authors: is this a known issue?

@mikefarah and the community, could you give me some helpful advice re yq virustotal info I can pass to Choco people?

One nuance: if you'll activate virustotal.com by URL, it will run a less number of checks and pass. This is reproducible by using the 'upload file' thing.

**Comment by vasily-codefresh** [comment]
P.S. Windows Defender also doesn't like the Windows/386 build.
can we please verify it does not contain actual trojans? for some reason yq 3.2.1 build had much less anti-virus warnings.

**Comment by vasily-codefresh** [comment]
hm, it's also very weird that yq for 32-bit windows [bundles](https://www.virustotal.com/gui/file/b563f69fdc8078f4f8feb95907d868beaf945efbcee8ba2a601a220a20bf491a/behavior/QiAnXin%20RedDrip) a weird executable named `c86ae3305b5e729ae5339c677f388bcb5df7965a.exe` and references it from the `temp` directory.

**Comment by mikefarah** [comment]
@ chillum originally did the Chocolate build.

That exe looks suspicious to me - not sure what it is. 

In the latest build (3.3.x), in addition to some new featuers, I upgraded some libraries and started using the latest golang version (1.14 instead of 1.13). Does the 64bit build have similar issues?

**Comment by mikefarah** [comment]
Hah just realised you are Chillum #facepalm

**Comment by mikefarah** [comment]
Yeah no idea. You're right about the URL thing, if I give it the win64 url, https://github.com/mikefarah/yq/releases/download/3.3.0/yq_windows_amd64.exe, not issues are found. If I download then upload it - it complains.

**Comment by mikefarah** [comment]
Crap do I have a virus

**Comment by vasily-codefresh** [comment]
64-bit build has one false positive (3.2.1 builds had as well), but definitely something weird with 32-bit Windows build of 3.3.0 (that `c86ae3305b5e729ae5339c677f388bcb5df7965a.exe` is not Go's runtime). could you please assure it's the same file you complied and uploaded and it wasn't changed by anyone else?

**Comment by mikefarah** [comment]
How about the latest build - I uploaded that this weekend?

**Comment by mikefarah** [comment]
Just checked it myself - what's in github is the same as what I built - it has not been changed by anyone.

I built the windows binaries on my mac using gox. The latest build still complains of issues - no idea why. Has to be a compiled go thing I guess? Perhaps one of the dependencies?

**Comment by vasily-codefresh** [comment]
3.3.2 seems much better.

I still would suggest there's something wrong with windows/386 build of 3.3.0, I suggest to revoke this exact executable from github. or maybe re-build it.

**Comment by vasily-codefresh** [comment]
I'd say that a small number of false positives is okay with Go apps, but small is like 3 like with 3.3.2

but not ~30 like with 3.3.0, this definitely seemed strange

**Comment by mikefarah** [comment]
Strange - must have been an underlying lib, the biggest change from 3.3.0 to 3.3.1 is I upgraded go-yaml.

**Comment by mikefarah** [comment]
Re-built it - has the same number of issues. Ill take that build off, you happy to close this issue?

**Comment by chillum** [comment]
Yeah, thanks. I’ll upload 3.3.1 to Choco, it should pass

Vasily
________________________________
Від: Mike Farah <notifications@github.com>
Надіслано: Tuesday, June 16, 2020 2:47:38 AM
Кому: mikefarah/yq <yq@noreply.github.com>
Копія: Vasily Korytov <v.korytov@outlook.com>; Mention <mention@noreply.github.com>
Тема: Re: [mikefarah/yq] Virustotal (false?) positives in Windows/386 build (#438)


Re-built it - has the same number of issues. Ill take that build off, you happy to close this issue?
