### ISSUE TITLE
w and merge reformats file in an unexpected way

### ISSUE THREAD

**Issue by zhujik** [mikefarah/yq#444]
For example, running 

    yq w -i values.yaml rbac.create false

On this file: https://raw.githubusercontent.com/helm/charts/master/stable/grafana/values.yaml

Will cause 77 lines added and 114 lines removed for just one change.

Most noticable is that he removes empty lines and moves the indentation level of some block comments.

**Comment by mikefarah** [comment]
Yeah unfortunately the underlying go-yaml parser does not perfectly preserve the original formatting (though I think it does a reasonable job).

**Comment by mikefarah** [comment]
https://github.com/go-yaml/yaml/issues/627
