### ISSUE TITLE
yq merge panics if comments contains Unicode

### ISSUE THREAD

**Issue by lingsamuel** [mikefarah/yq#446]
**Describe the bug**
When the comment contains Unicode such as Chinese, yq merge will panic.

**Input Yaml**
Minimal test yamls below:

a.yaml:
```yaml
a: work
```

b.yaml:
```yaml
中文: work
```

c.yaml:
```yaml
c: error # 中文
```

d.yaml
```yaml
d: 中文
```

**Command**

```bash
yq merge a.yaml b.yaml # Okay
yq merge a.yaml c.yaml # Panic!
yq merge a.yaml d.yaml # Okay
yq merge b.yaml d.yaml # Okay
```

**Actual behavior**

![image](https://user-images.githubusercontent.com/14567045/83088876-8647a600-a0c7-11ea-937c-55362758d58a.png)

From the stack trace, maybe it's not a `yq` bug but a `yaml.v3` bug.

**Expected behavior**

Comments with Unicode should work.

**Additional context**

yq version:
![image](https://user-images.githubusercontent.com/14567045/83088913-9e1f2a00-a0c7-11ea-93ec-89818f36171f.png)

**Comment by lingsamuel** [comment]
yaml.v3 bug: https://github.com/go-yaml/yaml/issues/538
It's closed but still exists...

**Comment by mikefarah** [comment]
Yeah I'm hoping someone on that project will pick it up :(

**Comment by lingsamuel** [comment]
https://github.com/go-yaml/yaml/issues/538#issuecomment-635209047
I think the fix will fly soon.

**Comment by lingsamuel** [comment]
Hello, `yaml.v3` fixed this issue: https://github.com/go-yaml/yaml/issues/538.

**Comment by mikefarah** [comment]
yup - next release will have that fix!
