### ISSUE TITLE
Hang when converting JSON file to JSON

### ISSUE THREAD

**Issue by Nuru** [mikefarah/yq#447]
**Describe the bug**
Processing file [hang.txt](https://github.com/mikefarah/yq/files/4705217/hang.txt) takes longer than I have patience for. I expect `yq` has entered an infinite loop. 

**Input Yaml**
Attached [hang.txt](https://github.com/mikefarah/yq/files/4705217/hang.txt)

**Command**
The command you ran:
```
yq r -j hang.txt
```

**Actual behavior**

Burns CPU with no output until I lose my patience and kill it.

**Expected behavior**

Output in under 1 second.

**Additional context**

The input file is a Grafana dashboard from Grafana.com

**Comment by mikefarah** [comment]
This should be fixed in 3.3.2
