### ISSUE TITLE
yq compare does not need to check order

### ISSUE THREAD

**Issue by yoshwata** [mikefarah/yq#449]
## Is your feature request related to a problem? Please describe.

yq compare checks the order and handles it as diffs. That makes frustrations when a yaml is made by some steps (delete, merge or insert), then it was compared expected one for testing.

## Describe the solution you'd like
If we have a.yml like:

```yaml
a:
    b: 1
    c: 2
```

And we have a.yml like:

```yaml
a:
    c: 2
    b: 1
```

And we run a command:

```bash
$ yq compare  a.yaml b.yaml
 a:
-  b: 1
   c: 2
+  b: 1
```

I'd like to deal it as equal.

## Describe alternatives you've considered
An option to compare strictly in order.

**Comment by mikefarah** [comment]
Hmm best way to do this in my mind is to add a sortKeys flag that will sort before comparing

**Comment by bharti0708** [comment]
yq r -j a.yaml (Converts yaml to json, and sorts it alphabetically), You can then compare these 2 json.

**Comment by yoshwata** [comment]
```bash
yq compare -j a.yaml b.yaml
```
The command above seems sufficient. 

It looks something like a side-effect because `toJson` option works over what it should to bear, to say one comment.

**Comment by Nielius** [comment]
I'd like to still have something like a sortKeys flag that sorts before comparing, as @mikefarah suggested in https://github.com/mikefarah/yq/issues/449#issuecomment-644560233.

For example, I'm using version 3.4.1 on Mac, and when I compare these two files that are identical up to ordering:

```
$ cat fileA.yaml
a:
    b: 1
    c: 2
d:
    e: 3
    f: 5
$ cat fileB.yaml
d:
    f: 5
    e: 3
a:
    c: 2
    b: 1
```

then both with `yq compare -j` and with `yq compare -j -P`, I get the following results:

```
$ yq compare -j fileA.yaml fileB.yaml
-{"a":{"b":1,"c":2},"d":{"e":3,"f":5}}
+{"d":{"f":5,"e":3},"a":{"c":2,"b":1}}
$ yq compare -j -P fileA.yaml fileB.yaml
 {
-  "a": {
-    "b": 1,
-    "c": 2
-  },
   "d": {
-    "e": 3,
-    "f": 5
+    "f": 5,
+    "e": 3
+  },
+  "a": {
+    "c": 2,
+    "b": 1
   }
 }
 ```

 neither of which is very helpful when I don't care about the order. Of course, I could still sort the files before comparing them, but I'd find something like

    yq compare -S fileA.yaml fileB.yaml

very useful!

**Comment by Nielius** [comment]
Sorry, I only now found an issue that is more or less the same as this one:
https://github.com/mikefarah/yq/issues/516
(It was opened just 2 days after this one was closed.)
