### ISSUE TITLE
Supports writing multiple value at once

### ISSUE THREAD

**Issue by runzexia** [mikefarah/yq#453]
Now if I want to write more than one value, I need to call `yq` multiple times.
```
yq w -i xxx.yaml a.b c
yq w -i xxx.yaml d.e f
```

**Describe the solution you'd like**

```yaml
yq w -i xxx.yaml d.e f a.b c
```

And we run a command:

```bash
yq w -i xxx.yaml d.e f a.b c
```

it could output

```yaml
a:
  b: c
d:
  e: f
```

**Describe alternatives you've considered**

if we could update
 `func readUpdateCommands(args []string, expectedArgs int, badArgsMessage string) ([]yqlib.UpdateCommand, error) `.
Let the length of the `[]yqlib.UpdateCommand` not always be 1.

**Comment by mikefarah** [comment]
There are two ways to do this:
a) Use a update script (https://mikefarah.gitbook.io/yq/commands/write-update#using-a-script-file-to-update) which is where the length of UpdateCommand is greater than 1
b) pipe the result into another yq write command (https://mikefarah.gitbook.io/yq/commands/write-update#from-stdin)

I'm reluctant to allow multiple updates from a single command in the CLI as it will make the usage complex, in particular when you add all the flags for writing (e.g. tag, style) and I'll soon be adding more..

**Comment by runzexia** [comment]
> I'm reluctant to allow multiple updates from a single command in the CLI as it will make the usage complex, in particular when you add all the flags for writing (e.g. tag, style) and I'll soon be adding more..

For example, helm's support this https://helm.sh/docs/helm/helm_install/
Multi-value writing is a bit complicated for the yq v3 API.
In yq v4, we could refer to the API design of helm CLI.

**Comment by mikefarah** [comment]
v4 supports `jq` like syntax and you can have multiple operations in a single expression :)

https://mikefarah.gitbook.io/yq/v/v4.x/

```
yq eval '(.a.b = "foo") | (.d.e = "bar")' file.yml
```

**Comment by runzexia** [comment]
cool !!! 
thanks @mikefarah 🤩🤩

**Comment by ljubon** [comment]
I'm not sure if this is the right place to ask this, but is Union + Evall-all supported? 
`yq eval-all -i '(.version = "CHANGEME"),(.image.tag = "CHANGEME"),(.appVersion = "CHANGEME")' values.yaml Chart.yaml`
