### ISSUE TITLE
The flag "--style" is not implented (yet?) in the 3.1.2 from the @rmescandon repo for Ubuntu 16.04

### ISSUE THREAD

**Issue by DrRetro** [mikefarah/yq#454]
**Describe the bug**
The flag "--style" is not implented in the 3.1-2 version from the @rmescandon repo for Ubuntu 16.04(?) When i try to use the flag for Quotation Marks e.g. --style=double i get the following error message:
```
user@host:~# yq write -i --style=double ./example.yml config.app.name 'This String should be in quotation marks!'

Error: unknown flag: --style
Usage:
  yq write [yaml_file] [path_expression] [value] [flags]

Aliases:
  write, w

Examples:

yq write things.yaml 'a.b.c' true
yq write things.yaml 'a.*.c' true
yq write things.yaml 'a.**' true
yq write things.yaml 'a.(child.subchild==co*).c' true
yq write things.yaml 'a.b.c' --tag '!!str' true # force 'true' to be interpreted as a string instead of bool
yq write things.yaml 'a.b.c' --tag '!!float' 3
yq write --inplace -- things.yaml 'a.b.c' '--cat' # need to use '--' to stop processing arguments as flags
yq w -i things.yaml 'a.b.c' cat
yq w -i -s update_script.yaml things.yaml
yq w things.yaml 'a.b.d[+]' foo # appends a new node to the 'd' array
yq w --doc 2 things.yaml 'a.b.d[+]' foo # updates the 3rd document of the yaml file
      

Flags:
  -d, --doc string      process document index number (0 based, * for all documents) (default "0")
  -f, --from string     yaml file for updating yaml (as-is)
  -h, --help            help for write
  -i, --inplace         update the yaml file inplace
  -s, --script string   yaml script for updating yaml
  -t, --tag string      set yaml tag (e.g. !!int)

Global Flags:
  -I, --indent int    sets indent level for output (default 2)
  -P, --prettyPrint   pretty print
  -j, --tojson        output as json. By default it prints a json document in one line, use the prettyPrint flag to print a formatted doc.
  -v, --verbose       verbose mode

2020/06/04 22:43:44 unknown flag: --style

```

**Additional context**
Version check:
```
user@host:~# yq --version
yq version 3.1.2
user@host:~# apt-cache policy yq
yq:
  Installed: 3.1-2
  Candidate: 3.1-2
  Version table:
 *** 3.1-2 500
        500 http://ppa.launchpad.net/rmescandon/yq/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
user@host:~# 
```

**Comment by rmescandon** [comment]
mm... I'm just only the deb package maintainer. Just tried the snap and I've got that same error. @mikefarah do you know if the feature was landed to master?

**Comment by DrRetro** [comment]
In the end it would be enough to use the same package as in the bionic part. You manage that too, right? This was my current workaround for Ubuntu 16.04. There the "--style" feature is already in there. 
And of course I don't guarantee that this will work as smoothly for everyone as it does for me ;)

**Comment by mikefarah** [comment]
Yep should be there (but I think it came after 3.1.x) - just made another release and updated and checked snap too. @rmescandon if you could rebump the debian packages that would be ace.

**Comment by mikefarah** [comment]
Latest is now 3.3.1 fwiw

**Comment by DrRetro** [comment]
Since I stumbled across the installation again today. There is still the old version in the xenial repository. Only by switching from xenial to bionic in the source list it is possible to get the latest version in Ubuntu 16.04. Will it stay that way? 
If so, it would probably be best for everyone involved to note in the documentation that the repo is not properly maintained.

**Comment by mikefarah** [comment]
Closing - 3.x is no longer supported, rmescandon has been publishing 4.x
