### ISSUE TITLE
yq w -i wrong

### ISSUE THREAD

**Issue by ccssyybb** [mikefarah/yq#456]
asus AX88U
yq w -i /koolshare/merlinclash/config.yaml socks-port 23456
panic: runtime error: index out of range [9] with length 9 [recovered]
	panic: runtime error: index out of range [9] with length 9

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0x83bb84)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/yaml.go:276 +0x8c
panic(0x21e020, 0x907790)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x118
gopkg.in/yaml%2ev3.write(0x82e5a0, 0x907740, 0x9, 0x10, 0x83ad10, 0x1)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:90 +0x218
gopkg.in/yaml%2ev3.yaml_emitter_write_comment(0x82e5a0, 0x907740, 0x9, 0x10, 0x907768)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:1978 +0x198
gopkg.in/yaml%2ev3.yaml_emitter_process_head_comment(0x82e5a0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:1111 +0x64
gopkg.in/yaml%2ev3.yaml_emitter_emit_block_mapping_key(0x82e5a0, 0x92a198, 0x43005401, 0x5453)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:775 +0x68
gopkg.in/yaml%2ev3.yaml_emitter_state_machine(0x82e5a0, 0x92a198, 0x1)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:297 +0x2ec
gopkg.in/yaml%2ev3.yaml_emitter_emit(0x82e5a0, 0x82e6c4, 0x907780)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:153 +0xe4
gopkg.in/yaml%2ev3.(*encoder).emit(0x82e5a0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:81 +0x28
gopkg.in/yaml%2ev3.(*encoder).emitScalar(0x82e5a0, 0x816c20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x8fbe02, 0x907770, 0xb, ...)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:417 +0x218
gopkg.in/yaml%2ev3.(*encoder).node(0x82e5a0, 0x870e10, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:559 +0xe84
gopkg.in/yaml%2ev3.(*encode

**Comment by mikefarah** [comment]
That's not enough information to diagnose the issue - please follow the bug template
