### ISSUE TITLE
AX88U yq_arm  yq w -i wrong 2

### ISSUE THREAD

**Issue by ccssyybb** [mikefarah/yq#457]
yq write -i /koolshare/merlinclash/config.yaml socks-port 2323
Error: Error reading document at index 0, yaml: line 25: did not find expected key: yaml: line 25: did not find expected key
Usage:
  yq write [yaml_file] [path_expression] [value] [flags]

Aliases:
  write, w

Examples:

yq write things.yaml 'a.b.c' true
yq write things.yaml 'a.*.c' true
yq write things.yaml 'a.**' true
yq write things.yaml 'a.(child.subchild==co*).c' true
yq write things.yaml 'a.b.c' --tag '!!str' true # force 'true' to be interpreted as a string instead of bool
yq write things.yaml 'a.b.c' --tag '!!float' 3
yq write --inplace -- things.yaml 'a.b.c' '--cat' # need to use '--' to stop processing arguments as flags
yq w -i things.yaml 'a.b.c' cat
yq w -i -s update_script.yaml things.yaml
yq w things.yaml 'a.b.d[+]' foo # appends a new node to the 'd' array
yq w --doc 2 things.yaml 'a.b.d[+]' foo # updates the 3rd document of the yaml file
      

Flags:
  -d, --doc string      process document index number (0 based, * for all documents) (default "0")
  -f, --from string     yaml file for updating yaml (as-is)
  -h, --help            help for write
  -i, --inplace         update the yaml file inplace
  -s, --script string   yaml script for updating yaml
      --style string    formatting style of the value: single, double, folded, flow, literal, tagged
  -t, --tag string      set yaml tag (e.g. !!int)

Global Flags:
  -C, --colors        print with colors
  -I, --indent int    sets indent level for output (default 2)
  -P, --prettyPrint   pretty print
  -j, --tojson        output as json. By default it prints a json document in one line, use the prettyPrint flag to print a formatted doc.
  -v, --verbose       verbose mode

01:40:54 main [ERRO] Error reading document at index 0, yaml: line 25: did not find expected key: yaml: line 25: did not find expected key

**Comment by mikefarah** [comment]
Please follow the bug issue template
