### ISSUE TITLE
flag -e always fail

### ISSUE THREAD

**Issue by r0bj** [mikefarah/yq#459]
**Describe the bug**
Using flag -e causing always "Error: No matches found"

**Input Yaml**
data1.yml:
```yaml
foo: bar
```

**Command**
The command you ran:
```
yq r data1.yml foo -e
```

**Actual behavior**

```yaml
$ yq r data1.yml foo -e
Error: No matches found
```

**Expected behavior**

```yaml
$ yq r data1.yml foo -e
bar
```

**Additional context**
The same command without `-e` works fine:
```
$ yq r data1.yml foo
bar
```

**Comment by mikefarah** [comment]
oh wow I don't know how I missed that 🤦

**Comment by mikefarah** [comment]
Fixed.
