### ISSUE TITLE
yq arm/arm64 runtime error

### ISSUE THREAD

**Issue by ccssyybb** [mikefarah/yq#464]
**Describe the bug**
like: yq d -i /koolshare/merlinclash/Pro.yaml redir-port
panic: runtime error: index out of range [9] with length 9 [recovered]
	panic: runtime error: index out of range [9] with length 9

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0x400017f6a0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/yaml.go:276 +0xa0
panic(0x23b580, 0x40001691e0)
	/usr/local/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x11c
gopkg.in/yaml%2ev3.write(0x4000090380, 0x4000142f70, 0x9, 0x10, 0x400017da80, 0x120401)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:90 +0x214
gopkg.in/yaml%2ev3.yaml_emitter_write_comment(0x4000090380, 0x4000142f70, 0x9, 0x10, 0x4000142f98)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:1978 +0x17c
gopkg.in/yaml%2ev3.yaml_emitter_process_head_comment(0x4000090380, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:1111 +0x68
gopkg.in/yaml%2ev3.yaml_emitter_emit_block_mapping_key(0x4000090380, 0x4000172330, 0x400017db01, 0x11d5f8)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:775 +0x68
gopkg.in/yaml%2ev3.yaml_emitter_state_machine(0x4000090380, 0x4000172330, 0x1)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:297 +0x33c
gopkg.in/yaml%2ev3.yaml_emitter_emit(0x4000090380, 0x40000905c0, 0x400017dd08)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/emitterc.go:153 +0x108
gopkg.in/yaml%2ev3.(*encoder).emit(0x4000090380)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:81 +0x34
gopkg.in/yaml%2ev3.(*encoder).emitScalar(0x4000090380, 0x4000016c60, 0xa, 0x0, 0x0, 0x0, 0x0, 0x400016c402, 0x4000142fa0, 0xb, ...)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:417 +0x224
gopkg.in/yaml%2ev3.(*encoder).node(0x4000090380, 0x40000c40a0, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:559 +0xe98
gopkg.in/yaml%2ev3.(*encoder).node(0x4000090380, 0x400007bea0, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:508 +0x874
gopkg.in/yaml%2ev3.(*encoder).node(0x4000090380, 0x400007bd60, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:463 +0x1ac
gopkg.in/yaml%2ev3.(*encoder).nodev(0x4000090380, 0x22a940, 0x400007bd60, 0x16)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:421 +0x6c
gopkg.in/yaml%2ev3.(*encoder).marshalDoc(0x4000090380, 0x0, 0x0, 0x22a940, 0x400007bd60, 0x16)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/encode.go:101 +0x1c4
gopkg.in/yaml%2ev3.(*Encoder).Encode(0x400003d710, 0x22a940, 0x400007bd60, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/gopkg.in/yaml.v3/yaml.go:251 +0xe4
github.com/mikefarah/yq/v3/pkg/yqlib.(*yamlEncoder).Encode(0x400000c620, 0x400007bd60, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/pkg/yqlib/encoder.go:47 +0x244
github.com/mikefarah/yq/v3/cmd.mapYamlDecoder.func1(0x4000042a50, 0x4000042a50, 0x600)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:301 +0x258
github.com/mikefarah/yq/v3/cmd.readStream(0x7ffe6aedbf, 0x1f, 0x400000c640, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:520 +0x1e8
github.com/mikefarah/yq/v3/cmd.readAndUpdate(0x2ad320, 0x400000e018, 0x7ffe6aedbf, 0x1f, 0x4000063530, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:393 +0x20c
github.com/mikefarah/yq/v3/cmd.updateDoc(0x7ffe6aedbf, 0x1f, 0x4000063500, 0x1, 0x1, 0x2ad320, 0x400000e018, 0x4000068480, 0x40000634d0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/utils.go:348 +0xbc
github.com/mikefarah/yq/v3/cmd.deleteProperty(0x400008f600, 0x40000633e0, 0x2, 0x3, 0x0, 0x0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/cmd/delete.go:40 +0x17c
github.com/spf13/cobra.(*Command).execute(0x400008f600, 0x40000633b0, 0x3, 0x3, 0x400008f600, 0x40000633b0)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/github.com/spf13/cobra/command.go:842 +0x30c
github.com/spf13/cobra.(*Command).ExecuteC(0x400008e580, 0x2, 0x4000063260, 0x425a4)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/github.com/spf13/cobra/command.go:950 +0x260
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/Users/mikefarah/dev/go/src/github.com/mikefarah/yq/yq.go:13 +0x54

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
Pro.yaml
this: should really work
# HTTP 端口
port: 3333

# SOCKS5 端口
socks-port: 7891

# Linux 及 macOS 的 redir 端口
redir-port: 7892

 allow-lan: true

data2.yml:
```yaml
but: it strangely didn't
```

**Command**
The command you ran:
yq d -i /koolshare/merlinclash/Pro.yaml redir-port

**Actual behavior**

```yaml
cat: meow
```

**Expected behavior**

```yaml
this: should really work
but: it strangely didn't
```

**Additional context**

**Comment by ccssyybb** [comment]
i find the reason ， the chinese word ，like
#端口 
port 3333
then it cant work

**Comment by mikefarah** [comment]
Sorry but I can't decipher the sample input yaml - could you please format it properly in a code block?

Which version of yq is this - the latest version (3.3.1) has a unicode fix..

**Comment by ccssyybb** [comment]
> Sorry but I can't decipher the sample input yaml - could you please format it properly in a code block?
> 
> Which version of yq is this - the latest version (3.3.1) has a unicode fix..

sample yaml like this:
# HTTP 端口
port: 3333
# SOCKS5 端口
socks-port: 23456
# Linux 及 macOS 的 redir 端口
redir-port: 7892
allow-lan: true
# 仅适用于设置 allow-lan 为 true 时
# "*": 绑定所有 IP 地址
# 192.168.122.11: 绑定单个 IPv4 地址
# "[aaaa::a8aa:ff:fe09:57d8]": 绑定单个 IPv6 地址
# bind-address: "*"
# Rule / Global / Direct (默认为 Rule 模式)
mode: Rule
# 设置输出日志的等级 (默认为 info)
# info / warning / error / debug / silent
log-level: info
# RESTful API for clash
external-controller: 192.168.2.1:9990

# you can put the static web resource (such as clash-dashboard) to a directory, and clash would serve in `${API}/ui`
# input is a relative path to the configuration directory or an absolute path
# external-ui: folder

# Secret for RESTful API (Optional)
# secret: ""

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为true
  # interface-name: en0 # 出站接口名称

# 本地 SOCKS5/HTTP(S) 服务器认证
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# # 实验性 hosts, 支持通配符（如 *.clash.dev 甚至 *.foo.*.examplex.com ）
# # 静态域的优先级高于通配符域（foo.example.com > *.example.com）
#hosts:
#  'mtalk.google.com': 108.177.125.188
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'
dns:
   enable: true # set true to enable dns (default is false)
   ipv6: false # default is false
   listen: 0.0.0.0:55

linux_arm and linux_arm64 v3.3.1
yq r sample.yaml port  【OK】
yq r sample.yaml dns.enable 【OK】
yq w -i sample.yaml port 1234  【runtime error】
yq d sample.yaml port 【runtime error】
yq m -x -i sample.yaml sample2.yaml 【runtime error】

now i use sed -i 's/#.*//' sample.yaml  to clean all the "# "

**Comment by mikefarah** [comment]
that's not valid yaml- please put valid yaml in a code block, and please let me know which version of yq you are using.

https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by ccssyybb** [comment]
> that's not valid yaml- please put valid yaml in a code block, and please let me know which version of yq you are using.
> 
> https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

version 3.3.2 it solve the problem 。
