### ISSUE TITLE
how to pass environment variable as value

### ISSUE THREAD

**Issue by vikram-katkar** [mikefarah/yq#468]
**Describe the bug**
how to pass environment variable as value?

yq w temp.yaml data.role ${VALUE}

**Comment by mikefarah** [comment]
As you would with any other shell command.

```
export VALUE=cat
yq w temp.yaml data.role $VALUE
```

**Comment by StianOvrevage** [comment]
How is this done on v4, where everything is in a string that will not get expanded by the shell?

**Comment by StianOvrevage** [comment]
This works, even though it's a bit ugly:

`yq eval ".imageTag = \"$GITHUB_SHA\"" deploy/values-old-dev.yaml > deploy/values-dev.yaml`

**Comment by bilalinamdar** [comment]
I tried above it just got me the thing i changed. other parameters got DELETED !

**Comment by bilalinamdar** [comment]
for v4 this works

To change with var
myvar="data:/root"
yq eval ".services.app.volumes[0] = \"$myvar\"" -i docker-compose.yml
Thanks to above command @StianOvrevage

**Comment by sromocki** [comment]
@bilalinamdar 

I still had to escape the double quotes in your above response to get it to work

```bash
yq eval ".services.app.volumes[0] = \"$myvar\"" -i docker-compose.yml
```

**Comment by CarMoreno** [comment]
In a Dockerfile, I created an `ARG` called `VARIABLE` which is set from a `docker-compose.yaml` file. I used this sentence and it worked:

```Dockerfile
ARG VARIABLE
yq -i '.this.is.yourproperty = strenv(VARIABLE)' file.yml
```

**Comment by aerlaut** [comment]
@CarMoreno that inserts the value as a string right? Is there a way to parse VARIABLE into an integer?

**Comment by CarMoreno** [comment]
Yes @aerlaut as string. I did not know a way to parse it into an integer, sorry

**Comment by mikefarah** [comment]
Just use `env(VARIABLE)` instead :)

**Comment by leonarac** [comment]
> Just use `env(VARIABLE)` instead :)

can i get a value from yml file, and store to a variable in a pipeline? im working with azure

**Comment by evelizg** [comment]
Hi @mikefarah 
I need your support please.
I put this shell but doesn't work:
yaml is an environment variable
`yq -i 'del(yaml)' ejemplo_config.yml`
