### ISSUE TITLE
the linux_arm binary cant work in asus router cpu armv7

### ISSUE THREAD

**Issue by ccssyybb** [mikefarah/yq#469]
the linux_arm binary cant work in asus router cpu armv7

**Comment by mikefarah** [comment]
Possibly related: https://github.com/mikefarah/yq/issues/434

For additional info, I'm using https://github.com/mitchellh/gox to cross-compile the binary and using go14.

I don't have access to anything running arm - but the source code is available. If you can find out how to get it working I'd be happy to accept a PR.

**Comment by ccssyybb** [comment]
> Possibly related: #434
> 
> For additional info, I'm using https://github.com/mitchellh/gox to cross-compile the binary and using go14.
> 
> I don't have access to anything running arm - but the source code is available. If you can find out how to get it working I'd be happy to accept a PR.

ok.i use go1.14.4.windows-amd64 compile successfully 
$env:CGO_ENABLED=0
$env:GOOS="linux"
$env:GOARCH="arm"
$env:GOARM=7
go build -o yq_armv7 -trimpath -ldflags "-s -w" ./yq.go
and the size just 3MB

**Comment by ccssyybb** [comment]
go1.14.4.windows-amd64

$env:CGO_ENABLED=0
$env:GOOS="linux"
$env:GOARCH="arm"
$env:GOARM=5
$env:CC="arm-linux-gnueabi-gcc-4.7"
go build  -o yq_arm  ./yq.go

it work!
