### ISSUE TITLE
Version information is sent to STDERR 

### ISSUE THREAD

**Issue by tomncooper** [mikefarah/yq#472]
`yq --version` sends the version string output to standard error, which makes it harder to write scripts to check the installed version number.

version of yq: 3.3.2
operating system: Linux

This may be linked to the changes to address #440. It is not blocker but it means you need to use something like:

```
yq --version 2> >(grep -Po '\d.\d.\d')
```
Instead of the typical:
```
yq --version | grep -Po '\d.\d.\d' 
```

So scripts that used the later will stop working after an updated to 3.3.1+

**Comment by mikefarah** [comment]
yep - unintended side effect sorry! Will look into this.

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.4.0
