### ISSUE TITLE
cmd.print is writing to stderr

### ISSUE THREAD

**Issue by vanneback** [mikefarah/yq#479]
**Describe the bug**
cmd.print , which in this case is used by yq compare, writes output to stderr and not stdout. This makes piping the output more difficult. For example i want to to `yq compare -pp 1.yaml 2.yaml '**' | grep -field` to see if certain values are not set.

version of yq: 3.3.2
operating system: Ubuntu 18.04

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
```yaml
important: info
useless: info
more: info
```

data2.yml:
```yaml
more: info
```

**Command**
The command you ran:
```
yq compare -pp data1.yml data2.yml '**' | grep important`
```

**Actual behavior**

```
-important
-useless
```

**Expected behavior**

```
-important
```

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.4.0
