### ISSUE TITLE
Combine multiple files into a yaml stream

### ISSUE THREAD

**Issue by ghostsquad** [mikefarah/yq#485]
**Is your feature request related to a problem? Please describe.**

Given multiple files, or combine into a yaml stream (document list)

**Describe the solution you'd like**

```shell
yq r dir/*
```

or

```shell
yq s dir/*.yml
```

`s` stands for `stream`

result:

```yaml
foo: bar
---
baz: biz
```

**Describe alternatives you've considered**

This works, but is not as succinct and easy to remember how to do

```bash
awk 'FNR==1 && NR>1 { printf("\n%s\n\n","---") } 1' subdir/*.yml > combined.yaml
```

**Comment by MPV** [comment]
Did something similar today:
`cat dir/* | yq r -d'*' - metadata.name`

Would be nice if it was possible to do:
`yq r -d'*' dir/* metadata.name`

**Comment by ghostsquad** [comment]
cat `dir/*` would only work if you already had the `---` separators between documents, right?

I'm doing this to add that separator:

```shell
$AWK 'FNR==1 && NR!=1 {print "---"}{print}' ./* > __combined.yml
```

**Comment by mikefarah** [comment]
This will work in the next release on v4

**Comment by jlongtine** [comment]
> This will work in the next release on v4

Oh, I'm excited by this... this is a problem I've been trying to solve for a while. Thank you, @mikefarah! 🙏🏻

**Comment by mikefarah** [comment]
Released!

**Comment by ghostsquad** [comment]
just fyi @MPV `cat deploy/*` will not do what you expect if you have any yaml files in there containing multiple "documents". E.g.

> first.yaml
```
foo: bar
```

> second.yaml
```
baz: biz
---
faz: fizz
```

**Comment by mikefarah** [comment]
You should just be able to do something like

```
yq e '.' mydir/*.yaml
```

**Comment by mikefarah** [comment]
Ill put it in the docs somewhere.. hmm

**Comment by mikefarah** [comment]
https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#combining-multiple-files-into-one thoughts?
