### ISSUE TITLE
Validation output regression in 3.3.1

### ISSUE THREAD

**Issue by hottomato4** [mikefarah/yq#486]
When I follow the [Basic - invalid, from stdin](https://mikefarah.gitbook.io/yq/commands/validate#basic-invalid-from-stdin) steps in yq 3.3.1 I do not get the expected output to stderr (although the return code is still correct):
```
$ docker run -it mikefarah/yq:3.3.1 sh 
/workdir # echo '[1234' | yq v -
/workdir # echo $?
1
/workdir # echo '[1234]' | yq v -
/workdir # echo $?
0
```

This worked in 3.3.0:
```
$ docker run -it mikefarah/yq:3.3.0 sh 
/workdir # echo '[1234' | yq v -
14:00:41 main [ERRO] yaml: line 1: did not find expected ',' or ']'
/workdir # echo $?
1
/workdir # echo '[1234]' | yq v -
/workdir # echo $?
0
```
This is a regression of the documented behaviour.

**Comment by bjw-s** [comment]
I see the same behavior in 3.3.4

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.4.0
