### ISSUE TITLE
can I have multiple selectors when filtering?

### ISSUE THREAD

**Issue by jurgenweber** [mikefarah/yq#487]
**Is your feature request related to a problem? Please describe.**
Is there a way to have multiple selectors?

asdf.yaml:
```taml
asdf:
  - a: a
    b: b
    c: c
  - a: d
    b: e
    c: f
```
So when I run:
```bash
yq read asdf.yaml 'asdf.(a==d,b==e)'
```

I have tried many different combinations but am unable to find how to do this:

it could output

```yaml
    a: d
    b: e
    c: f
```

**Comment by jurgenweber** [comment]
after some more research in here, looks like I am not the only one:

https://github.com/mikefarah/yq/issues/458

Is there a way I can chain it up with a pipe?

```
yq read -c asdf.yaml 'asdf.(a==d)' | yq read - .(b==e)
```?

**Comment by llienard** [comment]
Hi,

You can try this :
`yq read asdf.yaml 'asdf.(a==d)' --collect | yq r - '(b==e)'`

This should work but it would be great to support multiple conditions to find elements (with AND and OR operators).

**Comment by mikefarah** [comment]
This is now possible in v4 using `jq` like syntax with the union op: https://mikefarah.gitbook.io/yq/v/v4.x/union
