### ISSUE TITLE
How to install the latest version of yq on Centos

### ISSUE THREAD

**Issue by DaniBet** [mikefarah/yq#488]
Hello,

Do you have any idea of how to install the last version of yq on Centos?

Best regards,
Daniel

**Comment by EngineerReversed** [comment]
Yes, I am working on HPC box containing CentOS on machine. I want to install yq on it. Let us know if `yum` can do it.

_PS : I have seen workarounds of extracting linux zip file and using binary._

**Comment by mikefarah** [comment]
You should be able to download the right binary for your system architecture and off you go.

**Comment by mikefarah** [comment]
Added wget instructions https://github.com/mikefarah/yq/#wget

The checksums are also available in the release if you'd like to check them for security.

**Comment by redlad** [comment]
BINARY=yq_linux_amd64 
sudo wget -q  $(wget -qO- https://api.github.com/repos/mikefarah/yq/releases/latest 2>/dev/null | grep browser_download_url | grep $BINARY\"\$|awk '{print $NF}' ) -o /usr/bin/yq && sudo chmod +x /usr/bin/yq

**Comment by sjkoelle** [comment]
thank you for the useful answer @redlad
