### ISSUE TITLE
Installing yq from source

### ISSUE THREAD

**Issue by sergioRMM** [mikefarah/yq#490]
Hi, we have some network restrictions and our mac workers don't have access to github but through an artifactory remote. How may I install yq without using brew. I tried make install but it tries to get external resources. How may I use the binaries? Thank you for your time answering this question.

Regards.

**Comment by mikefarah** [comment]
The binaries should just work if you get the right one for you system architecture. 

Mac workes as in apple laptops? Try the darwin releases.

**Comment by mikefarah** [comment]
Oh - you may need to get them via wget or some other means other than downloading from a browser. My mac complains that it doesn't trust the binaries from github when I download it via FF.
