### ISSUE TITLE
Select nodes without a given child

### ISSUE THREAD

**Issue by Jamstah** [mikefarah/yq#492]
**Is your feature request related to a problem? Please describe.**
Need to find nodes that are missing a child

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
a:
  b:
    c
```

And we run a command:

```bash
yq read data1.yml "a[!d]"
```

it could output

```yaml
b:
  c
```

**Describe alternatives you've considered**
Nothing compares to this impressively thought out plan.

**Comment by Jamstah** [comment]
Equivalent xpath is: `/root/*[not(c)]`

So this might be related to #458 where you're considering adding `or` and `and` conjunctions

**Comment by mikefarah** [comment]
This is now possible in v4 using `jq` like syntax (see the `not` and `has` operations) https://mikefarah.gitbook.io/yq/v/v4.x/
