### ISSUE TITLE
Writing after deleting content outputs JSON

### ISSUE THREAD

**Issue by driesmeyers** [mikefarah/yq#493]
**Describe the bug**
Deleting the only node in a yaml file and writing new nodes after that results in a json output in my .yaml file

version of yq: 3.3.1
operating system: Ubuntu 18.04.4 LTS

**Input Yaml**
data1.yml:
```yaml
b:
  c: cat
```

**Command**
The command you ran:
```
yq d -i data1.yml b
```
```
yq w -i data1.yml b.c cat
```
**Actual behavior**

```yaml
{b: {c: cat}}
```

**Expected behavior**

```yaml
b:
  c: cat
```

**Comment by mikefarah** [comment]
This is expected...let me explain:

The top level node is a map, which has a single entry `b`. The first command removes `b` which leaves an empty map `{}`.

If you inspect the output, that's what you'll see.

Now when you modify that map to add another key, `b` again in this case, `yq` keeps the formatting of the original doc `{}` and so the bracers remain.

The core thing is deleting the last key of a map leaves an map (as opposed to being nothing). You can use prettyPrint to force the idiomatic yaml style.
