### ISSUE TITLE
unable to read a value with special character

### ISSUE THREAD

**Issue by indraindrajit71** [mikefarah/yq#498]
Hello
I had this yaml :
I am unable to read the value of "kubernetes.io/hostname using :
**yq r storage.yaml "spec.pools[0].nodeSelector[0].kubernetes.io/hostname"**

It returns blank with no output. What am I doing wrong. / being  a special character, also tried a preceding backlash but it doest works. wanted to have "machine-1" as output.

![image](https://user-images.githubusercontent.com/45243018/88024550-89539580-cb50-11ea-84ef-1360af0de607.png)

**Comment by unclesamwk** [comment]
I have the same issue ... ```yq new /etc/openldap/ldap/.conf key
/etc/openldap/ldap/:
  conf: key``

**Comment by aboettger-tuhh** [comment]
same here.

**Comment by aboettger-tuhh** [comment]
> Hello
> I had this yaml :
> I am unable to read the value of "kubernetes.io/hostname using :
> **yq r storage.yaml "spec.pools[0].nodeSelector[0].kubernetes.io/hostname"**
> 
> It returns blank with no output. What am I doing wrong. / being a special character, also tried a preceding backlash but it doest works. wanted to have "machine-1" as output.
> 
> ![image](https://user-images.githubusercontent.com/45243018/88024550-89539580-cb50-11ea-84ef-1360af0de607.png)

whats about

```
yq r storage.yaml 'spec.pools[0].nodeSelector[0]."kubernetes.io/hostname"'
```

**Comment by mikefarah** [comment]
This is also in the docs: https://app.gitbook.com/@mikefarah/s/yq/usage/path-expressions#special-characters

**Comment by Daxiongmao87** [comment]
Excuse me, but why in the world is your documentation behind a non-publicly accessible link ?
