### ISSUE TITLE
yq r -j Sorts the file alphabetically and strip out commented lines, white spaces

### ISSUE THREAD

**Issue by bharti0708** [mikefarah/yq#500]
Problem = yq r -j <values.yaml>
Output is file converted into json and sorted alphabetically, blank lines and comments are stripped out.

Solution I would like : File should be converted to json in its original format.

Example : 
```cat values1.yaml
#Comments


j:
 f:something
b:
  a:something
a:
  g:something

yq r -j values1.yaml
{"a":"g:something","b":"a:something","j":"f:something"}
```

**Comment by mikefarah** [comment]
Hard to tell what exactly you mean here by original format? Originally it was YAML?

JSON doesn't support comments, so naturally they're gone.

The JSON encoder built into go unfortunetly orders keys alphabetically :(, and has no support for whitespace.

The only thing I can suggest is to use the pretty flag to pretty print json

**Comment by mikefarah** [comment]
Closing - order of json keys issue is raised here already https://github.com/mikefarah/yq/issues/435
