### ISSUE TITLE
"on" in JSON is translated to boolean in YAML

### ISSUE THREAD

**Issue by hangxie** [mikefarah/yq#503]
**Describe the bug**
`on` in JSON is translated to boolean in YAML

version of yq: 3.3.2
operating system: ubuntu

**Input JSON**
source.json
```json
{"GO111MODULE": "on"}
```

**Command**
The command you ran:
```
echo '{"GO111MODULE": "on"}' | /go/bin/yq r -P -
```

**Actual behavior**

```yaml
GO111MODULE: on
```

**Expected behavior**

```yaml
GO111MODULE: 'on'
```

**Additional context**
There are several issues discussed similar problem, but I could not find a workaround for `yq r`.

**Comment by mikefarah** [comment]
This is because yq uses the YAML 1.1 spec in which 'on' is no longer considered a boolean. You can force quotes by using the '--style' flag
