### ISSUE TITLE
--exitStatus not working as expected

### ISSUE THREAD

**Issue by joshuaspence** [mikefarah/yq#506]
**Describe the bug**
The `--exitStatus` flag seems to cause `yq read` to always return an error.

version of yq: 3.3.1
operating system: Ubuntu 18.04

**Input Yaml**
```yaml
---
foo: 'bar'
```

**Command**
`yq read test.yaml foo -e`

**Actual behavior**
```
Error: No matches found
```

**Expected behavior**
```
bar
```

**Comment by mikefarah** [comment]
Fixed in 3.3.2
