### ISSUE TITLE
'!!str' tag does not quote big numbers

### ISSUE THREAD

**Issue by msuret** [mikefarah/yq#509]
**Describe the bug**
Passing the `--tag '!!str'` tag does not correctly quote the value after some threshold.
E.g. `1e308` is quoted, but `1e309` is not.

version of yq: 3.3.2

**Command**
The command you ran:
```
yq new --tag '!!str' key 1e309
```

**Actual behavior**

```yaml
key: 1e309
```

**Expected behavior**

```yaml
key: "1e309"
```

**Comment by mikefarah** [comment]
I'm thinking that 1e309 is larger than the biggest integer you can specify, and so it's always a string.

**Comment by mikefarah** [comment]
If you want to force quotes, use this: https://mikefarah.gitbook.io/yq/usage/value-parsing#the-style-flag

**Comment by msuret** [comment]
I still think it's a bug because there is no maximum number size in the YAML specification.
But `--style single` did the trick for me, thanks!
