### ISSUE TITLE
Sort keys `-S` as well as a more 'diff like' output `-D`.

### ISSUE THREAD

**Issue by SleepyBrett** [mikefarah/yq#516]
**Is your feature request related to a problem? Please describe.**
I have two documents, one which will always have keys in sorted order (it's coming off an api) and one that will not. I want to be able to determine what is different between the two.

Currently the only known workaround that I have for doing this in yq is to call `yq compare` with a `-j` flag to convert both documents into json before doing the compare.

The problem being that they output, assuming a difference, is the the whole document twice in json format one prefixed with + the other with -. This makes it very hard to find the actual differences. 

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
aaa: blah
ccc: foo
bbb:
- blah
- hoop
- yada
ddd: bar
```

and data2.yml (sorted) like:
```yaml
aaa: blah
bbb:
- blah
- foo
- hoop
ccc: foo
ddd: baz
eee: yada
```

And we run a command:

```bash
yq compare -SD data1.yml data2.yml
```

it could output.. and I'm just spitballing

```yaml
< bbb:
< - blah
< - hoop
< - yada
> bbb:
> - blah
> - foo
> - hoop
---
< ddd: bar
> ddd: baz
---
> eee: yada
```

**Describe alternatives you've considered**
As I said, `-j` kinda get's me there, but not if I want to actually be able to pin down the actual differences especially when the file gets large.

**Additional context**
none

**Comment by mikefarah** [comment]
V4 has a sort keys operator: https://mikefarah.gitbook.io/yq/v/v4.x/sort-keys

**Comment by SleepyBrett** [comment]
nice!
