### ISSUE TITLE
Where/how to contribute to documentation?

### ISSUE THREAD

**Issue by tfurf** [mikefarah/yq#518]
For example, just on https://mikefarah.gitbook.io/yq/commands/read, the section on `collect` and `length` both have typos/errors (`-C` vs `-c` and `-L` vs `-l`).

Maybe it's just my ignorance with respect to how gitbooks works.

**Comment by mikefarah** [comment]
Oh nice, thanks! gitbook doesn't let you do PRs, and to open it up to other authors you need to $$.

I will fix those errors though

**Comment by mikefarah** [comment]
FWIW I was using github's built in docs before, which does allow other users to make changes, but it was cumbersome and couldn't make pretty docs.

**Comment by tfurf** [comment]
> FWIW I was using github's built in docs before, which does allow other users to make changes, but it was cumbersome and couldn't make pretty docs.

Your project, your choice! Thanks for the fix and the tool in general.
