### ISSUE TITLE
Add support for built-in function 'keys, keys_unsorted'

### ISSUE THREAD

**Issue by kenjones-cisco** [mikefarah/yq#52]
Add support for built-in [function 'keys, keys_unsorted'](https://stedolan.github.io/jq/manual/#example18)

```
The builtin function keys, when given an object, returns its keys in an array.

The keys are sorted “alphabetically”, by unicode codepoint order. This is not an order that makes particular sense in any particular language, but you can count on it being the same for any two objects with the same set of keys, regardless of locale settings.

When keys is given an array, it returns the valid indices for that array: the integers from 0 to length-1.

The keys_unsorted function is just like keys, but if the input is an object then the keys will not be sorted, instead the keys will roughly be in insertion order.
```

**Comment by mikefarah** [comment]
Re opening as there is a strong interest for this feature

**Comment by nat2k5us** [comment]
This would be great feature 👍 
The functionality I am wanting is that the yaml can sort based of a particular order of key array
 for example in swagger.yaml I would like to sort in the order of these top level keys
[swagger, basePath, securityDefinitions, consumes, produces, definitions]

yq -w -i -sort swagger.yaml [swagger, basePath, securityDefinitions, consumes, produces, definitions]

**Comment by mikefarah** [comment]
As far as I can tell, this is now supported in version 3 of yq by doing:

```
yq read document.yaml '**' -pp
```
