### ISSUE TITLE
Merge does not properly preserve object key type 

### ISSUE THREAD

**Issue by dejvid-smth** [mikefarah/yq#522]
**Describe the bug**
When using **yq merge** to merge two files and the second file contains an object with string key that looks like number the key will be number type in the result.

version of yq: 3.3.2
operating system: Ubuntu 18.04

**Input Yaml**
data1.yml:
```yaml
paths: {}
```

data2.yml:
```yaml
paths: 
  '200': {}
```

**Command**
```
yq merge -P data1.yml data2.yml
```

**Actual behavior**

```yaml
paths:
  200: {}
```

**Expected behavior**

```yaml
paths:
  '200': {}
```

**Comment by mikefarah** [comment]
Fixed in 4.5.1!
