### ISSUE TITLE
can't write file inplace from stdin

### ISSUE THREAD

**Issue by qch2012** [mikefarah/yq#526]
**Describe the bug**
I want to do inplace change to a file from stdin ,   however -i option doesn't seem to work

cat test.yaml | yq w -i -  foo bar 
Error: stat -: no such file or directory

version of yq:  3.3.2
operating system: centos7

**Input Yaml**
test.yaml:
foo: test

**Command**
cat test.yaml | yq w -i - foo bar

**Actual behavior**
cat test.yaml | yq w -i - foo bar
Error: stat -: no such file or directory

**Expected behavior**
file is modified inplace

**Comment by mikefarah** [comment]
using inplace does not make sense with STDIN - you can't modify STDIN inplace. You need to pass the file if you want to do that
