### ISSUE TITLE
Added field on JSON is not well formated

### ISSUE THREAD

**Issue by sebglon** [mikefarah/yq#527]
**Describe the bug**

version of yq:  3.3.2
operating system: Ubunt

**Input JSON**
Concise yaml document(s) (as simple as possible to show the bug)
sample.json:
```json
{
 "KEY_A": "VALUE_A",
 "KEY_C": "VALUE_C"
}
```

**Command**
The command you ran:
```
yq w -i small.json KEY_B --style=double VALUE_B
```

**Actual behavior**

```json
{"KEY_A": "VALUE_A", "KEY_C": "VALUE_C", KEY_B: "VALUE_B"}
```
Format is lost and `KEY_B` does not have double quotes

**Expected behavior**

```json
{
 "KEY_A": "VALUE_A",
 "KEY_C": "VALUE_C",
 "KEY_B": "VALUE_B"
}
```

**Additional context**
The `-P` arg break the JSON and replace it by YAML format

**Comment by sebglon** [comment]
It work if we set the arg `-j`

**Comment by mikefarah** [comment]
Yep use the ```-j``` flag - this is primarily a yaml editor and so defaults to yaml formatting (no quotes for keys).
