### ISSUE TITLE
create bash arrays from yaml lists

### ISSUE THREAD

**Issue by splaisan** [mikefarah/yq#530]
I would like to use a yaml file to create a number of bash arrays which I need in my code for validation

Could you please send me in the right direction?

 Thanks in advance

The following example shows what I aim at

```
## allowed actions
action:
  - create
  - edit
  - delete

# allowed types
type:
  - standard
  - special
```

running a **yq** bash command (?) will set and export two arrays with content:

```
>echo ${action[@]}
create edit delete

>echo ${type[@]}
standard special
```

**Comment by mikefarah** [comment]
You can do that using readarray:

```
readarray action < <(./yq r examples/sample.yaml 'action[*]')
readarray type< <(./yq r examples/sample.yaml 'type[*]')
```

**Comment by splaisan** [comment]
> You can do that using readarray:
> 
> ```
> readarray action < <(./yq r examples/sample.yaml 'action[*]')
> readarray type< <(./yq r examples/sample.yaml 'type[*]')
> ```

Hi Mike, this is a bash 4 command and I have only 3 on my mac, could you implement the readarray part in yq to make it more universal?
Anyway it is good to know about it.
Thanks a lot for the info and code example

**Comment by iainsproat** [comment]
It should be possible without readarray by using a while loop, as follows:

```bash
while IFS= read -r value; do
    action+=($value)
done < <(yq eval '.action' "examples/sample.yaml)
```

**Comment by c33s** [comment]
4.x syntax:
```
readarray action < <(./yq eval examples/sample.yaml 'action[]')
```
with the old syntax `[*]` you get `Error: '' expects 2 args but there is 1` so you have to switch to `[]`

**Comment by mikefarah** [comment]
Thanks @c33s - I've just added this to the tips page:  https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#create-bash-array

**Comment by nrichard21** [comment]
I've found that using 
```
readarray action < <(./yq r examples/sample.yaml 'action[*]')
```
causes an additional newline character to be appended to the elements in `action`, e.g. `echo "|${action[1]}|"` outputs
```
|edit
|
```

Instead you can use
```
action=($(./yq r examples/sample.yaml 'action[*]'))
```
then `echo ${action[@]}` still outputs `create edit delete` and `echo "|${action[1]}|"` outputs
```
|edit|
```

**Comment by fardarter** [comment]
Any chance of a mac version of this? No readarray on macOS

**Comment by splaisan** [comment]
> Any chance of a mac version of this? No readarray on macOS
meanwhile I installed bash v5 via macport (you could do with other package managers) and I can use additional syntaxes like readarray

**Comment by fardarter** [comment]
For the sake of anyone with a similar issue, this let's me act on each object in the list individually.

```yaml
list:
  - name: aname2
    key1: value
    key2: "ip-address"
  - name: aname1
    key1: value
    key2: "value"
```

```bash
actions=$(yq e -o=j -I=0 '.list[]' list.yaml)

while IFS=\= read action; do
    echo "$action" | yq e '.name'
done <<EOF
$actions
EOF
```

**Comment by techouse** [comment]
Or you could just loop over the items that `yq` gives you, i.e.

```bash
for action in $(yq -r '.list[]' list.yaml); do
  # do your validation here
done
```

**Comment by aukevanleeuwen** [comment]
> 4.x syntax:
> 
> ```
> readarray action < <(./yq eval examples/sample.yaml 'action[]')
> ```
> 
> with the old syntax `[*]` you get `Error: '' expects 2 args but there is 1` so you have to switch to `[]`

Like @nrichard21 is saying this will add a newline at the end of the items. You can avoid that with using `readarray -t` (https://helpmanual.io/builtin/readarray/).

```shell
readarray -t action < <(./yq eval examples/sample.yaml 'action[]')
```

@mikefarah maybe good to change on the best practices page since since it seems to me that this would be wanted behaviour?
