### ISSUE TITLE
Passing multiple keys/values on one line

### ISSUE THREAD

**Issue by kamzar1** [mikefarah/yq#531]
Passing multiple keys / values / lists on a single line would make it easier in bash to use arrays as new values.
Arrays can be defined as "" or '' or comma separated or any other way?
yq parses the array and for each value executes the same command.

Scenario 1:
yq w -i sample.yaml a.b.c cat
yq w -i sample.yaml a.b.d dog

New feaurture:
yq w -i sample.yaml "a.b.c cat; a.b.d dog"

Scenario 2:
yq w -i sample.yaml b.c[+] cat
yq w -i sample.yaml b.c[+] dog
would return:
b:
  c:
    - cat
    - dog

New feature:
yq -i sample.yaml write b.c[++] "cat dog fish"; delete b.c. mouse; create b.c.f ok

would return:
b:
  c:
    - cat
    - dog
    - fish
      f: ok

**Comment by mikefarah** [comment]
this is now possible in yq v4, which uses jq like syntax
e.g

```
yq eval '.a.b.c = .a.b.c + [1,2,3]' sample.yaml
```
