### ISSUE TITLE
Bump choco build

### ISSUE THREAD

**Issue by mikefarah** [mikefarah/yq#534]
Hey @chillum could you please bump the choco build to 3.3.4

**Comment by vasily-codefresh** [comment]
@mikefarah sure. is there a chance you have sha256 hashes for windows builds (both x86 and x64) at hand to speed me up?

**Comment by vasily-codefresh** [comment]
heck, I'd better use @chillum account next time, was too lazy to log off =(

**Comment by mikefarah** [comment]
Sure, the checksums file has checksum for each binary with a variety of hashes, including sha256 (via https://github.com/rhash/RHash)

**Comment by mikefarah** [comment]
In bash you can:

```
cat checksums| awk '/yq_windows/ {print $1" "$19}'
```

**Comment by vasily-codefresh** [comment]
ok, done. [commit](https://github.com/chillum/choco-packages/commit/18dc793e3de6c891ffde780f0f739041427069a8), [package](https://chocolatey.org/packages/yq/3.3.4)

**Comment by mikefarah** [comment]
Cheers!
