### ISSUE TITLE
Ability to merge all docs in a YAML into a single one

### ISSUE THREAD

**Issue by mattymo** [mikefarah/yq#535]
**Is your feature request related to a problem? Please describe.**
It's possible to merge multidoc YAMLs, but I want to combine all docs in a YAML file into a single doc, where the last doc has priority over the previous one.

**Describe the solution you'd like**
```
echo << EOF > values.yaml
---
foo:
  bar: value
---
bar:
  something: value
---
foo:
    baz: value
EOF
yq m -i -d'*' values.yaml
cat values.yaml
```
---
foo:
  bar: value
  something: value
  baz: value
```

**Describe alternatives you've considered**
This would be possible by writing each YAML doc to a separate file, but that method is rather tedious.

**Additional context**
I'm trying to solve an issue in helmfile that would allow me to determine which user-generated values changed prior to running a "helm upgrade" command. The issue is that the rendered YAMLs appear as a list of YAMLs. If I use sed to change the list into separate YAML docs in a single file, I nearly can solve the issue.
https://github.com/roboll/helmfile/issues/1460#issuecomment-691026205

**Comment by mikefarah** [comment]
Without trying this myself, you should be able to do this with multiple yq commands: e.g.:

```
yq merge $(yq r document.yaml -d0)  $(yq r document.yaml -d1) $(yq r document.yaml -d2)
```

**Comment by mikefarah** [comment]
oh wait not that won't work :( silly me

**Comment by mikefarah** [comment]
Yeah I can only think of what you were saying, using temp files - something like this means you dno't have to manually create the files:

https://unix.stackexchange.com/questions/495254/creating-a-temporary-file-from-standard-input

**Comment by mikefarah** [comment]
this is now possible in v4 alpha, see https://app.gitbook.com/@mikefarah/s/yq/v/v4.x/multiply and https://app.gitbook.com/@mikefarah/s/yq/v/v4.x/document-index

**Comment by flavono123** [comment]
how?

> this is now possible in v4 alpha, see https://mikefarah.gitbook.io/yq/v/v4.x/multiply and https://mikefarah.gitbook.io/yq/v/v4.x/document-index

**Comment by flavono123** [comment]
i have found [this](https://stackoverflow.com/questions/66694238/merging-two-yaml-documents-while-concatenating-arrays), using `ireduce` rather thant `di`.
