### ISSUE TITLE
version output goes to stderr instead of stdout

### ISSUE THREAD

**Issue by Alexhha** [mikefarah/yq#537]
**Describe the bug**
It's not a common practice to use STDERR for such things

version of yq: 3.3.4
operating system: CentOS7

**Command**
The command you ran:
```bash
$ yq --version
```

**Actual behavior**

```bash
$ yq --version > test.txt
$ cat test.txt
```

**Expected behavior**

```bash
$ yq --version > test.txt
$ cat test.txt
yq version 3.3.4
```

**Additional context**

**Comment by Alexhha** [comment]
BTW

yq 3.3.0 use STDOUT, but 3.3.1 use STDERR

**Comment by mikefarah** [comment]
Fixed in https://github.com/mikefarah/yq/releases/tag/3.4.0
