### ISSUE TITLE
Ability to sort output by keys

### ISSUE THREAD

**Issue by cnlics** [mikefarah/yq#538]
**Is your feature request related to a problem? Please describe.**
in version 2.x, after merge, the result will list key and value sorted by key name and clear all comment.
in version 3.x, no this function, in the doc of 3.x, that is default feature of sort by key name. but the result is not and there is no this args to sort, seems caused by this feature: "Keeps yaml formatting and comments when updating"

**Describe the solution you'd like**
is there some args to sort and clear comments ?

for example:

file1:
a: aaa
#comment 
c: ccc

file2:
b: bbb
f: fff

when : yq m file1 file2 > temp
the content in temp:
a: aaa
b: bbb
c: ccc
f: fff

**Comment by mikefarah** [comment]
There's no sort, but there is a strip comments flag: https://mikefarah.gitbook.io/yq/usage/output-format#strip-comments

**Comment by mikefarah** [comment]
Sort keys is now available in v4 
https://mikefarah.gitbook.io/yq/v/v4.x/sort-keys
