### ISSUE TITLE
Reading non-existing property 

### ISSUE THREAD

**Issue by j-zimnowoda** [mikefarah/yq#539]
**Describe the bug**
If you try to read non existing property the yq exits with 0 code.

version of yq: 3.3.0
operating system: MacOS

**Input Yaml**
data1.yml:
```yaml
this: should really work
```

**Command**
The command you ran:
```
echo 'this: should really work' | yq r - 'nnn' ```

**Actual behavior**

exit with zero

**Expected behavior**

should exit with error code, e.g: 1

**Comment by mikefarah** [comment]
You'll need to use the `--exitStatus` flag if you want it to fail when there are no matches.

**Comment by j-zimnowoda** [comment]
@mikefarah Thanks for hint. 
In version 3.3.0 I don't see it.
In which version it was introduced ?

**Comment by hrvoj3e** [comment]
Still missing in help. :) Would be nice to have it there also.

```shell
./yq_linux_amd64 -V
yq version 3.4.1

./yq_linux_amd64 -h | grep -i exit

./yq_linux_amd64 r --exitStatus proxy.yml aaa.bbb; echo $?;
Error: No matches found
1
```
