### ISSUE TITLE
yq validate not working

### ISSUE THREAD

**Issue by jonassteinberg1** [mikefarah/yq#540]
**Describe the bug**
# returns nothing
echo '[1234' | yq v -

version of yq: 3.3.3
operating system: macOS Catalina 10.15.6 | Darwin Kernel Version 19.6.0

**Input Yaml**
# see simple test above

**Additional context**
1) other functions work
2) zsh 5.8 (x86_64-apple-darwin19.3.0)
3) oh-my-zsh is update to date

**Comment by mikefarah** [comment]
Fixed in 3.4.0

**Comment by mikefarah** [comment]
wait - I thought I was closing another issue

**Comment by ehernandez-xk** [comment]
Hello all!

Same issue here:

cat invalid.yaml
```
:xxx
s]ss<
```

```
cat invalid.yaml | yq v -
echo $?
0
```

**Comment by mikefarah** [comment]
Though I have no idea why - that invalid.yml validates in all the online yaml validation tools I tried.

*shrug*

Willing to reopen this issue if the provided yaml is valid in yq but invalid in other yaml parsers.

**Comment by mikefarah** [comment]
Sample linters for reference:

https://onlineyamltools.com/validate-yaml
http://www.yamllint.com/

**Comment by ehernandez-xk** [comment]
@mikefarah tks for your time.
regarding of the output, is this a bug?

```
cat invalid.yaml | yq r - some.value
:xxx s]ss<
```
some.value key does not exist and the yq output is not correct.
many thanks

**Comment by maheshsadhanagiri** [comment]
yq v test.yml 
this is not working when I used in Powershell , other yq commands are working fine. I am getting following error.

PS C:\yq> yq v test.yml
Error: 1:1: invalid input text "v"

**Comment by jtristan-pinc** [comment]
Not working for me either

**Comment by anschnapp** [comment]
i also get the same error as @maheshsadhanagiri version is 4.30.8

i guess this tickert should be reopened

**Comment by mikefarah** [comment]
Ah those commands from from v3 - v4 has changed quite a bit, it's much more like `jq` now. 

For validation take a look at this: https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#validating-yaml-files

For general advice about moving from v3 to v4: https://mikefarah.gitbook.io/yq/upgrading-from-v3
