### ISSUE TITLE
Issues writing values containing curly braces {{ value }}

### ISSUE THREAD

**Issue by JamesDowning** [mikefarah/yq#543]
**Describe the bug**
Currently no way to literally write {{ value }} into a file without any quotation marks.

version of yq:  `yq version 3.3.3`
operating system: macOS Mojave

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
```yaml
key: value
```

**Command**
The command you ran:
```
yq write -i data1.yaml key {{ .Release.Namespace }}
```

**Actual behavior**

```
Error: Must provide <filename> <path_to_update> <value>
Usage:
  yq write [yaml_file] [path_expression] [value] [flags]
...
```

**Expected behavior**

```yaml
key: {{ .Release.Namespace }}
```

**Additional context**
Surrounding the value with quotes does pass the value successfully but the resulting value will also be surrounded by the same quotation marks.

**Comment by mikefarah** [comment]
Curly braces are special characters in yaml - as yaml is a superset of JSON.

It will need quotes around it if you want the string values.
