### ISSUE TITLE
Incorrect command in "Delete from all documents" documentation section

### ISSUE THREAD

**Issue by Szymongib** [mikefarah/yq#545]
**Describe the bug**

Just a small issue as the command in [Delete from all documents](https://mikefarah.gitbook.io/yq/commands/delete#delete-from-all-documents) doc is invalid.

Did not find where can I fix it, so I figured to create an issue.

**Command**
The command in docs:
```
yq w -d'*' sample.yaml field
```

**The proper command**
```
yq d -d'*' sample.yaml field
```

**Comment by mikefarah** [comment]
Fixed! Thanks for finding and raising
