### ISSUE TITLE
Container image seems to have a high severity vulnerability

### ISSUE THREAD

**Issue by pbnj** [mikefarah/yq#550]
**Describe the bug**
The image used to build `yq` seems to have high security vulnerability.

version of yq: 
Tested `latest` and `3`

**Input Yaml**

N/A

**Command**

N/A

**Actual behavior**

N/A

**Expected behavior**

N/A

**Additional context**

It's likely that all that's needed is to bump the alpine minor version of alpine image used [here](https://github.com/mikefarah/yq/blob/master/Dockerfile#L15) from `3.8` to `3.12`.

**Screenshot**

![Screen Shot 2020-09-30 at 1 45 07 AM](https://user-images.githubusercontent.com/6811830/94664089-5865ae80-02bf-11eb-88be-c0e6bc8687f0.png)

Happy to submit a PR for this.

**Comment by mikefarah** [comment]
Nice - I'd accept a PR :)
