### ISSUE TITLE
Creating multiarch docker images

### ISSUE THREAD

**Issue by bahetiamit** [mikefarah/yq#555]
**Is your feature request related to a problem? Please describe.**
I came across this tool while using tektoncd. We were executing test cases of tecktoncd on POWER(ppc64le) platform but were not able to execute them as the yq docker image which is used for tests is only available for amd64.

**Describe the solution you'd like**
Automate building docker images using _**docker buildx**_  (https://docs.docker.com/buildx/working-with-buildx/) which can build for multiple supported architectures & take care of manifests and push the image to docker repo using github action. I have seen few repos already doing this making the process simple. Alternatively, script can also be created which can do the same if github actions is not preferred at this point.

**Describe alternatives you've considered**
The only alternative is to build and push the image ourselves. This tool should be readily available as multiarch image on all the supported architectures making it easier for other tools to use yq on other platforms.

**Additional context**
I see an old issue https://github.com/mikefarah/yq/issues/395 which was raised and yet to be worked upon. I can work on this  and submit the required PR.

**Comment by mikefarah** [comment]
Cool - yeah I'd definitely take a PR for that
