### ISSUE TITLE
Update v3 branch to be current

### ISSUE THREAD

**Issue by travisgroth** [mikefarah/yq#564]
**Is your feature request related to a problem? Please describe.**

When using github actions to reference this repo, I'd like to reference a major release branch/tag like mikefarah/yq@v3.  There is currently a `v3` branch, but it is significantly behind the latest release to 3.x.

**Describe the solution you'd like**

Update the v3 branch (or make it a tag) line up with with 3.x releases.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mikefarah** [comment]
I've changed v3 to a tag, and put it inline with 3.4.1

**Comment by travisgroth** [comment]
@mikefarah thanks!
