### ISSUE TITLE
brew formula is missing shell completions

### ISSUE THREAD

**Issue by isaacl** [mikefarah/yq#565]
See Homebrew/homebrew-core#62927

**Comment by mikefarah** [comment]
I'm guessing there's something that can be done in the brew formula...any know how? Or maybe an example from another brew that could be copied?

**Comment by isaacl** [comment]
Yes it's a formula thing.

These have completions:
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/hub.rb
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/awscli.rb

**Comment by mikefarah** [comment]
Looks like someone has updated the formula to include completions
