### ISSUE TITLE
validate does not work

### ISSUE THREAD

**Issue by michaelajr** [mikefarah/yq#572]
**Describe the bug**

```
yq v some.sh
```

(where some.sh is a bash script)

exits 0

Seems that should fail. Am I missing something?

version of yq: 3.4.1
operating system: Mac

**Comment by janneppi** [comment]
Isn't this tool only for .yaml files and not .sh?

**Comment by michaelajr** [comment]
@janneppi yes. yes it is. I still expect a non 0 exit when the contents of a file is not valid yaml. To me, nothing in stderr and exit 0 means SUCCESS. And obviously it was not successful.

**Comment by janneppi** [comment]
Hmm...yes, kinda makes sense. One interesting finding as well, if I have a file with yaml content in it named yaml.sh and another file file.yaml the tool won't mege the yaml.sh to the file.yaml. So maybe the tool just ignores all other extensions than .yaml.

**Comment by michaelajr** [comment]
It will read other files. yq r foo.sh spits out the contents all on one line - like it tried to format it. It is a nice tool.

**Comment by mikefarah** [comment]
You might find that the contents of your shell file is actually valid yaml - try an online yaml validation tool.

Otherwise, I'll need some sort of sample to be able to replicate the bug...
