### ISSUE TITLE
`yq merge` - empty value not interpreted as empty object

### ISSUE THREAD

**Issue by ryanmcnamara** [mikefarah/yq#576]
**Describe the bug**
When merging a key that does not have a value, the existing value is deleted. This doesn't seem right, I believe but I'm not sure that the empty value should be considered the empty object

a.yml
```
a:
  x: "0"
```

b.yml
```
a:
```

execute
```
yq m -a=append a.yml b.yml -P > actual.yml
```

actual.yml:
```
a:
```

expected.yml:
```
a:
  x: "0"
```

I suspect the reason for this is that the type of `a` in `b.yml` is not able to be inferred, so it defaults to overriding.
I think interpreting an empty value as the empty object would be much more intuitive. A workaround for this is to explicitly state the value is the empty object.

change b.yml
```
a: {}
```

Now, 
execute
```
yq m -a=append a.yml b.yml -P > actual.yml
```

actual.yml:
```
a:
  x: "0"
```
As desired / expected. This workaround is pretty cumbersome though.

**Comment by mikefarah** [comment]
I looked up the yaml 1.2 spec, it says the empty value is parsed as null

https://yaml.org/spec/1.2/spec.html#id2805071

Going to close this issue as I think it's working to spec
