### ISSUE TITLE
Numeric keys are converted to strings when merging.

### ISSUE THREAD

**Issue by bferg88** [mikefarah/yq#577]
**Describe the bug**
Numeric keys are converted to strings when merging two yaml files, but maybe only for files following the first one. 
I'm quite certain that numeric keys are valid yaml, though I can't definitely point at a spec for that one except to say that yamllint (python) doesn't mind it and a few discussion threads seem to think it's fine.

My guess is there is some conversion to JSON happening during the merge. Since numeric properties are invalid JSON, they are probably implicitly converted to strings. 

version of yq: 3.3.4 and 3.3.2
operating system: Ubuntu

**Input Yaml**
data1.yml:
```yaml
100: this key is a number
```

data2.yml:
```yaml
200: this key is a number too
```

**Command**
The command you ran:
```
yq merge data1.yml data2.yml
```

**Actual behavior**

```yaml
100: this key is a number
"200": this key is a number too
```

**Expected behavior**

```yaml
100: this key is a number
200: this key is a number too
```

**Comment by Hammond95** [comment]
@mikefarah it seems to me that yq is not able to differentiate between a numeric and a string key:

case 1:
```yaml
"10": "num-sting"
```

case 2:
```yaml
10: "num"
```

case 1 and case 2 are both valid yaml. Is there and can coexists in the same yaml file. Is there any way to differentiate between the two in the yq query?
