### ISSUE TITLE
empty yaml hash should produce empty json object, not null

### ISSUE THREAD

**Issue by mjcherbert** [mikefarah/yq#579]
$ echo 'a: ' | yq -c
{"a":null}

(should produce '{"a":{}}')

$ echo 'a: ' | yq -y
a: null

(round-trip should produce 'a:' or 'a: ')

unsure whether these are correct behaviour, but might make honouring the above more difficult:

$ echo 'a: {}' | yq -c
{"a":{}}
$ echo '{"a":{}}' | yq -y
a: {}

**Comment by mjcherbert** [comment]
another option might be to let the user decide what to do with an empty hash when doing yaml->json - either mogrify into a null (current behaviour) or an empty object (desired behaviour) ... clearly there will be knock-on issues when doing json->yaml ...

**Comment by mjcherbert** [comment]
... this might be a standards thing: https://yaml.org/spec/1.2/spec.html#id2761292

**Comment by mikefarah** [comment]
yep it's a standards thing, empty node is null (https://yaml.org/spec/1.2/spec.html#id2805071)
