### ISSUE TITLE
prettyPrint not compatible with style flag

### ISSUE THREAD

**Issue by fty4** [mikefarah/yq#581]
**Describe the bug**
The flag `--prettyPrint` is not compatible with `--style`.
If I do not use the `--prettyPrint` flag the output is correct.

version of yq: yq version 3.4.1
operating system: Ubuntu 20.04.1 LTS

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
file.yml:
```yaml
my:
  value: 10:32:03
```

**Command**
The command you ran:
```
yq w --inplace --style double --prettyPrint file.yml 'my.value' $(date +"%H:%M:%S")
```

**Actual behavior**

```yaml
my:
  value: 10:36:44
```

**Expected behavior**

```yaml
my:
  value: "10:36:44"
```

**Comment by mikefarah** [comment]
Ah yep - prettyPrint just recursively sets the style to "" which has the affect of forcing the yaml to have a default format.

In v4 (coming soon) you will be able to control styling better
