### ISSUE TITLE
`yq compare` silently ignores files with multiple documents 

### ISSUE THREAD

**Issue by steakunderscore** [mikefarah/yq#583]
**Describe the bug**
When using `yq compare`, if the yaml files contain multiple yaml documents, only the first document is compared. The output from yq is misleading as the output is that of two identical documents, but the files can be completely different. 

Ideally yq would either output the diff of all documents, or at least fail hard stating that it couldn't compare all objects, or something better. After having a quick look I couldn't see any docs talking about mult doc files, maybe updating the docs might also be a good option also.

installed using: `GO111MODULE=on go get github.com/mikefarah/yq/v3`
version of yq: yq version 3.4.1
operating system: Ubuntu 18.04.5 LTS

**Input Yaml**
data1.yml:
```yaml
---
a: "a"
---
b:
  - 1
```

data2.yml:
```yaml
---
a: "a"
---
b:
  - 2
```

**Command**
The command you ran:
```
yq compare data1.yml data2.yml
```

**Actual behaviour**

The output to stdout is empty

The exit status code:
```
echo $?
0
```

**Expected behaviour**

The output to stdout:
```
 b:
-  - 1
+  - 2
```

With the exit code:
```
echo $?                       
1
```

**Additional context**

**Comment by steakunderscore** [comment]
With a bit more issue hunting I found #16, which this might be a dup of.

**Comment by mikefarah** [comment]
In v3, by default, it only runs against the first document, you'll need to set the document flag to '*' for all docs.

Note that in v4, the default is all docs
