### ISSUE TITLE
Rename/rebrand project

### ISSUE THREAD

**Issue by WibblyDibbler** [mikefarah/yq#584]
_yq_:  a lexical derivative of _jq_ - named to induce adoption?  **Bah!**  Consider

- **yk**
  - ID
    - F6847B1E-235D-4662-AD99-A9ACB063E89F
  - Meaning
    - **y**aml **k**nife
    - **y**u**k** (laugh every time)
    - **y**ou **k**now... [that thing I was trying to do - what was it]
- **oy**
  - ID
    - 8FD791B3-E8FC-4A76-B558-9D22B485D7AA
  - Meaning
    - **o**nly **y**aml...
    - **o**ver **y**onder (identifying a gnarly section)
- **g****f****y**
  - ID
    - 59EC461F-638E-4882-B2DE-9ADD2F363606
  - Meaning
    - **g**o / **f**ind in **y**aml
    - [term of endearment]

**Comment by mikefarah** [comment]
Nice - `yk` is pretty cool "yaml knife" like a swiss army knife.

However, I can't bring myself to go through the whole renaming thing. Not at this stage anyway
