### ISSUE TITLE
Inconsistent treatment of sexagesimal when converting from JSON to YAML

### ISSUE THREAD

**Issue by sjwl** [mikefarah/yq#587]
**Describe the bug**
Treatment of potential strings that look like sexagesimal numbers are not consistent with strings that look like other numbers like integers and floats.

version of yq: `3.3.0`
operating system: `alpine`

**Command**
The command you ran:
```
echo '{"foo": "9:00"}' | yq r - -P
```

**Actual behavior**

```yaml
foo: 9:00
```

**Expected behavior**

```yaml
foo: "9:00"
```

**Additional context**
```
echo '{"foo": "9.00"}' | yq r - -P
```
produces
```yaml
foo: "9.00"
```
notice the double quotes around the value

**Comment by mikefarah** [comment]
So yaml puts quotes around the `9.00` so it knows it's a string and not a number - it does the same thing with boolean values like `true`. With `9:00` - there is no built in type for sexagesimal, and so it is recognised as a string, even without quotes. Just like `cat` would be.

**Comment by sjwl** [comment]
@mikefarah 
> there is no built in type for sexagesimal

It is in the YAML spec: https://yaml.org/type/float.html

### Example 1. !!float Examples
```
canonical: 6.8523015e+5
exponentioal: 685.230_15e+03
fixed: 685_230.15
sexagesimal: 190:20:30.15
negative infinity: -.inf
not a number: .NaN
```

**Comment by sjwl** [comment]
As you can see, the string that looks like a `sexagesimal` is the only one *not* wrapped in quotes:
```
bash-5.0$ echo '{"foo": "6.8523015e+5"}' | yq r - -P
foo: "6.8523015e+5"
bash-5.0$ echo '{"foo": "685.230_15e+03"}' | yq r - -P
foo: "685.230_15e+03"
bash-5.0$ echo '{"foo": "685_230.15"}' | yq r - -P
foo: "685_230.15"
bash-5.0$ echo '{"foo": "190:20:30.15"}' | yq r - -P
foo: 190:20:30.15
bash-5.0$ echo '{"foo": "-.inf"}' | yq r - -P
foo: "-.inf"
bash-5.0$ echo '{"foo": ".NaN"}' | yq r - -P
foo: ".NaN"
```

**Comment by mikefarah** [comment]
Oh I see - I had no idea that it was supported. Though I also noticed that those docs are for the yaml 1.1 spec, whereas the 1.2 spec (which is what the underlying [go-yaml library supports](https://github.com/go-yaml/yaml/tree/v3)) does not (https://yaml.org/spec/1.2/spec.html#id2804092), you can also see the different the the regular expression for floats in 1.1 vs 1.2.

In 1.2 it seems they have taken a number of things out of the 1.1 spec - guess they must have been trying to simplify the standard.

**Comment by mikefarah** [comment]
Funnily enough it's documented in wikipedia more clearly: https://en.wikipedia.org/wiki/Sexagesimal#YAML
