### ISSUE TITLE
I want no automatic conversion of datetime types

### ISSUE THREAD

**Issue by TobyHFerguson** [mikefarah/yq#590]
**Describe the bug**
When I translate a yaml file containing the following key/value pair:

```
Version: 2012-10-17
```
using
```
yq -j r 
```
I get back the 'timezone corrected' value:

```
"Version": "2012-10-17T00:00:00Z"
```

which breaks Cloudformation's notion of what a 'Version' is.

I need some way of telling yq 'treat datetime types as strings; don't convert them' (and I want to do that without having to modify the  yaml itself'

version of yq: 
```
docker run --rm -v ${PWD}:/workdir mikefarah/yq yq --version
yq version 3.4.1
```
operating system: `Don't now

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug)
data1.yml:
```yaml
Version: 2012-10-17
```
output:
```
{"Version":"2012-10-17T00:00:00Z"}
```

**Command**
The command you ran:
```
echo Version: 2012-10-17 >yq-bug.yaml
docker run --rm -v ${PWD}:/workdir mikefarah/yq yq -j r /workdir/yq-bug.yaml
```

**Actual behavior**

**Expected behavior**

What I'm wanting to do is somehow tell yq NOT to convert that Version string to a timezone - I want it left alone!

**Additional context**
This is for processing Cloudformation templates where datetime strings are used extensively as version strings.

**Comment by mikefarah** [comment]
Oh I see. Looking into this, yaml as a `timestamp` type, and that value matches that type (see https://yaml.org/spec/1.2/spec.html).

What's happening is, when converting to JSON, it serializes a timestamp value, which defaults to the ISO formatted datetime string.

What you need to do, is quote the value in yaml to force it to be a string, for instance:

```
yq w yq-bug.yaml --style="single" '**' -j
```

**Comment by TobyHFerguson** [comment]
Yeah - unfortunately this use of yq is in the middle of a pipeline (generated by `docker compose convert --format yaml` should you care to wonder!) and to put quotes around the value would require parsing the yaml for which I'd use `yq`, but I think by then its too late. Would it be useful to at least have a flag that said something like 'don't do type conversions'? That's what I'd like, but maybe mine is such an odd case its not worth it? ...

**Comment by TobyHFerguson** [comment]
oh - and thanks for making this `yq` - I'm very familiar with `jq` so I'm looking forward to working more with `yq` as I play with more yaml!
