### ISSUE TITLE
Print several keys at the same time

### ISSUE THREAD

**Issue by gavenkoa** [mikefarah/yq#598]
I want to extract name+size pairs from multi-document yaml file.

How can I do it with simple one liner?

My attempt was: `yq r -d '*' instances.yml  'name,disks[0].diskSizeGb'`

**Comment by mikefarah** [comment]
Use v4 👍 it in beta atm - but should be promoted soon (~ week)
https://mikefarah.gitbook.io/yq/v/v4.x/union#combine-selected-paths
