### ISSUE TITLE
In place update fails when YAML file is in a directory named "bin"

### ISSUE THREAD

**Issue by cryptarchnoble** [mikefarah/yq#599]
**Describe the bug**
It seems that YQ throws the following error whenever trying to perform an in-place update of a YAML file and the YAML file is inside a directory named "bin".

Version of yq: 3.4.1
Operating system: ubuntu 18.04
Installed via: snap

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)

The following succeeds:
/home/user/test.yml:
```yaml
test: result
```
command: yq w -i /home/user/test.yml test "working"

The following also succeeds:
/home/user/conf/test.yml:
```yaml
test: result
```
command: yq w -i /home/user/conf/test.yml test "working"

The following fails:
/home/user/bin/test.yml:
```yaml
test: result
```

yq w -i /home/user/bin/test.yml test "working"
01:18:10 safelyRenameFile [ERRO] Failed copying from /tmp/temp797223154 to /home/user/bin/test.yml
01:18:10 safelyRenameFile [ERRO] open /home/user/bin/test.yml: permission denied

**Additional context**

Tried this with multiple user accounts, including root.

**Comment by mikefarah** [comment]
Tried it locally without snap, it works fine.

This will be a snap issue for sure - it has this concept of 'confinements' for apps (https://github.com/mikefarah/yq/#snap-notes) and https://snapcraft.io/docs/snap-confinement - even running yq in sudo does not allow it to break its confinement.
