### ISSUE TITLE
Tar Downloads

### ISSUE THREAD

**Issue by erwbgy** [mikefarah/yq#600]
**Please describe your feature request.**
Some download managers do not set the execute bit on downloaded files and others disallow files without known extensions.

**Describe the solution you'd like**
Package each binary in a tar.gz so that it has a well-known extension and preserves the execute bit when unpacked.

**Describe alternatives you've considered**
Fixing these download managers would be the proper solution but this is not always straight-forward.

**Additional context**
Smaller files to store and download are also a benefit.

Perhaps v4 would be an opportunity to make this change without disrupting existing users too much.

**Comment by mikefarah** [comment]
How annoying - which download manager are you using?

**Comment by erwbgy** [comment]
As with most big corporates, downloads of external software go through a scanning and vetting process and whatever software is used there causes the issues.  I know I'm not the only one who has these problems.

**Comment by mikefarah** [comment]
Yeah been through it myself.

Just ran them through gzip and it's surprising how much smaller the files are! I'll upload both compressed and uncompressed in the next release.

**Comment by erwbgy** [comment]
Thank you @mikefarah.  If they could be .tar.gz rather than just .gz that would resolve the permissions issue as well.

**Comment by mikefarah** [comment]
From what I understand tar is only useful for bundling files?

https://serverfault.com/questions/357066/compress-every-file-in-a-directory-into-its-own-compressed-file

**Comment by erwbgy** [comment]
Yes and the bundling preserves permissions on the files - for example
```
$ chmod 644 yq_linux_amd64-3.4.1
$ ls -l yq_linux_amd64-3.4.1
-rw-r--r-- 1 myuser mygroup 6076668 Dec 21 12:05 yq_linux_amd64-3.4.1
$ tar -zcf yq_linux_amd64-3.4.1.tar.gz yq_linux_amd64-3.4.1
$ rm yq_linux_amd64-3.4.1
$ tar -xf yq_linux_amd64-3.4.1.tar.gz
$ ls -l yq_linux_amd64-3.4.1
-rw-r--r-- 1 myuser mygroup 6076668 Dec 21 12:05 yq_linux_amd64-3.4.1
$ rm yq_linux_amd64-3.4.1.tar.gz

$ chmod 755 yq_linux_amd64-3.4.1
$ tar -zcf yq_linux_amd64-3.4.1.tar.gz yq_linux_amd64-3.4.1
$ chmod 600 yq_linux_amd64-3.4.1.tar.gz
$ rm yq_linux_amd64-3.4.1
$ tar -xf yq_linux_amd64-3.4.1.tar.gz
$ ls -l yq_linux_amd64-3.4.1
-rwxr-xr-x 1 myuser mygroup 6076668 Dec 21 12:05 yq_linux_amd64-3.4.1*
$ rm yq_linux_amd64-3.4.1.tar.gz
```

Even if the download manager messes with the permissions of the .tar.gz file when it is uncompressed the executable bit on the file remains.
