### ISSUE TITLE
restore the old command line options

### ISSUE THREAD

**Issue by allenbrunson** [mikefarah/yq#604]
so today, mac brew served up a version of yq that broke about two dozen of my automated scripts. for all practical purposes, there is no way they can be made to work with your new "eval" format, because i am exposing arguments to my callers that closely mimic the old-style write and read commands.

how about giving us a command-line option, or environment variable, etc, to restore the old command line format? without that, i will be abandoning this app altogether.

figuring out how to get an old version of yq installed was, in itself, a multi-hour project. and now i have to maintain a version of the old source code until i can figure out something better.

this is a really terrible change. give us a way to revert it.

**Comment by mikefarah** [comment]
What a rude and entitled way to raise an issue. You are totally free to still use v3 of `yq` or to abandon the app. I really am sorry you've spent multiple hours trying to get the old version, however keep in mind that I've spent years on `yq` and months on this latest release. You certainly don't need to maintain a version of the source code, the git releases are all there as well as docker.

Brew is community run, and anyone can create a brew tap. One of brew's downsides is that it's always been hard to control versions of what you are downloading. This is normally OK for adhoc usage but terrible for anything scripted. If you wanted, you could create a yq3 tap based on the latest v3 of yq (https://stackoverflow.com/questions/3987683/homebrew-install-specific-version-of-formula).

In my opinion, dependencies in scripts should be treated like library dependencies in code - that is you use a specific version and only upgrade after testing. To my knowledge, you can't really do that with brew.

I'd recommend using something like wget/curl to obtain a specific version of `yq` in your scripts. 

The way of reverting is simply not using that version - use the older version.

**Comment by mikefarah** [comment]
Note that v3 install is now available via snap and brew (see readme docs)
