### ISSUE TITLE
Default value option was dropped (?)

### ISSUE THREAD

**Issue by xoxys** [mikefarah/yq#605]
**Describe the bug**
Looks like the defaultValue option from v3 was dropped. If it can't be added back maybe document it as breaking change.

**Comment by mikefarah** [comment]
Oops - looks like I missed that, I'll add a 'alternative //' operator like `jq` https://stedolan.github.io/jq/manual/#Alternativeoperator:// in the next release

**Comment by xoxys** [comment]
Cool, thanks!
