### ISSUE TITLE
I cannot use bash variables anymore.

### ISSUE THREAD

**Issue by DeLoWaN** [mikefarah/yq#606]
**Describe the bug**
I used yq like this

```yq eval -i config.yaml foo "${bar}"```

With `yq` eval, I cannot use anymore bash variables in expressions:

```
foo=bar yq eval ".foo = $foo" toto/toto.yaml
Error: '=' expects 2 args but there is 1
```

For info, `jq` uses the `--arg` flag to import variables in expression.

**Environment**
Version of yq: 4.0.0
Operating system: debian
Installed via: binary release

**Comment by mikefarah** [comment]
You'll need to wrap the value in quotes so yq knows its a string (as opposed to a path/expression..)

```bash
foo=bar; yq eval  ".foo = \"$foo\"" toto/toto.yaml
```

**Comment by mikefarah** [comment]
note that there is a now a simpler way to manage environment variables in 4.3.1: https://mikefarah.gitbook.io/yq/env-variable-operators

**Comment by Maraudingas** [comment]
The link doesn't work:
https://mikefarah.gitbook.io/yq/env-variable-operators

**Comment by bencat-sixense** [comment]
@Maraudingas this is the working url : https://mikefarah.gitbook.io/yq/operators/env-variable-operators
