### ISSUE TITLE
--unwrapScalar causes an error in v4.x

### ISSUE THREAD

**Issue by mccarthy-james** [mikefarah/yq#608]
Using 4.0.0 on a Mac installed via Homebrew.

Following the guide here but updating for v4.x formatting: https://mikefarah.gitbook.io/yq/v/v4.x/usage/output-format -- I see this error:

```
$ yq e --unwrapScalar=false example.yml
Error: unknown flag: --unwrapScalar
```

Have I got the formatting wrong or is this a bug? Thanks!

**Comment by mikefarah** [comment]
looks like I missed that flag - will add it to the next release

**Comment by mccarthy-james** [comment]
Thanks, Mike. This certainly fixed the bug, but it turns out it doesn't solve my issue!

I have:

```a:>-
  some text
  goes here```

When I put that through `yq` I get:
```a:>-
  some text  goes here```

With `a:|-` there is no change, but I would have thought there would be no change above either because the block style indicator is an instruction to the end application rather than yq? This is not my area of expertise so I am happy to be told otherwise!

Thank you for your help. James

**Comment by mccarthy-james** [comment]
@mikefarah Not sure if you saw my note above because the ticket was closed when I added it. My formatting was also broken, so I've fixed that. Happy to open a new issue, but didn't want to if it's not a bug as.
