### ISSUE TITLE
V3 Compatibility mode?

### ISSUE THREAD

**Issue by gharris999** [mikefarah/yq#610]
Well, all my scripts using yq are broken now, of course, using V4.  And since most of these scripts are for network configuring,  I'm in a position where running these scripts against a V4 yq can put a machine in a non-remotely recoverable state.  So ... ouch.

How difficult would it be to add a --compatibility feature to V4 so that it interprets V3 r w commands?

I don't have a sense of the magnitude of this request, so I'll accept a simple "Too difficult" answer if it would be non-trivial to add this.

Thus far, my work around is to simply modify my scripts that install yq so that I'm never installing V4:

	#~ YQ_INDEX='https://github.com/mikefarah/yq/releases/latest/'
	YQ_INDEX='https://github.com/mikefarah/yq/releases/tag/3.4.1/'

..which hopefully will prevent disasters.

**Comment by mikefarah** [comment]
Sorry V3 compatibility mode will be too much work to add and maintain, best bet is to use a specific version like you are doing 👍

**Comment by mikefarah** [comment]
Personally, I think that's a good idea for scripts to lock in versions (at least major) - just as you would in development for a library (and only upgrade after running some tests).
