### ISSUE TITLE
YAML anchors cannot be set

### ISSUE THREAD

**Issue by jbapu** [mikefarah/yq#612]
**Describe the bug**
Anchor cannot be set in V4 using the `anchorName` CLI option.

Version of yq: 4.0.0
Operating system: Windows
Installed via: docker (mikefarah/yq)

**Input Yaml**
data1.yml:
```yaml
a: should really work
```

**Command**
The command you ran:
```
yq eval '.a = "test"' --anchorName="myAnchor" -i data.yml
```

**Actual behavior**
```
Error: unknown flag: --anchorName
```

**Expected behavior**

```yaml
a: &myAnchor test
```

**Additional context**
Solution described [here ](https://github.com/mikefarah/yq/issues/377#issuecomment-621112033) doesn't work anymore in V4.

**Comment by mikefarah** [comment]
yep missed that, next release will have an `anchor` and `alias` operator:

```
yq e '.a anchor = "myAnchor"' -i data.yml
```


```
yq e '.a alias= "someAlias"' -i data.yml
```
