### ISSUE TITLE
Syntax to write and append array with v4

### ISSUE THREAD

**Issue by hobti01** [mikefarah/yq#613]
**Describe the bug**
Advice on v4 append to array syntax compared to v2.  In version 2 appending to an array is nicely concise, the only deficiency is not handling an empty file.  In version 4 it seems very verbose to do the same thing.  Hopefully I'm overlooking a better syntax?

Version of yq: 4.0.0
Operating system: mac
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
delete: me
```

**Command**
The command you ran:
v2:
```
file=data1.yml
# v2 cannot use empty files
echo 'delete: me' > "$file"
for x in a b c; do
  yq2 write --inplace "$file" "key.array[+]" "$x"
done
yq2 delete --inplace "$file" 'delete'
```

v4:
```
file=data1.yml
yq eval --null-input '.key.array=[]' > $file
for x in a b c; do
  yq eval ". *+ {\"key\":{\"array\":[\"$x\"]}}" "$file" --inplace
done
```

**Actual behavior**
v2:
```yaml
key:
  array:
  - a
  - b
  - c
```
v4:
```yaml
key:
  array: [a, b, c]
```

**Expected behavior**

It "works" but is there any option for better syntax with v4?

**Comment by mikefarah** [comment]
You can use the [relative assign operator](https://mikefarah.gitbook.io/yq/assign#relative-form-or) along with the [add](https://mikefarah.gitbook.io/yq/add#concatenate-arrays)

```
yq e '.key.array |= . + [1]' file.yaml
```

**Comment by hobti01** [comment]
Thank you! (and thanks for yq)
