### ISSUE TITLE
Bring back read and write commands as alias to eval

### ISSUE THREAD

**Issue by rjcoelho** [mikefarah/yq#614]
Hi,

Latest version (v4) broke all the scripts and there is no simple way to have scripts work both on v3 and v4. Problem is now I'm forced to ask every developer (including jenkins jobs) to update the yq. Until then i'm forced to remain on v3.

Bring back read and write commands (as alias to eval) or document a way using shell scripting to autodetect v3 and v4 and use the correct flags. My use case is just to convert yaml to json.

Also -P/--prettyPrint flag is no longer recognized.

Thanks

**Comment by mikefarah** [comment]
Just lock in the older version - this is what semantic versioning is for...
________________________________

**Comment by mikefarah** [comment]
Note that v3 install is now available via snap and brew (see readme docs)
