### ISSUE TITLE
Quote in multiline string not handled

### ISSUE THREAD

**Issue by diseq** [mikefarah/yq#624]
**Describe the bug**
Quote in multiline string not handled

Version of yq: 4.1.0
Operating system: ubuntu 20.04
Installed via: binary release

**Command**
```
test=$(cat <<-END
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1"
}
END
)
curl https://docs.projectcalico.org/manifests/canal.yaml | yq eval ".data.cni_network_config = \"${test}\"" -
```

**Actual behavior**

```yaml
Error: Parsing expression: Lexer error: could not match text starting at 2:4 failing at 2:6.
unmatched text: "na"
```

**Expected behavior**
.data.cni_network_config replaced with variable $test

**Additional context**
Command works without the quotes in the variable

**Comment by mikefarah** [comment]
This is a bash substitution, wrapped in double quotes. Having double quotes within the variable will evaluate and end the quotes in the expression.

I'd recommend removing the quotes (or using single quotes).

**Comment by diseq** [comment]
I get your point. I was just referring to your [example](https://mikefarah.gitbook.io/yq/v/v4.x/usage/tips-and-tricks#using-bash-variables).

Unfortunately, I cannot switch to single quotes in the replacement text as it is json.

the closest i could get so far is:
```
test=$(cat <<-END
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1"
}
END
)
curl https://docs.projectcalico.org/manifests/canal.yaml | yq eval ".data.cni_network_config = ${test}" - |more
```

eats the quotes: (expected)
```
  cni_network_config:
    name: k8s-pod-network
    cniVersion: 0.3.1
```

**Comment by mikefarah** [comment]
Gotcha, give this a go then:

https://app.gitbook.com/@mikefarah/s/yq/usage/tips-and-tricks#multi-line-bash-variables

**Comment by mikefarah** [comment]
Note - you need 4.2.1 for this to work

**Comment by diseq** [comment]
thanks for this! i got one step closer:
yq version 4.2.1

quotes:
```
test=$(cat <<END
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1"
}
END
)
yq ea "select(fi==0).data.cni_network_config = select(fi==1)" <(curl https://docs.projectcalico.org/manifests/canal.yaml ) <(echo "${test}")
```

single quotes:
```
test=$(cat <<END
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1"
}
END
)
yq ea 'select(fi==0).data.cni_network_config = select(fi==1)' <(curl https://docs.projectcalico.org/manifests/canal.yaml ) <(echo "${test}")
```

quotes from file: (just in case)
```
cat <<"END" >test.json
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1"
}
END
yq ea "select(fi==0).data.cni_network_config = select(fi==1)" <(curl https://docs.projectcalico.org/manifests/canal.yaml ) test.json
```

single quotes from file: (just in case)
```
cat <<"END" >test.json
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1"
}
END
yq ea 'select(fi==0).data.cni_network_config = select(fi==1)' <(curl https://docs.projectcalico.org/manifests/canal.yaml ) test.json
```

all of fhe above result in the following for the inserted part (curly brackets are eaten but quotes are there and the "|" multiline string marker is missing):
```
  cni_network_config:
    "name": "k8s-pod-network"
    "cniVersion": "0.3.1"
```

**Comment by mikefarah** [comment]
Which multiline string marker?

**Comment by diseq** [comment]
apologies, meant the Block Style Indicator: '|'

eg.
```
  cni_network_config: |
    "name": "k8s-pod-network"
    "cniVersion": "0.3.1"
```

**Comment by mikefarah** [comment]
Ok there's a new way to do this via the env operators (https://mikefarah.gitbook.io/yq/env-variable-operators):

```bash
VALUE=$(cat <<-END
{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1"
}
END
)

VALUE=$VALUE ./yq e -n '.a = strenv(VALUE)'
```

**Comment by diseq** [comment]
awesome. thanks!! works like a charm.
