### ISSUE TITLE
brew install yq@3.4.1:  No available formula or cask with the name "yq@3.4.1".

### ISSUE THREAD

**Issue by bitsofinfo** [mikefarah/yq#626]
```
brew install yq@3.4.1
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
Updated 2 formulae.

==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "yq@3.4.1".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by mikefarah** [comment]
As far as I can tell - brew doesn't really do versioning :(

**Comment by mikefarah** [comment]
Best way about it (I think) is to add a `yq3` brew install (https://github.com/Homebrew/homebrew-core/pull/67921)

**Comment by mikefarah** [comment]
I stand corrected, there is a concept of 'versions' in brew! https://github.com/Homebrew/homebrew-core/pull/67923

If this goes through, then it will be `brew install yq@3` to get yq v3 (which the latest is 3.4.1).

**Comment by bitsofinfo** [comment]
cool thanks! would be great to have the same w/ snap!

**Comment by pmthexton** [comment]
```brew install yq@3``` yields no results for me.

```% brew install yq@3                                                                                                                                        11:35
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "yq@3".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by bitsofinfo** [comment]
https://github.com/mikefarah/yq/issues/625

**Comment by mikefarah** [comment]
This has now been merged into homebrew,

```
brew install yq@3
```

See instructions under https://github.com/mikefarah/yq/#macos--linux-via-homebrew

**Comment by bitsofinfo** [comment]
thx

**Comment by Talador12** [comment]
@mikefarah 
```
Error: yq@3 has been disabled because it is not maintained upstream!
```

**Comment by hassanbsee2071** [comment]
@mikefarah 
yq compare -P live.yaml conf.yaml  users
This command does not work in latest 4 version of release.

**Comment by mikefarah** [comment]
Yeah v4 works quite differently from v3 - v4 is more like jq and you give it an expression. Take a look here at how do upgrade from v3: https://mikefarah.gitbook.io/yq/upgrading-from-v3#comparing-yaml-files
