### ISSUE TITLE
cannot use bash environment variable

### ISSUE THREAD

**Issue by vimalk78** [mikefarah/yq#633]
**Describe the bug**

I have a yaml
```
a:
  b: value1`
```
i want to replace `value1` with `localhost:5000/value1`, 
```
a:
  b: localhost:5000/value1`
```

and i want to do the same in many yamls

So i extract the `.a.b` and save it in env variable, and i try to do the following to replace

```
$ yq e '.a.b = $variable' sample.yaml 
Error: Parsing expression: Lexer error: could not match text starting at 1:8 failing at 1:9.
	unmatched text: "$"
```

Version of yq: yq version 4.2.0
Operating system: ubuntu 20.04
Installed via: go get

**Comment by mikefarah** [comment]
you need to interpolate the variable with double quotes, and wrap the value with double quotes so `yq` knows its a string. I'm going to add this to the docs as it seems to be a recurring thing.

```
yq e ".a.b = \"$variable\"" sample.yaml 
```

**Comment by mikefarah** [comment]
note that there is a now a simpler way to manage environment variables in 4.3.1: https://mikefarah.gitbook.io/yq/env-variable-operators
