### ISSUE TITLE
Add a way to assign a value from a CLI parameter

### ISSUE THREAD

**Issue by gajus** [mikefarah/yq#635]
**Describe the solution you'd like**

```yaml
foo: bar

```

And we run a command:

```bash
export FOO=BAR

yq eval '.foo = $1' ./foo.yaml -p "$FOO"

```

(or a variation of this that allows to bind parameters)

it could output

```yaml
foo: baz

```

**Describe alternatives you've considered**

I am currently simply doing:

```bash
yq eval '.foo = "'$FOO'"' ./foo.yaml

```

but that's fragile.

**Comment by bertpersyn** [comment]
If the path you want too set is also a var:
```bash
    expr=$(echo "'$YPATH = \"$VAL\"'")
    eval "yq e $expr -i $VALUESPATH"
```

From jq docs:

--arg name value:

This option passes a value to the jq program as a predefined variable. If you run jq with --arg foo bar, then $foo is available in the program and has the value "bar". Note that value will be treated as a string, so --arg foo 123 will bind $foo to "123".

**Comment by gajus** [comment]
ah! This is exactly what I was looking for.

Where is this documented though...

I don't see `--arg` in `--help` of either `yq --help` or `yq eval --help`.

**Comment by bertpersyn** [comment]
@gajus : edited. I was referring to jq, not yq.

**Comment by mikefarah** [comment]
The latest version (4.3.1) now has env operators:
https://mikefarah.gitbook.io/yq/env-variable-operators
