### ISSUE TITLE
How to support `yq p` command in v3 at V4? 

### ISSUE THREAD

**Issue by jichenjc** [mikefarah/yq#637]
**Please describe your feature request.**
A clear and concise description of what the request is and what it would solve. 
Eg. I wish I could use yq to [...]

Note:
- how to questions should be posted in the discussion board and not raised as an issue.
- V3 will no longer have any enhancements.

**Describe the solution you'd like**
If we have data1.yml like:
(please keep to around 10 lines )

```yaml
country: Australia
```

And we run a command:

```bash
yq eval 'predictWeatherOf(.country)'
```

it could output

```yaml
temp: 32
```

`yq p ` can add prefix but it's not listed here https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3
any way to do it in v4? thanks

**Describe alternatives you've considered**

**Additional context**

**Comment by mikefarah** [comment]
Oh yes sorry - updated the docs:

https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3#prefix

**Comment by jichenjc** [comment]
thanks :)
