### ISSUE TITLE
v4 Migration Help

### ISSUE THREAD

**Issue by rajatvig** [mikefarah/yq#638]
**Describe the bug**
In v3 of `yq`, there was an option `-c` to collect the output as an array. When combined with the `-j` option and `-d*`, it produced a JSON with each YAML document converted to JSON in an array which was valid JSON.

Version of yq: 4.2.1
Operating system: mac
Installed via: homebrew

**Input Yaml**
data1.yml:
```yaml
a: 1
---
b: 1
```

**Command**
The command for v4:
```
yq eval -j -P a.yaml
```

**Output**

```yaml
{
  "a": 1
}
---
{
  "b": 1
}
```

The command for v3:
```
yq read -c -d* -j -P a.yaml
```

**v3 Output**

```yaml
[
  {
    "a": 1
  },
  {
    "b": 1
  }
]
```

**Additional context**
Am not sure if the desired functionality is missing or not documented.

**Comment by mikefarah** [comment]
Use the [collect operator](https://mikefarah.gitbook.io/yq/collect-into-array)

I'm not at my machine, but it would be something like

```
yq eval '[.]' a.yaml
```

**Comment by rajatvig** [comment]
That seems to get

```
❯ yq eval '[.]' -j -P a.yaml
[
  {
    "a": 1
  }
]
[
  {
    "b": 1
  }
]
```

That is not valid json. I tried with `'[.*]` as well.

**Comment by mikefarah** [comment]
Sorry my mistake, as you need to process multiple documents at once, you cannot use the default streaming 'eval', you need to use eval-all:

```
yq ea '[.]' a.yaml
```

**Comment by rajatvig** [comment]
Thanks a ton for the assist.
