### ISSUE TITLE
Unable to create a YAML file from scratch

### ISSUE THREAD

**Issue by jremond** [mikefarah/yq#639]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.2.1
Operating system: linux
Installed via: binary release

**Input Yaml**
At first, I start with an empty file
```
$ touch data1.yaml
```

**Command**
The command you ran:
```
$ yq e  '.b = "cat"' data1.yaml
$
```

**Actual behavior**

The output is empty.

**Expected behavior**

I'm trying to migrate from v3.4.1
```$ yq-3.4.1 w data1.yaml b cat
b: cat
```

** Additional information **
If the file is not empty, it works.
```$ cat data1.yaml 
b: cat
$ yq e '.b = "dog"' data1.yaml 
b: dog
$ yq e '.c = "dog"' data1.yaml 
b: cat
c: dog
$ 
```

Trying with `-n`flag shows the exact same behaviour.

**Comment by mikefarah** [comment]
`-n` works for me?

```
yq e  -n '.b = "cat"' > data1.yml

cat data1.yml 
b: cat
```

**Comment by jremond** [comment]
> `-n` works for me?
> 
> ```
> yq e  -n '.b = "cat"' > data1.yml
> 
> cat data1.yml 
> b: cat
> ```

Ok the difference is with the redirection
```
$  yq-4.2.1 e -n  '.b = "cat"' data1.yaml
$  yq-4.2.1 e -n  '.b = "cat"' 
b: cat
$ 
```
I used to create an empty file and then put some value, I guess I need to change how I put the first value in the file.

I also tried using `-i` to edit in place without success, any suggestion ?

Otherwise I/you can close this ticket, thanks for this awesome tool !

**Comment by srheaume** [comment]
I strongly believe that this is a bug and not a feature. We should be able to add an element to an empty file.

The trick I'm using right now to work around this is to replace the following command:

```
touch values.yaml
```

by

```
echo "---" > values.yaml
```

By doing this, it is now possible to use the "edit in place" command for your first value without changing your code.

Hopefully this trick will help for the moment while waiting for a fix.

**Comment by jremond** [comment]
I think the thing that took me the most time to understand is why
```
$  yq-4.2.1 e -n  '.b = "cat"' data1.yaml
```
doesn't do anything and doesn't fail/warn/notify.

Thanks for the workaround.

**Comment by mikefarah** [comment]
Good idea, Using `yq` with `-n` and passing in files now errors (4.3.1)
