### ISSUE TITLE
How to get the env value in V4

### ISSUE THREAD

**Issue by lanvige** [mikefarah/yq#641]
**Describe the bug**

I need to get the env value to set in YAML file, but in 4.x cannot use $ to get the value

Version of yq: 4.2.1
Operating system: mac
Installed via: homebrew

In 3.x

we can use like this:

```
yq w -i config/config.yml app.version $(git describe --abbrev=0)
```

how to get the value in 4.x style?

```
yq eval '.app.version = $(git describe --abbrev=0)' config/config.yml
```

this is a demo shell and not works?

**Comment by mikefarah** [comment]
https://mikefarah.gitbook.io/yq/usage/tips-and-tricks

**Comment by lanvige** [comment]
yeah, it works, thanks mike!
