### ISSUE TITLE
Support arguments (or environment variables)

### ISSUE THREAD

**Issue by bartfeenstra** [mikefarah/yq#642]
Allow the `yq` command to take arguments, similar to [jq's --arg argument](https://stedolan.github.io/jq/manual/#Invokingjq). This prevents people from having to perform shell substitution or use temporary files (as per the [yq documentation](https://mikefarah.gitbook.io/yq/v/v4.x/usage/tips-and-tricks)). As yq is distributed as a snap package, using files may cause users to run into the snap's restricted permissions (depending on how it's installed).

## Definition of Done
- Add the `--arg $name $value` to the `yq` command.
- If invoked with `yq --arg fruit apple`, this makes the `$fruit` variable available inside expressions, and the variable will be evaluated as the string `"fruit"`.

## Advantages
- This is easier and more straightforward than shell substitutions, as well as reading from (temporary) files.
- Each shell has its own substitution logic, so user support would either be easier, or involve fewer disappointments because we can't support people's individual shells.
- This avoids consequences of strict snap confinement, such as restricted file access.

**Comment by mikefarah** [comment]
Got another suggestion, I could add a $<envVariable> style operator to yq that reads the 'envVariable' value from the environment variables.

so you could do something like:

```bash
blorg=cat yq e '.a.b = $blorg' file.yaml
```

Note the single quotes so bash (or whatever cli you are using) does not interpret the value. 

The value would be parsed as yaml, so, for instance, if you wanted the string "123" you would need to include the quotes:

```bash
blorg='"123"'
```

Thoughts?

**Comment by bartfeenstra** [comment]
After I posted this I realized my original suggestion of treating values as strings was needlessly restrictive and not consistent with how yq works now. Thanks for confirming that.

I can't see any problems with your proposal (yet). It uses the same expression syntax as jq does so that's good, and even if someone comes up with a good reason for requesting command line arguments in the future like I did originally, that could still be added on top of your idea to read environment variables without breaking BC.

**Comment by mikefarah** [comment]
I'm a bit worried that using '$' will confuse people between bash interpolating variables and yq.

I'm now thinking of:
```
var=true yq e -n '.a = env(var)'
```

This would evaluate the `var` environment variables as yaml (kind of like the argJson in `jq`, and so true is the boolean true.

```
var=true yq e -n '.a = strenv(var)' 
```
This would evaluate var as the string "true".

**Comment by srheaume** [comment]
> I'm a bit worried that using '$' will confuse people between bash interpolating variables and yq.
> 
> I'm now thinking of:
> 
> ```
> var=true yq e -n '.a = env(var)'
> ```
> 
> This would evaluate the `var` environment variables as yaml (kind of like the argJson in `jq`, and so true is the boolean true.
> 
> ```
> var=true yq e -n '.a = strenv(var)' 
> ```
> 
> This would evaluate var as the string "true".

I like the idea of env and strenv

**Comment by mikefarah** [comment]
Added the new operators to 4.3.1
https://mikefarah.gitbook.io/yq/env-variable-operators

**Comment by bartfeenstra** [comment]
Cool! Thanks a lot :)

**Comment by georgettica** [comment]
@mikefarah  it moved to https://mikefarah.gitbook.io/yq/operators/env-variable-operators

**Comment by tikicoder** [comment]
For me this is not quite there. The nice part about using the jq version is I can have a json file as a template and replace it there and it replaces the variable. This I have to tell it what the path is

**Comment by tukusejssirs** [comment]
Just like @tikicoder, I found the current behaviour from JSON strings as env var values bad.

```bash
$ a='{"c": "1", "d": "a", "e": true}' yq -n '.a = env(a)'
# Current output:
a: {"c": "1", "d": "a", "e": true}

$ yq -n '.a = {"c": "1", "d": "a", "e": true}'
# Expected output of the previous command with `env(a)`:
a:
  c: "1"
  d: a
  e: true
```

**Comment by deitch** [comment]
Sorry to come at this a few years later. 

Does this mean that `--arg` no longer exists in 4.x? Normally, it wouldn't matter, but it does mean that you no longer can set values as part of the args _to_ `yq`, and it has to be set _before_ `yq` is called. 

When everything is args, I can do:

```
yq --arg foo bar --arg a b ....
```

That means that whatever `yq` is - a command in the path, a shell function, an alias to docker, a shell function that calls docker, nerdctl, anything at all - it works consistently.

If I _have_ to set it before:

```
foo=bar a=b yq ...
```

Then that changes. Env vars get passed to commands and to aliases, not necessarily to functions, not automatically to calling VMs or containers or other such, which makes it messy.

Did I misunderstand?

**Comment by AdamMAtWork** [comment]
> Did I misunderstand?

@deitch I believe the version of 'yq' you're referring to is from another author: https://github.com/kislyuk/yq

For some reason, that version is what brew installed on my mac, while this version is what got installed in an Alpine-based container I built.

**Comment by deitch** [comment]
I didn't think so, but I guess it is possible. I always thought I had used pure original yq, but maybe I accidentally used the other one in a project and didn't realize it.

Either way, is the use-case valid?

**Comment by MagicRB** [comment]
I also don't think that using environment variables for passing what is configuration data is satisfactory, environment variables should *never* be used for that purpose in my opinion. Neither that nor passing secrets. As such I think this issue should be reopened.
