### ISSUE TITLE
yq is no longer usable with environment variables

### ISSUE THREAD

**Issue by srheaume** [mikefarah/yq#643]
As it was possible with the previous version (v3.x.x), yq is no longer usable with environment variables.

With version v3.x.x, it was possible to write values such as integers, floats or booleans and have the possibility to preserve their type without them being converted to text values.

For example, it was possible to write values such as integers, floats or booleans:

```
int_value=5
yq w -i output.yaml "a.i" "${int_value}"

bool_value=true
yq w -i output.yaml "a.b" "${bool_value}"

text_value="some text"
yq w -i output.yaml "a.t" "${text_value}"
```

output.yaml:

```
a:
  i: 5
  b: true
  t: some text
```

If a conversion of the values to text was desired, this could be done:

```
int_value=5
yq w -i --tag '!!str' output.yaml "a.i" "${int_value}"

bool_value=true
yq w -i --tag '!!str' output.yaml "a.b" "${bool_value}"

text_value="some text"
yq w -i --tag '!!str' output.yaml "a.t" "${text_value}"
```

output.yaml:

```
a:
  i: "5"
  b: "true"
  t: "some text"
```

If we try to get the same behavior with version 4, it's quite impossible.

For example:

```
int_value=5
yq eval -i ".a.i = ${int_value}" output.yaml

bool_value=true
yq eval -i ".a.b = ${bool_value}" output.yaml

text_value="some text"
yq eval -i ".a.b = ${text_value}" output.yaml
```

For the boolean and the text values, we will get the following error:

Error: Parsing expression: Lexer error: could not match text starting at ...

For this to work, you have to surround the variable with double quotes. In case we want to preserve the original type of the value, this technique doesn't work. At the moment, version 4 doesn't offer us an alternative to solve this problem.

**Comment by mikefarah** [comment]
Booleans worked for me:

```bash
bool_value=true ./yq e ".a = $bool_value" -n
a: true
```

As for strings, you need to put it in quotes, see https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#using-bash-variables

Also - there's another issue where I'm looking for input in adding extra operators to make this a bit cleaner:

https://github.com/mikefarah/yq/issues/642

Please feel free to add your thoughts there

**Comment by srheaume** [comment]
I don't think you understand the problem.

If you use an environment variable and you don't know in advance what kind of value will be assigned to it, it doesn't work. If you set a string to bool_value, you'll get a parser error. The only way to avoid this is to surround the variable with double quotes. However, by doing this, any values written will be strings.

This problem does not exist in version 3. It is newly introduced in version 4 and it makes migration impossible for many scripts.

**Comment by mikefarah** [comment]
I see, it should be solved by what I'm suggesting in the other issue I linked to then. A getenv operator would evaluate the type correctly.
________________________________

**Comment by nmccready** [comment]
This is a bug, you should not have to define any variables to query the document. It's just straight text. This is a major breaking change .

**Comment by nmccready** [comment]
What if you relying on returning those env vars as is as KEYS to build a document to be processed at a later time. This breaks that.

**Comment by srheaume** [comment]
I agree with @nmccready.

I read what you are trying to solve with issue #642 and it seems to solve the problem described here. However, issue #642 is mentioned as an improvement. Here we are really talking about a bug affecting all v3 users. A migration to version 4 is currently impossible because of this detail. I would take this issue more seriously in my opinion.

P.S.: Apart from that, I greatly appreciate the development effort that has been made for version 4. It brings a lot more flexibility, but it would be a real shame if this detail would undermine all these efforts.

**Comment by mikefarah** [comment]
Sorry it's not clear to me what the issue is with the proposed env / strenv solution.  Can you give specific examples that demonstrate your point.
________________________________

**Comment by mikefarah** [comment]
Added the new env operators in 4.3.1: https://mikefarah.gitbook.io/yq/env-variable-operators

**Comment by iomarcovalente** [comment]
The above link doesn't work. Working link to the relevant docs: https://mikefarah.gitbook.io/yq/v/v4.x/operators/env-variable-operators

**Comment by iomarcovalente** [comment]
@mikefarah 
I think this solution does not solve a scenario that was covered by version 3 which is building a yaml file dynamically, that is previously I was doing: 
```    
    imageName=$(echo "${imageName}_version" )
    imageTag=$(yq r $file versions[0].tag)
    yq w -i docker-image-changelog.yaml ${imageName} ${imageTag}
```

whilst now the equivalent does not work:
```
imageName=$(echo "${imageName}_version" ) imageTag=$(yq e '.versions[0].tag' $file) yq e -n '.env(imageName) = env(imageTag)' >> docker-image-changelog.yaml
```

as I get:
```
Error: Parsing expression: Lexer error: could not match text starting at 1:6 failing at 1:7.
	unmatched text: "i"
```

**Comment by baardkrk** [comment]
I'm still not able to do this. I've tried a couple of different versions:
```bash
$ HELLO="hello"
$ WORLD="world"
$ h=$HELLO w=$WORLD yq e -n '.hello.world = env(h)'  # works
hello:
  world: hello
$ h=$HELLO w=$WORLD yq e -n '.strenv(h).strenv(w) = env(h)'  # does not work
Error: Parsing expression: Lexer error: could not match text starting at 1:9 failing at 1:11.
	unmatched text: "h)"
$ h=$HELLO w=$WORLD yq e -n '.env(h).env(w) = env(h)'
Error: Parsing expression: Lexer error: could not match text starting at 1:6 failing at 1:8.
	unmatched text: "h)"
$ keystring=$(echo ".$HELLO.$WORLD") yq e -n 'strenv(keystring) = "hello world"'  # Is evaluated but returns empty string
```
Did anyone find a solution or is there any plans to support this at a later date? I see the issue is closed but... It would be nice to be able to reference environment variables as keys.

**Comment by mikefarah** [comment]
Docs here: https://mikefarah.gitbook.io/yq/operators/env-variable-operators#dynamic-key-lookup-with-environment-variable

**Comment by baardkrk** [comment]
> Docs here: https://mikefarah.gitbook.io/yq/operators/env-variable-operators#dynamic-key-lookup-with-environment-variable

Great! Thank you very much! Sorry for not seeing it
