### ISSUE TITLE
Add webi as install method

### ISSUE THREAD

**Issue by adithyasunil26** [mikefarah/yq#644]
Webi is a convenient way to install developer tools and yq has been added to the list of tools that can be installed using Webi.

Installing yq using webi
```
webi yq
```

Visit official website https://webinstall.dev/ for details on Webi.
Visit github repo https://github.com/webinstall/webi-installers/tree/master/yq for yq specific details.

**Comment by mikefarah** [comment]
Thanks @adithyasunil26 , I've added it to the readme
