### ISSUE TITLE
Unknown command "w" for "yq"

### ISSUE THREAD

**Issue by rehrler** [mikefarah/yq#645]
Commands are not accepted for the yq command.

Version of yq: 4.2.1
Operating system: linux ubuntu 18.04
Installed via: snap.

When I try `yq w -i my_yaml.yaml my_parameter new_value`, I got the following error:
`Error: unknown command "w" for "yq"` \
`Run 'yq --help' for usage.`

**Comment by dw2kim** [comment]
I am getting this error as well..

**Comment by dw2kim** [comment]
https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3#updating-writing-documents

Tried this and still returns
`Error: unknown command "eval" for "yq"
Run 'yq --help' for usage.`

**Comment by srheaume** [comment]
@rehrler  **yq write or yq w** is a command supported by version 3 and not version 4. Read the "Upgrading from V3" documentation for more details: https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3#updating-writing-documents.

If you are not ready to make the jump to version 4, you can install yq this way:

```
snap install yq --channel=v3/stable
```

**Comment by rehrler** [comment]
@mikefarah @srheaume Sorry, my fault! Thanks for the solution and the overall great tool. Cheers
