### ISSUE TITLE
anchor and alias operators in yq4

### ISSUE THREAD

**Issue by atticus-sullivan** [mikefarah/yq#646]
**Describe the bug**
When using the anchor and alias operators like described in [https://mikefarah.gitbook.io/yq/v/v4.x/anchor-and-alias-operators](https://mikefarah.gitbook.io/yq/v/v4.x/anchor-and-alias-operators), the filtering doesn't work right anymore (in older version this was possible), see the description for reproduction below.

Version of yq: 4.2.1
Operating system: linux
Installed via: the Arch User Repository but tested the comiled binary from this repository too.

**Input Yaml**
data1.yml:
```yaml
f:
  a: &a cat
  b: *a
```
(Example from the website [https://mikefarah.gitbook.io/yq/v/v4.x/anchor-and-alias-operators](https://mikefarah.gitbook.io/yq/v/v4.x/anchor-and-alias-operators))

**Command**
```
yq eval 'explode(.f.b)' data1.yml
```

**Actual behavior**

```yaml
f:
  a: &acat
  b: cat
```

**Expected behavior**

```yaml
cat
```
In earlier Versions one had to specify a Flag so that aliases get expanded, but this seams to be handled with the `explode` function. When using
```bash
$ yq eval 'explode(.f)' sample.yaml
f:
  a: cat
  b: cat
```
everything seams alright, but as soon as I try to filter for a more precise key, the filtering does not work right anymore.

In addition when only using 
```bash
$ yq eval 'explode(.f)' sample.yaml
f:
  a: cat
  b: cat
```
as far as I know the output should only be
```bash
a: cat
b: cat
```

So I conclude the `explode` function somehow destroys the filtering.

**Comment by mikefarah** [comment]
explode returns the same node it was given, but exploded, so you need to:

```
yq eval '.f | explode(.)'
```

or even

```
yq eval 'explode(.) | .f'
```

This is so you can explode child anchors whilst still returning or apply more filters at the parent level.

**Comment by slintz** [comment]
**I am unhappy.** To make queries, now I ALWAYS have to do something like '.explode(.path.i.really.want)' unless I can GUARANTEE that the last element of my path is NOT a reference. Unless I require the output to maintain the input's anchors/aliases (an important yet much less common case, I believe), I want the input to always be "exploded" from the document root(s). 

Thus, I would prefer:

- By DEFAULT, the old "-f" behavior (automatically explode everything)
- Have a flag ("-F" ?) that turns off the automatic explosion and then use the "explode(<path>)" function as needed

**Comment by mikefarah** [comment]
I'm reluctant to change the default behaviour as this would affect everyone using `yq`.

If you want everything to always be exploded, then you can `explode(.) | <exp you want>`. 

If a flag was added, for backwards compatibility it wouldn't explode by default, so then usage would be something like:
```
yq --explode '.path.you.really.want'
``` 

not that different afaik to what you can do now:

```
yq 'explode(.) | .path.you.really.want'
```
