### ISSUE TITLE
Equivalent of globbing in v4?

### ISSUE THREAD

**Issue by hutchisr** [mikefarah/yq#648]
Version of yq: 4.2.1
Operating system: linux
Installed via: snap

yq v3 has globbing so you can easily do something like `yq d file.yaml '**.name'` to delete all keys named `name` in the entire document. I've read through the v4 documentation but have been unable to figure out how to accomplish the same thing in the v4 syntax.

**Comment by mikefarah** [comment]
You'll need to use the recursive decent operator `..` with delete, I think I'll add it as a tip and trick:

```
yq e 'del(.. | select(has("name")).name)' file.yaml
```
