### ISSUE TITLE
Question: Double quote escape for variable substitution does not seem to work in github action?

### ISSUE THREAD

**Issue by steven-xufan** [mikefarah/yq#649]
I was following the [Tips and Tricks page](https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#using-bash-variables) to do variable substitution `yq e ".a.b = \"$myvalue\"" file.yaml` and it works locally in the command line. However I am having some issue to get it work with Github Action.

**Example**
I created a simple yaml and workflow file [here](https://github.com/steven-xufan/public-test/commit/6dee20b7ae1a342cb9d764a54fbc8649a9e97261).
I am just trying to replace a value in yml file with:
```yaml
cmd: >
  yq eval --inplace ".bar.tag = \"${ABC}\"" test.yml
```

For completeness, `test.yml` looks like this:
```yaml
foo: a
bar:
  tag: xxx
c: c
```

And it fails with the following. The log can also accessed [here](https://github.com/steven-xufan/public-test/runs/1668008747).
```
/usr/bin/docker run --name cc49561edb686f734b47adbd13252d2f99bd4f_5e9d18 --label cc4956 --workdir /github/workspace --rm -e ABC -e INPUT_CMD -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/public-test/public-test":"/github/workspace" cc4956:1edb686f734b47adbd13252d2f99bd4f  "yq eval --inplace \".bar.tag = \\"${ABC}\\"\" test.yml
"
/entrypoint.sh: eval: line 1: syntax error: unterminated quoted string
yq eval --inplace ".bar.tag = \${ABC}\" test.yml
```

The only way I could get this to work is the following. (example [commit](https://github.com/steven-xufan/public-test/commit/cfb6e776da7eb096e30d9c2c553a11f4c0e707bc) and [workflow log](https://github.com/steven-xufan/public-test/runs/1668017539))
```
yq eval --inplace '.bar.tag = "'${ABC}'"' test.yml
```

I looked through the code at [yq/github-action](https://github.com/mikefarah/yq/tree/master/github-action) and it is just passing in the argument.

Am I doing anything wrong? Or is the github action not able to escape `\"` properly?

**Comment by mikefarah** [comment]
Perhaps because the github action itself is defined in yaml - it's not escaping properly :/

But yeah, looks right to me.

Next release I'm going to add new env/strenv operators that will mean less escaping confusion (see https://github.com/mikefarah/yq/issues/642).

**Comment by mikefarah** [comment]
Try the new env/strenv operators https://mikefarah.gitbook.io/yq/env-variable-operators

**Comment by steven-xufan** [comment]
that works great. thank you!

**Comment by StephanX** [comment]
Took me a moment to decipher the documentation, but managed to decipher the env(value) like so:
```
yq --null-input '.some.value = "abc123"' > file.yaml
my_bash_value="xyz789" 
myYQvalue="${my_bash_value}" yq '.some.value = env(myYQvalue)' file.yaml
some:
  value: xyz789
```
