### ISSUE TITLE
yq 4.3.0 test failed

### ISSUE THREAD

**Issue by chenrui333** [mikefarah/yq#650]
looks like per [this commit](15e18bb), the yq test behavior got changed.

```
==> /opt/homebrew/Cellar/yq/4.3.0/bin/yq eval --null-input ".key" -
Error: Cannot pass files in when using null-input flag
```

Can you help me on how to update the test?

```
pipe_output("#{bin}/yq eval --null-input \".key\" -", "key: cat", 0)
```

relates to https://github.com/Homebrew/homebrew-core/pull/68631

**Comment by dtrodrigues** [comment]
Test is now updated - https://github.com/Homebrew/homebrew-core/pull/68631/commits/301de125d9012dded3f183c63203b206c9b34fee

This issue can be closed.

**Comment by chenrui333** [comment]
Thanks @dtrodrigues, close the issue.
