### ISSUE TITLE
"write as update only" - porting from v3 to v4

### ISSUE THREAD

**Issue by past-due** [mikefarah/yq#655]
As a follow-up on #111,

@mikefarah mentions:
> This is now doable in yq version 4 (as well as @mkyc approach in v3)

Forgive me, but how does one accomplish this in v4?

I was using:
`yq m --overwrite --autocreate=false "${file1}" "${file2}" > "${output}"` in v3
and:
`yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' "${file1}" "${file2}" > "${output}"` in v4
 adds new ones from file2

(I'm also seeing the v4 command stripping entire values/lines from file1 if the line has a trailing comment, and other issues with comments, but I suppose this might be related to fixes in 4.3.0+ - do you know when the Snap (stable) might be updated to 4.3.1?)

(Also, just a quick kudos on a fantastic tool!) 🥳

**Comment by mikefarah** [comment]
To update an existing field only, you need to filter out maps that already have that key.

For example, if you had

```yaml
a:
  b: thing
```
And you only wanted to update `b` if it exists, then you could run:

```
yq e '(.a | select(has("b")).b) = "bob"' data1.yml
```

I've just updated snap, it has an auto-triggered build when I release, but usually takes about a day or so to complete - limitation of free compute I guess?

**Comment by mikefarah** [comment]
4.4.0 now has a merge only existing fields functionality, like the work around you had for write as update only:

https://mikefarah.gitbook.io/yq/operators/multiply#merge-only-existing-fields
