### ISSUE TITLE
join operator or equivalent?

### ISSUE THREAD

**Issue by hobti01** [mikefarah/yq#658]
**Please describe your feature request.**
I wish I could use yq to replace
```
yq eval '.. | path' data1.yaml --tojson | jq 'join(".")'
```

with
```
yq eval '.. | path | join(".")' data1.yaml
```

**Describe alternatives you've considered**
* jq piping like above
* tried to use (new) string concatenation but can't figure out if it's possible

Really I want to output a file that does not have values (or all values are replaced), only keys, while keeping the structure.  Flattening the paths like this is a workaround in itself.  Two use cases:
* redacting sensitive values in logging output
* debugging yaml files with sensitive data (where the values are not needed) but the original structure is important

**Additional context**
Thanks for your continuing effort and timely responses!

**Comment by mikefarah** [comment]
My pleasure :)

Fixed in 4.4.0

https://mikefarah.gitbook.io/yq/operators/string-operators
