### ISSUE TITLE
Output array as multiple documents

### ISSUE THREAD

**Issue by dmivankov** [mikefarah/yq#659]
**Describe the bug**
Can't find a way to output array as multiple yaml documents, at best getting yaml array.

Version of yq: 4.3.2
Operating system: linux
Installed via: binary release

**Input Json**
data1.json:
```json
[{"a":1},{"a":2}]
```

**Command**
The command you ran:
```
cat data1.json | yq eval -P -
```

**Actual behavior**

```yaml
- a: 1
- a: 2
```

**Expected behavior**

```yaml
a: 1
---
a: 2
```

**Additional context**
With https://github.com/kislyuk/yq 2.11.1 following commands can be used to get array or multiple docs
```sh
$ echo '[{"a":1},{"a":2}]' | yq . --yaml-output
- a: 1
- a: 2
$ echo '[{"a":1},{"a":2}]' | yq .[] --yaml-output
a: 1
---
a: 2
```

**Comment by mikefarah** [comment]
This can't be done yet, but it could be done with a new operator, something like

```
cat data1.json | yq e -P '.[] | collectDocs' -
```

Where 'collectDocs' takes all the matches (the splatted array) and puts each one into a separate doc.

Out of curiosity, what do you need to do this for?

**Comment by dmivankov** [comment]
I was trying to mimic kubecfg: get input yaml files, process with jsonnet libs, output k8s manifests

**Comment by mikefarah** [comment]
Just realised that it should be called 'split' and not 'collect' - added in 4.4.0:

https://mikefarah.gitbook.io/yq/operators/split-into-documents

**Comment by travisghansen** [comment]
I would like to do something similar to this but slightly different. Is it possible to take a file with multiple documents and output each document as an array element?

```
---
foo :bar
---
bar: baz
```

To yield

```
- foo: bar
- bar: baz
```

**Comment by justinmchase** [comment]
`split_docs` doesn't seem to work in the lastest version, it gets Lexer errors if you try to use the verbatim example in those docs.
