### ISSUE TITLE
Writing into a blank document not working in v4

### ISSUE THREAD

**Issue by idasbiste** [mikefarah/yq#660]
**Describe the bug**
A yaml file is not updated when trying to do so _iff_ it is initially empty.

Version of yq: 4.3.2
Operating system: Ubuntu 19.04
Installed via: snap

**Input Yaml**
Empty file; I'm trying to generate a yaml file from scratch with a few bash instructions that run a command like `yq e ".$1 = $2" -i $file`

**Command**
The command you ran:
```
file=generated.yml
echo -n "" > $file | yq e '.grid = true' -i $file
```

**Actual behavior**

```yaml
```

**Expected behavior**

```yaml
grid: true
```

**Additional context**
It worked when using latest v3 - `snap install yq --channel=v3/stable`
```
yq w -i $file grid true
```

**Comment by mikefarah** [comment]
Because the file is empty, there are no matches for `yq` to run through the expression pipeline - for what it's worth, this is what `jq` does as well.

To create a fresh yaml file, use the `--null-input` flag and pipe the result directly to the file you want

```
yq e -n '.grid=true' > $file
```

**Comment by idasbiste** [comment]
> for what it's worth, this is what `jq` does as well

Ok, it makes sense ✔️ 

> use the --null-input flag and pipe the result directly to the file you want

Testing between v3 and v4 I ended up using that approach at some point 👍 but I wanted to flag this anyway as you might consider it as a bug.

Thank you!

**Comment by mikefarah** [comment]
Great! I'll update the docs to help ensure no one else has the same problem
