### ISSUE TITLE
I'm unable to reproduce merge with --array append in v4

### ISSUE THREAD

**Issue by MikaelSmith** [mikefarah/yq#663]
I was doing `yq merge a.yaml b.yaml --arrays append`. An example is

```
$ cat a.yaml
key:
  array: [a, b]
$ cat b.yaml
key:
  array: [c]
$ yq merge a.yaml b.yaml --arrays append
key:
  array: [a, b, c]
```

With v4, I've been unable to find a way to do this. Things I've tried are
```
$ yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' a.yaml b.yaml
key:
  array: [c, b]
$ yq eval-all 'select(fileIndex == 0).key.array |= select(fileIndex == 0) + select(fileIndex == 1).key.array | select(fileIndex == 0)' a.yaml b.yaml

key:
  array: [a, b]
$ yq eval-all 'select(fileIndex == 0).key.array += select(fileIndex == 1).key.array | select(fileIndex == 0)' a.yaml b.yaml

key:
  array: [a, b]
$ yq eval-all 'select(fileIndex == 0).key.array + select(filename == "b.yaml").key.array' a.yaml b.yaml

Error: Cannot index array with 'key' (strconv.ParseInt: parsing "key": invalid syntax)
```

**Comment by mikefarah** [comment]
You need to user the merge and append operator `*+` https://mikefarah.gitbook.io/yq/v/v4.x/operators/multiply#merge-appending-arrays:

```
yq ea 'select(fi==0) *+ select(fi==1)' a.yaml b.yaml
```

Side note - your last two examples worked for me...

**Comment by MikaelSmith** [comment]
I was using 4.3.1. Just updated to 4.3.2 and looks like it fixed the last 2 examples.

**Comment by mikefarah** [comment]
Oh yeah I got it now - looks like a operator precedence bug - I'll raise an separate issue. for the record, if you put brackets around the select(...).key.array' it works.
