### ISSUE TITLE
Array pipe adding multiple key values

### ISSUE THREAD

**Issue by tanenbaum** [mikefarah/yq#668]
**Describe the bug**
I expect to be able to traverse an array using `.[] | .a + .b` and combine the object values with the `+` operator in order. Instead it would appear that the operators are creating a combinatorial output.

For example, in `jq` I can do this:

`jq '.[] | .a + .b' test.json`

test.json:
```json
[
    {
        "a": "foo",
        "b": "bar"
    },
    {
        "a": "1",
        "b": "2"
    }
]
```
Output:
```json
"foobar"
"12"
```

Version of yq: 4.3.2
Operating system: linux
Installed via: snap

**Input Yaml**
test.yaml:
```yaml
- a: foo
  b: bar
- a: "1"
  b: "2"
```

**Command**
The command you ran:
```
yq e '.[] | .a + .b' test.yaml
```

**Actual behavior**

```yaml
foobar
foo2
1bar
12
```

**Expected behavior**

```yaml
foobar
12
```

**Comment by tanenbaum** [comment]
**NB** I've also tried this with v4.4.0, same result.

**Comment by mikefarah** [comment]
Yep - can confirm it's a bug - will fix in next release
