### ISSUE TITLE
[v4] Retrieving a string value from yaml and split it

### ISSUE THREAD

**Issue by moseskarunia** [mikefarah/yq#669]
Hello, first of all thanks for this library. I want to ask, let's say I want to:
1. retrieve a value from a yaml file 
2. split it
3. and prints it to the terminal

-----

This is my yaml file
```yaml
version: 1.0.0+1
```

And I want to print `1.0.0` without `1`, I thought I can do it with:

```sh
cat pubspec.yaml | yq e '.version | split("+") | .[0]' -
```

But then, there's this error:

> Error: Parsing expression: Lexer error: could not match text starting at 1:12 failing at 1:14. 
> unmatched text: "sp"

But if I try like 

```sh
cat pubspec.yaml | yq e '.version' -
```

It prints

```sh
1.0.0+1
```

Can you please shed some light into this? Thanks!

**Comment by mikefarah** [comment]
Which version of yq are you using? Split was recently added in 4.4.0
________________________________

**Comment by moseskarunia** [comment]
> Which version of yq are you using? Split was recently added in 4.4.0

@mikefarah hello thanks for the quick reply. Turns out, somehow `brew install yq` is installing the 4.3.2 instead of 4.4.0. Kinda weird cause I was freshly installed it several hours ago.

It works now, with both

```sh
cat pubspec.yaml | yq e '.version | split("+")[0]' -
```

and 

```sh
cat pubspec.yaml | yq e '.version | split("+") | .[0]' -
```

Thanks!
