### ISSUE TITLE
add alias array

### ISSUE THREAD

**Issue by nanadeis** [mikefarah/yq#675]
data.yaml like below
a: 1
b: 2
c: 
after run command it should be
a: 1
b: 2
c: 
  \- *a 
  \- *b
if use add it will be
c: 
  \- '*a' 
  \- '*b'
if use alias, it will be
c: *a
how to combine this two command？

**Comment by mikefarah** [comment]
```
yq e -n '.c[0] alias="a" | .c[1] alias="b"'
```
