### ISSUE TITLE
v 4.4.1 unable to work with Github Actions 

### ISSUE THREAD

**Issue by nstott** [mikefarah/yq#681]
it looks like 4.4.1 isn't tagged in dockerhub
https://hub.docker.com/r/mikefarah/yq/tags?page=1&ordering=last_updated
the reference here to 4.4.1 is breaking https://github.com/mikefarah/yq/blob/master/github-action/Dockerfile#L1 in github actions

thanks a tonne

**Comment by sebastian-toepfer** [comment]
I think its more a docker image issue than gh-actions, for me it seems that 4.4.1 is pushed as 4.4.0 to dockerhub, because both v4 and v4.4.0 updated at the same day but v4.4.0 is 6 days older than 4.4.1.

**Comment by mikefarah** [comment]
Yep - can confirm that there was a bug in the docker release pipeline, should be fixed now please check again.
