### ISSUE TITLE
Prevent an expression evaluation during merge

### ISSUE THREAD

**Issue by inianv** [mikefarah/yq#682]
I had an interesting question tagged in `yq` today in StackOverflow. Believe me, I'm trying to answer questions tagged with `yq` when people confuse the Python version with the Go version. See [Prevent yq from evaluating an expression while performing a merge](https://stackoverflow.com/q/65625938/5291015)

File-1

```yaml
a: "value"
b: "constant1"
```

File-2

```
a: {{ include "someothervalue" . }}
c: "constant2"
```
A union merge of two works fine like this

```bash
yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' 1.yaml 2.yaml
a:
  '':
b: constant1
c: constant2
```

But ends up evaluating `.a` as an expression. Is there a way to avoid that in the current version?

**Comment by mikefarah** [comment]
File-2 is not valid yaml and so it not supported - perhaps its a template for generating yaml
