### ISSUE TITLE
How do I select multiple keys for output?

### ISSUE THREAD

**Issue by holmesb** [mikefarah/yq#686]
Issue #287 was closed as fixed [without giving an example](https://github.com/mikefarah/yq/issues/287#issuecomment-763713912) (@SteveH-US) of the syntax needed to select multiple keys.

Input:
```
- alpha: 1
  beta: foo
  gamma: 0.3
  delta: bar
- alpha: 2
  beta: baz
  gamma: 1.23
  delta: buzz
```

And I want to select only the beta and delta keys, so that I get the following output:
```
- beta: foo
  delta: bar
- beta: baz
  delta: buzz
```
The poster (@ronniegane) gave the jq syntax:
``jq '.[] | .beta, .delta'``
or
``jq '.[] | {beta, delta}'``

But this doesn't work in yq.  Many thanks.

**Comment by mikefarah** [comment]
`yq` does have the same shorthand object creation notion as `jq`, so you have to be a bit more explicit:

```
yq e '[.[] | {"beta": .beta, "delta": .delta}]' file.yml
```

**Comment by SteveH-US** [comment]
Thank you!
