### ISSUE TITLE
Scalar values are not being unwrapped

### ISSUE THREAD

**Issue by mcnesium** [mikefarah/yq#687]
Expected behavior: when evaluating a list of numeric items, each should be printed on its own, as described in the docs:

> By default scalar values are 'unwrapped', that is only their value is printed

Actual behavior: full list including comments is printed:

    m@t4p ~ printf 'list:\n - 1 # one\n - 2 # two\n - 3 # three\n' > list.yml
    m@t4p ~ yq eval '.list' list.yml 
    - 1 # one
    - 2 # two
    - 3 # three
    
    m@t4p ~ yq --version
    yq version 4.4.1

**Comment by mikefarah** [comment]
you're not printing a scalar, you're printing an array.

If you want to print the individual (scalar) elements, you will need to splat the array

```
yq eval '.list[]' list.yml
```
