### ISSUE TITLE
Add support for built-in function 'floor'

### ISSUE THREAD

**Issue by kenjones-cisco** [mikefarah/yq#69]
Add support for built-in [function 'floor'](https://stedolan.github.io/jq/manual/#example38)

```
The floor function returns the floor of its numeric input.
```

**Comment by m-messiah** [comment]
@mikefarah could you comment please why is this issue closed and what is intended state? There is no `floor` function just now

**Comment by neiser** [comment]
@mikefarah As the `floor` function is still missing, the task of grouping an array into pairs of two is really cumbersome concerning the `key` index calculation, see below. 
Also, one needs to take care of the divide function, which always tags as `!!float`. 

Here's an example how to workaround this:
```
echo "[1, 2, 3, 4, 5]" | yq -oj -I0 '
to_entries
  | map(.key = ((.key / 2) - ((.key % 2) / 2) ) | .key tag = "!!int")
  | group_by(.key)
  | map(map(.value))
'
```

With a proper `floor` function (also taking care of tagging it as `!!int`), this could look like
```
echo "[1, 2, 3, 4, 5]" | yq -oj -I0 '
to_entries
  | map(.key = (.key / 2 | floor)
  | group_by(.key)
  | map(map(.value))
'
```
