### ISSUE TITLE
v4 can't traverse through keys containing spaces

### ISSUE THREAD

**Issue by ryran** [mikefarah/yq#714]
**Describe the bug**

Unable to traverse through keys containing spaces without using globbing (`*`).

Version of yq: 4.5.0
Operating system: linux
Installed via: direct download from github _releases/download/v4.5.0/yq_linux_amd64_

**Input Yaml**

a.yml:
```yaml
fly: [poop, everything, more poop]
flying fox: [flowers, lots o fruit]
```

**Command**
The command you ran:
```
yq e '."flying fox"' a.yml
```

**Actual behavior**
```
Error: Parsing expression: Lexer error: could not match text starting at 1:10 failing at 1:13.
	unmatched text: "fox"
```

**Expected behavior**
```yaml
[flowers, lots o fruit]
```

**Additional context**
yq v3 of course can handle spaces no problem.
```
$ yq3 -V
yq version 3.4.1

$ yq3 r a.yml 'flying fox[-1]'
lots o fruit
```

As can jq.
```
$ yq e -j . a.yml | jq '."flying fox"'
[
  "flowers",
  "lots o fruit"
]
```

I assumed that yq4 would mirror jq's syntax, but perhaps this is handled differently and I just couldn't find it in the docs...

**Comment by mikefarah** [comment]
```
yq e '.["flying fox"]' examples/data1.yaml
```

Documented here for the record: https://mikefarah.gitbook.io/yq/operators/traverse#special-characters

I've just updated the traverse operator to be 'Traverse (Read)' hope that's makes it easier for readers, though you can use the search function and find it if you look for 'special'..

**Comment by ryran** [comment]
Hi Mike. Thanks so much for taking the time to respond! I actually read over that page before posting and even saw the "special characters" example with the curly brackets; however, it didn't sink in that this is what I needed. (Since keys with spaces is such a common case, I would recommend addressing it with an explicit example.)

yq v2 and v3 were already so useful. I imagine that implementing the changes of v4 must have required such a complete refactor... I can't help but admire your dedication Mike. Thank you for acting on your passion and letting us all benefit. <3

**Comment by mikefarah** [comment]
Appreciate the feedback :) definitely a labour of love. 

Fair point, I'll add an example
