### ISSUE TITLE
Pretty-print doesn't work consistently

### ISSUE THREAD

**Issue by benmoss** [mikefarah/yq#716]
**Describe the bug**
the `-P / --prettyPrint` flag is showing some weird inconsistencies. 

Version of yq: 4.5.0
Operating system: linux
Installed via: binary release

**Input Yaml**
data1.yml:
```yaml
this: []
```

**Command**
The command you ran:
```
yq eval --prettyPrint '.this += 1' data1.yml
```

**Actual behavior**

```yaml
this: [1]
```

**Expected behavior**

```yaml
this:
- 1
```

**Additional context**
This produces the expected pretty-printed output, but then is plagued by #715 
```
yq eval -i '.this += 1' data1.yml
yq eval -P data.yaml
```

**Comment by mikefarah** [comment]
Yep  -you found another bug ;) For now you can:

```
yq e -i '... style=""' examples/data1.yaml
```

Will fix in the next release.
