### ISSUE TITLE
on Windows single quote doesn't work as command wrapper 

### ISSUE THREAD

**Issue by zmila** [mikefarah/yq#719]
**Describe the bug**
On Windows10, when I use command wrapped in single quotes '.a ....' and having some JSON object inside, 
then error "Parsing expression: Lexer error:" is raised. 
When I use double quotes ".a ...." for wrapper and escaped double quotes for JSON, 
this does work. 

Version of yq: 4.X.X
yq version 4.5.0

Operating system: windows10

Installed via: binary release yq_windows_amd64.zip

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)

`>yq eval -P sample.yml`

```yaml
a:
  - dog: woof
```

**Command**
The command you ran: Add new object to array

**Actual behavior**

`>yq eval '.a + {"cat": "meow"}' sample.yml`
    Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:2.
        unmatched text: "'"

**Expected behavior**

`>yq eval ".a + {\"cat\": \"meow\"}" sample.yml`
```yaml
- dog: woof
- cat: meow
```

**Additional context**

**Comment by mikefarah** [comment]
I'm assuming you're using powershell? I'm not too familiar with it, but reading this https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_quoting_rules?view=powershell-7.1  it looks like single quotes should work - so not sure what's going on? Which version of powershell are you using?

They also mention that you can do this to include double quotes within a double quoted string:

```
"As they say, ""live and learn."""
```

**Comment by mikefarah** [comment]
Out of curiosity do you use `jq` and does that work with single quotes?

**Comment by mikefarah** [comment]
Verified solution from @dhegland:

Here's powershell working right
PS > yq e -n '.test = ""something""'
test: something
PS >

I will add it in the doces.

**Comment by zmila** [comment]
Hello! 
Sorry for late reply. 

I appreciate your workaround with double quotes! This really works. 
But for literal strings only :)

My problem was with JSON object. See below. I try to add new {key: value} pair to file. It fails on parsing of JSON. 

![image](https://user-images.githubusercontent.com/1272885/108079745-34451700-7080-11eb-9535-a3b9add92926.png)

```
PS D:\temp\yq> ./yq.exe eval -P sample.yml
a:
  - dog: woof
PS D:\temp\yq> ./yq eval '.a + ""zzz""' sample.yml
- dog: woof
- zzz
PS D:\temp\yq> ./yq eval '.a + "zzz"' sample.yml
Error: Parsing expression: Lexer error: could not match text starting at 1:6 failing at 1:7.
        unmatched text: "z"
PS D:\temp\yq> ./yq eval '.a + {""cat"": ""meow""}' sample.yml
Error: Parsing expression: Lexer error: could not match text starting at 1:7 failing at 1:11.
        unmatched text: "\"cat:"
PS D:\temp\yq>
```
