### ISSUE TITLE
[4.5.1] Windows Defender detects Trojan

### ISSUE THREAD

**Issue by itscaro** [mikefarah/yq#724]
![image](https://user-images.githubusercontent.com/266018/107876729-fb624200-6ec7-11eb-9f7c-95f6a2022306.png)

Direct download is blocked as well

**Comment by mikefarah** [comment]
Strange - does it do it for older versions too?

**Comment by Bak-Jin-Hyeong** [comment]
> Strange - does it do it for older versions too?

I haven't tried all versions. However, it is definitely reproduced in versions 4.3.1 ~ 4.5.1.

It wasn't the case when I downloaded 4.5.1 on February 11th, 2021, so it seems to be a problem with Windows Defender that has been updated since then.

**Comment by mikefarah** [comment]
I know there were issues with the windows chocolately build too - not sure why it thinks the binaries are dodgy :(

**Comment by itscaro** [comment]
I was upgrading from 4.3.1 -> 4.5.1 yesterday

**Comment by itscaro** [comment]
4.6.1 ok
