### ISSUE TITLE
Read from one and write to other file

### ISSUE THREAD

**Issue by safderali5** [mikefarah/yq#726]
A pretty basic functionality to read from one file and write to other seems missing from the yq.
If there are ways to do that already, I could not find any documentation regarding that. There was no such example found on internet as well.

**Comment by safderali5** [comment]
Here I am taking about reading sections that include array. If I read them to variable first and then write to new file, whole yaml format is gone

**Comment by mikefarah** [comment]
please follow the issue templates as I don't know what you are talking about
