### ISSUE TITLE
Update value & overwrite file

### ISSUE THREAD

**Issue by smholvoet** [mikefarah/yq#731]
👋  Looking for some guidance on the following scenario.

I'm storing the output of a certain command in a variable, and want to use the value of said variable to update a specific property and save my `_config.yml` file right after.

**_config.yml:**
```yaml
...
remote-theme: mmistakes/minimal-mistakes@4.22.0
...
```

**Setting `myVar` value:**
```bash
myVar="newValue"
```

First thing I tried:
```bash
yq e '.remote_theme = $myVar' -i _config.yml
```
... which results in `remote-theme: $myVar` 🙈 

I then tried using [env variable operator](https://mikefarah.gitbook.io/yq/operators/env-variable-operators), but I'm not sure how I should overwrite the file:
```bash
yq e --null-input '.remote_theme = env(myVar)' -i _config.yml
```

👉 using version `4.6.0` on  Ubuntu 20.04

**Comment by mikefarah** [comment]
Don't use the --null-input flag as you want to use your file as input...

**Comment by smholvoet** [comment]
![](https://i.giphy.com/media/Mb982GyECVbJnxdpYx/200w.gif)

... well that was far easier than I expected, thanks.

I could add the above use case to the docs, but can't find a matching [Tips, Tricks, Troubleshooting](https://mikefarah.gitbook.io/yq/usage/tips-and-tricks) page in the [`doc`](https://github.com/mikefarah/yq/tree/master/pkg/yqlib/doc) folder.
