### ISSUE TITLE
Writing to empty yaml-file does not work with v4

### ISSUE THREAD

**Issue by fbartnitzek** [mikefarah/yq#732]
**Describe the bug**
Writing to empty yaml-file does not work.

Version of yq: 4.6.0
Operating system: linux
Installed via: binary

**Commands**
The command you ran:
```
$ :>a.yaml 
$ yq-v4.6.0 e '.hello2 = "world"'  a.yaml 
```

**Actual behavior**
Result is empty. Also empty yaml with `-i`.

**Expected behavior**
Should write to stdout / yaml file the content, as with non-empty file:

```
$ echo 'hello: world'>a.yaml
$ yq-v4.6.0 e '.hello2 = "world"'  a.yaml 
hello: world
hello2: world
```

e.g. as in v3:
```
$ :>a.yaml 
$ yq-3.4.1 w a.yaml 'hello2' 'world2'
hello2: world2
```

**Comment by mikefarah** [comment]
Yeah it's a quirk of the new way it works:
https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#creating-a-new-file-working-with-blank-documents

**Comment by mikefarah** [comment]
fwiw `jq` behaves the same way

**Comment by alienriver49** [comment]
I'm having issues with this approach if there exists an empty file already. I'm getting `cannot overwrite existing file`, any thoughts on what could be causing this?

Here's a simplistic version of what I'm trying to do (where test.yaml is an empty file):
`yq ea -i -P 'select(fileIndex==0).parent = select(fileIndex==1) | select(fileIndex==0)' > ./test.yaml <(echo '{"key": "value"}')`
