### ISSUE TITLE
yaml document separator --tojson creates literal '---' which is not json compatible ...

### ISSUE THREAD

**Issue by PaulCharlton** [mikefarah/yq#735]
**Describe the bug**

```bash
yq -V
yq version 4.6.1
```

input file consisting of document separators and no tags
1.yaml
```yaml
---
---
```

** command **
```bash
yq eval-all --tojson 1.yaml
```

**Actual behavior**

produces:

```json
null
---
null
```

**Expected behavior**

```json
null
null
```

```json
{}
{}
```

or, alternatively, 2 blank lines (like "// empty" in jq).    The literal '---' is not parseable by `jq`

**Comment by PaulCharlton** [comment]
I imagine the point would be for "--tojson" to strip document start when combining documents with 'eval-all'

**Comment by mikefarah** [comment]
Yeah fair call - for the moment, you can use the `-N/--no-doc` to get rid of the separators, next release will do that by default

**Comment by mikefarah** [comment]
https://github.com/mikefarah/yq/issues/730
