### ISSUE TITLE
Documentation Link on Readme is broken

### ISSUE THREAD

**Issue by BHTemenos** [mikefarah/yq#743]
Has this documentation been moved somewhere?  I googled but couldn't find it:

Example Broken Link:
[https://mikefarah.gitbook.io/yq/v/v4.x/select#select-and-update-matching-values-in-map](https://mikefarah.gitbook.io/yq/v/v4.x/select#select-and-update-matching-values-in-map)

**Comment by mikefarah** [comment]
Fixed - thanks for reporting :)
