### ISSUE TITLE
Broken comments handling?

### ISSUE THREAD

**Issue by oguyotot** [mikefarah/yq#745]
Hello,

yq version 4.6.1

I haven't been able to replicate this issue with a smaller sample, so here is the link to the full file I am using:
https://github.com/ibm-ecm/container-samples/blob/5.5.4/operator/descriptors/fncm_v1_fncm_cr_template.yaml

The problem is that when writing to the file, yq is messing up the indent for many of the comments.

For example, just run this command:
cp fncm_v1_fncm_cr_template.yaml fncm_v1_fncm_cr_template.yaml.ori
yq -i e '.metadata.name = "test"' fncm_v1_fncm_cr_template.yaml
diff fncm_v1_fncm_cr_template.yaml fncm_v1_fncm_cr_template.yaml.ori

=> I would expect on only "metadata.name" to be updated, but the output file is very different from the original one.

This is just one example, but the same problem is happening a lot with this file. For example, **after** running the command above, use the following commands to un-comment some data sources sections:
section_start=$(grep -n "dc_gcd_datasource:" fncm_v1_fncm_cr_template.yaml | head -n 1 | cut -d: -f1)
sed -i "${section_start},+6 s/#/ /" fncm_v1_fncm_cr_template.yaml
section_start=$(grep -n "dc_os_datasources:" fncm_v1_fncm_cr_template.yaml | head -n 1 | cut -d: -f1)
sed -i "${section_start},+6 s/#/ /" fncm_v1_fncm_cr_template.yaml

=> Check the content of the file at that point (data sources section), and compare again after running the following command:

yq -i e '.spec.datasource_configuration.dc_gcd_datasource.dc_database_type = "db2"' fncm_v1_fncm_cr_template.yaml

=> the indent for the data sources comments is modified again, in a way that makes further changes more difficult.

To me it looks like there are 2 different issues:

1. first, I think that the initial file is not correctly commented out, which might explain the issue (comments not respecting the proper indent). yq then does its best to fix the issue, but this is only making things worst. It would be nice to have an optional flag to prevent yq from re-indenting comments for such cases.

2. in some cases, yq is not behaving consistently. Take the 2 sections "initialize_configuration" and "verify_configuration" (near the end of the file). After changing .metadata.name (first command above), the 2 sections look very different, even though they were pretty much similar initially.

Thanks!

**Comment by mikefarah** [comment]
This is a known isssue with the underlying yaml parser - yq attempts to preserve comment positions and whitespace as much as possible, but it does not handle all scenarios (see https://github.com/go-yaml/yaml/tree/v3 for details)
