### ISSUE TITLE
Is it possible to compare in V4?

### ISSUE THREAD

**Issue by william-salt-cko** [mikefarah/yq#759]
In v3 there was a compare command, is it possible to do this in v4 with the new syntax?

**Comment by mikefarah** [comment]
Best way to do it is using `yq` to preprocess the files for diffing (e.g. normalising the style and indent, removing comments if you want to) and just using `diff`.

For example:
```
diff <(yq e -P examples/data1.yaml) <(yq e -P examples/data2.yaml)
```

Hmm might add this as a tip and trick

**Comment by mikefarah** [comment]
Added here: https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#comparing-yaml-files

**Comment by sanderma** [comment]
Hope it's ok to ask some more about this topic.

This diff example does not show the parent objects, just the string that is changed.

I'd like to diff two yaml's, and keep an object that has all changes, and includes the correct structure:
My usecase it that I have yaml objects with differences (one original and one with changes), and I'd like to create a yaml to use as an override that contains the changed fields in relation to the original.

so if data1.yaml would contain:

```yaml
key1:
  key2: "original"
  key3: "same"
key4: "same"
```

and data2.yaml would contain:

````yaml
key1:
  key2: "different"
  key3: "same"
key4: "same"
```

I would like output as:

````yaml
key1:
  key2: "different"
```

I have no clue how to approach this tbh :)
