### ISSUE TITLE
Expand YAML 1.1 merges

### ISSUE THREAD

**Issue by ostrolucky** [mikefarah/yq#766]
```
❯ cat foo.yaml
a: &a
  foo: bar
b:
  <<: *a
❯ yq e foo.yaml
a: &a
  foo: bar
b:
  !!merge <<: *a
❯ yq e foo.yaml -j
{
  "a": {
    "foo": "bar"
  },
  "b": {
    "foo": "bar"
  }
}
❯
```

It looks like `yq` doesn't have functionality to expand those merges. It does it only when transforming the output to different format.

**Comment by mikefarah** [comment]
It does, I just called it 'explode':

https://mikefarah.gitbook.io/yq/operators/anchor-and-alias-operators#explode-alias-and-anchor

I'll add 'expand' in that doc so it appears in the search
