### ISSUE TITLE
.key? support

### ISSUE THREAD

**Issue by ostrolucky** [mikefarah/yq#767]
**Describe the bug**
It looks like after using `..` in yq, I cannot do anything further with the result.

Version of yq: 4.6.2
Operating system: mac
Installed via: homebrew

**Input Yaml**
foo.yml:
```yaml
a:
  foo: bar
b:
  c:
    foo: baz
```

**Command**
The command you ran:
```
yq e '..|.foo?' foo.yaml

```

**Actual behavior**

```yaml
null
null
null
null
```

**Expected behavior**

```yaml
null
"bar"
null
"baz"
```

**Additional context**
This works with jq as expected and documented:
```
❯ yq e '.' foo.yaml -j | jq '..|.foo?'
null
"bar"
null
"baz"
```

**Comment by ostrolucky** [comment]
Indeed, that works

**Comment by mikefarah** [comment]
I'm not sure if `yq` actually needs the '?' operator - going to close, please re-open if there is something specific that needs to be done with it
