### ISSUE TITLE
yq r -- filename '--key-starting-with-dashes' doesn't return value on YAML with no top-level object

### ISSUE THREAD

**Issue by ingernet** [mikefarah/yq#769]
**Describe the bug**
[The YQ 3 Gitbook](https://mikefarah.gitbook.io/yq/v/v3.x/usage/path-expressions#keys-and-values-with-leading-dashes) states that adding a pair of dashes after the yq subcommand will keep it from parsing attributes whose names start with dashes. However, the only example given is with creating a new document:
```
yq n -j -- --key --value
```

The CLI help docs make the same claim, this time with `yq r`:
```
Examples:
...<snip>...
yq r -- things.yaml '--key-starting-with-dashes.blah'
```

**Version of yq:** I tried 3.2.1, then upgraded to 3.4.1 (we need 3 because of dependent IAC scripts)
**Operating system:** mac
**Installed via:** homebrew

**Input Yaml**
sql-instance-flags.yml:
```
---
- --backup-start-time: 05:00
- --database-flags:
    sql_mode: NO_ZERO_DATE,NO_ZERO_IN_DATE,NO_AUTO_CREATE_USER,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    default_time_zone: -08:00
```

**Command**
The command I ran that **didn't** return any results:
```
$ yq r config-sql-instance-patch-flags.yaml '--backup-start-time'
$
```
The command that worked:
```
$ yq r config-sql-instance-patch-flags.yaml '[0].--backup-start-time'
05:00
$
```

BUT when I went to get the sql_mode, this didn't work...
```
$ yq r config-sql-instance-patch-flags.yaml '[0].--database-flags.sql_mode'
$
```
...but this did:
```
$ yq r config-sql-instance-patch-flags.yaml '[1].--database-flags.sql_mode'
NO_ZERO_DATE,NO_ZERO_IN_DATE,NO_AUTO_CREATE_USER,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
$
```

So it looks like it's treating the file as an implicit list. Is this expected behavior for YAML? I have some experience with it, but I'm definitely not a subject matter expert on it.

**Additional context**
Unfortunately, I don't have any control over the syntax of the input YAML file, since it's a config syntax required by GCP in order to deploy a Cloud SQL instance with an `SQL Mode` attribute that is a comma-separated values string that apparently is being passed into the Cloud SQL creation function as...inline YAML or something? It's a whole thing.

[Edited a couple of times to add missing attributes, I apparently have forgotten how to talk to humans after spending hours working with YAML]

**Comment by mikefarah** [comment]
Yep the dashes in front of the items means it's an array, in this case an array of maps. The map with database-flags is in the second position of the array.
