### ISSUE TITLE
Add support for built-in function 'min, max, min_by(path_exp), max_by(path_exp)'

### ISSUE THREAD

**Issue by kenjones-cisco** [mikefarah/yq#77]
Add support for built-in [function 'min, max, min_by(path_exp), max_by(path_exp)'](https://stedolan.github.io/jq/manual/#example46)

```
Find the minimum or maximum element of the input array.

The min_by(path_exp) and max_by(path_exp) functions allow you to specify a particular field or property to examine, e.g. min_by(.foo) finds the object with the smallest foo field.
```

**Comment by electronmods** [comment]
Was this ever implemented? I can't find any references in the documentation, and the yq binary (v 4.27.2) rejects max_by as an invalid string. For now I am sorting and picking the first or last in the resulting array.
