### ISSUE TITLE
index an array after file select

### ISSUE THREAD

**Issue by kevin807210561** [mikefarah/yq#770]
yq version 4.6.3

 yq e 'select(fileIndex==0).[0].name="c"' yml

yml content
```
- name: a
  type: t1
- name: b
  type: t2
```

got Error: Bad expression, please check expression syntax

**Comment by mikefarah** [comment]
Just need to pipe after the the select
```
yq e 'select(fileIndex==0) | .[0].name = "c"' examples/data2.yaml
```
