### ISSUE TITLE
Better formatting on text with |-

### ISSUE THREAD

**Issue by EvanCarroll** [mikefarah/yq#771]
Currently when I run yq, I get

```
description: '* `1` — Success.

  * `0` — Failed. Check the `errors` field for more details.'
```

I would rather have the original source's format though like,

```
description: |-
  * `1` — Success.
  * `0` — Failed. Check the `errors` field for more details.
```

I would like the option to use the `|-` option any time YAML has a `\n` in the value.

This form is called [Block Scalar Styles](https://yaml.org/spec/1.2/spec.html#c-b-block-header(m,t)). Where the `-` tells the YAML parser to chomp the last newline.

**Comment by mikefarah** [comment]
Sorry I missed this - @EvanCarroll what command and input did you run to get that output?

**Comment by mikefarah** [comment]
Can't replicate this, perhaps this doc will help: https://mikefarah.gitbook.io/yq/operators/string-operators#string-blocks-bash-and-newlines
