### ISSUE TITLE
Parser does not backtrack when prefix matches a number but number does not parse

### ISSUE THREAD

**Issue by ProofOfKeags** [mikefarah/yq#775]
`yq e -i '.version = 2.3.0'` yields a bad expression error. I would have expected it to just parse this as a string the same way that the yaml parser would work. If i put `2.3.0` in quotes like this `"2.3.0"` the bad expression error goes away. My naive guess is that this could be fixed with a parser fallback to a string.

**Comment by mikefarah** [comment]
It would be nice - but I can see all sorts of nasty potential side effects, especially because dots are special characters already.
