### ISSUE TITLE
v4 package not available in ppa repo, not updated since August 2020

### ISSUE THREAD

**Issue by gerardo-garcia** [mikefarah/yq#776]
**Describe the bug**
The v4 of yq could not be found in ppa repo below:
https://launchpad.net/~rmescandon/+archive/ubuntu/yq

The ppa repo should be updated to include v4. 

**Command**
In ubuntu20.04, after adding the repository and installing yq, I ran:
```
$ yq --version
yq version 3.3.2
```

**Comment by mikefarah** [comment]
@rmescandon if you have time updating this would be much appreciated :)

**Comment by andgein** [comment]
Also there is no version for Ubuntu 20.10 (groovy) in ppa repo.

_Ubuntu 21.04 is on horizon!_

**Comment by jsoref** [comment]
[Hirsute Hippo](https://releases.ubuntu.com/21.04/) was released in April (on schedule).

And as of August 2021 [yq 3 will be EOL](https://github.com/mikefarah/yq#v4-released).

**Comment by mikefarah** [comment]
rmescandon is no longer supporting yq on debian - please use another way to install yq
