### ISSUE TITLE
In-place updating with styling enabled hangs

### ISSUE THREAD

**Issue by gmile** [mikefarah/yq#785]
**Describe the bug**

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.7.9
Operating system: macOS
Installed via: homebrew

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```yaml
a:
  b: "hello"
c: "world"
```

**Command**
The command you ran:
```
yq eval -i '.a.b="hello123" style="double"' data.yaml
```

**Actual behavior**

`yq` hangs.

**Expected behavior**

`yq` sets key `.a.b` to value `"hello123"`.

**Comment by mikefarah** [comment]
There's a syntax error there - it shouldn't hang ill look into that. The expression should be:


```
.a.b="hello123" | .a.b style="double"
```

**Comment by gmile** [comment]
@mikefarah I ended up being unable to find appropriate v4 syntax for this, your example is what helped me fix it. Thank you!
