### ISSUE TITLE
Yq v4 --style double

### ISSUE THREAD

**Issue by heliomartins** [mikefarah/yq#795]
Hello,

Apologies if I'm missing anything in the documentation, but I would like to know how can write a quoted value to YAML file without changing it entirely?

I've been trying many different approaches to write a single property of one of my YAML file quoted, but it seems that is no longer possible.

Running the following command it replaces all the properties existing in the YAML file with quotes.
`yq eval -i -- ''$1' = '$2' | .. style="double"' sample.yaml`

**What would be the write way to convert from yq v3 to yq v4 style?**
_This is what I was using for yq v3_
-    yq w -i --style double -- "$SYSTEM_YAML_CONFIG" "$1" "$2"

_This is what I tried to replace with in YQ v4_
+    yq eval -i -- ''$1' = '$2' | .. style="double"' "$SYSTEM_YAML_CONFIG"

I do appreciate your help.

Thank you

**Comment by mikefarah** [comment]
Yeah the '..' expression recursively matches all the yaml nodes, what you'll want to do is give it a specific path to set the style of (probably $1) - something like:

```
yq eval -i -- ''$1' = '$2' | '$1' style="double"' sample.yaml
```

**Comment by mikefarah** [comment]
This makes me realise I need an example like that in the docs -I'll add it

**Comment by heliomartins** [comment]
Wow!

Thanks for getting back to me so quickly. 

I've tried your suggestion but with no success. :(

I've attached a screenshot of my attempts and the output of the file. I hope it helps you.

![image](https://user-images.githubusercontent.com/2566718/116028514-a64a6580-a69a-11eb-9bf9-786f4bf61fa2.png)

**Comment by heliomartins** [comment]
Hello @mikefarah ,

It looks like it works like a charm.

Thanks so much for your quick response.

**Comment by mikefarah** [comment]
Pleasure - got me at the right time.

If you don't mind, could you have a look at the updated docs and let me know if they are sufficient?

https://mikefarah.gitbook.io/yq/operators/style

**Comment by heliomartins** [comment]
Approved! That was definitely the example I was looking for. You are a legend.

Feel free to close the issue. :)

Thank you so much once again.
