### ISSUE TITLE
Wildcard deleting all documents of a big file in v3 is much slower than in v4

### ISSUE THREAD

**Issue by tobernguyen** [mikefarah/yq#797]
**Describe the bug**
I'm trying to run this yq command in v3:
```
yq d -d'*' -i 040-Crd-kafka.yaml '**."app.kubernetes.io/managed-by"'
```
The command never exits (or maybe I'm not patient enough), and I can see `yq` process consumes a lot of CPU.

Version of yq: 3.4.1
Operating system: mac
Installed via: binary release on GitHub

But running the same operation in v4 (v4.7.1) works fine (and it returns within seconds):

```
yq -i eval 'del(.. | select(has("app.kubernetes.io/managed-by"))."app.kubernetes.io/managed-by")' 040-Crd-kafka.yaml
```

**Input Yaml**
Added `.txt` extension as GitHub doesn't allow uploading yaml file.
[040-Crd-kafka.yml.txt](https://github.com/mikefarah/yq/files/6389250/040-Crd-kafka.yml.txt)

**Expected behavior**
The command when using v3 should return within seconds and actually modify in place.

**Comment by mikefarah** [comment]
Yep the `**` operator in `yq` v3 is slow for big files. I recommend upgrading to v4 if you can
