### ISSUE TITLE
when running write inplace on a yaml file with anchors they seem to be evaluating and being saved to the file incorrectly. 

### ISSUE THREAD

**Issue by Epiclemonaid** [mikefarah/yq#803]
**Describe the bug**
when running YQ against a yaml file it seems to mess up the yaml anchors as shown below and adds a !!merge to it when I want it to just change the line specified

Version of yq: 3.4.7
Operating system: linux
Installed via: release download

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
data1.yml:
```defaults: &DEFAULTS
  Version v1
  repo: repo
  mainBranch: main
  revision: AUTO
  path: /home/user
  deployToCID:
    test-new-cluster: Auto
    test-cluster: Auto   #this is the value thats being added
  registry: hub.docker.com
applications:
  - <<: *DEFAULTS
    name: billybob

```
**Command**
The command you ran:
```
yq_linux_amd64 write --inplace --verbose application.yaml "defaults.deployToCID.test-cluster" "Auto"
```

**Actual behavior**

```defaults: &DEFAULTS
  Version v1
  repo: github.com
  path: /home/user
  deployToCID:
    test-new-cluster: Auto
    test-cluster: Auto   #this is the value thats being added and that works as expected
  registry: hub.docker.com
applications:
  - !! merge <<: *DEFAULTS <----- this is added for some reason and its breaking my parser.
    name: billybob
```

**Expected behavior**

```defaults: &DEFAULTS
  Version v1
  repo: github.com
  path: /home/user
  deployToCID:
    test-new-cluster: Auto
    test-cluster: Auto   #this is the value thats being added and that works as expected
  registry: hub.docker.com
applications:
  - <<: *DEFAULTS <-- the !!merge shouldnt be added
    name: billybob
```

**Additional context**

it seems for whatever reason yq is messing with the anchors and adding that !!merge and I'm trying to get that to stop. might be a bug?

**Comment by mikefarah** [comment]
This is actually correct behavior, see here for details: https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#yq-adds-a-merge-tag-automatically
