### ISSUE TITLE
Add jq entries functions

### ISSUE THREAD

**Issue by inianv** [mikefarah/yq#807]
The `select` and `del` functions on a flat map behavior is confusing, because with the pattern `select(.[] == "*test*")` on a flat map structure returns only the values and does not a return a key/value pair, but `del()` returns the map

Version of yq: 4.7
Operating system: Mac
Installed via: binary release

**Input Yaml**

data1.yml:

```yaml
a: abcsdf
b: hyuabc
c: iopabc
d: mnhbvgc
```

For example, when I want to select all k/v pairs when value contains `abc`, I thought doing below should work

```
yq e '.[]|select(. == "*abc*")' yaml
abcsdf
hyuabc
iopabc
```

But it didn't, as it was returning only the values. But delete worked

```
yq eval 'del( .[] | select( . != "*abc*" ) )' yaml
a: abcsdf
b: hyuabc
c: iopabc
```

Shouldn't the behavior of `select` and `del` be the same, since the `select` function is not quite the same as in `jq`. In `jq`, this works seamlessly with the `_entries` functions

```
jq 'with_entries(select(.value|test("abc")))'
```

**Comment by mikefarah** [comment]
I think I just need to add the entries functions

**Comment by mikefarah** [comment]
In the latest (4.8.0) release, you can now do this:

```
yq e 'with_entries(select(.value == "abc*"))' data1.yaml 
```
