### ISSUE TITLE
Argument order matters?

### ISSUE THREAD

**Issue by mecampbellsoup** [mikefarah/yq#811]
```
(⎈ minikube:default)➜  dev git:(develop) ✗ k get sealedsecrets.bitnami.com -n cloud github -o yaml | yq e - ".spec" | echo $?
0
Error: '-' expects 2 args but there is 0
(⎈ minikube:default)➜  dev git:(develop) ✗ k get sealedsecrets.bitnami.com -n cloud github -o yaml | yq e ".spec" - | echo $?
0
```
Also shouldn't the program return a non-zero code on errors (in the first/top exampmle)?

**Comment by mikefarah** [comment]
Yes argument order matters (need to tell which string is the expression vs the filename) and it does exist with non-zero codes

```
echo "{}" |  yq e - ".spec"  | echo $?
0
```

which version are you using?

**Comment by mikefarah** [comment]
Yes argument order matters - (I need to tell which argument is the expression and which are the filenames), and it does exit with non-zero codes:

```
echo "dog" |  yq e - ".spec"          
Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:1.
	unmatched text: "-"
 echo $?                      
1
```
