### ISSUE TITLE
base64 encode/decode pipeline option

### ISSUE THREAD

**Issue by avoidik** [mikefarah/yq#819]
**Please describe your feature request.**

I wish I could use yq to be able to base64 encode and base64 decode data

**Describe the solution you'd like**

```yaml
country: QXVzdHJhbGlh
```

And we run a command:

```bash
yq eval '.country | base64d'
```

it could output

```yaml
Australia
```

or vice-versa

```yaml
country: Australia
```

And we run a command:

```bash
yq eval '.country | base64'
```

it could output

```yaml
QXVzdHJhbGlh
```

**Describe alternatives you've considered**

```bash
echo 'country: QXVzdHJhbGlh' | yq eval '.country' - | base64 -d
```

and

```bash
yq eval '.country = "QXVzdHJhbGlh"' --null-input
```

**Additional context**

N/A

**Comment by mikefarah** [comment]
I don't think base64 encoding/decoding should be built into `yq` - `yq` is just about slicing and dicing `yaml`.

**Comment by baryluk** [comment]
I think yq should support this, just like jq. It is very common to have some data in base64 in yaml files, i.e. in kubernetes secrets, but wishing to convert back and forth.

With single value it is possible to do this by using extenral command, no problem.

But how would you convert this jq script to yq?

```
khe get secret airflow-secrets -n airflow -o json  | jq '.data | with_entries({key: (.key), value:(.value|@base64d)})'| yq -P e -
```

not so trivial.

**Comment by tis-rpage** [comment]
@mikefarah base64 is called out in the yaml draft standard for encoding opaque binary data:
https://yaml.org/type/binary.html

As multiple users have identified, base64 is crucial for rendering encoded yaml/json values that are binary in nature and not supporting the most common encoding mechanism is hurting the user base. This is exemplified by multiple people using kubernetes having to resort to `jq` to accomplish what should be trivial for `yq` to accomplish.

I kindly request you reconsider your position on the basis that `yq` lack the ability to embed binary data in yaml output values

**Comment by tis-rpage** [comment]
This now implemented https://github.com/mikefarah/yq/issues/1112#issuecomment-1052899816
