### ISSUE TITLE
Add support for built-in function 'index(s), rindex(s)'

### ISSUE THREAD

**Issue by kenjones-cisco** [mikefarah/yq#82]
Add support for built-in [function 'index(s), rindex(s)'](https://stedolan.github.io/jq/manual/#example51)

```
Outputs the index of the first (index) or last (rindex) occurrence of s in the input.
```

**Comment by ChristianCiach** [comment]
Hat this been reverted? I am using `yq (https://github.com/mikefarah/yq/) version v4.45.4` and there doesn't seem to be an `index` function.
