### ISSUE TITLE
Change in attribute appending between 4.6.1 and 4.9.2

### ISSUE THREAD

**Issue by pmthexton** [mikefarah/yq#830]
The following script executed with yq 4.6.1 

```
#!/bin/bash

end() {
  echo "contents:"
  cat $file
}

trap end EXIT

file=testfile.yml
yq eval --null-input '.name="something"' > $file
yq -i e '.attributes |= [{"key": "att1", "value": "val1"}]' $file
yq -i e '.attributes += [{"key": "att2", "value": "val2"}]' $file
```

Will output

```
name: something
attributes:
  - key: att1
    value: val1
  - key: att2
    value: val2
```

However, when executing with 4.9.2 we get

```
name: something
attributes:
  - key: att1
    value: val1
  - {}
```

Every appended attribute is entered to the file as an empty object

Looking through the documentation I have found the syntax

`
yq -i e '.attributes *+ [{"key": "keyname", "value": "value"}]' $file  
`

This does successfully append to the array, however, it also writes out *only* the array to the file, meaning that in the example above the file output would become

```
- key: att1
  value: val1
- key: att2
  value: val2
```

Can you please offer some guidance? The documentation is very thorough but I can't see anything covering this specific use case I have to modify a document and insert a value in to an array, while maintaining the rest of the document.

Our execution environment is CI pipelines executing on macOS machines, we use Brew to ensure yq is installed on the runner, which is making it difficult to specify the exact version of yq to install as the brew recipe appears to only support installing the latest 4.x build, we could use the Brewfile lock, but if this executes on a newly provisioned host it will again just install the latest version breaking our current implementation.

**Comment by mikefarah** [comment]
My apologies! Got me at a good time though, I've patched it and released 4.9.3 :)

**Comment by pmthexton** [comment]
Thanks @mikefarah , any idea how long it'll take for brew to start dishing out 4.9.3?

**Comment by mikefarah** [comment]
It's usually within hours - someone needs to create and approve a PR so I suspect it will be longer on the weekend

**Comment by Moulick** [comment]
@pmthexton  it's avail in Brew now
