### ISSUE TITLE
https://mikefarah.gitbook.io/yq/operators

### ISSUE THREAD

**Issue by phreed** [mikefarah/yq#837]
### Description of the Issue
As I go through the documentation I am finding errors.
I will post the related issues here.

Version of yq: 4.9.3
Operating system: windows/ubuntu
Installed via:
* windows: choco install yq 
* ubuntu: via wget

#### Input Yaml
data1.yml:
```yaml
a: cat
b: dog
```
#### Command
```
yq e '.a = .b' sample.yaml
```
#### Actual behavior {windows & ubuntu}
```yaml
a: dog
b: dog
```
#### Documented behavior
```yaml
a: cat
b: dog
```

**Comment by mikefarah** [comment]
Oops! thanks for the pickup
