### ISSUE TITLE
Add support for built-in function 'startswith(str)'

### ISSUE THREAD

**Issue by kenjones-cisco** [mikefarah/yq#84]
Add support for built-in [function 'startswith(str)'](https://stedolan.github.io/jq/manual/#example53)

```
Outputs true if . starts with the given string argument.
```

**Comment by zephyrdb** [comment]
Uh @mikefarah this doesn't seem to work in v4?

**Comment by ben-wing** [comment]
also had the experience that startswith did not work
```
$ yq --version
yq (https://github.com/mikefarah/yq/) version v4.44.5

$ cat 20250110-example-perms.yaml | yq e '.members[]|startswith("user:")'
Error: 1:12: invalid input text "startswith(\"user..."

```

however, @zephyrdb, i was able to use the `select` [operator](https://mikefarah.gitbook.io/yq/operators/select) to get the results i needed

```
$ cat 20250110-example-perms.yaml | yq e 'select(.members[] == "user:*")' | wc -l
2271
```

**Comment by zephyrdb** [comment]
Yeah I eventually figured that out.  I guess as long as this issue points to that it's ok.  Also worth pointing out that afaict jq doesn't allow that though.
