### ISSUE TITLE
Not able to install using Homebrew on Ubuntu 20.04

### ISSUE THREAD

**Issue by shinokada** [mikefarah/yq#842]
![image](https://user-images.githubusercontent.com/147320/120131368-4435d080-c203-11eb-83cd-1ae06ed60f4e.png)

**Describe the bug**

When I run ` brew install yq`, I get:

```
Error: The following formula cannot be installed from bottle and must be
built from source.
  yq
```

**Comment by drewgingerich** [comment]
In the last line it asks you to run `brew install gcc` and then try to install yq again. Does that work?

**Comment by mikefarah** [comment]
Closing - happy to reopen if this hasn't been resolved.

**Comment by shinokada** [comment]
`gcc` was installed but brew indicates a false warning.
So I restarted and it worked on Ubuntu 20.0.4.
Thanks.
