### ISSUE TITLE
Convert yaml structure to string

### ISSUE THREAD

**Issue by patrickhuy** [mikefarah/yq#849]
**Please describe your feature request.**
I would like yq to take a yaml and insert it into another yaml as a String
This can be useful when working with kubernetes and helm configuration files

**Describe the solution you'd like**
If we have data1.yml like:

```yaml
struct: { "a": 1 }
str: "hey"
```

And we run a command:

```bash
yq e '.str = .struct | .str tag = "!!str"' data1.yml
```

it could output

```yaml
struct: {"a": 1}
str: '{ "a": 1 }'
```

ideally it should be possible to define the style of how this is going to be converted, currently `yq e '.str = .struct style="flow" | .str tag = "!!str"' testfile.yaml` does not work (it runs very long and crashes eventually) - maybe I'm doing something wrong here.

**Describe alternatives you've considered**
YAML to string could be handled using a different tool but it needs to handle quoting accoedingly.

**Comment by mikefarah** [comment]
I think the best way for this is to do it in two commands - one to extract and format the yaml content from `struct`, store that in a bash environment variable. Then another yq command using the `strvenv` operator populate the `str`

**Comment by patrickhuy** [comment]
That sounds like a great suggestion, thanks!
