### ISSUE TITLE
yq does not inplace update empty files

### ISSUE THREAD

**Issue by patrickhuy** [mikefarah/yq#850]
**Describe the bug**
Version of yq: 4.9.4
Operating system: linux
Installed via: binary

**Input Yaml**

data1.yml:
File is empty but exists
```yaml
```
**Command**
The command you ran:
```
 yq -i e '.a=1' data1.yml
```

**Actual behavior**

No error occurs, the file remains empty
```yaml
```

**Expected behavior**
File is treated as an empty object an updated
```yaml
a: 1
```

**Additional context**

**Comment by mikefarah** [comment]
Yep this is a side-effect of how `yq` works (and jq) where when given an empty file it has no context to run the expressions against - see https://github.com/mikefarah/yq/issues/838
