### ISSUE TITLE
multiple nested keys with special characters (Error: Cannot index array)

### ISSUE THREAD

**Issue by strutswell** [mikefarah/yq#856]
**Describe the bug**

i'm struggling to create a file (with -n flag) or to update existing values that have nested keys with special characters. Hitting some kind of "index array error"

```
 $ yq eval '.a.["key.withdots"]["another.key"] = "blah"' -n
Error: Cannot index array with 'another.key' (strconv.ParseInt: parsing "another.key": invalid syntax)
```

Version of yq: 4.9.5
Operating system: linux (debian)
Installed via: homebrew (linux brew)

**Input Yaml**

data1.yml:
```yaml
a:
  b:
    c: bob
```

**Command**
The command you ran:
first command works fine, second command fails
```
yq eval '.a.["b.1"].c = "fred"' data1.yml
yq eval '.a.["b.1"]["c.2"] = "alice"' data1.yml
```

**Actual behavior**

`Error: Cannot index array with 'c.2' (strconv.ParseInt: parsing "c.2": invalid syntax)`

**Expected behavior**

```yaml
a:
  b:
    c: bob
  b.1:
    c: fred
    c.2: alice
```

**Additional context**
I'm coming from v3 so still a bit confused about v4 syntax, but it seems there always needs to be a leading dot in the path? For example I cannot do this: `yq eval 'a.b.c = "bob"' sample.yml`
```
Error: Parsing expression: Lexer error: could not match text starting at 1:1 failing at 1:3.
	unmatched text: "a."
```
it must be `yq eval '.a.b.c = "bob"' sample.yml`
but i couldn't find anywhere that this is described or explained

**Comment by mikefarah** [comment]
Fixed in 4.9.6
