### ISSUE TITLE
Not equal (!=) does not work on yq v4/stable from Snapcraft

### ISSUE THREAD

**Issue by giner** [mikefarah/yq#861]
**Describe the bug**
`!=` doesn't work on v4/stable from Snapcraft

Version of yq: 4.3.1 (v4/stable on Snapcraft)
Operating system: linux
Installed via: snap

**Command**
The command you ran:
```
echo 'key: value' | yq e '.[] | select(. != null)' -
```

**Actual behavior**

```yaml
Error: Parsing expression: Lexer error: could not match text starting at 1:16 failing at 1:17.
	unmatched text: "!"
```

**Expected behavior**
```yaml
value
```

**Additional context**
The same command works on the latest version of yq (4.9.6).
I would like to have major version of yq to be fixed as v4/stable in all my setups to avoid surprises and `!=` not working is a blocker. Any plans to update v4/stable snap?

**Comment by mikefarah** [comment]
Apologies, just updated v4/stable to the latest

**Comment by giner** [comment]
That was very quick. Thank you!
