### ISSUE TITLE
Unable to write `null`

### ISSUE THREAD

**Issue by sezu** [mikefarah/yq#862]
**Describe the bug**
When using variables, I'm unable to write a `null` value. I'm instead getting `"null"`.

Version of yq: 4.9.6
Operating system: mac
Installed via: homebrew

**Command**
```shell
$ value=dog
$ yq e -n ".value=\"$value\""

$ value=null
$ yq e -n ".value=\"$value\""
```

**Actual behavior**
```yaml
value: dog
```

```yaml
value: "null"
```

**Expected behavior**

```yaml
value: dog
```

```yaml
value: null
```

**Additional Context**
There also doesn't seem to be a way to convert strings to `null` either. Tried a few workarounds with no luck. Also worth mentioning that the following works, but only when `value` is set to `null`.
```
value=null
yq e -n ".value=$value"
```

**Update**
All these cases also fail.

1. Trying to convert `"null"` to `null`
```shell
$ value=null
$ yq e "select(.value == \"null\") | .value=null" <(yq e -n ".value=\"$value\"")
```
Output
```yaml
value: "null"
```

2. Trying to convert `""` to `null`
```shell
$ value=""
$ yq e "select(.value == \"\") | .value=null" <(yq e -n ".value=\"$value\"")
```
Output
```yaml
value: "null"
```

3. Trying to convert `NULL` to `null`
```shell
$ value=NULL
$ yq e "select(.value == \"NULL\") | .value=null" <(yq e -n ".value=\"$value\"")
```
Output
```yaml
value: "null"
```

Ironically, this works
```shell
$ value=dog
$ yq e "select(.value == \"dog\") | .value=null" <(yq e -n ".value=\"$value\"")
```
Output
```yaml
value: null
```

**Comment by mikefarah** [comment]
You need to set it to the literal `null` as opposed to the string `"null"`

```
yq e '.. =null' test.yml
```

**Comment by sezu** [comment]
Is there a syntax to write both `string`s and `null`s when using variables?

```shell
# Doesn't work for nulls
$ yq e -n ".value=\"$value\""

# Doesn't work for strings
$ yq e -n ".value=$value"
```

**Comment by mikefarah** [comment]
Something like this works:

```
value=null yq e -n '.val=strenv(value) | (.val | select( .== "null")) tag= "!!null"'
val: null
```

```
value=dog yq e -n '.val=strenv(value) | (.val | select( .== "null")) tag= "!!null"'
val: dog
```
