### ISSUE TITLE
DBus error "org.freedesktop.DBus.Error.InvalidArgs

### ISSUE THREAD

**Issue by noel-yap** [mikefarah/yq#866]
**Describe the bug**
I'm running `yq` in `bats` tests through `bazel` and running into `DBus error "org.freedesktop.DBus.Error.InvalidArgs` on some of the tests.

Version of yq: 4.X.X
```
$ yq --version
yq version 4.9.6
```

Operating system: mac/linux/windows/....
```
$ uname
Linux
```

Installed via: docker/binary release/homebrew/snap/...
```
$ type -p yq
/snap/bin/yq
```

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
values.yaml:
```yaml
standard-deployment:
  images:
    server:
      tag: server-tag
      name: server-name
    ui:
      tag: ui-tag
      name: ui-name
  containers:
    app:
      image: server
    ui:
      image: ui
```

**Command**
The command you ran:
```
cat '/home/nyap/.cache/bazel/_bazel_nyap/ac2a62558cded53a300b5f278f23fd6b/sandbox/linux-sandbox/137/execroot/grail/_tmp/e77861f066eb1c431f9cf018f3d7ab85/tmp.sVkBbVvBqz/testdata/deploymentNoClusterChart/chart/values.yaml' | yq eval '.standard-deployment.images.server.tag' -
```

**Actual behavior**

```shell
# (from function `assert_success' in file ops/releng/scripts/../../../third-party/bash/bats-assert/src/assert.bash, line 114,
#  in test file ops/releng/scripts/query-chart.bats, line 25)
#   `assert_success' failed with status 46
# 
# -- command failed --
# status : 46
# output : internal error, please report: running "yq" failed: cannot create transient scope: DBus error "org.freedesktop.DBus.Error.UnixProcessIdUnknown": [Process with ID 85 does not exist.]
# --
```

**Expected behavior**

Test passes.

**Additional context**
I've noticed that if I run the test using `--strategy=TestRunner=local` with `bazel test`, everything works fine. It's when that option isn't used that the test fails.

I've also tried `yq eval '.standard-deployment.images.server.tag' <(cat '/home/nyap/.cache/bazel/_bazel_nyap/ac2a62558cded53a300b5f278f23fd6b/sandbox/linux-sandbox/137/execroot/grail/_tmp/e77861f066eb1c431f9cf018f3d7ab85/tmp.sVkBbVvBqz/testdata/deploymentNoClusterChart/chart/values.yaml')` with no change in behavior.

**Comment by noel-yap** [comment]
Some more info:

If I replace `yq` in the script with `grep`, no error is emitted.
If I run the `bats` test directly (ie not through `bazel`), no error is emitted.

**Comment by noel-yap** [comment]
Yeah, looks like it's `snap`-related. I tried running a different snap-install command and it exhibits the same error.

**Comment by mikefarah** [comment]
cool - sorry I can't really help with general snap issues
