### ISSUE TITLE
Update value operation in CMD environment, error occurred

### ISSUE THREAD

**Issue by firekirin67** [mikefarah/yq#868]
**Describe the bug**
You, when I use the example in a cmd environment, the program gives me the error message
Command:yq eval '.a.b = "frog"'  yaml.yml
Error message. Parsing expression. lexer error: could not match text starting at 1:1 failing at 1:1.
        Did not match text."'"

Even if I pass the escape character, it is still the same
yq eval '.a.b = \\"frog\\"'  yaml.yml

Version of yq: 4.9.6
Operating system: windows
Installed via: binary release

**Comment by firekirin67** [comment]
When I tried other ways, I found that the command is feasible under powershell, whether it is escaped by \" or "", even if I don't escape the operation, I can get the correct result.
Moreover, when I was using the cmd environment, I found that when the input expression did not contain ‘, the result was correct. Example:

yq.exe e .a=9090 -i yaml.yml

But there is a strange phenomenon here. When the value of "a" is initially a string, the result of updating the value again is still a string, and cannot be converted into other types of values, such as when a: "8080 "Through the above example, the result after the update is a: "9090", and what I expect is a: 9090

**Comment by mikefarah** [comment]
Have you had a look here: https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#quotes-in-windows-powershell ? I don't use or know powershell unfortunately...

**Comment by firekirin67** [comment]
I have read it, but unfortunately this is a powershell solution. Just like what I said above, single quotes in cmd cannot be used correctly. If it is not used in single quotes, it can run normally. I cannot verify whether it is cmd. The problem is still the problem of the program, because I do not understand the go development language

**Comment by firekirin67** [comment]
> 你有没有看过这里：[https](https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#quotes-in-windows-powershell) : [//mikefarah.gitbook.io/yq/usage/tips-and-tricks#quotes-in-windows-powershell](https://mikefarah.gitbook.io/yq/usage/tips-and-tricks#quotes-in-windows-powershell)？不幸的是，我不使用或不知道 powershell ......

I have read it, but unfortunately this is a powershell solution. Just like what I said above, single quotes in cmd cannot be used correctly. If it is not used in single quotes, it can run normally (https://github.com/mikefarah/yq/issues/868#issuecomment-866709955) .  I cannot verify whether it is cmd. The problem is still the problem of the program, because I do not understand the go development language
