### ISSUE TITLE
yaml top document separator removed

### ISSUE THREAD

**Issue by rockandska** [mikefarah/yq#879]
**Describe the bug**

When editing Yaml files with `---` at its top, those hyphens are removed

Version of yq: 4.9.6
Operating system: linux
Installed via: docker

**Command**
```bash
$ cat << EOF > /tmp/test.yml
---
test: test
EOF
$ docker run --rm -v "/tmp":/workdir mikefarah/yq -i eval '.test = 1' test.yml
```

**Actual behavior**

```bash
$ cat /tmp/test.yml
test: 1
```

**Expected behavior**

```bash
$ cat /tmp/test.yml
---
test: 1
```

**Comment by mikefarah** [comment]
Yep - this is a known formatting issue with the underlying go-yaml parser.

Note that this only affects the readability of the document

**Comment by rockandska** [comment]
> Note that this only affects the readability of the document

and raise an error with yamlint

**Comment by mikefarah** [comment]
Oh that's interesting - I'm not aware of it being recommended in the yaml spec *shrug*.

It might be worth raising the issue in go-yaml.

**Comment by ikorchynskyi** [comment]
A kind of an ugly workaround, if you really need it:
```bash
$ cat sample.yml
---
type: shelter
pets:
  - a: cat
  - b: dog

$ yq e '.' sample.yml
type: shelter
pets:
  - a: cat
  - b: dog

$ yq e '["---",.][]' sample.yml
---
type: shelter
pets:
  - a: cat
  - b: dog
```

**Comment by mikefarah** [comment]
Well that's unexpected...I'm not sure how that works! Gotta look into that.

**Comment by mikefarah** [comment]
Oh I see now - nice trick

**Comment by mikefarah** [comment]
I'm going to fix this up in the next release

**Comment by mikefarah** [comment]
I've put a fix in `yq` to check and persist the top document separator in 4.10.0 :)
