### ISSUE TITLE
Can't upgrade/add apk packages

### ISSUE THREAD

**Issue by nikolay-koychev** [mikefarah/yq#883]
**Describe the bug**
It is not possible to run apk add in the docker container

Version of yq: 4.9.7
Operating system: linux
Installed via: docker

**Input cmd**

expected:
```cmd
/workdir # apk add bash
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ncurses-terminfo-base (6.2_p20210109-r0)
(2/4) Installing ncurses-libs (6.2_p20210109-r0)
(3/4) Installing readline (8.1.0-r0)
(4/4) Installing bash (5.1.0-r0)
Executing bash-5.1.0-r0.post-install
Executing busybox-1.32.1-r6.trigger
OK: 8 MiB in 18 packages
```

error:
```cmd
/workdir $ apk add bash
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied

Root not working neither
/workdir $ apk add --root bash
ERROR: Unable to open root: No such file or directory
ERROR: Failed to open apk database: No such file or directory
```

**Additional context**
Not sure if the problem is regarding an upgrade with the alpine base image itself or a USER value was added to the yq Dockerfile itself. The image is used in a pipeline where more packages are added during runtime, no issues with the v4.9.6 though.

P.S. Really nice tool!

**Comment by LuayGrira** [comment]
I am having permission denied issue as well with the latest... I am using the tool to update a yaml file.

```
15:47:43 safelyRenameFile [ERRO] Failed copying from /tmp/temp46 to filename.yaml
15:47:43 safelyRenameFile [ERRO] open filename.yaml: permission denied
```

I tested with `4.9.6` no error.

**Comment by mikefarah** [comment]
It has to be this PR: https://github.com/mikefarah/yq/pull/860/files which now set the USER for CIS compliance.

Playing with docker I had to do the following to get the root user:

```
docker run --user="root" -it --entrypoint sh mikefarah/yq
```

I'll update the readme

**Comment by mikefarah** [comment]
Note that you can also:

```
FROM mikefarah/yq

USER root
RUN apk add bash
USER yq
```
