### ISSUE TITLE
pretty printer is not idempotent

### ISSUE THREAD

**Issue by dimbleby** [mikefarah/yq#903]
**Describe the bug**
Need to run the pretty printer twice to get to a stable output.

Version of yq: 4.11.2
Operating system: Ubuntu 20.04
Installed via: binary release

**Command**
```
$ echo '"{\n  \"key\": \"{\\n  \\\"foo\\\": \\\"bar\\\"\\n}\"\n}"' | yq e -P
{
  "key": "{\n  \"foo\": \"bar\"\n}"
}
```
but
```
$ echo '"{\n  \"key\": \"{\\n  \\\"foo\\\": \\\"bar\\\"\\n}\"\n}"' | yq e -P | yq e -P
key: |-
  {
    "foo": "bar"
  }
```

I would expect the pretty printer to be satisfied with its own output!

**Comment by dimbleby** [comment]
The above was derived from a real world incident, but here's a simplification:
```
$ echo '"{\n  \"key\": \"foo\"\n}"' | yq e -P
{
  "key": "foo"
}
$ echo '"{\n  \"key\": \"foo\"\n}"' | yq e -P | yq e -P
key: foo

```

**Comment by mikefarah** [comment]
This is a little bit of an odd-scenario - as you aren't actually passing in  a JSON structure - but a string _encoded_ json doc. You get the same result when you

```
 echo '"cat"' | yq e -P
cat
``` 

What prettyPrint is doing is removing the surrounding quotes of the string, typically this makes sense when converting something like

```
a: "cat"
```

to the more idiomatic:

```
a: cat
```

In your case it has a funny side effect that when you remove the surrounding quotes of your string, it becomes a JSON doc - and passing that through again will pretty print it.

Hope that makes sense - but imo this is not a bug.
