### ISSUE TITLE
Trying to intsall yq for ubuntu through ansible playbook but it fails with key server connection timed out

### ISSUE THREAD

**Issue by roshan1193** [mikefarah/yq#905]
fatal: [development]: FAILED! => changed=false
  cmd: apt-key adv --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 9A2D61F6BB03CED7522B8E7D6657DBE0CC86BB64
  msg: |-
    Warning: apt-key output should not be parsed (stdout is not a terminal)
    gpg: keyserver receive failed: Connection timed out
  rc: 2
  stderr: |-
    Warning: apt-key output should not be parsed (stdout is not a terminal)
    gpg: keyserver receive failed: Connection timed out
  stderr_lines: <omitted>
  stdout: |-
    Executing: /tmp/apt-key-gpghome.3VKeRk8hmY/gpg.1.sh --recv-keys --no-tty --keyserver hkp://keyserver.ubuntu.com:80 9A2D61F6BB03CED7522B8E7D6657DBE0CC86BB64
  stdout_lines: <omitted>

**Comment by mikefarah** [comment]
This does not seem to be something related to this project.
