### ISSUE TITLE
v4 multiply operator (merge) dropping object level anchors with append flag

### ISSUE THREAD

**Issue by styu99** [mikefarah/yq#906]
Reposting from https://github.com/mikefarah/yq/issues/694#issuecomment-882839225 for greater visibility
------
When using the v4 multiply operator with the append flag, object node anchors are dropped.

**Input yaml**
a.yml:
```yaml
:test:
  :foo: &common
    - PROP_A
  :bar:
    - *common
    - TEST
```
b.yml:
```yaml
:test:
  :foo: &common
    - PROP_B
```
**Command**
`yq eval-all 'select(fileIndex == 0) *+ select(fileIndex == 1)' a.yml b.yml > c.yml`
**Actual output**
c.yml:
```yaml
:test:
  :foo:
    - PROP_A
    - PROP_B
  :bar:
    - *common
    - TEST
```
**Expected output**
c.yml:
```yaml
:test:
  :foo: &common
    - PROP_A
    - PROP_B
  :bar:
    - *common
    - TEST
```

**Comment by tomlankhorst** [comment]
Comments seem to be gone too, again:

`a.yml`
```yml
# hello
a: 1
```
`b.yml`
```yml
b: 2
```
`$ yq eval-all 'select(fileIndex == 0) * select(fileIndex == 1)' a.yml b.yml`
```yml
a: 1
b: 2
```

**Comment by tomlankhorst** [comment]
Wouldn't it be nice to have some test cases in the form: `{[args], [inputs], expected_output}`? 
Then we can add these cases to avoid future regressions.

**Comment by mikefarah** [comment]
There are tests like that, have a look at the code :P

That is a separate issue related to handling of comments - please raise a new issue.
