### ISSUE TITLE
Add support for format and escaping using '@base64 @base64d'

### ISSUE THREAD

**Issue by kenjones-cisco** [mikefarah/yq#91]
Add support for [format and escaping using '@base64 @base64d'](https://stedolan.github.io/jq/manual/#example71)

```
@base64:

The input is converted to base64 as specified by RFC 4648.

@base64d:

The inverse of @base64, input is decoded as specified by RFC 4648. Note: If the decoded string is not UTF-8, the results are undefined.
```

**Comment by mabushey** [comment]
I guess this will never be added?

**Comment by tis-rpage** [comment]
This is now implemented: https://github.com/mikefarah/yq/issues/1112#issuecomment-1052899816
