### ISSUE TITLE
Use the standard input with the docker image

### ISSUE THREAD

**Issue by gautaz** [mikefarah/yq#915]
**Please describe your feature request.**
Looking at the documentation, I didn't see any way to use the standard input to feed `yq` when using the docker image:
```
docker run --rm -v "${PWD}":/workdir mikefarah/yq <command> [flags] [expression ]FILE...
```
I have tried things like:
```
docker-compose config | docker run --rm mikefarah/yq e . -
```
which renders a void output while using the "file way" shows the compose config:
```
docker-compose config > blub
docker run --rm -v "$PWD:/workdir" mikefarah/yq e . /workdir/blub
```

**Describe the solution you'd like**
AFAIK using the standard input directly would be an improvement.
I guess there is a reason for this not to work for now, I can help with some guidance.

**Describe alternatives you've considered**
For now the only workaround seems to use a temporary file.

**Additional context**
N/A

**Comment by mikefarah** [comment]
I think you will need to -i (--interactive) flag for the docker run command

```
docker-compose config | docker run --interactive --rm mikefarah/yq e . -
```

**Comment by gautaz** [comment]
@mikefarah That's it! Many thanks :-)
Perhaps having this in the documentation would help?
I can provide a PR for this.
Do you want me to keep the issue opened until it is done?

**Comment by mikefarah** [comment]
Great, thanks for letting me know! I'll add it to the readme
