### ISSUE TITLE
snap stable is on 4.11.1 - can this be changed to 4.11.2?

### ISSUE THREAD

**Issue by senyahnoj** [mikefarah/yq#916]
Our build pipeline brings in yq via snap and it's bringing in the stable channel version of 4.11.1

I believe that there is a critical bug in 4.11.1 which has been subsequently fixed in 4.11.2

https://snapcraft.io/yq

Is it possible to release 4.11.2 on the stable channel?

**Comment by mikefarah** [comment]
Done!
