### ISSUE TITLE
Lexer errors on colons in keynames

### ISSUE THREAD

**Issue by du5tball** [mikefarah/yq#920]
**Describe the bug**
The lexer fails on Keynames / Tagnames containing colons.

Version of yq: 4.11.2
Operating system: mac
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
test.yml:
```yaml
---
foo::bar: yes
```

**Command**
The command you ran:
```
yq e '.foo::bar' test.yaml
```

**Actual behavior**

```text
Error: Parsing expression: Lexer error: could not match text starting at 1:7 failing at 1:8.
        unmatched text: "b"
```

**Expected behavior**

```yaml
yes
```

According to the YAML 1.2 spec, these should be allowed and 3.2.1.2. even specifically mentions Perl as an example, denoting :: as namespace separators.

**Comment by mikefarah** [comment]
Have you tried doing this: https://mikefarah.gitbook.io/yq/operators/traverse-read#special-characters

**Comment by mikefarah** [comment]
I'll have a look into not needing the special character syntax - just have to see if it will affect other operators (including ones that could be added later)...but the special character syntax should work for now

**Comment by mikefarah** [comment]
Yeah `jq` does the same thing, you need to `'.["foo::bar"]'` - I'm going to therefore leave it as it is. Let me know if you have any other issues.

**Comment by fgksgf** [comment]
Hi, I encountered the similar issue when I tried to update the value:

```yaml
# test.yaml
config:
  foo:bar: 1
```

```bash
export newVal=2
yq e -i '.config.["foo:bar"] = \"$newVal\"' test.yaml
```

I got:
```
Error: Parsing expression: Lexer error: could not match text starting at 1:23 failing at 1:24.
        unmatched text: "\\"
```

**Comment by mikefarah** [comment]
That's actually a different issue - bash won't interpolate variables in single quoted strings, use https://mikefarah.gitbook.io/yq/operators/env-variable-operators#read-yaml-environment-variable instead
