### ISSUE TITLE
Dynamic key lookup with environment variable not working for nested items

### ISSUE THREAD

**Issue by iomarcovalente** [mikefarah/yq#922]
**Describe the bug**
As per title, Dynamic key lookup with environment variable not working for two or more levels nested items

yq (https://github.com/mikefarah/yq/) version 4.11.2
Operating system: mac
Installed via: binary release

**Input Yaml**
Concise yaml document(s) (as simple as possible to show the bug, please keep it to 10 lines or less)
example.yml:
```yaml
a:
  b: "text"
  c: "other text"

z: "hello"
```

**Command**
The command you ran:
```
NODE=a.b yq eval '.[env(NODE)]' example.yaml
```

**Actual behavior**

```yaml
null
```

**Expected behavior**

```yaml
text
```

**Additional context**
It works only with one level nesting

**Comment by mikefarah** [comment]
It's only supposed to work with one level, as it's the method used to look up keys with dots and other special characters.

You can split your path into an array and use ireduce reduce that array of keys with the yaml file as the accumulator:

```bash
 NODE=a.b yq e '(strenv(NODE) | split(".") | .[]) as $i ireduce (. ; .[$i])'
text
```
