### ISSUE TITLE
Bash variables

### ISSUE THREAD

**Issue by kamzar1** [mikefarah/yq#928]
V4
Bash ENV is very limited, as it just takes the variable defined before yq.
works:
VAL='123' yq e '.a = strenv(VAL)' example.yaml
Doesnt work:
VAL='123'; yq e '.a = strenv(VAL)' example.yaml

when I got a lot of variables previously defined. need to do:

`\"${ABC}\""  or "'${ABC}'"  or \"$ABC\"` which are quite challenging (compared to the simplicity of version 3) when you need to embed in a shell script with a lot of variables.

**Comment by mikefarah** [comment]
You can either put it in the expression and let bash interpolate, or use the `env/strenv` operators.

Note that you need to _export_ the variables so subprocesses can see it. this is just how bash works.

```
export VAL='123'; yq e '.a = strenv(VAL)' example.yaml
```

**Comment by kamzar1** [comment]
Sorry for re-opening this again.
Appreciate the great work and it has been useful to me at v3.
Now v4, I am sure, the amount of improvement and new functions wouldn't be possible without breaking the backwards compatibility.
As for the bash variables, it is still possible, just I hadnt found a hint in Docs.
Perhaps, it should be mentioned.
v3:
`yq w temp.yaml data.role $VALUE`
v4:
`yq e -i '.'$user'.'$vm'.backups.'$bkname' += {"size": '\"${size}\"' , "created_at": '\"${date}' '${hour}\"'}' $yaml.file`

3 Parts:
1. single quote sufficient:
`.'$user'.'$inst'.backups.'$bkname' `
2. singlequote, escape, doublequote:
`{"size": '\"${size}\"' , "created_at": '\"${date}' '${hour}\"'}`
3. plain (as expected)
`$yaml.file`

**Comment by mikefarah** [comment]
I'm not sure what you are talking about here. The environment variable interpolation in a string is done by _bash_ not yq. You can read up the bash documentation on that. 

_Bash interpolates and environment variables in the string argument before `yq` gets called_. 

There's some docs here if it helps - but this is bash documentation not yq. https://tldp.org/LDP/abs/html/parameter-substitution.html.
