### ISSUE TITLE
Assign + Alternative causes the assignment to disappear

### ISSUE THREAD

**Issue by forivall** [mikefarah/yq#930]
**Describe the bug**

```
$ yq e --null-input '(.foo |= "bar")'
foo: bar

$ yq e --null-input '(.foo |= "bar") // null'
{}
```

I expect the results in both cases to be `foo: bar`

Note that any how to questions should be posted in the discussion board and not raised as an issue.

Version of yq: 4.12.1
Operating system: mac
Installed via: binary homebrew

**Input Yaml**
null input

**Command**
The command you ran:
```
yq e --null-input '(.foo |= "bar") // null'
```

**Actual behavior**

```yaml
{}
```

**Expected behavior**

```yaml
foo: bar
```

**Additional context**
I'm using this in conjunction with `select` -- alternatively, if conditionals were implemented, i could use that instead. https://github.com/mikefarah/yq/issues/95

example of fuller context:
```
$ yq e --null-input '[(.foo |= "bar")] | [.[], (null | .bar |= "baz")] | .[] | ((select(.foo) | .bees = "buzz") // .) | [.]'
- foo: bar
- bar: baz

$ yq e --null-input '[(.foo |= "bar")] | [.[], (null | .bar |= "baz")] | .[] | ((select(.foo) | .bees = "buzz")) | [.]'
- foo: bar
  bees: buzz
```
<details>
<summary>
In writing the fuller context, i found some more erroneous cases:
</summary>

```
$ yq e --null-input '[(.foo |= "bar"), (.bar |= "baz")]'
# hangs, infinite loop or something
```

```
$ yq e --null-input '[(.foo |= "bar")] | [. | (.bar |= "baz")'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x125f3e6]

goroutine 1 [running]:
github.com/mikefarah/yq/v4/pkg/yqlib.(*Operation).toString(0x0, 0xc00022e9d8, 0x1381ad8)
	github.com/mikefarah/yq/v4/pkg/yqlib/lib.go:152 +0x26
github.com/mikefarah/yq/v4/pkg/yqlib.(*expressionParserImpl).createExpressionTree(0xc000266820, 0xc000026e80, 0xc, 0x10, 0xc000026e80, 0xc, 0x10)
	github.com/mikefarah/yq/v4/pkg/yqlib/expression_parser.go:49 +0xe5
github.com/mikefarah/yq/v4/pkg/yqlib.(*expressionParserImpl).ParseExpression(0xc000266820, 0x7ffeefbff49a, 0x28, 0xc000273af8, 0x100f518, 0x20)
	github.com/mikefarah/yq/v4/pkg/yqlib/expression_parser.go:37 +0xf4
github.com/mikefarah/yq/v4/pkg/yqlib.(*streamEvaluator).EvaluateNew(0xc000273d50, 0x7ffeefbff49a, 0x28, 0x13f3d50, 0xc0000b3d50, 0x0, 0x0, 0x78, 0x132a620)
	github.com/mikefarah/yq/v4/pkg/yqlib/stream_evaluator.go:31 +0x63
github.com/mikefarah/yq/v4/cmd.evaluateSequence(0xc0000b7180, 0xc000074420, 0x1, 0x2, 0x0, 0x0)
	github.com/mikefarah/yq/v4/cmd/evalute_sequence_command.go:143 +0x816
github.com/spf13/cobra.(*Command).execute(0xc0000b7180, 0xc000074400, 0x2, 0x2, 0xc0000b7180, 0xc000074400)
	github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000b6f00, 0x0, 0xffffffff, 0xc0000220b8)
	github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	github.com/mikefarah/yq/v4/yq.go:11 +0x2a
```
</details>

**Comment by mikefarah** [comment]
Wow you have a knack for finding expressions that break `yq` - I'll have to have  a look at those. 

I'll fix the alternative op problem in the next release - need more digging for the errors you had.

It's worth noting that you can do:

```
yq e --null-input '[{"foo":"bar"}, {"bar": "baz"}]'
- foo: bar
- bar: baz

```

But the expressions you had should work too... :/

**Comment by mikefarah** [comment]
Fixed the infinite loop bug! 

I'll make a release 4.12.2 to include those fixes.

The last problem you had was a bad expression missing the last closing `]` bracket - which then led to the next problem of trying to index an array with `.bar`. 

If you could raise a separate issue for that on giving a nice error message for bad expressions, and I'll look into that for the next release.

**Comment by forivall** [comment]
Opened further issues as #932

And yeah, my knack for finding edge cases is one of the things that broke me when i worked on an alt-js language years ago (though i want to restart that work)
