### ISSUE TITLE
Unable to select and add a key/val without loosing much of the document.

### ISSUE THREAD

**Issue by mabushey** [mikefarah/yq#935]
**Describe the bug**
Unable to select and add a key/val without loosing the rest of the document

Version of yq: 4.12.2
Operating system: linux
Installed via: binary release

This is a wonderful utility that is incredibly hard to use as almost all docs are wrong. There are multiple yq utilities, and the versions between the same yq have nothing in common except the name and purpose. This `yq` really should be renamed to `yqv4` so it's possible to google problems.

I can use this: `yq e '.clusters[] | select(.cluster.server == "https://172.*") .cluster.proxy-url="http://localhost:9999"' /tmp/kube.config`, and it works, except it "looses" much of the original document; anything that is not under `.clusters`. It does not seem to work to move .clusters[] into the select() as I don't know how reference the matching [] in the following proxy-url declaration.

**Comment by mabushey** [comment]
This works (Using sed): ✗  `sed -i -e '/proxy-url:/d' -e '/server: https:\/\/172./i \    proxy-url: http://localhost:8888'`

**Comment by mikefarah** [comment]
When you say the docs are wrong, are you talking about my official yq docs linked from the github page? If so let me know.

Glad you like `yq` you're just missing some brackets, put the brackets around the LHS of the `=` operator (otherwise, what you are doing is filtering the document, and then updating it):

```
yq e '.(clusters[] | select(.cluster.server == "https://172.*") .cluster.proxy-url)="http://localhost:9999"' /tmp/kube.config
```
