### ISSUE TITLE
"YAML" directive 1.2 causes: Error: yaml: found incompatible YAML document

### ISSUE THREAD

**Issue by Slooz** [mikefarah/yq#938]
**Describe the bug**
A ["YAML" directive](https://yaml.org/spec/1.2.1/#directive/YAML/) causes the following:

> Error: yaml: found incompatible YAML document

Version of yq: 4.12.2
Operating system: mac
Installed via: homebrew

**Input Yaml**
data1.yml:
```yaml
%YAML 1.2
---
foo
```

**Command**
The command you ran:
```zsh
yq eval '' data1.yml
```

**Actual behavior**

> Error: yaml: found incompatible YAML document

**Expected behavior**

> foo

**Additional context**
The [YAML specification](https://yaml.org/spec/1.2.1/#directive/YAML/) says:

> A version 1.2 YAML processor must accept documents with an explicit “%YAML 1.2” directive

**Comment by Slooz** [comment]
I see that this issue is caused by the following:
https://github.com/go-yaml/yaml/issues/298

**Comment by mikefarah** [comment]
The go-yaml repo has been pretty quite lately :(

**Comment by Slooz** [comment]
I realize that there's not much that can be done about this. Feel free to close this issue.

**Comment by mikefarah** [comment]
Fixed in v4.30 (basically I preprocess files so go-yaml never sees it)
