### ISSUE TITLE
Document separator '---' removed when changing file in place

### ISSUE THREAD

**Issue by jangroth** [mikefarah/yq#945]
**Describe the bug**

`Version 4.6.3` - document separator '---' removed when changing file in place.

**Input Yaml**

test.yaml:
```
---
foo: bar
```

**Command**

```
yq eval --inplace '.foo = "baz"' test.yaml
```

**Actual behavior**

test.yaml:
```
foo: baz
```

**Expected behavior**

test.yaml:
```
---
foo: baz
```
**Additional context**
I've spent the last 30 min or so reading through various older incidents, and I can see that this has been brought up a few times (what a pickle to search for '---' on GitHub 🤯 ), and from the comments it seems that it should work since version 4. 

Also, the option `-N, --no-doc         Don't print document separators (---)` seems to imply that document separators are included by default rather than left out.

This is a bit of a pickle in our workflow as 'missing document start marker' is a default warning in https://github.com/adrienverge/yamllint.

Reporting this as a bug.

**Comment by mikefarah** [comment]
This has been fixed in new versions of `yq` - please update to the latest version :)
