### ISSUE TITLE
Unable to add to array from STDIN

### ISSUE THREAD

**Issue by chrisholly-skyuk** [mikefarah/yq#946]
Using yq4, I have been trying to add to an array while parsing a large string from a file.

**Working example:**
`yq4 eval '.array_to_add_to += {"k1": "v1","k2": "v3"}' file-to-add-to.yaml`

**Working Outcome:**
```
array_to_add_to:
  k1: v1
  k2: v3
```

**Parsing from stdin (not working):**
`echo '{"k1": "v1","k2": "v3"}' | yq4 eval '.array_to_add_to += -' file-to-add-to.yaml`

**Expected Outcome:**
```
array_to_add_to:
  k1: v1
  k2: v3
```

**Actual Outcome:**
```
Error: Parsing expression: Lexer error: could not match text starting at 1:21 failing at 1:21.
	unmatched text: "-"
```

There seems to be very little documentation for parsing from stdin for yq4. Can you help?

**Comment by mikefarah** [comment]
The `-` is used as the filename not in the expression:

```
cat file.yaml | yq e '.a.b[0].c' -
```
