### ISSUE TITLE
Allow to generate multi yaml docs from json file

### ISSUE THREAD

**Issue by glerchundi** [mikefarah/yq#973]
I'm trying to create a multi document YAML from a JSON and I wasn't able to make it work although I found that this seems to be solved in this issue: https://github.com/mikefarah/yq/issues/470.

Taking this YAML file as an example (https://github.com/fluxcd/flux2/releases/download/v0.19.0/install.yaml) and executing the following command `yq` fails although I would expect that to work:

```bash
$ cat install.yaml | yq eval -j | yq eval -  
Flag --tojson has been deprecated, please use -o=json instead
{"apiVersion": "v1", "kind": "Namespace", "metadata": {"labels": {"app.kubernetes.io/instance": "flux-system", "app.kubernetes.io/part-of": "flux"}, "name": "flux-system"}}
Error: yaml: line 11: did not find expected <document start>
```

Current `yq` version:

```bash
$ yq -V                                    
yq (https://github.com/mikefarah/yq/) version 4.13.4
```

**Comment by mikefarah** [comment]
Right I see - there are two things you need to do to get this to work:
a) output the json docs so that they are printed in a single line (set the indent to 0 via `-I=0`)
b) add the yaml document separators between the docs


```
yq e examples/data1.yaml  -j -I=0 | sed '{N;s/\n/\n---\n/;}' | yq e -P -
```

**Comment by mikefarah** [comment]
Actually that sed command doesn't quite work :/ need to find something else that puts `---` between the docs
