### ISSUE TITLE
Assign value from JS file fail with error

### ISSUE THREAD

**Issue by YanivYuzis** [mikefarah/yq#999]
**Describe the bug**
Assign value from JS file fail with following error:
Error: Parsing expression: Lexer error: could not match text starting at 2:21 failing at 2:23.
	unmatched text: "er"

Version of yq: 4.14.1
Operating system: mac
Installed via: homebrew

% cat value.js
if (error) {
  session.reject('{"error":"failed"}');
}

% yq e -n '.test = "'"$(< ./value.js)"'"'
Error: Parsing expression: Lexer error: could not match text starting at 2:21 failing at 2:23.
	unmatched text: "er"

**Comment by mikefarah** [comment]
Use the strenv command - otherwise you will get escaping issues
